### ISSUE TITLE
Building instructions / dependencies might be incomplete

### ISSUE THREAD

**Issue by kumzugloom** [Return-To-The-Roots/s25client#1]
Hi everyone,
I noticed, that the building instructions might be incomplete or outdated and at least do not work for me. I already figured out, that I have to install the following additional libraries/packages, in order to complete the configuration for building:
```
sudo apt-get install g++ libbz2-dev mesa-common-dev libgl1-mesa-dev gettext libsdl1.2-dev libsdl-mixer1.2-dev
```
But now, when configuration is finished, I still cannot build, as I receive the following error:
```
kuzugloom@debian:~/dev/s25client/build$ make
Scanning dependencies of target updateversion
make[2]: /home/kumzugloom/dev/s25client/build/version/src/version: Command not found
make[2]: *** [CMakeFiles/updateversion] Error 127
make[1]: *** [CMakeFiles/updateversion.dir/all] Error 2
make: *** [all] Error 2
```
Can someone point me to what I'm missing?
Thanks! :)

PS: In the build instructions it says "submodules" instead of "submodule", which could be corrected as well. :)

**Comment by Flow86** [comment]
Hi,
have you followed these instructions?

```
git clone https://github.com/Return-To-The-Roots/s25client s25client
cd s25client
git submodules update --init
cd build
./cmake.sh --prefix=.
make
```

I think you have forgotten the "git submodules update --init" step. otherwise some of the necessary directories are empty ;-)

**Comment by kumzugloom** [comment]
Hi,
you're correct. I tried to follow that procedure but somehow mixed up directories with an earlier try, where this command was not run before.
Strange enough, I now found, that I also have to install *libcurl4-gnutls-dev* to make the cmake run again.

Still, building keeps failing:

```
[ 21%] Building CXX object libutil/src/CMakeFiles/s25util.dir/UPnP.cpp.o
/home/kumzugloom/dev/s25client/libutil/src/UPnP.cpp:78:33: fatal error: miniupnpc/miniupnpc.h: No such file or directory
compilation terminated.
make[2]: *** [libutil/src/CMakeFiles/s25util.dir/UPnP.cpp.o] Error 1
make[1]: *** [libutil/src/CMakeFiles/s25util.dir/all] Error 2
make: *** [all] Error 2
```

:-(

**Comment by Flow86** [comment]
you will need miniupnpc (i.e from https://launchpad.net/~flosoft/+archive/ubuntu/s25rttr/ or directly from ubuntu)

**Comment by kumzugloom** [comment]
True,
additionally installing the follwing packages finally did the trick for me (debian wheezy amd64):
```
sudo apt-get install miniupnpc libminiupnpc-dev 
```

Therefore, the current and hopefully complete list for a fresh-installed debian system would be:
```
sudo apt-get install g++ libbz2-dev mesa-common-dev libgl1-mesa-dev gettext libsdl1.2-dev libsdl-mixer1.2-dev miniupnpc libminiupnpc-dev 
```

Thanks @Flow86 for sorting this out. :+1: 


"make" is finally successful. Now "make install" fails (even when run as root):
```
[...]
## Installing RTTR directory
cp: `./../RTTR/COLORS.ACT' and `./share/s25rttr/RTTR/COLORS.ACT' are the same file
cp: `./../RTTR/languages' and `./share/s25rttr/RTTR/languages' are the same file
cp: `./../RTTR/LSTS' and `./share/s25rttr/RTTR/LSTS' are the same file
cp: `./../RTTR/MAPS' and `./share/s25rttr/RTTR/MAPS' are the same file
cp: `./../RTTR/MUSIC' and `./share/s25rttr/RTTR/MUSIC' are the same file
cp: `./../RTTR/s25update' and `./share/s25rttr/RTTR/s25update' are the same file
cp: `./../RTTR/SAVE' and `./share/s25rttr/RTTR/SAVE' are the same file
cp: `./../RTTR/s-c_resample' and `./share/s25rttr/RTTR/s-c_resample' are the same file
cp: `./../RTTR/sound-convert' and `./share/s25rttr/RTTR/sound-convert' are the same file
cp: `./../RTTR/sound.scs' and `./share/s25rttr/RTTR/sound.scs' are the same file
cp: `./../RTTR/splash.bmp' and `./share/s25rttr/RTTR/splash.bmp' are the same file
cp: `./../RTTR/texte' and `./share/s25rttr/RTTR/texte' are the same file
CMake Error at /home/kumzugloom/dev/s25client/cmake/preinstall.cmake:14 (MESSAGE):
  ERROR: Preinstallscript failed: Maybe you need administrative privileges?
Call Stack (most recent call first):
  cmake_install.cmake:36 (INCLUDE)

make: *** [install] Error 1
```

**Comment by Flow86** [comment]
yes, you should use "make install DESTDIR=$dirtoinstallto" otherwise it would try to install into the same directory (thats why "are the same file ..." message occur)

**Comment by kumzugloom** [comment]
Thanks. That works indeed.
