### ISSUE TITLE
Seafaring crashes

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#10]
Seafaring crashes the game at the moment quite often, we used to play 1v1 with one AI player and the game crashed two times, we then decided to stop playing.

Also those replays crash if you play them till the end and press "p" to continue.

Note: Those replays may async when "jumping"

http://www.rfmonline.de/rttr/spike/seafaringcrash.rar

**Comment by Flamefire** [comment]
Aren't those issues fixed now? Can you check that again please?

**Comment by Spikeone** [comment]
Guess it's fixed
