### ISSUE TITLE
Build images missing ccmake

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1002]
At least the apple image misses `ccmake` which makes it harder to debug the build process. Any reason this was not installed?

If not, could it be installed?

**Comment by Flamefire** [comment]
Similiar for gdb (host system). I'd want to debug e.g. cmake to find what goes wrong.

**Comment by Flow86** [comment]
I dont think these images need these packages by default

you can easily install them manually if you need them

``` 
apt-get update && apt-get install cmake-curses-gui gdb
```

**Comment by Flamefire** [comment]
The problem is that by default a proxy for apt is configured which needs to be removed first. Without any editor this is hard and you easily forget it. Maybe at least remove the proxy?

**Comment by Flow86** [comment]
oh right, you need to remove `/etc/apt/apt.conf.d/30proxy` too, but I will not remove it, since some builds using these images do install packages every build, and I do not want to download them over and over again.

**Comment by Flamefire** [comment]
What is the purpose of that proxy? From my machine it cannot be reached. Is it something local to the build server?

**Comment by Flow86** [comment]
yes thats a apt-cacher-ng caching all debian packages
