### ISSUE TITLE
README.md doesn't cover libsdl2 deps

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1005]
Which additional deps does the libsdl2 port need? It works for me, but don't know why :) also I think it's now a minimum of gcc-6 for linux?

**Comment by Flamefire** [comment]
Just the SDL2 dev libs.

Yep. Anything capable of C++14

**Comment by stefson** [comment]
but which bindings does it need?

**Comment by stefson** [comment]
Ah, okay, this is some kind of debianism. Nevermind, I'm going to open a pullrequest for the readme to add the deps.
