### ISSUE TITLE
Auto version update broken

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1008]
As we moved the version determination into a subfolder we had to put it into CMake cache. This breaks the auto-update once the date or revision changes.

What shall we do?

Currently the version is required as a (regular or cache) variable in rttrConfig when configuring the header, in the main CMakeLists for CPack and in the (OSX) bundle.

I see 2 options:

1. Set the version (possibly via a CMake function) as a regular variable in the main CMakelists and fatal_error in using code if it isn't set
2. Set the version as a target property of rttrConfig from which it can be queried.

I'd say 1. Any other ideas? @Flow86

**Comment by Flow86** [comment]
thats why I always build with `-DRTTR_VERSION=OFF -DRTTR_REVISION=OFF` in jenkins

**Comment by Flamefire** [comment]
Correct. This forces to get a recent version even if it was set in the cache previously. I'd suggest however to set a common value for `RTTR_VERSION` which is used by all builds in Jenkins to avoid a long running build get 2 versions.

However we need to solve this for local builds too. Shall we go with 1?

**Comment by Flow86** [comment]
> Correct. This forces to get a recent version even if it was set in the cache previously. I'd suggest however to set a common value for `RTTR_VERSION` which is used by all builds in Jenkins to avoid a long running build get 2 versions.
> 
> However we need to solve this for local builds too. Shall we go with 1?

I dont understand that? how should a long running build get 2 versions? Perhaps we should simply disable caching these values?

**Comment by Flamefire** [comment]
If you set `RTTR_VERSION=OFF` cmake will use the current system date for it. If the builds start around midnight this might lead to 2 versions.

> Perhaps we should simply disable caching these values?

The variables are set in the subdir so they are not visible to others unless:
- we set them as cache variables
- we set them in PARENT_SCOPE (might break when multiple parents are there)
- we set them in the top-level CMakeLists
- we set them as a target property

**Comment by Flow86** [comment]
perhaps we should simply generate it manually in the ci build script so the midnight problem can never happen when building via ci?

or we simply set and use the standard cmake project variables CMAKE_VERSION_MAJOR/MINOR/PATCH for it?

**Comment by Flow86** [comment]
(oh its PROJECT_VERSION_....)

**Comment by Flow86** [comment]
oh and I think its not a problem at all, since the ci will only run between 1 and 5 am

**Comment by Flamefire** [comment]
> perhaps we should simply generate it manually in the ci build script so the midnight problem can never happen when building via ci?

That's what I meant above: `I'd suggest however to set a common value for RTTR_VERSION which is used by all builds in Jenkins to avoid a long running build get 2 versions.`   
However we need to handle this for custom builds too.

We currently have:
- `RTTR_VERSION` -> Based on date of build. Sortable.
- `RTTR_REVISION` -> actual commit from which this is build

Which one would you replace by `PROJECT_VERSION`? Except for stables I'd rather keep these 2 but maybe we can join RTTR_VERSION with PROJECT_VERSION? Like `0.9.20190115` if that would be valid.

**Comment by Flow86** [comment]
no 0.9 needs to be specified otherwise somewhere inside the branch files where it should not.
I think its the easiest way to keep it like it is?

**Comment by Flamefire** [comment]
And how shall we solve the auto-update issues? I listed the options above, which would you prefer`?

**Comment by Flow86** [comment]
well, we should keep rttr version and revision separate - the revision should be updated always on each build. version format should also stay the same, but should be regenerated if not set by cmake commandline (is checking cache vs commandline possible?)

**Comment by Flamefire** [comment]
> the revision should be updated always on each build.

This was possible with `-DRTTR_REVISION=OFF` (or not setting it initially but this forces it to be regenerated)

> but should be regenerated if not set by cmake commandline

Same as above

> is checking cache vs commandline possible?

No. There is only cache vs non-cache and IIRC you can't even distinguish between those. So we need to NOT set those 2 in the cache. This way they are regenerated unless they are set on the command line. So we need to decided between the last 3 options from https://github.com/Return-To-The-Roots/s25client/issues/1008#issuecomment-453839618. I'd set them in the top-level CMakeLists (just like PROJECT_VERSION would be set there)
