### ISSUE TITLE
AppVeyor Build fails

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#1010]
Boost 1.64 is not available for VS2015 on appveyor: https://www.appveyor.com/docs/windows-images-software/#boost

**Comment by Flow86** [comment]
oh you already changed it. wtf?

**Comment by Flow86** [comment]
ah! its still wrong here:

https://github.com/Return-To-The-Roots/libsiedler2/blob/master/appveyor.yml

**Comment by Flamefire** [comment]
Fixed https://github.com/Return-To-The-Roots/libsiedler2/commit/5b0586b56635700d428bdae827d00cf58ea72c68
