### ISSUE TITLE
configure can't detect >=libsdl2-2.0.9

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1013]
Did you remove it, or force-pushed something new which I didn't got?

**Comment by stefson** [comment]
this is my binary of libsdl2-2.0.9, if you feel like having a look at the headers and so on: [libsdl2-2.0.9.zip](https://github.com/Return-To-The-Roots/s25client/files/2777010/libsdl2-2.0.9.zip)

**Comment by Flamefire** [comment]
> Could NOT find SDL2 (missing: SDL2_SDL2MAIN_LIBRARY) (found suitable version "2.0.9", minimum required is "2.0.4")

Your libSDL2main.a is missing. How did you install SDL2? In the ubuntu packages it is included: https://packages.ubuntu.com/trusty/amd64/libsdl2-dev/filelist

**Comment by stefson** [comment]
You're right in the sense that libSDL2main.a is missing. It wasn't obvious to me, because having static-libs installed is controlled via USE="static-libs", which was not enabled on my system. However, it wasn't honored by the package manager and the static libs were installed anyway. Now it is - therefore, I lost the static libs during the upgrade without any intention of doing so. With libsdl2-2.0.9 and with static-libs enabled, your config scripts are able to detect it and all is doing just fine. 

Now, one question. If I want to see how libvideosdl2.so is linked it gives me this output: 
```
ldd /usr/lib64/s25rttr/video/libvideoSDL2.so  | grep SDL
	libSDL2-2.0.so.0 => /usr/lib64/libSDL2-2.0.so.0 (0x00007f5f0eca3000)
```
doesn't this imply that it isn't linked against the beforementioned static-libs of libsdl2 at all?

**Comment by Flamefire** [comment]
> doesn't this imply that it isn't linked against the beforementioned static-libs of libsdl2 at all?

Static libs are compiled into the binary so they are not shown in `ldd` etc. SDL(2)main.a is a special library used for static and dynamic SDL(2).
