### ISSUE TITLE
windows: cant start client from junctionpoint

### ISSUE THREAD

**Issue by elonderin** [Return-To-The-Roots/s25client#1021]
i'm a poweruser and use junction points in windows for a lot of stuff. happens that rttr was sitting in one and that doesnt work anymore:

```
PS C:\MNT\sd3d-2_games\s25rttr_20190127> .\s25client.exe
Return To The Roots v20190127-e96fd08dc1a52fb64769394d60685bb9835d363f
Compiled with Gnu GCC C/C++ (7.3.0) for Microsoft Windows 64 Bit

Starting in C:\MNT\sd3d-2_games\s25rttr_20190127
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::read_symlink: The request is not supported: "C:/MNT\sd3d-2_games"
```
the last version that i have been using that didnt have this issue was: s25rttr_20180213 x64

**Comment by Flamefire** [comment]
This is a known issue in Boost: https://svn.boost.org/trac10/ticket/10900 I'm not sure if we can fix this but I'll give it a try.

**Comment by elonderin** [comment]
ok, thx for the answer. dont go out of your way too much, to fix this. a more readable error message would suffice i guess. I just got tripped up by this and seeing the error i had a hunch that the junctionpoint might be the cause.

**Comment by Flamefire** [comment]
@elonderin Can you check with the upcoming nightly ( 48c81c1 ) that it is fixed for you?

**Comment by elonderin** [comment]
hi, i chked both the 48c version and also the latest build 7c39600. the client starts but when loading a game get this:

 ```
 Loading 32 entries: done in 10ms
Loading directory C:\games\s25rttr_20190129\.\RTTR\LSTS\io_new.LST
  Loading 14 entries: done in 5ms
Loading "C:\games\s25rttr_20190129\.\RTTR\LSTS\languages.ini": done in 1ms
Loading "C:\games\s25rttr_20190129\.\RTTR\LSTS\logo.bmp": done in 1ms
Loading "C:\games\s25rttr_20190129\.\RTTR\LSTS\menu.bmp": done in 12ms
finished in 39ms
Loading LST,LBM,BOB,IDX,BMP,TXT,GER,ENG,INI files from "C:\Users\me\Saved Games\Return To The Roots\LSTS"
finished in 1ms
Loading "C:\games\s25rttr_20190129\.\RTTR\MUSIC/S2_Standard.pll"
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::read_symlink: The request is not supported: "C:/games"
PS C:\games\s25rttr_20190129>

```

**Comment by Flamefire** [comment]
Damn. Thanks for bringing this up it shows a serious bug in Boost.Filesystem which might even extend to `std::filesystem` in the C++ standard. I'll see what can be done

**Comment by elonderin** [comment]
as i said, it's not a biggy. unless u feel responsible for the library or want to contribute to it, dont bother on my behalf.

**Comment by Flamefire** [comment]
Should be fixed now by avoiding the buggy functions. I also opened a PR in Boost to fix those there.
