### ISSUE TITLE
-DRTTR_BUILD_UPDATER isn't honored by the build system

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1023]
While I read through the cmake options of the s25client project, I noticed that there seems to be an option do drop the updater from being built. This seems to be controlled via RTTR_BUILD_UPDATER, but passing it to cmake during configure doesn't make a difference, the binary is still built inside of build/libexec/ and also its shown in the build log. 

When I read the CMakeLists of s25client, it seems as if thats more of a logic that enables building the updater for the case of any x86, amd64 or mac system present at build, but disables it for all others. Which would most likely arm being the only one disabled. 

Would you mind making this work?

**Comment by stefson** [comment]
The patch works for me! :) 

I wonder, does this drop the libcurl dependency?

**Comment by Flamefire** [comment]
probably yes
