### ISSUE TITLE
Is there a dependency on xz-utils for s25client?

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1026]
while having a look at the library dependencies of the main binary, s25client that is, the last one surprised me kind of: 
```
ldd /usr/bin/s25client | grep liblzma
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007ff5788a1000)
```
Unless this is some kind of automagic dependency, and thus unwanted, it would require to add it to the list in the readme under how to build (its liblzma5 at runtime, plus liblzma-dev at compile time for debian et al), and it might be a good idea to add a check for it.

**Comment by Flamefire** [comment]
only bzip2 is needed
