### ISSUE TITLE
s25rttr-0.8.2 - submodules are empty and unreferenced

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1027]
I thought about going for an update and to package 0.8.2 for gentoo. 

There are various tags available, I went for 0.8.2-18. 

However, the following submodule folders are empty: libendian, liblobby, libsiedler2, libutil, mygettext, s-c, s25update, version. Which I guess are all submodules? 

So, is there a way to find out which commit to checkout for each submodul?

**Comment by Flow86** [comment]
hi, you simply have to do a

`git submodule init --recursive --update`

**Comment by Flow86** [comment]
or you could use `git clone --recursive ...`

**Comment by stefson** [comment]
ok, so with these I still get an error about libsiedler2: 

Submodul-Pfad: 'RTTR/languages': 'd94221dd85d1ad00164d5f8614f77d95b816a836' ausgecheckt
Submodul-Pfad: 'contrib/kaguya': 'd91418d07ed6096a7bfdade27f10e1e3f24f118d' ausgecheckt
Submodul-Pfad: 'libendian': '81139817f551cf144b25269f4f0bd9c9b0f5e99b' ausgecheckt
Submodul-Pfad: 'liblobby': '30da4cf7d4f17493530b53c98e50e9dff824a4ad' ausgecheckt
Submodul-Pfad: 'libsiedler2': '9309a87a83a2478e9bff588aa74877643f8e32b1' ausgecheckt
Submodul-Pfad: 'libutil': '4a280a340d82a936d6e80ca4565ce3c225fb23c1' ausgecheckt
Submodul-Pfad: 'mygettext': 'efd1f32f5bcb8b7e3bfaaf24bd17fe7cc3ac8920' ausgecheckt
Submodul-Pfad: 's-c': 'c605631fc69a51a3a0ec5634e9a33b9fcdb8cc3c' ausgecheckt
Submodul-Pfad: 's25update': '4de0924f16153db53ce8afe26b7e5c749b262a96' ausgecheckt
Submodul-Pfad: 'version': 'c6228e185a5b81e7ae7269efc7e95f2b59079e21' ausgecheckt

**Comment by Flamefire** [comment]
Don't bother. Wait for the next release before trying this or remove clang-format from your path

**Comment by stefson** [comment]
It is painfull to make it going, true. Do you plan to make a revbump to a possible 0.8.3 in the near future?

**Comment by Flamefire** [comment]
Yes. 0.9 is around the corner. See the website

**Comment by stefson** [comment]
Ok, closing then :) 

(theres actually a bug about localization not working at the moment, I'll hand in a bug report soon)
