### ISSUE TITLE
localization of s25client defaults to english

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1032]
I'm on 6b53e2199de86079085d7f54fe8efc89ccba255c , using glibc 2.27 and my systems gettext is 0.19.8.1

here is a log from starting up s25client and the config file: [startup log and config.zip](https://github.com/Return-To-The-Roots/s25client/files/2829525/startup.log.and.config.zip)
locale

and the output from locale: 
```
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE=C
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
``` 
The language is set to System language, but changing to any other language from the menue does have no effect, whatsoever.

**Comment by Flamefire** [comment]
Is this fixed with the latest nightly?

**Comment by stefson** [comment]
no, it isn't :/

**Comment by stefson** [comment]
this is sort of a head scratcher, because the nightly binary isn't affected by this.

**Comment by Flamefire** [comment]
Sorry I double checked on my linux VM and it works. Try removing your build folder to start fresh. We changed some folders from symlinks to copies which might be the problem

**Comment by stefson** [comment]
Do you know by which commits this has been introduced?

**Comment by Flamefire** [comment]
https://github.com/Return-To-The-Roots/s25client/commit/5098361053fe9b60715ac4d4191758abd22eed52#diff-b2331bbeed80eac30fbaff166b1c6d03

**Comment by stefson** [comment]
I checked out the parent (1ebf9284ea6a0544916bc759cb11fcf55e979b85), to no avail. 

Any other guesses?

**Comment by Flamefire** [comment]
Have you rebuild from scratch? (build folder removed?) Checkout the latest master and make sure all is up to date with `git status`

**Comment by stefson** [comment]
there are two folders created with the language files inside of them: 

build/share/s25rttr/languages/
build/share/s25rttr/RTTR/languages/

the second should be the one which is expected from you point of view, right? 

I use `-DCMAKE_INSTALL_PREFIX=/usr` , so they end up in /usr/share/ - this happens for all files but not for those in `languages` , if copied over with `cp` all is fine :-S

**Comment by Flamefire** [comment]
Ah you try to start from the installed location... I'll check why/what is missing.

**Comment by stefson** [comment]
if you fix the double generation of the languages folder, it should suffice

**Comment by Flamefire** [comment]
This is intentional. The 2nd version is to enable debugging from inside the build tree

**Comment by Flamefire** [comment]
Try this: https://github.com/Return-To-The-Roots/s25client/pull/1038

**Comment by stefson** [comment]
Looks good to me, the folder build/share/s25rttr/languages is gone now. I hope this was your intention? :-)

**Comment by Flamefire** [comment]
One of them, yes

**Comment by stefson** [comment]
fixed, thanks :)
