### ISSUE TITLE
Scrolling with the mouse wheel through the readme is going in the wrong way

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1039]
Scrolling with the mousewheel works sort of, but its going up when the user scrolls down with the mouswheel, und down when the user scrolls up.

**Comment by stefson** [comment]
Same problem with the `Tastaturbelegung` , which is accessable from within the running game.

**Comment by Flamefire** [comment]
Only affects SDL2, fix incoming
