### ISSUE TITLE
readme and keyboardlayout default to english

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1040]
there is a german version for both of them, and if system language is set to german it should be choosen over the english?

**Comment by stefson** [comment]
I know you haven't merged this into the main tree yet, but still I want to leave some feedback: It works now if the language setting is set to `System language`, which means that with my settings from #1032 it gives me the german readme. But if language is set explicitly to German, it still defaults to English.

**Comment by Flamefire** [comment]
Thanks. took care of that, so #1042 should now fix this.

**Comment by stefson** [comment]
I can confirm it is fixed now. 

By the way, I noticed that these symbols are misrendered as a questionmark: `[` `]` `|` `~`
