### ISSUE TITLE
some special symbols aren't rendered when showing the readme from within the game client

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1043]
Instead they are shown as a questionmark. 
This is true for: `[` `]` `|` `~`

**Comment by stefson** [comment]
Are you going to pick this up at some point?

**Comment by Flamefire** [comment]
Added milestone. Needs glyphs for the fonts

**Comment by Spikeone** [comment]
Do those fit?

https://drive.google.com/open?id=1QQ6aiQ02amZjZ2FU15ul3nh65AnKHuls

**Comment by Flamefire** [comment]
I guess so. You you put them into the fonts? See https://github.com/Return-To-The-Roots/s25client/wiki/How-to-edit-fonts, then you can check them yourself if you are satisfied :)

**Comment by Spikeone** [comment]
@Flamefire where can I find the current `lstpacker.exe` ? The link `Download the lstpacker.exe from https://github.com/Return-To-The-Roots/libsiedler2/blob/master/test/lstpacker.exe to create and extract lst-files.` seems no longer valid and I can't find the latest version anywhere - using the old packer for now :)

**Comment by Spikeone** [comment]
![Chars](https://user-images.githubusercontent.com/1276342/66702713-f5c07f00-ed0a-11e9-916b-f4ab78e568ef.png)

This is size 1, no idea where 0 and 2 are used at all.

https://drive.google.com/open?id=1sZ24NZ27KSeq7rOQulVgIECMUxtdXAFR

**Comment by stefson** [comment]
it works now, thank you! :)
