### ISSUE TITLE
Cannot run game on Windows (OpenGL)

### ISSUE THREAD

**Issue by FROGGS** [Return-To-The-Roots/s25client#1050]
Hi, I only see a blank (white) window ang get the following output:
```
Return To The Roots v20190223-2f33ff0075597ff1310e0ba3954262fc1476a3d8
Compiled with Gnu GCC C/C++ (7.3.0) for Microsoft Windows 64 Bit

Starting in C:\s25rttr

WARNING: Your application version has changed - please recheck your settings!

Suche nach Treibern in C:\s25rttr\driver/video
3 video drivers found!
Loaded video driver "(SDL) OpenGL via SDL-Library"
OpenGL 2.0 supported

FATAL ERROR: OpenGL  2.1 is not supported. Try updating your GPU drivers or hardware!

FATAL ERROR: Failed to initialize the OpenGL context!

ERROR: Failed to start the game
Press ENTER to close this window . . .
```

As you can see I'm running the latest version.
This might be related to #1037, but I'm just guessing.
I cannot tell when I played the game for the last time, so I cannot guess at what time it might broke.

Thanks for any pointers.

**Comment by Flow86** [comment]
Hi,

> Try updating your GPU drivers or hardware!

you will need a OpenGL 2.1 compliant video driver. Try updating your driver via the manufactures website. ( i.e www.nvidia.com, www.amd.com, www.intel.com )

The standard windows graphic driver is most of the time extremely outdated and does even not support OpenGL 2.1 (for your information, OpenGL 4.x is the current one ...)

**Comment by FROGGS** [comment]
Okay, it looks like I have to replace my son's laptop then. Since it seems to only support OpenGL 1.5 (Intel 965GM Express Graphics).

This will take a while, but thanks for your help.

**Comment by Flamefire** [comment]
As per the output it seems to at least support 2.0.

At the moment we don't use any OpenGL 2.1 features so we could drop back to 2.0. Will prepare a commit for that, but note that we may switch to 2.1 later on. Just watch the error output as above.

For devs:

OpenGL 2.1 introduced Pixel buffer objects and Non-square matrices in GLSL. When those are needed, update the required version. (OpenGL 2.1 is 13 years old)

**Comment by Flamefire** [comment]
@FROGGS It should work on your sons laptop starting with the next nightly again. Happy playing! :)

**Comment by FROGGS** [comment]
Hi, thank you for the patch!
I'll try and report back here as soon as the nightly covers this commit.
