### ISSUE TITLE
compile fails with gcc-8.2.0

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1053]
did the update from gcc-7 to gcc-8, and now the compile fails: 

/var/tmp/portage/games-strategy/s25rttr-9999-r4/temp/build.log | grep error: -b3
```

272718-[ 36%] Building CXX object external/s25edit/CMakeFiles/s25edit.dir/CIO/CSelectBox.cpp.o
272815-cd /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999_build/external/s25edit && /usr/bin/x86_64-pc-linux-gnu-g++ -DBOOST_NOWIDE_USE_FILESYSTEM -DHAVE_STRUCT_TIMESPEC -D_EDITORMODE -isystem /usr/include/SDL -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/rttrConfig/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libendian/include -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/nowide/include -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/common/include -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/libGamedata -isystem /usr/include/lua5.2 -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/mygettext/include -isystem /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/kaguya/include   -Og -ggdb -mfpmath=sse -msse2  -ggdb   -Wall -pedantic -Wextra -Werror -Wpedantic -Wparentheses -Wno-error=type-limits -Wfloat-conversion -Wno-long-long -Wno-unknown-pragmas -fno-strict-aliasing -Wsuggest-override -Wno-error=suggest-override -std=c++14 -o CMakeFiles/s25edit.dir/CIO/CSelectBox.cpp.o -c /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/s25edit/CIO/CSelectBox.cpp
274215-/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/s25edit/CMap.cpp: In member function ‘void CMap::drawMinimap(SDL_Surface*)’:
274399:/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/s25edit/CMap.cpp:1489:35: error: ‘%d’ directive writing between 1 and 11 bytes into a region of size 10 [-Werror=format-overflow=]
274671-             sprintf(playerNumber, "%d", i + 1);
274737-                                   ^~~~

```
compressed build log: [gcc-8-build.log.zip](https://github.com/Return-To-The-Roots/s25client/files/2980280/gcc-8-build.log.zip)

**Comment by Flow86** [comment]
I think these are the same issues which are blocking #1052

**Comment by Flamefire** [comment]
It will probably be fixed by #1052 when I'm ready. I'm currently including clang-tidy fixes which also found some possible nullptr-derefs and some more stuff which make the code shorter and cleaner.

Intresting though that this is a problem. We test on travis with g++8

**Comment by stefson** [comment]
take your time, it still works with clang-7 instead. 

The output of gcc/g++ may vary between distros. You can't bootstrap a debian/ubuntu rootfs from gentoo for instance, as the patchsets are incompatible.

**Comment by stefson** [comment]
by the way, do you need clang-8 to be tested?

**Comment by stefson** [comment]
clang-8 is fine.

**Comment by Flamefire** [comment]
I'm currently applying fixes found by the static analyzer clang-tidy using version 8. I'll also add this to travis CI as this  leads to cleaner code. Besides that it already found a couple of bugs which are hard to find manually. However this is an enormous amount of work which will take some time.

**Comment by stefson** [comment]
I keep an eye on #1052 , and even though the travis test build now passes for all but clang+macos, it still throws out the same error as before. The checkout of submodules is working as expected: 
```
GIT update -->
   repository:               https://github.com/Return-To-The-Roots/s25edit.git
   at the commit:            c53793aa8202dbbbdec22a0db96bda0b225532a8
```
