### ISSUE TITLE
Crashes using Harbors / Ships

### ISSUE THREAD

**Issue by floomat** [Return-To-The-Roots/s25client#1071]
Hello Guys, first of all - Great work you did here with this game.
But i have a fatal problem, i really like to play maps with Harbors and many Isles but somehow AI does crash the game after some time on these.. thats frustrating, i would like to play it till the end, but no chance.

So here are the facts: 
1. If you abort an Expedition before it loads up the ship on a Harbor, the game crashes.
2. Sometimes the game crashes if you attack an Harbor that has an open Expedition on it. This is the point where you can't play along because you are not able to stop an attack.
3. The Game sometimes even crashes, if you burn down the Harbor if an Expedition is open on it.

I think AI will sometimes stop an Expedition or does something else with it and the game crashes.

If somebody has an Idea that would be great, it is really frustrating if you play for 2 hours straight and then you are forced to quit because it does always crash on the same frame. I tried everything i think.

best regards
Flo

**Comment by Flow86** [comment]
Hi,
can you please upload either a savegame or a so called replay? (.rpl)

**Comment by Flamefire** [comment]
And please state the exact version you are using (if not using nightly, try that first)

**Comment by floomat** [comment]
Sure, it crashes at frame xxx338 for your information, it depends on the harbor southeast of the Red AI-Player, because i attacked it. The game crashes as soon as my soldiers arrive.

I don't know which is the correct replay, i just attach the latest three i have.

I use the latest nightly, just updated through the built in updater before i started playing.
config file says:
version=13
gameversion=3c6e59b1556d1d154d16ed45a7ef4711f64b71bf

[inseltest.zip](https://github.com/Return-To-The-Roots/s25client/files/3353830/inseltest.zip)
