### ISSUE TITLE
can't escape from fullscreen via alt+tab with sdl1 as a videodriver on x64-linux

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1080]
Hey there, just noticed this on testing stuff out randomly. It is possible to switch to the desktop via alt+tab when sdl2 is used, but it's impossible when the older sdl1 is used. This is a problem when the application is passed through gdb for debugging, the debugger catches a crash and thus freezes the application. The only way to escape from here would be to kill X and login from a new session, loosing the debugger output.

**Comment by Flamefire** [comment]
We can't do anything about this as SDL manages the windows. Use SDL2 or multiple monitors to work-around this.

> The only way to escape from here would be to kill X and login from a new session, loosing the debugger output.

Or blindly type the resume command.

**Comment by stefson** [comment]
I see, one simply has to use normal window during debugging.
