### ISSUE TITLE
s25client fails to compile on arm with: "RTTR_USE_UNALIGNED_ACCESS" is not defined, evaluates to 0 [-Werror=undef]  #if RTTR_USE_UNALIGNED_ACCESS"

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1089]
log's are here: 

[config.zip](https://github.com/Return-To-The-Roots/s25client/files/3489841/config.zip)
[error.log.zip](https://github.com/Return-To-The-Roots/s25client/files/3489837/error.log.zip)

this might be from libsiedler2?

**Comment by Flamefire** [comment]
Fixed by #1085
