### ISSUE TITLE
DLLs missing in nightly builds

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1092]
To run RttR you need the "lua52.dll" but this one is missing. 
To run the rttr.bat you need the "libgcc_s_seh-1.dll" but that one is missing too.

It's not possible to run the nightly at the moment.

**Comment by Flamefire** [comment]
Hm. Seems that even the update is not built. Investigating...

@Flow86 Build server reports out-of-diskspace so no new nighlies are deployed
