### ISSUE TITLE
data/win32 is pulled in on non MSVC compilation by gcc

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1096]
I've fooled around a bit with the source code and deleted a few folders, notably the `external/lua` folder, to see wether they get pulled in by accident. 

Now, the folder `data/win32` seem to have included only win specific files and one header, which states in the comment section that it is used exclusivly by `s25client.rc` (what is that even?) 

the removal of the win32 folder makes the build fail with gcc-9.2.0 on linux: 

[gcc-9.2.0.log.zip](https://github.com/Return-To-The-Roots/s25client/files/3503075/gcc-9.2.0.log.zip)

while it passes with clang-9.0.0_rc1 

I'm doing another compile with more stable gcc-8.3.0/clang-8.0.1

**Comment by stefson** [comment]
same with gcc-8.3.0: [gcc-8.3.0.log.zip](https://github.com/Return-To-The-Roots/s25client/files/3503100/gcc-8.3.0.log.zip)

and clang-8.0.1 is fine

**Comment by Flamefire** [comment]
That doesn't seem right. First there is no `data/win32` folder in `external/lua` so those are not related.

`/data/win32/s25client.rc` is a resource script (see the comment there)

The removal of the win32 folder (which one?) has no influence on the error. You probably removed `/external/lua/include` which is what triggers the error.

Not sure why it doesn't happen with clang 8 on your machine as this should be (almost) independent of the compiler. Would need the log and be sure that you didn't put back the lua include folder.

**Comment by stefson** [comment]
Hmm. I don't think that I meant some folder within lua. That was meant as an example on why I chose to delete them, which is to prevent and also to detect unwanted automagic behavior, where the compiler pulls them in regardless of the users intention. 

It's the folder data/win32. The logs are already attached, but as an additional information, here's which folders I deleted from the git checkout: 

```
	# Ensure no bundled libraries are used
	rm -r external/lua || die
	rm -r external/macos || die
	rm -r external/libsamplerate || die

	# this causes an error with gcc
	rm -r data/win32 || die

	# Prevent installation of git stuff
	rm -r external/languages/.git/ || die
	rm external/languages/.gitignore || die
```

The trigger for the error above is this line: 

```
rm -r data/win32 || die
```

**Comment by Flamefire** [comment]
~~Do a clean checkout (or rest state) and your first `rm -r external/lua` should already trigger the error because `/external/lua/include` is deleted.~~

Ups, I thought you meant the CMake `Could not find lua.h in contrib`, but that is only a warning. Please include the error message you are referring to in the original post to help focus on the actual problem.

Found and fixing

**Comment by stefson** [comment]
It's this error here: 

cat gcc-9.2.0.log | grep error: -b2

```
240383-[ 24%] Building CXX object extras/videoDrivers/SDL/CMakeFiles/videoSDL.dir/__/__/__/libs/driver/src/DriverInterface.cpp.o
240514-cd /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999_build/extras/videoDrivers/SDL && /usr/bin/x86_64-pc-linux-gnu-g++ -DBOOST_NOWIDE_USE_FILESYSTEM -DBUILD_DLL -DHAVE_STRUCT_TIMESPEC -DvideoSDL_EXPORTS -I/usr/include/SDL -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/data/win32 -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/driver/include -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/common/include -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/include -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libendian/include -I/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/external/libutil/nowide/include   -O2 -march=znver1 -pipe -mfpmath=sse -msse2  -ggdb -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -pedantic -Wextra -Werror -fno-strict-aliasing -pedantic-errors -Wcast-qual -Wdisabled-optimization -Wfloat-conversion -Wformat-nonliteral -Wformat-security -Wformat=2 -Wimport -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wpacked -Wparentheses -Wpedantic -Wpointer-arith -Wstrict-aliasing=2 -Wundef -Wunused -Wunused-parameter -Wwrite-strings -Wno-unknown-pragmas -Wctor-dtor-privacy -Wnoexcept -Woverloaded-virtual -Wstrict-null-sentinel -Wsuggest-override -Wno-maybe-uninitialized -Wno-error=suggest-override -Wredundant-decls -Wunreachable-code -std=c++14 -o CMakeFiles/videoSDL.dir/__/__/__/libs/driver/src/DriverInterface.cpp.o -c /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/libs/driver/src/DriverInterface.cpp
242250:cc1plus: error: /var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/data/win32: No such file or directory [-Werror=missing-include-dirs]
242449-cc1plus: all warnings being treated as errors
242495-make[2]: *** [extras/videoDrivers/SDL/CMakeFiles/videoSDL.dir/build.make:63: extras/videoDrivers/SDL/CMakeFiles/videoSDL.dir/__/__/__/libs/driver/src/DriverInterface.cpp.o] Error 1
```

The `could not find lua in contrib.h` is just a config warning, which is perfectly fine in my opinion.
