### ISSUE TITLE
some dependency libraries s25client links against are not documented in the readme.md

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1098]
ldd /usr/bin/s25client shows: 

this is all boost: 
```
	libboost_program_options.so.1.65.0 => /usr/lib64/libboost_program_options.so.1.65.0 (0x00007f7199056000)
	libboost_filesystem.so.1.65.0 => /usr/lib64/libboost_filesystem.so.1.65.0 (0x00007f7199015000)
	libboost_system.so.1.65.0 => /usr/lib64/libboost_system.so.1.65.0 (0x00007f719900e000)
	libboost_iostreams.so.1.65.0 => /usr/lib64/libboost_iostreams.so.1.65.0 (0x00007f7198fec000)
```

this is glibc: 

```
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7199033000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7198e1c000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7198ad0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f71988f9000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f71988d4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f71996b6000)
```

this is gcc: 

```	
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/libstdc++.so.6 (0x00007f7198c10000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/libgcc_s.so.1 (0x00007f71988de000)
```

these are covered: it's miniupnpc, lua, bz2, libsamplerate

```
	libminiupnpc.so.17 => /usr/lib64/libminiupnpc.so.17 (0x00007f7198fdb000)
	liblua5.2.so.0 => /usr/lib64/liblua5.2.so.0 (0x00007f7198fa5000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f7198f90000)
	libsamplerate.so.0 => /usr/lib64/libsamplerate.so.0 (0x00007f7198e22000)
```

these are zlib and xz-utils, not documented! 
	libz.so.1 => /lib64/libz.so.1 (0x00007f71988ba000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f7198892000)

todo: find out wether the -dev package is needed for libz.so and liblzma.so ; in case the dev package is needed I'll add them to the readme.md, also mention that curl is optional if not building the updater. 

my questions to you: why doesn't the configure script checks for zlib and xz-utils? And why can I compile the whole project anyway, even when liblzma.so isn't in it's path? 

todo: check the s25edit binary (libbsd, ncurses, glu?)

**Comment by Flamefire** [comment]
The libraries you mentioned are indirect dependencies through boost::iostreams. We don't directly link those so they don't need to be mentioned. Especially as we don't use that functionality.

No -dev packages for those are needed.

Doing a quick check for `find_package` shows that all direct dependencies are documented. Hence closing.

**Comment by stefson** [comment]
Thanks for the explanation, I had no idea that there is such a thing as an indirect dependency. But that def. explains why the binary is linked against liblzma, even though I removed it temporarily: boost links against it, and s25client links through libbost to liblzma.
