### ISSUE TITLE
Replays async when jumping

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#11]
Replays often async when jumping while replaying them. Playing them without a jump (even at 1GF/ms) nothing happens.

Two example Replays
http://www.rfmonline.de/rttr/spike/seafaringcrash.rar

OS: Win7 x64 with RttR x64

**Comment by jhkl** [comment]
The replay "2015-07-06_20-31-29.rpl" goes async at gameframe 166049 regardless of jumping or not jumping for me.

VS Debug Build 32bit, 3bf7f236276e5a4bc139320cb8c84f47fa2ed86a

**Comment by jhkl** [comment]
The same is true for the second replay.

Both replays go async on a ChangeTools (ordering tools or changing production settings for tools) command, but I do not see anything wrong with that command.

I close this with Won't fix for now. Please reopen and add another replay if it happens again while playing with a newer version.
