### ISSUE TITLE
README.md doesn't list all boost deps

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1100]
with libboost-dev and all others installed, the configure looks like this: 

```
CMake Error at /usr/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_system
          boost_filesystem
          boost_iostreams
```

[log-file.zip](https://github.com/Return-To-The-Roots/s25client/files/3513141/log-file.zip)

proposed fix: https://github.com/Return-To-The-Roots/s25client/pull/1099

**Comment by stefson** [comment]
also these warnings appear: 

```
-- Could NOT find SNDFILE (missing: SNDFILE_INCLUDE_DIR SNDFILE_LIBRARY) 
-- Could NOT find FFTW (missing: FFTW_LIBRARY FFTW_INCLUDE_DIR) 
```
they are non fatal, is that correct? seems libsndfile and fftw headers are missing.

**Comment by Flamefire** [comment]
Thanks, merged.

Yes they are not required at all. There is a PR on libsamplerate but it doesn't get much attention: https://github.com/erikd/libsamplerate/pull/69 (should get https://github.com/erikd/libsamplerate/pull/82 merged first due to conflicts)
