### ISSUE TITLE
runtime error with raspbian-10 for s25client

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1101]
here's the log from console: 

```
~/s25client/build/bin $ ./s25client 
Return To The Roots v20190818-376bc8557041e8b679a5de008ec63e96da834986
Compiled with GNU C++ version 8.3.0 for linux 32 Bit

Starting in /home/pi/s25client/build
Suche nach Treibern in /home/pi/s25client/build/lib/driver/video
2 video drivers found!
Loaded video driver "(SDL) OpenGL via SDL-Library"
OpenGL 3.1 supported
Suche nach Treibern in /home/pi/s25client/build/lib/driver/audio
1 audio drivers found!
Loaded audio driver "(SDL) Audio via SDL_mixer-Library"

Starte Spiel
Lade "/home/pi/s25client/build/share/s25rttr/RTTR/splash.bmp": fertig in 91ms
X Error of failed request:  GLXBadContextTag
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  16 (X_GLXVendorPrivate)
  Serial number of failed request:  51
  Current serial number in output stream:  52
```

I used this command for config: 

`cmake -DCMAKE_BUILD_TYPE=Release .. -DRTTR_BUILD_UPDATER=OFF -DBUILD_TESTING=OFF`

The hardware is a rpi2, but as I stated I haven't used the optimizations. Maybe something in the cmake scripts has decided to go for opengl-3.1, but the rpi doesn't allow that? Does the cmake script detect opengl comp at compile time? 

p.s: s25edit works just fine :-)

**Comment by stefson** [comment]
strace from the binary's startup: [strace.log.zip](https://github.com/Return-To-The-Roots/s25client/files/3513396/strace.log.zip)

seems like a bug in raspbian?

**Comment by Flamefire** [comment]
Probably a bug in the OpenGL lib (try to google the error and you'll find more)
You can try SDL2 too, maybe that works.
