### ISSUE TITLE
Fullscreen not working with Windows 10

### ISSUE THREAD

**Issue by BestNoob** [Return-To-The-Roots/s25client#1113]
Hello,
i dont know the reason ... but often its not doable to go into fullscreen on Windows 10 x64
Taskbar visible or it simply wont go from windowed to fullscreen. Nvidia graphics card.

**Comment by Flamefire** [comment]
Make sure SDL2 is selected in the video settings section of RttR. That should work better.

**Comment by Spikeone** [comment]
@BestNoob Any luck trying SDL2?

**Comment by BestNoob** [comment]
I didnt played enough to say more about this. But SDL2 doesnt had an effect for me.

**Comment by neXorianus** [comment]
Running nightly: `s25rttr_20200516` on WIN 10, starting the `rttr.bat` or the `s25client.exe` both gave me totally nice fullscreen (with SDL2).
Tried tabbing in and out a few times didn't give me any problems either.

Running the Game in WinAPI AND windowed in my screens native resolution made the game window shift up, so i could not grab the window bar or move it... 
In this mode, the Taskbar also is in front of the game!
But if i reposition the game in SDL2 Mode and switch back to WinAPI, the Windowbar is visible and can be dragged to be correctly on screen

Interestingly, setting the game to (native Screen res.) 1920x1200 windowed actually respects the Taskbar and the Window bar (both horizontal and vertically).
![image](https://user-images.githubusercontent.com/1299616/82236179-0a659500-9934-11ea-852c-2f2dfb648294.png)

One flaw i saw is when switching between drivers is, that the game may shift up and left a little.

**Comment by Flamefire** [comment]
Treating this as fixed in SDL2 (the recommended driver)

Switching between drivers without a restart just works. No guarantees about positions or sizes are given unless fullscreen is used, so deviations are fine and cannot be easily avoided anyway.

**Comment by Spikeone** [comment]
I ask Nexor to test it and @Flamefire steals the "close" :x

Just kidding, thanks for testing @neXorianus
