### ISSUE TITLE
[wish] Replays im Spiel löschen

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#112]
Hey Jungs!

ich wünsche mir, dass man im Spiel einzelne Replays (wenns geht auch Speicherstände) löschen kann.
Ich hoffe das ist nicht zu aufwändig.Für mich wäre es auf jeden Fall eine Bereicherung!

https://bugs.launchpad.net/s25rttr/+bug/610853

**Comment by Flamefire** [comment]
Deleting savegames too would be possible, but we'd need a design for that. So postboned.
Replays can be deleted now.
