### ISSUE TITLE
Teamvictory not working

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1120]
Looks like teamvictories are broken again.
Setup:
7 Players on Christmas
2 Players human, Team 2
5 Players AI, Team 1
Random start location

After defeating all enemies no victory window popped up, I thought I'd forgotten to enable it so I gave up. Suddenly the victory window for my ally popped up.

![2019-10-10_23-01-59](https://user-images.githubusercontent.com/1276342/66634984-8bc2af80-ec0e-11e9-8b9b-dc325d3a79a0.png)

https://drive.google.com/open?id=1WnoRB974VhSD6g77ZOikM96XbTkLNeqC

**Comment by Spikeone** [comment]
Edit: We used "Total domination" and I guess teams are simply no longer honored by that option

**Comment by Spikeone** [comment]
Working in the latest rev (20200113)

**Comment by Flamefire** [comment]
Just checked the code: The values are updated with statistics. This means only after 750 GFs. 

I guess TotalDomination should simply mean: No enemies alive? If so the code has to be corrected and can be simplified.

**Comment by Spikeone** [comment]
Oh, since when? I remember maqs who was thinking about how to implement and check any possible combination

**Comment by Flamefire** [comment]
Sorry I don't understand what you mean. All works as intended. The locked team restriction was probably added so you can't form teams kill the last one and be the winner. Or have temporary teams but winning is only possible afterwards. E.g. team up against AI and kill each other after

**Comment by Spikeone** [comment]
Well, I didn't knew we had such restrictions. Maqs once added a check for temporary teams (as far as I remember) so they can win in fact as we don't have such thing as "force all treaties to break" or  something alike.
But good to know it works that way ;). Although I don't think this is very transparent for the player, I have no idea how one could change that (apart from force-removing the last team).

**Comment by Flamefire** [comment]
> Maqs once added a check for temporary teams

Not sure what this means. There is a check that the teams are locked otherwise team victory isn't even checked. 

> Although I don't think this is very transparent for the player, I have no idea how one could change that (apart from force-removing the last team).

Well if there are no teams at the start there is no team victory. This seems pretty reasonable to me. I guess this is also due to the fact, that we implemented "teams" as players having treaties right from the start so we don't distinguish treaties and teams later. Maybe we should... Locked teams then means that the team is kept otherwise a treaty is established and the "team" removed. You can create new treaties during the match but team victory means that the team from the start  (with locked teams) wins.   
What do you mean by force-removing the last team? With what goal?

**Comment by Spikeone** [comment]
> Not sure what this means. There is a check that the teams are locked otherwise team victory isn't even checked.

I was pretty sure it was. I remember (maybe I'm wrong) that @MarcusSt once thought about the way how to implement a team victory, e.g. Player 1 is in Team A and Team B, Player 2 is in Team A, Player 3 is in Team B - now the setting is 75% size of country, player 1 may win with Team A or Team B. Thats why I was sure, that we had a check for dynamic team victorys.

> Well if there are no teams at the start there is no team victory. This seems pretty reasonable to me. I guess this is also due to the fact, that we implemented "teams" as players having treaties right from the start so we don't distinguish treaties and teams later.

> Just checked the code: The values are updated with statistics. This means only after 750 GFs.

Guess that was the reason. We were teamed (and guess even locked teams) but did not wait 750GFs. I 'd expect the "total domination" victory to be checked every time a player gives up / is defeated.

> What do you mean by force-removing the last team? With what goal?

In some games those "temporary" teams are simply auto-broken if there is only 1 team left. E.g. Player 1 and 2 are in Team A, Player 3 is alone. Player 3 is defeated - now only 1 Team but 2 Players remain. In some games now Team A is simply removed, in other games there is a timer and the the team gets removed. That way the remaining 2 players are forced to fight each other - for total domination.

But then again I'd never play with dynamic teams as only 1v1, 2v2, 3v3, 4v4 play fair :p

**Comment by Spikeone** [comment]
@Flamefire the replay is still linked in the issue description

**Comment by Flamefire** [comment]
Oh thanks. Yes issue is lockedTeams=false

**Comment by Spikeone** [comment]
Hm - why the heck did I disable that :D sorry :x

**Comment by Flamefire** [comment]
Maybe we should show a message somewhere when all players have teams, victory conditions are enabled and locked teams are disabled? Where and how?

**Comment by Spikeone** [comment]
Well, maybe give a choice in the "victory" window - end game, disband all teams, continue?

**Comment by Flamefire** [comment]
And then? 4v4, 1 team wins, disband teams, 2v2 is established during this "after match" and victory needs to be rechecked again, then 1v1?. IMO victory should be shown once only

**Comment by Spikeone** [comment]
Well, disband and lock teams I meant^^

**Comment by Flamefire** [comment]
Hm, that would be new to change the game settings mid-game... I'd prefer a message on game start I think. Maybe we could add a message when you are the last team. Not to great though as that could have to be shown multiple times.

**Comment by Spikeone** [comment]
Or simply display a text message in the chat when unlocking the team, telling "When playing without locked teams, only one player may win but not a team!"?

**Comment by Flamefire** [comment]
I'd rather show this message only when everyone has a team and lock is deactivated. This would need a persistent message somewhere which I'm not sure where...
Showing it to often (eg not everyone has a team) might annoy people

**Comment by Spikeone** [comment]
You do not change that setting very often - you may enable and disable it one or two times, this is still resonable. Not talking about showing it everytime a player sets a team :)
