### ISSUE TITLE
Use UTF8 codepage on windows

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1130]
We currently use a slightly modified version of [Boost.Nowide](https://github.com/artyom-beilis/nowide), which was accepted into Boost 2 years ago, but hasn't made any progress into inclusion.

After a few bugs were fixed it is working quite well but has a few drawbacks:
- Another dependency
- More includes -> compile time
- Own implementation of `basic_filebuf` with limited functionality (no conversion) and (almost) no buffering leading to worse performance on windows, see https://github.com/artyom-beilis/nowide/issues/31

A solution is to require Windows 10 1903 as the minimum version for RttR and use the [UTF8 codepage](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page) via manifest. Then swap out all uses of Boost.Nowide by their Boost.Filestream counterparts (for `boost::filesystem::path` support) or even the `std` ones.

I'm pretty sure this will work "always", as boost functions using `path` continue to use the wide API and conversion from strings will use UTF8 as input (and output the other way). The filestreams will use the narrow API with (now correct) UTF8 encoded strings.

There is a difference when using `boost::filesystem::fstream` though: On MSVC it will use the wide API (MS extension), while it uses the narrow API on GCC/MinGW: https://github.com/boostorg/filesystem/blob/93f0c76869c8a7a04b79f0719393f31b878284a2/include/boost/filesystem/fstream.hpp#L27

Remaining downside: `boost::filesystem::path` stores paths on windows as `widechars` wasting space and runtime on conversion. Even the `std` one has the same behavior.

This drops support for Win Vista, 7, 8, unpatched 10.

So intermediate solution: Use a custom repo with a fork of Boost.Nowide (e.g. mine) as a submodule (or better: a subtree) of libutil. With the subtree approach nothing really changes: The source will still be there. A custom fork should be used, to use clean CMake files and have my bugfixes applied.

**Comment by Flow86** [comment]
I think we can first do this step in about 6-7 months (when MS support for windows 7 is definitly over, with half a year additional time)

**Comment by Flamefire** [comment]
I don't think this even solves all our problems: How can we get UTF-8 encoded arguments? They are passed to main which is the earliest point we could change the codepage and hence already to late.

**Comment by Flamefire** [comment]
After BoostNowide got included into Boost and fixed the performance issues I think this is no longer worth the trouble.
