### ISSUE TITLE
Convert external sources in libutil into git subtrees

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1131]
libutil has some external libraries which are currently "stupid" code dumps, some even modified. I added some "source.txt" files to it to help tracking it.

The better solution is git submodules, but that has the drawback that we now require recursive submodules (s25client->libutil->nowide) and in some cases they have submodules too, which we don't want but would get with `git submodule update --recursive`

So I'd suggest to use git subtree, add a simple shell script to set up relevant remotes (executable from git bash on windows too) and a short docu with C&P commands to update a subtree.

As all(?) libs contain changes, I'd clean up my forks of them and use my forks as the source. This has the benefit of being able to accept or cherry-pick patches from others.

I expect the work to be minor and hence suitable for 0.9

This came up with #1130

**Comment by Flow86** [comment]
we should provide our own forks in Return-To-The-Roots for that instead (and use git subtree... like you said)

**Comment by Flamefire** [comment]
I can transfer my fork of Boost.Nowide when I'm done fixing it. I'm going over it and fix and add tests to make it fully reliable. I have a subtree local branch where I also remove the utf8cpp library (Boost.Local and Boost.Nowide provide everything) and it's looking good so far

**Comment by Flow86** [comment]
good

**Comment by Flow86** [comment]
any progress on that, or should we postpone it after the release?

**Comment by Flamefire** [comment]
Git subtree turned out to be incredibly hard to work with so I abandoned that.

I went with CMakes `FetchContent` and removed utf8cpp completely in favor of what BoostNowide provides. So this is solved now.
