### ISSUE TITLE
Do you plan release a new stable release after 2 years?

### ISSUE THREAD

**Issue by cr0ssmind** [Return-To-The-Roots/s25client#1142]
Do you plan release a new stable release after 2 years? :-)

There was a huge amount of development - sdl2, etc..

**Comment by Flamefire** [comment]
Yes. See tracking issue https://github.com/Return-To-The-Roots/s25client/issues/1088 and milestone https://github.com/Return-To-The-Roots/s25client/milestone/1

**Comment by cr0ssmind** [comment]
Thank you! :)
