### ISSUE TITLE
[Addon] Refund Resources

### ISSUE THREAD

**Issue by Vinkdicator** [Return-To-The-Roots/s25client#1149]
Oftentimes I want to destroy my mines but wish that the food could be taken out of them first. I was thinking maybe an addon where the food (or water or iron etc) could be added to the refund portion when the building is destroyed could work.

**Comment by Spikeone** [comment]
Well, that one is german as well (because they are quite old) but its a duplicate of #67

**Comment by Flamefire** [comment]
@Spikeone Maybe you could translate the old issues are copy request texts like this into the old issues when they appear?
