### ISSUE TITLE
[LUA] RegisterTranslations not working correctly

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1153]
I finally found time (and motivation) to have a look at the mission scripts and add the english translations.
Sadly RegisterTranslations seems not to work as expected.
I added en_GB and de (as in the test), english is working quite fine but it looks like it is always used. I'm referring to the lines in the script:

L37: msg1 is defined (en_GB)
L84: msg1 is defined (de)

When calling _('msg1') I always get the  english text - even if I set the game to German (rather than System Language).

Strangely enough, the _('Diary') is translated, but it doesn't look like it comes from my translations. I changed
L82: Diary = 'Tagebuchssss',

but the Code in L134 still shows the Title 'Tagebuch' when setting the game to german.

[MISS200.zip](https://github.com/Return-To-The-Roots/s25client/files/4015850/MISS200.zip)

Can you please have a look into this @Flamefire ?

**Comment by Flamefire** [comment]
Your argument is wrong: You need to pass in a single table where the keys are languages and the values tables of translated strings. You passed in multiple tables. Unfortunately it doesn't seem possible to catch cases where to many arguments were passed.

I'll add a log entry for when a translation is not available together with the available translations which allows to detect this easier. Could you document this function in the wiki?

**Comment by Spikeone** [comment]
Argh, missplaced those brackets. Thanks!

And yes, gonna update the wiki, but I first wanted a working example :)
