### ISSUE TITLE
[LUA] Can't forbid player changes

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1160]
You can forbid the player to change aiNation, aiColor, aiTeam but sadly you can't forbid changing teams for the player (nor color or nation).
This should be possible as well.

**Comment by Flamefire** [comment]
You have ownNation, ownColor, ownTeam for that. I updated the wiki, thanks for catching that.

**Comment by Spikeone** [comment]
Ah, thanks :)
