### ISSUE TITLE
Compiling s25util_common fails

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1161]
I wanted to 'fix' some minor stuff, so I followed the instructions given. I guess everything was working okay (although some stuff failed when running b2.exe).

Now I'm having this problem:
```
1>------ Erstellen gestartet: Projekt: ZERO_CHECK, Konfiguration: Debug Win32 ------
1>Checking Build System
2>------ Erstellen gestartet: Projekt: nowide-static, Konfiguration: Debug Win32 ------
3>------ Erstellen gestartet: Projekt: endian_static, Konfiguration: Debug Win32 ------
2>Building Custom Rule F:/RttRV3/s25client/external/libutil/nowide/CMakeLists.txt
3>Building Custom Rule F:/RttRV3/s25client/external/libendian/CMakeLists.txt
3>read.cpp
2>cstdio.cpp
3>write.cpp
2>iostream.cpp
3>endian_static.vcxproj -> F:\RttRV3\s25client\build\external\libendian\Debug\endian_static.lib
2>system.cpp
2>Code wird generiert...
2>nowide-static.vcxproj -> F:\RttRV3\s25client\build\external\libutil\nowide\Debug\libnowide.lib
4>------ Erstellen gestartet: Projekt: s25util_common, Konfiguration: Debug Win32 ------
4>Building Custom Rule F:/RttRV3/s25client/external/libutil/libs/common/CMakeLists.txt
4>BinaryFile.cpp
4>LocaleHelper.cpp
4>MyTime.cpp
4>Serializer.cpp
4>SingletonPolicies.cpp
4>StringConversion.cpp
4>System.cpp
4>System_Win32.cpp
4>Tokenizer.cpp
4>fileFuncs.cpp
4>getExecutablePath.cpp
4>md5.cpp
4>strFuncs.cpp
4>tmpFile.cpp
4>ucString.cpp
4>C:\Program Files (x86)\Windows Kits\8.1\Include\um\shlobj.h(1054): error C2220: Warnung wird als Fehler interpretiert, es wurde keine object-Datei generiert. (Quelldatei wird kompiliert F:\RttRV3\s25client\external\libutil\libs\common\src\System_Win32.cpp)
4>C:\Program Files (x86)\Windows Kits\8.1\Include\um\shlobj.h(1054): warning C4091: "typedef ": Ignoriert auf der linken Seite von "tagGPFIDL_FLAGS", wenn keine Variable deklariert wurde (Quelldatei wird kompiliert F:\RttRV3\s25client\external\libutil\libs\common\src\System_Win32.cpp)
4>Die Erstellung des Projekts "s25util_common.vcxproj" ist abgeschlossen -- FEHLER.
========== Erstellen: 3 erfolgreich, 1 fehlerhaft, 0 aktuell, 0 übersprungen ==========
```
I'm not sure if this could be caused by this when running the bootstrap.bat: 

![image](https://user-images.githubusercontent.com/1276342/71777177-90dc9400-2f9c-11ea-8c11-967a25c290c1.png)

System: 
- MSVC2017 (but using 14.0 toolset)
- boost 1.72.0
- cmake 3.16.2

Guess I did something wrong then, can someone help?

**Comment by Flamefire** [comment]
Are you using WIn10 or Win8.1?

Why the 14.0 toolset? This is for Boost, isn't it? Then it means take the MSVC2015 compiler and might not work with MSVC2017

The error is caused by MS fucking up. -.- Can you try updating your SDK? Either via VS installer or from https://developer.microsoft.com/de-de/windows/downloads/sdk-archive

**Comment by Spikeone** [comment]
Well, I installed boost with 14.1 again, I uninstalled and reinstalled the latest win10sdk / win8.1 sdk I can get via installer (although there is 1 newer win10sdk but the error is a 8.1 sdk error).

I'm using neither windows 10 nor windows 8.1, using 7.

I disabled warnings as errors for the s25util_common - which lets me build and run :)

**Comment by Flamefire** [comment]
After you reinstalled 8.1 SDK did the error change? Usually this should not happen because this is a system header where no error should be reported.

I double checked with the latest 8.1SDK from the above site and the mentioned line is different.

**Comment by Spikeone** [comment]
Installing the 8.1 SDK again AND uninstalling the 8.1 SDK in vs worked - thought they are the same but looks like they don't
