### ISSUE TITLE
[Wiki/LUA] How to find AddonIds

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1162]
@Flamefire can you please write down how to find the AddonId for SetAddon?

I found out this is working: `rttr:SetAddon(ADDON_FRONTIER_DISTANCE_REACHABLE, true)` by checking your tests where any addon ID I could find was simply prefixed with ADDON_, did so as well for the FRONTIER_DISTANCE_REACHABLE addon and it also works.

Is there a better way to find the correct IDs or is it the way to go?

**Comment by Flamefire** [comment]
That is correct: The name is `ADDON_` + any of those: https://github.com/Return-To-The-Roots/s25client/blob/master/libs/s25main/addons/const_addons.h#L50

**Comment by Spikeone** [comment]
updated
