### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by spacemanspiff2007** [Return-To-The-Roots/s25client#1164]
The Editor crashes without error messages when I try to click the arrow button

![grafik](https://user-images.githubusercontent.com/10754716/71795360-1a946c00-3046-11ea-9736-b6f6fefe91d2.png)

**Comment by Spikeone** [comment]
moved this issue to https://github.com/Return-To-The-Roots/s25edit/issues/25 as it's s25edit related, not s25client :)
