### ISSUE TITLE
[LUA] IsInRestrictedArea seems to work wrongly

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1168]
While trying to figure out a good way to lift restricted areas for the AI, I found the function IsInRestrictedArea.

Sadly this functions seems to be called although the spots are not restricted (see screenshot).
![image](https://user-images.githubusercontent.com/1276342/72140396-f5c72e00-3390-11ea-8091-83b2d3b022bd.png)

I'm using the script attached.
[MISS202.zip](https://github.com/Return-To-The-Roots/s25client/files/4044781/MISS202.zip)

Or am I doing something wrong?

**Comment by Flamefire** [comment]
Erm: A function returns a value. `IsInRestrictedArea` returns if the point IsInRestrictedArea. No points are shown as restricted in your screenshot. Hence working as expected.

**Comment by Spikeone** [comment]
@Flamefire the documentation says it returns true if the given point is in a restricted area:

> IsInRestrictedArea(x, y)
> Return true if (x,y) is in the restricted area

As this point is not in the restricted area, it should return false, shouldn't it?

**Comment by Flamefire** [comment]
I guess we need a better name. "Restricted" means "bounded, partially allowed". In this case the restricted area is the area where you are allowed to build. I find it very hard to define via this polygon-with-holes. I'm for renaming GetRestrictedArea to GetAllowedPoints and add functions AddAllowedArea, RemoveAllowedArea which take 1 polygon and add/remove the points inside the polygon from the list of allowed points.

But probably this is not even what we want, is it? Wasn't this in the original the area the AI would not build (or build all but military)? Is the current restricted area even useful? Do you ever want to disallow a player from having buildings( or territory, what was it?) in an area?

**Comment by Spikeone** [comment]
Ah, you are right. We always first set a restricted area to allow building, so if  building is allowed it is restricted. So if you don't keep that in mind the naming seems missleading.

Well, it does not reassemble the original thats right. Also there is the problem, that lifting the  restriction does not force an update for any border next to it. On the other hand, thats the only way you may create something like the original ending maps.
The original simply forbid building military buildings in certain areas. We once discussed that in the forum and agreed, that it'd be great to have something like the restricted areas but that you can pass a list of buildings restricted in that area. That way you could even create a swamp where only barracks are allowed and stuff like that.

So, currently, this works close to the original but does not look alike and in some cases even ugly. As I'm currently playing all the missions again and check what needs be done, this does not seem (yet) very important for now. Well, maybe only the update thingy ;)

**Comment by Spikeone** [comment]
@Flamefire thats where I discussed this with etother some time ago. https://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1611

**Comment by Flamefire** [comment]
I don't mind ditching the function and use a better one. E.g. `Disallow/AllowMilitaryBuildingsInArea`.

Restricting to building types is something I don't really like. It could feel strange for users. I'd say use terrain for that.

Other question is whether this should be for AI only or for all players.

Feel free to design this feature and present it in an issue with pros/cons and considered alternatives summarized :)
