### ISSUE TITLE
RttR sometimes hangs when opening windows

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1169]
Lately RttR often simply "hangs" when opening a new window. Often one you haven't before. In my case I had this (~20sec) application freeze in those cases:

- I opened the building overview
- I opened the attack window
- I opened the building info window of a lookout tower

Only thing that is familar:

- It was on scripted maps
- Those buildings were enabled after the game started

maybe it is somehow related to that, gotta test it
EDIT: Can't reproduce it, neither by replay nor by setting up the scenario I described

**Comment by Flamefire** [comment]
No idea what could cause this. Only known hang is when opening a text window (e.g. readme) because it has to find + read the file and calculate all the linebreaking out of a single string which takes some time. But it should be quite fast nonetheless and barely noticeable in release builds

**Comment by Spikeone** [comment]
Well, as I'm currently trying the reworked mission files, I will try to remember my exact action when the game hangs the next time. But as this happened 3 times in different situations I think this could happen more often.

**Comment by Flamefire** [comment]
If you find anything to reproduce this kinda reliably I'll look into it. Until then I'd have no idea what to look for.

**Comment by Spikeone** [comment]
This did not happen in the games I played lately so no idea what the cause is/was.
