### ISSUE TITLE
Version too long for game menu

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1170]
The version text is too long for the Game menu window

![image](https://user-images.githubusercontent.com/1276342/72204663-c5f45500-347a-11ea-9fe1-454be890efa9.png)

**Comment by Flow86** [comment]
perhaps we simply make it a bit higher and add a 3rd line here? 

like this:
```
Return To The Roots
v2020...
Copyright ...
````

**Comment by Flamefire** [comment]
Like this ?
![2020-01-19_22-00-24](https://user-images.githubusercontent.com/309017/72688398-27659500-3b07-11ea-9e41-f25d5a0b94d2.png)

**Comment by Flow86** [comment]
much better :+1:

**Comment by Spikeone** [comment]
Although we may drop the space between (C) and 2005 :p
