### ISSUE TITLE
Victory window uses invalid glyph

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1180]
![image](https://user-images.githubusercontent.com/1276342/72634963-03198500-395c-11ea-92d0-43bb61f40406.png)

**Comment by Flow86** [comment]
looks like the newline is not handled properly

**Comment by Flamefire** [comment]
Yes correct. A ctrlText is used, which is only for single lines

**Comment by Flamefire** [comment]
From my test with change:
![2020-01-19_16-30-54](https://user-images.githubusercontent.com/309017/72683608-30d80880-3ad9-11ea-9b4b-71b5cda282a8.png)
