### ISSUE TITLE
[LUA] RttR can't load games with scripts that use umlauts

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1183]
I've just created a mission, saved the game and tried to load it. Sadly the game stops working as translations seem not to load properly.

I guess this is caused by german umlauts.

Savegame attached.

[tyran01.zip](https://github.com/Return-To-The-Roots/s25client/files/4081267/tyran01.zip)

**Comment by Flamefire** [comment]
Can you attach the original? There is a U+FEFF in front of the lua script which triggers this as the lua interpreter seems to be unable to handle it although it is (kinda) valid

**Comment by Flamefire** [comment]
Ah, this is a ByteOrderMark. I'll fix this so this gets handled

**Comment by Spikeone** [comment]
[tyrann01.zip](https://github.com/Return-To-The-Roots/s25client/files/4083389/tyrann01.zip)

Well, it was originally coded as ANSI, but that did not work with 'ä' etc as the game said unknown character, so I saved it as Unicode - which didn't work with RttR either, so I saved it as UTF-8 which then worked.
Maybe thats what the char comes from.

**Comment by Flamefire** [comment]
Yes everything in/for RttR must be UTF-8 (except the maps which use OEM, but that shouldn't bother anyone). Some programs use a byte order mark at the start of the file which is mostly useless. Some lua version can handle this when loading a file, but not when loading from a string like in a savegame.

I now simply detect and remove it during load and only use 1 load method so it either fails when creating the game or never , not succeed on start but fail to load
