### ISSUE TITLE
Computer is lacking wood to build a sawmill at the beginning of a game

### ISSUE THREAD

**Issue by 88ernie** [Return-To-The-Roots/s25client#1198]
Just like in the title, computer players can't build a sawmill. Sometimes it's 1 player, sometimes all (in the replay I belive it's 3 computer players). It happens on settings with: hard AI, very low goods at start and computers being in teams set.

Version: stable and nightly (20200328, ebde280)

To see it you can just watch the replay or start a game with these settings.

Replay:
[2020-03-29_19-56-57.zip](https://github.com/Return-To-The-Roots/s25client/files/4399478/2020-03-29_19-56-57.zip)

**Comment by Spikeone** [comment]
Hey,

when using very low goods the AI doesn't perform well. This has been reported here: #953

**Comment by 88ernie** [comment]
Hi,
ok i see. I'm green in programming but isn't a solution here to add maybe 2 boards of wood for a computer  that he could build sawmill and then he would be able to work properly?

**Comment by Spikeone** [comment]
It'd be better if the AI worked properly. But you can create a lua script which simply changes wares (or even disables all buildings but the sawmill until finished) to fix that issue.

**Comment by 88ernie** [comment]
Ok, thanks for information, Maybe I'll try to do it :)
