### ISSUE TITLE
0.8.2 crashes when hosting a game

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1200]
When hosting a game via internetlobby (possibly lan / direct IP as well) the game crashes. Hosting a singleplayergame works fine.

**Comment by Flamefire** [comment]
We should just push out a new version. I don't think checking 0.8.2 for issues is worth it...

**Comment by Flow86** [comment]
confirmed - but perhaps its definitely better to push out a new version - what was missing for 0.9?

**Comment by Flamefire** [comment]
See https://github.com/Return-To-The-Roots/s25client/milestone/1

I'd include the SDL2 change and (my currently local branch) of some libutil changes (namely Boost.Nowide use and removal of utf8cpp)

**Comment by Spikeone** [comment]
@Flamefire @Flow86 
Guess we could push back #935 #1112 to 0.9.1
But I think we should include #1182 (which'd be on my side)
