### ISSUE TITLE
can't start 25client binary anymore with recent git-lfs changes

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1201]
```
~/s25client/build/bin $ LANG=C ./s25client 
Return To The Roots v20200407-b184727193bcdfb08f81db96125d6f5d057377e9
Compiled with GNU C++ version 9.2.0 for linux 64 Bit

Starting in /home/tim/s25client/build
Searching for drivers in /home/tim/s25client/build/lib64/driver/video
2 video drivers found!
Loaded video driver "(SDL2) OpenGL via SDL2-Library"
OpenGL 4.6 supported
Searching for drivers in /home/tim/s25client/build/lib64/driver/audio
1 audio drivers found!
Loaded audio driver "(SDL) Audio via SDL_mixer-Library"

Starting the game
Loading "/home/tim/s25client/build/share/s25rttr/RTTR/splash.bmp": done in 1ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PAL5.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PAL6.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PAL7.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PALETTI0.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PALETTI1.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/S2/GFX/PALETTE/PALETTI8.BBM": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/RTTR/COLORS.ACT": done in 0ms
Loading "/home/tim/s25client/build/share/s25rttr/RTTR/LSTS/fonts.LST": failed: File had the wrong header. Possibly wrong file format


ERROR: Some files failed to load.
Please ensure that the Settlers 2 Gold-Edition is installed 
in the same directory as Return to the Roots.
Clearing textures: Finished in 0ms
```

**Comment by stefson** [comment]
I don't really understand what is happening here, I've got git-lfs installed and followed the instructions, as usually. It's possible to restore the old file from git history and replace the new file with the old one, which makes it all work again. 

the nightly binary hosted on siedler25.org is unaffected by this behavior.

**Comment by Flamefire** [comment]
You likely missed the updated instructions. You need to call once `git lfs install` and now (as you already checked out) `git lfs pull`

**Comment by Flamefire** [comment]
Oh those are only in the PR yet: https://github.com/Return-To-The-Roots/s25client/pull/1193/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by stefson** [comment]
Can you promise to release the upcoming v0.9.0 with all these files you now transformed to git lfs in the tarball, please? It's seriously difficult to implement this git lfs commands with package managers, and might not be tolerated by the individuals distro's policies of not downloading anything additional than the source file itself. 

By the way, if you pull a zip file via https://github.com/Return-To-The-Roots/s25client/archive/master.zip it still doesn't include these lst files you now moved to git lfs, but only the asci txt files acting as their link.

**Comment by Flamefire** [comment]
Likely a good idea. I've got something which I can easily adapt. Will check soon

**Comment by Flamefire** [comment]
@Flow86 That's a serious downside of git lfs: The additional commands required on checkout and not having all files even from this repo in the archive :/ Not even sure if one would notice that a checkout contains wrong/outdated files

**Comment by Flow86** [comment]
any modern git should automatically have git-lfs installed. most probably the package should contain a build-dependency to git-lfs. (i.e I don't need to manually do a "git lfs install" on a fresh checkout)

**Comment by stefson** [comment]
that's not exactly true. I had to ~~install~~ compile go-bootstrap, go and compile git-lfs. 

Also my distro doesn't have git-lfs support for packages who need it at compile time, source: https://github.com/gentoo/gentoo/blob/master/eclass/git-r3.eclass 

This also shows the amount of effort needed to tame git itself, let alone speak of git-lfs.

**Comment by Flamefire** [comment]
> any modern git should automatically have git-lfs installed. most probably the package should contain a build-dependency to git-lfs. (i.e I don't need to manually do a "git lfs install" on a fresh checkout)

Nope. I just installed a fresh Linux Mint (Ubuntu 16 based) and installed the git package, but had to install git-lfs separately and also issue `git lfs install` manually afterwards. I've forgotten that as it's been long since I set up my PC.

**Comment by Flow86** [comment]
ok then its only on windows where its included automatically

**Comment by Ekliptor** [comment]
currently also running into a git fs issue. Without those files the build fails with the same error as above

```
git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/Return-To-The-Roots/s25client.git/info/lfs'
```

**Comment by Flamefire** [comment]
> It's seriously difficult to implement this git lfs commands with package managers, and might not be tolerated by the individuals distro's policies of not downloading anything additional than the source file itself.

@stefson What about the submodules? And CMake FetchContent (pulling in stuff from remote on configure time)? I'd like to get this easy enough for package maintainers. I'm asking specifically as I'm changing Boost.Nowide which is currently included in the git submodule libutil to be fetched via FetchContent from the current upstream repo by git tag. It would be possible to add a configure switch to use a system version or only FetchContent if `find_package` fails or both

**Comment by stefson** [comment]
It's not a question of annoying package maintainers less, but to not make their job impossible. You don't want a bootstrap script downloading unknown stuff with root priveliges from the internet, first for the obvious security reasons, but also to not depend overly much on a server that might be turned off one day in the future. Or where nothing can be downloaded until the first day of the next month, because the maximum amount of traffic has been spent. 

I know that this behaviour has been in fashion for some time now in the open source community, for instance rust forces you to run a shell script from some site with root priveliges, just for bootstrapping it - distros have to go through some lenghts to be able to bootstrap without the need to download random files from some server. 

Anything that can be fetched via `git clone --recursive` is fine, if all submodules can be licensed. There's no support for git lfs and no support for cmake FetchContent. 

I've never heard of Boost.Nowide, but it's propably a good idea to unbundle it from libutil, please change it to an external dependency (forced or optional, your choice) and I'm sure someone is going to package this, at least for my own distro ;-)
