### ISSUE TITLE
Remove usage of git lfs

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1204]
git-lfs is hard to use (requires setup commands, additional packages, ...), see https://github.com/Return-To-The-Roots/s25client/issues/1201 

Additionally it also has a quota which seems to be low, see https://github.com/Return-To-The-Roots/s25client/pull/1187#issuecomment-612609665

I hence propose we remove git-lfs.

What we needed it for:
- pre-compiled binaries (especially MSVC)
- big LSTs

My proposal to resolve:
- Add a separate repo with pre-compiled binaries that we currently have in the repo. We can clear and reuse the rttr-contrib folder (IMO we don't need what currently is in there). This keeps this stuff optional
- Add a rttr-data repo for lsts and potentially other big files and include as submodule.   
  Got to check what to move there. The whole data folder isn't good as e.g. RTTR/gameData (scripts) should be in the main repo. But LSTs and MAPs should go. Maybe 2 repos? Having an own repo for maps seems to be a good idea.

@Flow86

**Comment by Flow86** [comment]
yes if we split, than we should definitely split maps into a separate repo
