### ISSUE TITLE
Tool ordering invisible numbers

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1207]
When using the tool ordering addon, the number 10 is not visible, 11 is visible and any higher number is invisible in the ordering screen

**Comment by Flow86** [comment]
do you have a screenshot for that?

**Comment by Spikeone** [comment]
![image](https://user-images.githubusercontent.com/1276342/79583065-e7458c80-80cc-11ea-9e92-6d7ca031d713.png)

**Comment by Flow86** [comment]
it doesnt fit in there, so its not displayed :dagger:
