### ISSUE TITLE
Opening lst graphics

### ISSUE THREAD

**Issue by Ekliptor** [Return-To-The-Roots/s25client#1211]
Is there any editor to open the `.lst `files of this game? And ideally edit + save them.
Specifically all `.lst` files under `data/RRT/LSTS/`

If found this link explaining the file format: https://settlers2.net/documentation/lst-file-format/
But the suggested tool in the comments in no longer linked on the RTTR homepage.

edit: preferably for OSX, but Win is als fine

**Comment by Spikeone** [comment]
There you go: https://github.com/Return-To-The-Roots/libsiedler2/releases/tag/v1.0.0

**Comment by Flamefire** [comment]
That would make a great wiki entry. The readme at https://github.com/Return-To-The-Roots/libsiedler2/tree/master/examples is short and not easily to be found but good. PRs and Wiki to improve this are welcome.

Closing as question has been answered

**Comment by Spikeone** [comment]
@Flamefire I sadly can't edit the wiki anymore :-/

**Comment by Flow86** [comment]
@Spikeone  this should be fixed.
