### ISSUE TITLE
Remove emailaddress from logfile

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#1214]
Inside the logfile the user's emailaddress gets logged. We should anonymize it.
Printing the first + last letter of alias and domain should be visible so we can verify it, but like this less accidents can happen, that the user posts or uploads its emailadress to a post or issue

**Comment by Flamefire** [comment]
Good point. You know where it is coming from?

**Comment by Flow86** [comment]
```
<<< NMS_LOBBY_LOGIN_DONE(...)
```
