### ISSUE TITLE
KI baut Köhlerei, jedoch wird fast nie Waren darin produziert.

### ISSUE THREAD

**Issue by Uwe1981** [Return-To-The-Roots/s25client#1215]
KI baut Köhlerei, jedoch wird das benötigte Umfeld zu Produktion von Kohle fast immer zugebaut, so dass die Herstellung der Waren nicht möglich ist. Kann das ggf. entsprechend angepasst werden?

**Comment by Spikeone** [comment]
Hi @Uwe1981 

habe mal den Report #1206 erweitert, damit alles mit dem Köhler + AI in einem Ticket landet
