### ISSUE TITLE
crash when s25client help

### ISSUE THREAD

**Issue by adysnook** [Return-To-The-Roots/s25client#1218]
So I know the command should be `s25client --help`, but if you write `s25client help` without the **--** you get a crash.

Version info:
`>s25client.exe --version
Return To The Roots v20200430-1960d86e3e4c4f9fb4c8c3976d9eab4bc8e5b837
Compiled with GNU C++ version 7.3-win32 20180506 for Win32 64 Bit`

**Comment by Spikeone** [comment]
Sounds like this happens whenever you call s25client with unknown parameters.

Does ```--NonExistingParam``` (or any similar) also crash the application?

**Comment by Flamefire** [comment]
I see, I made it so i treats a positional param as a map name which it then tries to quickstart. It shouldn't crash though, that's a bug. I'll look into it
