### ISSUE TITLE
[wish] Zufälliges Volk bei Volk auswählen

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#122]
Volk sollte auch mal einfach auf Zufall drücken können :)

Blackeagle (sebastianbogner) wrote on 2011-07-07:   #1
Bei Volk :D

Blackeagle (sebastianbogner) wrote on 2011-07-07:   #2
Zu Spät sorry für das schlechte Deutsch :D

FloSoft (flosoft) wrote on 2011-07-07:  #3
ja als Volk wie z.b bei Age of Empires "Random" bzw "Zufällig" auswählbar wäre gut.

dro1d (sir-moc) wrote on 2011-07-12:    #4
das fänd ich auch super!

**Comment by Flamefire** [comment]
Duplicate #463
