### ISSUE TITLE
libaudioSDL.so - Failed to load library

### ISSUE THREAD

**Issue by shadowvzs** [Return-To-The-Roots/s25client#1221]
> Skipping ...../s25rttr_20200430/lib/driver/audio/libaudioSDL.so: Failed to load library. Check dependencies!

the few year old version can detect my sound driver just the new version no, itried to update too but not helped.

v20200430 - linux mint 19.1 (ubuntu 18.04)

**Comment by Flamefire** [comment]
Run a `ldd libaudioSDL.so` on that file to see which dependency is missing

**Comment by Flow86** [comment]
isn't that the "old" SDL1 library?

**Comment by shadowvzs** [comment]
> Run a `ldd libaudioSDL.so` on that file to see which dependency is missing

	

> linux-vdso.so.1 (0x00007ffc1f998000)
> 	libSDL2_mixer-2.0.so.0 => not found
> 	libSDL2-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007fe461e38000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe461aaf000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe461711000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe4614f9000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe461108000)
> 	libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007fe460e01000)
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe460bfd000)
> 	libpulse.so.0 => /usr/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007fe4609ad000)
> 	libsndio.so.6.1 => /usr/lib/x86_64-linux-gnu/libsndio.so.6.1 (0x00007fe46079d000)
> 	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fe460465000)
> 	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fe460253000)
> 	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fe460049000)
> 	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fe45fe46000)
> 	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fe45fc36000)
> 	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fe45fa2b000)
> 	libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1 (0x00007fe45f827000)
> 	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fe45f621000)
> 	libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fe45f41f000)
> 	libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fe45f210000)
> 	libwayland-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007fe45f008000)
> 	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fe45edc9000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe45ebaa000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe45e9a2000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007fe46216a000)
> 	libpulsecommon-11.1.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so (0x00007fe45e724000)
> 	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fe45e4d7000)
> 	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fe45e2c2000)
> 	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fe45e09a000)
> 	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fe45de90000)
> 	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fe45dc8a000)
> 	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fe45da82000)
> 	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fe45d7fe000)
> 	libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007fe45d5f4000)
> 	libsndfile.so.1 => /usr/lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007fe45d37b000)
> 	libasyncns.so.0 => /usr/lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007fe45d175000)
> 	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fe45cf71000)
> 	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fe45cd6b000)
> 	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fe45cb45000)
> 	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fe45c929000)
> 	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fe45c60d000)
> 	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007fe45c3f3000)
> 	libFLAC.so.8 => /usr/lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007fe45c17c000)
> 	libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007fe45bf73000)
> 	libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007fe45bd48000)
> 	libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007fe45ba9f000)
> 	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fe45b884000)
> 	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fe45b66f000)

**Comment by Flamefire** [comment]
@Flow86 no, it just hasn't been renamed. I guess the packaging is incomplete. Can you check and make sure the updater distributes `libSDL2_mixer.so` instead of 1?

**Comment by Flow86** [comment]
we never bundled these files.

@shadowvzs:
yes you have to install libsdl2-mixer
