### ISSUE TITLE
s25updater should use https

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#1223]
currently it still uses http.

Since the server now supports https (powered by letsencrypt) we should switch to https.

**Comment by Flamefire** [comment]
Does our curl library support this? Wouldn't we need a libssl? Otherwise we can just change the string and be done

**Comment by Flow86** [comment]
thats what we need to find out ;-)

**Comment by Flamefire** [comment]
Looks easy: https://curl.haxx.se/libcurl/c/https.html

**Comment by Flamefire** [comment]
Build on Linux with `https://` and no problem. So test on windows now, but currently can't do that.

**Comment by Flamefire** [comment]
Tested successfully on windows, pushed to submodule

**Comment by Flow86** [comment]
did you update the submodule already?

**Comment by Flamefire** [comment]
Not yet. I have it as part of a greater, clang-tidy-9 sanitized PR
