### ISSUE TITLE
Feature Request:  Movable 'Work Area'

### ISSUE THREAD

**Issue by akuenzi** [Return-To-The-Roots/s25client#1228]
I assume that the work area for a particular building is centered on the building itself, and then extends out to a certain radius.  In other words, the tree planter will plant trees __ meters from his building.  It would be nice if one could move the work area.  If enough trees have been planted with the building in the center, move the center of the work area off of the building to a new location (within reason) so he can keep working.

Thank you for considering this. :)

**Comment by Spikeone** [comment]
see #129
