### ISSUE TITLE
Feature Request:  Allow Building While on Pause

### ISSUE THREAD

**Issue by akuenzi** [Return-To-The-Roots/s25client#1229]
One of the most annoying things to face in-game (at least for me :) ), is when I'm in the middle of placing where I want buildings to go... and then I get a notification that my settlement is under attack.  In the early stages of the settlement, I like to monitor closely what's going on in the battle... which then hinders my building placement.  Of course, none of this matters to the AI, who can continue their building projects AND do battle against his mere human... 

As such, it would be nice, upon receiving such a notification, to be able to hit 'pause,' and then be allowed to finish placing where I want buildings to go, and then go watch the battle.  And of course, I don't mean that the literal building of them would continue; I'm only talking about having the ability to place them and link up roads to them, so that my settlers can get going on them as soon as I hit 'unpause.'

Thank you for considering this. :)

**Comment by Spikeone** [comment]
As this is only for singleplayer, isn't it enough to simply slow down the game (hit + / -)? At 1 GF = 70ms the game is quite slow^^.

Also the AI only do actions every 1000 / 500 / 100 GF (not sure if the numbers are correct) so in fact they also do wait^^

**Comment by Flamefire** [comment]
I would deny this. Not being able to actually do multiple things at once is part of the RTS genre and what makes it challenging. Also RttR is as well for multi-player and there PAUSE means pause. It would not be fair if others could build during that time.
