### ISSUE TITLE
Feature Request:  Settlement Border Flag Road Joining Bug

### ISSUE THREAD

**Issue by akuenzi** [Return-To-The-Roots/s25client#1230]
This is probably the silliest feature request ever, mainly for amusement.  I was in college when the first version of Settlers came out (aka Serf City).  A friend I was staying with had Settlers I on his Amiga computer.  At some point we discovered an amusing bug, which is shown in this YouTube video (click below and take a look starting at 0:42):
[![The Settlers 1 waynet-bug](http://img.youtube.com/vi/YjR-XZupBrI/0.jpg)](http://www.youtube.com/watch?v=YjR-XZupBrI&t=42s))
I didn't have an Amiga computer, and my version of Settlers I didn't come with this bug... but it was a lot of fun to have it.  When I got 'mad' at one of my enemies, it was fun to have him start building stuff for me on my property, or to waste his resources.  Thereafter, I can assure you that the border remained extremely peaceful... lest anything was done to break this important link. ;)

Is it possible to ask for a 'bug' as a feature request?  I guess that's what this is, but maybe we could call it a 'cheat feature' instead.  It would be interesting to have the ability to 'tap into' the enemy's supply line and resources on a border where one could join up with his roads using a flag, as shown in the video above.  And to make it a feature that can be toggled on or off in the settings, of course, if one doesn't want to allow this as a cheat.

I'm sure it probably won't be implemented, but thanks for reading and considering this anyway. :)

**Comment by Flamefire** [comment]
While this is indeed funny it is simply impossible in RttR due to the design.
