### ISSUE TITLE
Windows Windowed Mode Green Overlay / Graphics failure

### ISSUE THREAD

**Issue by Seriousness** [Return-To-The-Roots/s25client#1233]
![screen](https://user-images.githubusercontent.com/1168497/82367926-dca44d00-9a14-11ea-87ed-2c88522d16a4.jpg)

Havent had that before, only in windowed mode.

**Comment by Spikeone** [comment]
Win 10 I guess?
Which video driver are you using?

**Comment by Seriousness** [comment]
Yes Win10
Intel Graphics 520 / Version 27.20.100.8236

Please tell me if I can help further, I'm not so good at hardware/driver specs and the necessary information ;)

**Comment by Flamefire** [comment]
Go to Settings->video and select SDL2.

I doubt that this is something we can fix on our side if this doesn't help

**Comment by Flow86** [comment]
Also try to install the latest video drivers for your intel graphics card from https://downloadcenter.intel.com/de/product/88355

**Comment by Seriousness** [comment]
@Flamefire SDL2 was selected and switching through didnt change a thing.

@Flow86 As far as I can see I updated the driver ~ 2 weeks ago, but I guess i've played in between... I'll see if reinstalling the driver works and hope this is a problem on my driver side ;)

**Comment by Spikeone** [comment]
@Seriousness any luck with reinstalling the driver?

**Comment by Seriousness** [comment]
Yes, sorry for my delay. Just tried it out and it works normal again. As everything else worked fine I guessed it was a bug... sorry.
