### ISSUE TITLE
Intro button not working

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1234]
The intro button is not working

**Comment by Flow86** [comment]
did we have an intro? perhaps we should remove the button

**Comment by Spikeone** [comment]
@Flow86 right, it sadly never did - are you sure that we shouldn't add the intro?

**Comment by Flow86** [comment]
we never implemented playing a video file. but perhaps we could do that somehow @Flamefire

**Comment by Flamefire** [comment]
Is it worth the work? We'd just use it for the intro...

**Comment by Spikeone** [comment]
Well, never watched the intro (is it even included or is it only if you have the cd?) - but having it would be quite nice for the feeling (e.g. you watch it on first start and then it autoskips) as it brings back some memories.
But I don't know how much work it really is.

**Comment by Flow86** [comment]
perhaps we should disable the button for 0.9, so its clear that its not working (yet) . then we can think about it. I also would like to have it if I'm honest

**Comment by Flamefire** [comment]
> perhaps we should disable the button for 0.9, so its clear that its not working (yet)

Yep just remove it.

>  I also would like to have it if I'm honest

Implementing a video player is non-trivial. I don't even know where that intro is located at and haven't found any hint. So I'd say no, but feel free ;)

**Comment by Spikeone** [comment]
[VIDEO.zip](https://github.com/Return-To-The-Roots/s25client/files/4673360/VIDEO.zip)

It's actually located in the VIDEO folder :D which is often not included in any online version as it's nearly 15Mb. It's a *.SMK File.

**Comment by Flamefire** [comment]
Good luck: https://en.wikipedia.org/wiki/Smacker_video

> In Smacker video, a frame is split into 4×4 blocks in raster-scan order.[2] Each block can be coded in one of six coding modes: skip, fill, mono, and three full modes. Each mode can be signaled for multiple blocks in a run-length encoding scheme. 

It goes on with more cases. https://wiki.multimedia.cx/index.php/Smacker has more info with huffman trees for video and audio.

As mentioned: non-trivial

**Comment by Spikeone** [comment]
Well, there is a lib for smacker video: https://git.ffmpeg.org/gitweb/ffmpeg.git/tree/HEAD:/libavcodec

**Comment by Flamefire** [comment]
@Flow86 Didn't even want to include a zip library as a dependency to allow for compressed resources. And just the library isn't enough either...

**Comment by Flow86** [comment]
yes if we want to decode it, we should implement a small decoder by ourself. I don't think its too complicated to decode. The more interesting thing would be implementing the playback of the video

**Comment by Flow86** [comment]
![grafik](https://user-images.githubusercontent.com/656249/82754767-96157080-9dcf-11ea-8529-ff1719ffa201.png)
