### ISSUE TITLE
Remove Online Ranking

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#124]
Über ein Online Ranking wurde bereits hier schon einmal diskutiert:
http://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=805

https://bugs.launchpad.net/s25rttr/+bug/899114

**Comment by Spikeone** [comment]
Should we really add a ranking function? In my opinion it is quite hard to create a usefull way to actually rank players. One could just display games played (or better hours) or something like that. Although I'd really like to show of my skill by rank, I don't think we really need such a feature nor that it'd be usefull. Any thoughts  @MarcusSt @Flamefire @jhkl @Flow86

**Comment by Flamefire** [comment]
The lobby server is prepared for this (it has games won at least and a rank/strength) but I don't know if this was ever used/set and I wouldn't know where/how to set this.

**Comment by Spikeone** [comment]
For me the main problem is still the following: Playing 10 games on a 32x32 map and winning isn't as good as playing 10 games on 256x256 map and winning. Playing 2v2 is not the same as 1v1v1v1 - those points will never tell something usefull in my opinion. Even played games don't as small maps don't take much time at all.

**Comment by Flamefire** [comment]
That's why I would not include a rank but just a games played & won
No scoring and everybody can figure this out on their own. It would be a rough estimate not more. 
Or just remove this completely

**Comment by Spikeone** [comment]
I personally would vote for removing it completely - also Settlers 2 is not that competitive at all that one could create such a ranking.

**Comment by Flow86** [comment]
Sure!

**Comment by Spikeone** [comment]
I think we agreed on removing the ranking, didn't we? Maybe we can give players a chance to simply rate themselves but - people communicate before they play so it's not really needed.

**Comment by Spikeone** [comment]
The button is still present?

**Comment by Flow86** [comment]
only in the old stable

**Comment by Flow86** [comment]
no its still in there
