### ISSUE TITLE
Maps silently not shown/loaded

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1243]
Reported by Aden in Discord.

> My son just made a map using the RTTR editor.  It's saved in the 'worlds' folder (in .SWD format), but when we go in-game, we can't find it.  It otherwise opens fine in the editor.  Two questions:
> 
> 1. What do we need to do to get the game to recognize the map?
> 2. A number of years ago there was a separate .exe program I used to 'fix' the coastal harbor places.  Is there something similar we need to do to the map files to get it to accept harbor locations, or is that not an issue in rttr?

Map is https://cdn.discordapp.com/attachments/524755374331658240/716579549118332928/Lugees_Map.swd

@Spikeone mentioned:

> looks like we silently don't load maps with players > 8

Hence the editor shouldn't create 16 player maps and RTTR should show a message/warning at least

@Spikeone How verbose should such a warning be? When showing the map selection a message box for each faulty map? It usually shouldn't happen at all and the user might then want to fix or remove the map. Or just a log entry? Any other ideas?

**Comment by Spikeone** [comment]
Hm, thought about this a bit - I think we should display a message once (There are invalid maps in your WORLDS folder. See Log for more information) and the Log should show why they are invalid  (e.g. high player count, block size invalid or something like that).

**Comment by Flamefire** [comment]
Ok checked the code and there are 2 places where an error is detected: One is the loading of the directory where the headers only are loaded. There any error was silently ignored.   
The 2nd place was when a map got selected, where it was fully loaded (e.g. to show the preview). There a messageBox is shown and the map is removed on error.

For consistency I moved most error reporting to the latter place (we had mapsize check there but players at first place). So now:
- Failing to load the map header (e.g. wrong file format) results in a log entry and a messagebox `"%1% map(s) could not be loaded. Check the log for details"`
- On select the map is fully verified and a message box is shown with the error

Example: 
![mapfail](https://user-images.githubusercontent.com/309017/83405000-ee6df300-a40b-11ea-80d1-131d149c56c8.png)

Broken maps are "cached" and hence reported only once while the map screen is open. That cache is cleared when the map screen is closed.

I could of course move the size and player verification to the log and don't display those maps at all, but I think there is value in showing all (kinda) valid maps and error out on selection only.

Minor issue: The first map in the list is auto-selected on switching to that folder. So if that is faulty is is removed right away. Shall we maybe unselect any selection instead? I think this makes sense as you are unlikely to start the first map anyway in the general case

**Comment by Spikeone** [comment]
So, if one player copies a lot of maps into his worlds folder and there are quite a number of broken maps, he has to confirm the message for each map, right?
Well, should not happen often so - it doesn't really matter^^

**Comment by Flamefire** [comment]
Yes. But only when selecting it.
