### ISSUE TITLE
Automatic save games of maps with Umlauts cannot be loaded

### ISSUE THREAD

**Issue by fritzmg** [Return-To-The-Roots/s25client#1245]
If you play a map that has an Umlaut in it, like _Glücksklee_ for example and enabled automatic saving, the file will be named `GlÃ¼cksklee (Automatisches Speichern).sav` and it will not show up in the savegames list in-game.

v0.8.2-0383c0c

**Comment by Flow86** [comment]
Hi,
can you please retry it on the latest nightly? It is probably already fixed in one of the latest nightly builds, since we have done a lot of changes inside the file handling and locale code.

**Comment by fritzmg** [comment]
Yes, works fine in 1a1bc12 👍
