### ISSUE TITLE
[LUA] No function to determine time

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1251]
I wanted to build a scenario where a player has limited time. Sadly one can not how fast a player plays the mission - so I can not output any messages in human seconds but rather in left GFs. Although thats nearly the same, it'd be nice to either get the gamespeed or simply have something GFtoTime(GF, HH:MM:SS) or something alike.
It really feels better if you are told "10 minutes left" rather than "30000GF left".

```os.time()``` oh and that one is not working ;)

**Comment by Flamefire** [comment]
This needs exposing `GameClient::FormatGFTime` which returns `HH:MM:SS` for a gf number omitting the HH: when no hours are set. I guess this is what you need?

**Comment by Spikeone** [comment]
Guess thats enough for what I was thinking about:
- Show Info every n-Minutes about time left
- Update Help Text every minute
