### ISSUE TITLE
not all glyphes are implemented for the ai debugger

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1252]
![2020-06-07-153014_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/83973652-3ac3a200-a8e8-11ea-99ab-b02fa3dc8f6f.png)

I'm not sure which symbols are missing though, never actually used the ai debugger before

**Comment by Flamefire** [comment]
Those are newlines. Fixed locally by using a ctrlMultiline.

@Spikeone want a different background?

![2020-06-07_18-10-47](https://user-images.githubusercontent.com/309017/83974015-75c6d500-a8ea-11ea-8476-af52186c10a6.png)

**Comment by Spikeone** [comment]
I'd take the one here:
![image](https://user-images.githubusercontent.com/1276342/83980675-ee905600-a917-11ea-9418-c785400da390.png)
