### ISSUE TITLE
Inventory and Headquarters Number of Private don't match

### ISSUE THREAD

**Issue by Unterwald** [Return-To-The-Roots/s25client#1253]
Hello,
I found out, that the number of privates in the inventory is X+1 to the number in the Headquarters
![image](https://user-images.githubusercontent.com/66565940/83974805-44e99e80-a8f0-11ea-953d-09deed2dcae6.png)
Best regards, Unterwald

**Comment by Flow86** [comment]
Hi,
I think one private is reserved inside the head-quarters

**Comment by Unterwald** [comment]
I opened the Mission from the old roman campaign (VI-Die Schlange), and it was still there, even if i turn the reserve to 0.

**Comment by Flamefire** [comment]
The soldiers in "inventur" are the soldiers in "HQ" + the soldiers in the reserve of the HQ. This works as expected (just tested). So I'm not sure what you mean by "it was still there".

**Comment by Unterwald** [comment]
It seems to appear only in the Kampagne-Games...

**Comment by Spikeone** [comment]
Guess this is caused by using ```rttr:GetPlayer(p):ClearResources()```

**Comment by Flamefire** [comment]
@Spikeone spot on! We even have that as `TODO`: https://github.com/Return-To-The-Roots/s25client/blob/163f1274646aeac56989a1eaf62b8fd68615af85/libs/s25main/buildings/nobBaseWarehouse.cpp#L207

**Comment by Spikeone** [comment]
possibly the reason for this one: #1132

**Comment by Flamefire** [comment]
Unfortunately not. The replay in the linked issue does not have a lua file
