### ISSUE TITLE
Update clang-format

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1265]
We are currently using clang-format 5.0 which is pretty dated now. It also isn't possible for developers to use a newer one as different versions format differently and they may not even understand the clang-format style file due to changes.

Furthermore Ubuntu 20 / Linux Mint 20 doesn't even have clang-format 5 in its sources anymore. There it starts at 6.

I hence propose that we switch to a newer version. 10 is the current one, if we want to be conservative we could use 9, which should be available in most repos.

The update is almost trivial (changing versions at 2-3 places and rerun the format target) but may lead to conflicts for open PRs and ongoing work. To mitigate for changes where a rebase is not feasible the author can reformat the code with the new clang-format then merge the master to his branch so conflicts will be minimal if at all.

I suggest to do it before the release so it is a clean point

**Comment by Flow86** [comment]
sounds good. we need to check if the corresponding clang-format (I would go with) 9.0 is available for all our pipelines, or installable on them

**Comment by Flamefire** [comment]
We use it only on one point: https://github.com/Return-To-The-Roots/s25client/blob/2d56190b62d298b9fd9aee8787f283dd6392d206/.github/workflows/static-analysis.yml#L24

And there it is simply changing the version too, clang-format-9 is available in a docker image there :)

**Comment by Flow86** [comment]
then do it :-)

**Comment by Flamefire** [comment]
There is a new option about the space before a colon. Disabling that makes the following changes (example, both can be configured individually):
```
-    ChangeBuildOrder(Serializer& ser) : GameCommand(CHANGE_BUILDORDER), useCustomBuildOrder(ser.PopBool())
+    ChangeBuildOrder(Serializer& ser): GameCommand(CHANGE_BUILDORDER), useCustomBuildOrder(ser.PopBool())
     {
-        for(auto& i : data)
+        for(auto& i: data)
```

I actually like the space removal but wanted to hear your opinion on that. "Advantage" of not removing its is less changes to the code, advantage of removing it is a more compact view which may or may not be good. Maybe we should use the space as e.g. the examples use it too: https://en.cppreference.com/w/cpp/language/range-for

**Comment by Flow86** [comment]
I would keep the space, it makes it more readable, I would also like to have
```
BreakConstructorInitializers: BeforeComma
```
but I think we should keep it the way it is at the moment
