### ISSUE TITLE
Delays weiter im Spiel verstecken

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#127]
Es wäre schön, wenn man die Delays beim Fahnen und Bauplatzsetzen weiter im Spiel verstecken könnte oder gar beheben. Mir passiert es oft, dass ich einen Bauplatz setze => weg zur fahne baue
Da das gebäude durch die verzögerung noch nicht existiert geht der weg erst durch die baustelle, verschwindet dann und ich muss ihn neu bauen.

https://bugs.launchpad.net/s25rttr/+bug/910784

**Comment by Spikeone** [comment]
In my opinion it is quite good as it currently is.

**Comment by baka0815** [comment]
Might be the same as #906 and should therefore be fixed with https://github.com/Return-To-The-Roots/s25client/commit/a6a4e4c9b386ad3b5784d31618a9da8a41367873
