### ISSUE TITLE
[addon] Capturing enemy Headquarters

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#128]
How it should work:
- once you defeat all soldiers in enemy HQ, you should capture that building like it is a normal military building
- you should also capture all area around
- you should be able to possess all the goods and workers inside, like it is your own HQ
- you should be able to possess as many HQ as you want
- you can also burn captured HQ buildings
- you can't burn HQ if you have only one left
- you should be able to gain building materials from HQ if you decide to burn/dismantle it
- HQ can't be destroyed by catapults (no change here)

How to enable this addon:
- this addon should be optional. Should be available like other RttR addons (in options).

Why this addon:
Sometimes you might like to capture enemy HQ to steal his goods and workers. Especially if you know that your opponent is/was rich and might have a lot of precious things inside that might be very helpful for your empire. This is (IMO) a realistic and logical option.

https://bugs.launchpad.net/s25rttr/+bug/1394115

**Comment by K4T** [comment]
Like that idea, sounds logic and awesome.

**Comment by Spikeone** [comment]
should be part of #121
