### ISSUE TITLE
Drop support for MSVC 2015

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1282]
Continuation of #897 and https://github.com/Return-To-The-Roots/s25client/issues/897#issuecomment-480494023

C&P:

```
Coming across this again. The "constexpr does not imply const in C++14" comes up again. The C4814 is not even listed on the MS pages -.-

Although it is not really required playing with constexpr would be great. This needs MSVC 2017 which also has the /std:c++14 flag with improved compatibility. [@Flow86 ] Do you have any references on the "most used VS"? Is it really required with MSVC 2019 just released and 2017 community edition available?
```

Others found the same issue: https://gitmemory.com/issue/Return-To-The-Roots/s25client/897/480494023

Being able to "just use C++14" would be nice and will avoid having to fix valid C++14 code to be compatible with the C++11/14 mix of MSVC 2015

Is MSVC 2015 still relevant in 2020?

**Comment by Flow86** [comment]
MSVC yes, but probably not 2015 anymore. We should go with VS 2019 now, As long as our cross compiler supports it, we can go to a higher C++ version if we need to

**Comment by Flamefire** [comment]
Sorry typo, should have been "MSVC 2015", fixed above.

Ok, then I'll prepare a PR changing this on the CIs. Going up to 2017 should be enough for now. Although the variant, optional and filesystem support is nice I wouldn't go to C++17 for a while to not exclude people.
