### ISSUE TITLE
Require Boost 1.69

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1290]
We currently require Boost 1.64+ but in #1289 I run into an issue fixed by Boost.Test 1.69: https://github.com/boostorg/test/commit/cc7796fbe953293ddb153f31bacac0a67622602d

Basically: For `BOOST_TEST(value)` the print_helper specialization is ignored making it fail for unprintable types.

Maybe it is time to upgrade Boost to 1.69.

In the same commit it makes sense to upgrade CMake to 3.14:
- We have a copy of FetchContent from 3.14 to make it work on earlier versions
- We have a copy of FindBoost from 3.11 to be able to find versions up to 1.67, hence we need a newer version for 1.69

**Comment by Flamefire** [comment]
@Flow86 Hitting again an issue with Boost 1.64 which is fixed in 1.65 by https://github.com/boostorg/test/commit/aece067770203cdff62baaab494599bb1f2d4a3d

Can we upgrade? If so only a minor upgrade to 1.65 or 1.69 and CMake to 3.14?

**Comment by Flow86** [comment]
didnt we update already?

**Comment by Flow86** [comment]
ah, we did not, since debian:busters default boost is 1.69 and cmake 3.13

**Comment by Flamefire** [comment]
So Boost 1.69 as the minimum and CMake 3.13 (or just keep the current one)?

I'd also like to optionally FetchContent https://github.com/boostorg/variant2 when on Boost < 1.73 as I find myself using variant more often and Variant2 is C++11 instead of (slow) MPL and on 1.73 it is even trivial for most usages meaning it is fast

**Comment by Flamefire** [comment]
@Flow86 Could you update the linux runners on the build server to 1.69 please?

**Comment by Flow86** [comment]
the problem is that we need to package the libs then, or do we use them statically anyhow?

**Comment by Flamefire** [comment]
We have never packaged boost and always build statically: `-DRTTR_USE_STATIC_BOOST=ON`

**Comment by Flow86** [comment]
I've changed the linux runner now to use the official backport package (boost 1.71)
