### ISSUE TITLE
Boater dies when removed

### ISSUE THREAD

**Issue by fritzmg** [Return-To-The-Roots/s25client#1296]
In particular places (or on particular maps?) the boater simply dies if you remove the water route, instead of going back on to the shore:

![boat_death](https://user-images.githubusercontent.com/4970961/90974429-0ba1f180-e523-11ea-84fb-8fccff62a2a4.gif)

This happened on the map "Die Raute" with v0.8.2-0383c0c

At first I thought it only happened if either one end was connected to mountainous terrain. But in this test case it also happened if both ends were connected to green land. However, I have observed it working correctly between green land on the same map - but only ever noticed it not working in the "mountainous waters".

**Comment by Spikeone** [comment]
Please use the latest nightly builds. This has been fixed some time ago.
