### ISSUE TITLE
Sea attack settings: can't see options in German translation

### ISSUE THREAD

**Issue by fritzmg** [Return-To-The-Roots/s25client#1297]
Something that has been bugging me for a while: when using the German translation, it is impossible to see which option is which for the **Sea attack settings** within the addon settings 😁 

<img src="https://user-images.githubusercontent.com/4970961/90974582-8d464f00-e524-11ea-82e1-26b771ba3f54.png" width="220">

Note to self and others: the options are:

* Enemy harbors **don't** block
* Enemy harbors block
* No sea attacks

v0.8.2-0383c0c

**Comment by Spikeone** [comment]
![grafik](https://user-images.githubusercontent.com/1276342/90984056-f0f76900-e572-11ea-9f59-992307323a3e.png)

Does hoovering not suffice?

**Comment by fritzmg** [comment]
Ah, is that a new feature of the current nightly build? It's not there in the current stable (v0.8.2-0383c0c).

**Comment by Spikeone** [comment]
Mh, looks like then :)

**Comment by Flamefire** [comment]
So that's fixed.
