### ISSUE TITLE
drawing error when a new expedition is available

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1298]
hi, the builder isn't fully drawn when a new expedition is ready to set sails. I only see his blue shirt and one arm/leg! :-)

![2020-08-31-104441_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/91701069-0eca5c80-eb77-11ea-9161-40a50bb52e2a.png)

**Comment by Flamefire** [comment]
Hm, the code looks correct. Can I haz savegame?

**Comment by stefson** [comment]
here's the savegame: [random.sav.zip](https://github.com/Return-To-The-Roots/s25client/files/5150525/random.sav.zip)

I have to say that I lost the random map when playing around, and both the game was started and the map generated with https://github.com/Return-To-The-Roots/s25client/pull/1187/commits/9a89bd615f07f64fcf5775b041a6139d098b668b from https://github.com/Return-To-The-Roots/s25client/pull/1187

**Comment by stefson** [comment]
but the error also shows up when using latest git master branch and loading this savegames. Haven't tried to reproduce yet with a new game
