### ISSUE TITLE
Update to clang-format-10 and #pragma once issues

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1302]
I noticed that clang-format-10 is available in all ubuntu repos where clang-format-9 is so to be more future proof I'd like to update that. I just checked that no changes from the update alone happen.

However I'd like to change 2 options:

**IndentPPDirectives:**

```
#ifdef WIN32
#    include <windows.h>
#    define IS_OK 1
#endif
```

And also change the line length to 120 (from 140) as I noticed that the few lines above 120 we have cause readability issues in conflict resolving tools and some IDEs with sidebars. With 120 it seems to be much better and there won't be many lines affected, so that one is easy.

However the first cause problems when we have:

```
#pragma once
#ifndef foo_h
#define foo_h
```

I already suspected that using both is a pessimization because compilers detect the include-guard pattern and handle that automatically making at as fast as `#pragma once` (see #1073) and having include-guards and the pragma is more work for maintainers for no (noticeable) gain. This is confirmed by clang-format not detecting the above as include guards and trying to format it as 
```
#pragma once
#ifndef foo_h
#    define foo_h
```
while it does not do so (detecting include guard pattern) without the pragma once.

@Flow86 I'd hence like to press for a decision to choose either include guards or the pragma, not both. I'd go for the pragma as it is shorter and C&P. No need to come up with a name or keep it updated when renaming/extracting files. We even have some faulty include guards which I only noticed due to the formatter. The pragma once is easier to check for. And I don't think we support any compiler not understanding it.

CCing @vader1986 @stefson if there is any strong argument for either

**Comment by vader1986** [comment]
Reducing line length to 120 is great. For readability I'd also prefer `pragma once` only, although I'm happy either way, if it has impact using both.

**Comment by Flamefire** [comment]
> For readability I'd also prefer pragma once only, although I'm happy either way, if it has impact using both.

Does that mean you'd use both if it were ok? If so why, in which order and why? I tried to gather reasoning for that decision (either one, both and which order) and wrote in the linked issue, e.g. https://github.com/Return-To-The-Roots/s25client/issues/1073#issuecomment-674207797

**Comment by vader1986** [comment]
I prefer using only `#pragma once` in the header file if that wasn't clear from my answer.

**Comment by stefson** [comment]
Actually I don't use clang-format, since I'm only test compiling and breaking your code every once in a while! ;-)

**Comment by Flow86** [comment]
if its working on all compilers, we should go with `#pragma once` only. I'm fine with both of the other settings (indent + line length).

Probably a bug in clang-format if  it can't handle define indentation + include guards separately

**Comment by Flamefire** [comment]
> Probably a bug in clang-format if it can't handle define indentation + include guards separately

It can in general. But if `#pragma once` is present before the include guard then clang doesn't detect it as include guards anymore. This is described in the GCC docs too: TLDR is "There must not be anything outside the guards."

According to Wikipedia all semi-recent compilers support it and as we require C++14 we can assume recent enough compilers. I'll add a PR replacing the guards and adding verification to CI if there is no objection
