### ISSUE TITLE
AI demolishes Inexhaustible mines 

### ISSUE THREAD

**Issue by RM87** [Return-To-The-Roots/s25client#1309]
With Inexhaustible mines enabled AI demolishes mines frequently(and rebuilds). Seems like if no food available for some time, mine will be demolished.

**Comment by Hexoplon** [comment]
Unable to reproduce after running newest master (commit d43a21b) with 5 AIs on hard for 80000 gameframes. Maybe it was fixed some time ago?

Also possible to add checks to AIPlayerJH::HandleNoMoreResourcesReachable to handle potential edge cases when the plugin is enabled.

**Comment by RM87** [comment]
seems ok to me also
