### ISSUE TITLE
No possibility to set water priority for Donkey breeding

### ISSUE THREAD

**Issue by Fajny666** [Return-To-The-Roots/s25client#1311]
The problem is obvious from the title, I hope that it is not intentional...
![Donkey_breeding_water](https://user-images.githubusercontent.com/74626427/99452611-0be43a00-2924-11eb-9e4a-0e16f0b9323f.png)

**Comment by Spikeone** [comment]
Just to make sure, I checked the original and you are right indeed:
![grafik](https://user-images.githubusercontent.com/1276342/99493921-673c1980-2970-11eb-999c-7a3f1953f8b5.png)

**Comment by Fajny666** [comment]
Thanks for your reply :+1: 
Now I can see that the building was originally called as "Donkey breeder", but it was renamed to "Donkey breeding" in RTTR :).

**Comment by Flamefire** [comment]
Problem does not exist in nightly, so this was seemingly fixed some time ago
