### ISSUE TITLE
Invalid Savegame: File is not in a valid format

### ISSUE THREAD

**Issue by sgfan206** [Return-To-The-Roots/s25client#1315]
Hi,

I wanted to try out the latest version of RTTR and continue the map "SpikeWorld" from about 5 years ago.

When starting up the game and trying to load the savegames, they aren't displayed.

In the console it states "Invalid Savegame "(Path to savegame)"! Reason: File is not in a valid format!

Is there any way to restore those saves in order to play them in the new version?

Thanks in advance,

sgfan206

(attached the latest savegame as .zip file)

[World, XXVI.zip](https://github.com/Return-To-The-Roots/s25client/files/5660942/World.XXVI.zip)

**Comment by Spikeone** [comment]
As far as I know: no, there is no way to increase savegame version. You may use an older build in order to continue. Or is there any other way @Flamefire ?

**Comment by Flamefire** [comment]
No there is no way.

In recentish iterations of the savegame format I made sure there is some compatiblity, i.e. although the savegame format changes older ones can still be loaded in newer versions of RttR. But there is a limit and especially save games from before that change cannot be used any longer. So either use the old version of RttR you used back then or start a new game. Sorry about that but conversion of savegame versions is simply to much work

**Comment by sgfan206** [comment]
Well, thank you for the answer anyway.

And thank you Spike for this amazing mod and map alike!

Guess I'll start my virtual world conquest from anew then. XD
