### ISSUE TITLE
cmake fails

### ISSUE THREAD

**Issue by JensUngerer** [Return-To-The-Roots/s25client#1323]
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye

./cmake.sh --prefix=.
Setting Install-Prefix to "."
Activating release build
Generating files for "Unix Makefiles"
Running "cmake -G 'Unix Makefiles'  -DCMAKE_INSTALL_PREFIX=. -DCMAKE_BUILD_TYPE=Release './..'"
CMake Deprecation Warning at CMakeLists.txt:7 (CMAKE_POLICY):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Configuring for native compiling to Linux-5.6.0-2-amd64 on x86_64
-- Using platform config cmake/linux.cmake
-- Linking against boost dynamic libraries
-- Set boost library directory hint to: 
-- Boost 1.74.0 detected. No backport required
CMake Warning at CMakeLists.txt:151 (find_package):
  By not providing "FindClangFormat.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ClangFormat", but CMake did not find one.

  Could not find a package configuration file provided by "ClangFormat"
  (requested version 5.0.0) with any of the following names:

    ClangFormatConfig.cmake
    clangformat-config.cmake

  Add the installation prefix of "ClangFormat" to CMAKE_PREFIX_PATH or set
  "ClangFormat_DIR" to a directory containing one of the above files.  If
  "ClangFormat" provides a separate development package or SDK, be sure it
  has been installed.

-- Performing Test CXX_OVERRIDE_OK
-- Performing Test CXX_OVERRIDE_OK - Success
-- Performing Test CXX_OVERRIDE_FAIL
-- Performing Test CXX_OVERRIDE_FAIL - Failed
CMake Error at CMakeLists.txt:385 (ADD_SUBDIRECTORY):
  The source directory

    /home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/version

  does not contain a CMakeLists.txt file.

-- Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR) 
CMake Warning at driver/video/SDL/src/CMakeLists.txt:34 (MESSAGE):
  : SDL library not found: Not building SDL videodriver

-- Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR) 
-- Could NOT find SDL_mixer (missing: SDL_MIXER_LIBRARIES SDL_MIXER_INCLUDE_DIRS) 
CMake Warning at driver/audio/SDL/src/CMakeLists.txt:5 (MESSAGE):
  : SDL library not found: Not building SDL audiodriver

CMake Error at CMakeLists.txt:397 (ADD_SUBDIRECTORY):
  The source directory

    /home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/libendian

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:398 (ADD_SUBDIRECTORY):
  The source directory

    /home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/mygettext

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:399 (ADD_SUBDIRECTORY):
  The source directory

    /home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/libsiedler2

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:400 (ADD_SUBDIRECTORY):
  The source directory

    /home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/libutil

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:403 (ADD_SUBDIRECTORY):
  The source directory

    /home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/liblobby

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:404 (ADD_SUBDIRECTORY):
  The source directory

    /home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/s-c

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:405 (ADD_SUBDIRECTORY):
  The source directory

    /home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/s25update

  does not contain a CMakeLists.txt file.

CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindOpenGL.cmake:305 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  src/CMakeLists.txt:3 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Could not find a package configuration file provided by "boost_filesystem"
  (requested version 1.74.0) with any of the following names:

    boost_filesystemConfig.cmake
    boost_filesystem-config.cmake

  Add the installation prefix of "boost_filesystem" to CMAKE_PREFIX_PATH or
  set "boost_filesystem_DIR" to a directory containing one of the above
  files.  If "boost_filesystem" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:258 (boost_find_component)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:448 (find_package)
  src/CMakeLists.txt:5 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/build/CMakeFiles/CMakeOutput.log".
See also "/home/jens-ungerer/settlers2/0.8.2-16/s25client-0.8.2-16/build/CMakeFiles/CMakeError.log".
An error occured - please check above!

**Comment by Flamefire** [comment]
You need to run `git submodule update` first and then install the dependencies, i.e. SDL2, Boost, etc. See the output and the Readme
