### ISSUE TITLE
warning: writing 1 byte into a region of size 0 when compiling

### ISSUE THREAD

**Issue by JensUngerer** [Return-To-The-Roots/s25client#1327]
~/s25client/build$ make
[  3%] Built target translations
[  3%] Built target glad
[  4%] Built target boost_nowide
[  5%] Built target endian_static
[  8%] Built target s25util_common
[ 16%] Built target siedler2
[ 17%] Built target s25util_log
[ 18%] Built target s25util_network
[ 19%] Built target mygettext
[ 20%] Built target s25Common
[ 21%] Built target rttrConfig
[ 22%] Built target SGE
[ 23%] Built target gamedata
[ 26%] Built target s25edit
[ 26%] Built target s25update
[ 27%] Built target samplerate
[ 27%] Built target audiodrv
[ 28%] Built target videodrv
[ 28%] Built target videoSDL2
[ 28%] Built target audioSDL
[ 28%] Built target drivers
[ 29%] Built target lobby
[ 29%] Built target lobby_c
[ 29%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/GamePlayer.cpp.o
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp: In member function ‘void GamePlayer::Deserialize(SerializedGameData&)’:
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp:328:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  328 |         toolsSetting = sgd.PopUnsignedChar();
      |         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp:328:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp:328:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp:328:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
cc1plus: all warnings being treated as errors
make[2]: *** [libs/s25main/CMakeFiles/s25Main.dir/build.make:355: libs/s25main/CMakeFiles/s25Main.dir/GamePlayer.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1889: libs/s25main/CMakeFiles/s25Main.dir/all] Fehler 2
make: *** [Makefile:182: all] Fehler 2

**Comment by Flow86** [comment]
that looks like a false positive - can you tell me which compiler do you use? (`gcc --version`)

**Comment by JensUngerer** [comment]
Thank you for your immediate response.

I am using:
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye

with the latest updates (apt-get upgrade).

So it is:
~$ gcc --version
gcc (Debian 10.2.1-3) 10.2.1 20201224
Copyright (C) 2020 Free Software Foundation, Inc.

You can find out the version of all used libraries (and other software) via (e.g.)
https://packages.debian.org/bullseye/gcc

**Comment by stefson** [comment]
Do you think you're able to guide me to the debian.tar.xz file of your gcc that packs all the patches, hacks and spec files? I can't find it nowhere, thanks.

**Comment by Flow86** [comment]
@JensUngerer You can try to run cmake with `-DRTTR_ENABLE_WERROR=OFF` so it should display the warnings, but not bail out on them.

**Comment by JensUngerer** [comment]
> Do you think you're able to guide me to the debian.tar.xz file of your gcc that packs all the patches, hacks and spec files? I can't find it nowhere, thanks.

According to [0], it is possible to show a package and its dependencies
via e.g.    
```
apt-cache show gcc
```
"Even better", it is possible to get all dependencies of gcc via [1]

```
apt-cache rdepends --installed gcc
```

-->

```
gcc
Reverse Depends:
  g++
 |libtool
 |libfile-fcntllock-perl
  build-essential
 |libdpkg-perl
 |dpkg-dev
  cmake
```


and

```
apt-cache rdepends gcc
```

-->

```
gcc
Reverse Depends:
  gcc-doc
  notion-dev
  lmbench
  gcc-doc
  python3-numpy
  game-data-packager
  yotta
  wine64-tools
  varnish
  valac
  uwsgi-dev
  syrthes
  sa-compile
  libsimgrid-dev
 |sfront
  scilab-cli
  python3-sasmodels
  sasm
  rustc
 |ruby-inline
  selinux-policy-doc
  r-base-dev
  prayer-templates-dev
  perlbrew
 |pentium-builder
  liboctave-dev
  ocaml-nox
 |nodeenv
  g++
  nim
  musl-tools
  mklibs
  linux-source-5.9
 |libtool
 |libinline-c-perl
 |libfile-fcntllock-perl
  libdevel-cover-perl
  libdevel-checklib-perl
  libalien-wxwidgets-perl
  lcov
 |kore
  kdevelop
  iraf-dev
 |ikiwiki-hosting-web
 |ikiwiki
  haskell-stack
  gprbuild
  pari-gp2c
  goo
  golang-1.15-go
  gnucobol
  ghc
  gerris
  gcl
  gobjc++
  gobjc
  gm2
  gfortran
  gccgo
  gccbrig
  gcc-offload-nvptx
  gcc-offload-amdgcn
  gcc-multilib
  gcc-hppa64-linux-gnu
  gcc-avr
  build-essential
  gap-dev
  gambas3-gb-jit
 |libfuntools1
  frama-c-base
 |flex-old
 |flex
  f2c
  eclipse-titan
  ecl
 |libdpkg-perl
 |dpkg-dev
  libdmalloc5
 |dkms
 |diploma
  dahdi-dkms
  cython3
  cxref
 |cwebx
  critcl
 |creduce
  cproto
 |cpanminus
  codelite
 |codeblocks
  cmake
 |cfortran
  cl-cffi
  cbmc
 |cargo
 |anjuta
 |bochs
  bmt
  binfmtc
  arduino-core
  apt-build
```

Now it is possible to download all these source packages via [2].
E.g. [3] leads to [4][5].


[0] https://wiki.debian.org/Packaging/SourcePackage
[1] https://askubuntu.com/questions/128524/how-to-list-dependent-packages-reverse-dependencies
[2] https://www.debian.org/distrib/packages
[3] https://packages.debian.org/bullseye/gcc
[4] http://deb.debian.org/debian/pool/main/g/gcc-defaults/gcc-defaults_1.189.tar.xz
[5] http://deb.debian.org/debian/pool/main/g/gcc-defaults/gcc-defaults_1.189.dsc

**Comment by JensUngerer** [comment]
> @JensUngerer You can try to run cmake with `-DRTTR_ENABLE_WERROR=OFF` so it should display the warnings, but not bail out on them.

Thanks a lot. Now it compiles without ``ERROR``

```
....
[ 32%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/GamePlayer.cpp.o
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp: In member function ‘void GamePlayer::Deserialize(SerializedGameData&)’:
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp:328:22: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  328 |         toolsSetting = sgd.PopUnsignedChar();
      |         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp:328:22: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp:328:22: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
/home/jens-ungerer/s25client/libs/s25main/GamePlayer.cpp:328:22: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
[ 32%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/GamePlayerInfo.cpp.o
....
```

**Comment by Flamefire** [comment]
Reopening to handle that soonish. Although it is likely a GCC bug, but let's see if we can do anything about it

**Comment by Flamefire** [comment]
Hm, can't reproduce locally and on godbolt: https://godbolt.org/z/rdPz5f
If you got a full compiler invocation that triggers the warning on godbolt we could do something

**Comment by stefson** [comment]
I can try to reproduce within the next days.

**Comment by JensUngerer** [comment]
To be honest, i do not have much experience in C / C++.
So, i am not able to make it reproducable on ``godbold``.

But, I can tell you which version of Debian I am using.
Perhaps it is possible to make it reproducable (e.g. in a VM) with an installed version.

Recently, I changed by Debian-Sources from ``testing`` to the next release version ``bullseye``:
As far i could see: this leads to an package update of gcc sources... .

At first you need the current installer of ``testing`` [0].
Then, it is necessary to change ``/etc/apt/sources.list`` from ``testing`` to ``bullseye`` [cf. 1]:

```
deb http://deb.debian.org/debian bullseye main contrib non-free
```
(please, disable all other source lines via a leading ``#``).

Now, ist possible to apply these sources:

```bash
apt update && apt-get upgrade && apt full-upgrade
```

[0] https://cdimage.debian.org/cdimage/daily-builds/daily/arch-latest/amd64/iso-cd/
[1] https://www.debian.org/releases/testing/ppc64el/release-notes.en.pdf

**Comment by JensUngerer** [comment]
I was wrong, regarding the update of gcc / g++.

I've just re-downloaded and re-build:

```bash
git clone --recursive https://github.com/Return-To-The-Roots/s25client settlers25client
cd settlers25client/
git pull && git submodule update --init --recursive
```

```bash
mkdir -p build
cd build/
cmake -DCMAKE_BUILD_TYPE=Release .. > ./cmake_std_out.log 2> ./cmake_std_err.log
make > ./make_std_out.log 2> ./make_std_err.log
```
please, compare the attached files:
[cmake_std_out.log](https://github.com/Return-To-The-Roots/s25client/files/5768839/cmake_std_out.log)
[make_std_out.log](https://github.com/Return-To-The-Roots/s25client/files/5768841/make_std_out.log)
[make_std_err.log](https://github.com/Return-To-The-Roots/s25client/files/5768842/make_std_err.log)

**Comment by Flamefire** [comment]
> Recently, I changed by Debian-Sources from testing to the next release version bullseye:

This sounds like you are using an unreleased version, like a release candidate or so. Is this correct? Especially as I can't find any release of GCC 10.2.1 in the official downloads: ftp://ftp.fu-berlin.de/unix/languages/gcc/releases/

I'm asking because this is definitely a compiler bug which should be reported to either the Debian guys or the GCC guys.

For reference: The code is:

```
    std::array<uint8_t, 8> militarySettings_;
    std::array<uint8_t, 12> toolsSettings_;
    // ...
    for(uint8_t& militarySetting : militarySettings_)
        militarySetting = sgd.PopUnsignedChar();

    for(uint8_t& toolsSetting : toolsSettings_)
        toolsSetting = sgd.PopUnsignedChar(); // Warning here
```

As you can see that not only is the warning bogus, it doesn't also trigger in the code directly before. Any chance you can reach out to however is responsible for that GCC 10.2.1 you are using and check back with them?

**Comment by stefson** [comment]
gcc-10.2.1 is usually a git snapshot, at least the date appended to the version suggests this.

**Comment by JensUngerer** [comment]
If my bug report is transferred correctly (and accepted), it will be available via [1]

[1] https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=gcc-10

**Comment by JensUngerer** [comment]
> > Recently, I changed by Debian-Sources from testing to the next release version bullseye:
> 
> This sounds like you are using an unreleased version, like a release candidate or so. Is this correct? 

Yes, that is correct.

```bash
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```
The ``testing`` release will lead to the next release called ``bullseye``.
As far as i know, the so called ``code freeze`` will be done within the next weeks.

**Comment by JensUngerer** [comment]
> > Recently, I changed by Debian-Sources from testing to the next release version bullseye:
> 
> This sounds like you are using an unreleased version, like a release candidate or so. Is this correct? Especially as I can't find any release of GCC 10.2.1 in the official downloads: ftp://ftp.fu-berlin.de/unix/languages/gcc/releases/
> 
> I'm asking because this is definitely a compiler bug which should be reported to either the Debian guys or the GCC guys.
> 
> For reference: The code is:
> 
> ```
>     std::array<uint8_t, 8> militarySettings_;
>     std::array<uint8_t, 12> toolsSettings_;
>     // ...
>     for(uint8_t& militarySetting : militarySettings_)
>         militarySetting = sgd.PopUnsignedChar();
> 
>     for(uint8_t& toolsSetting : toolsSettings_)
>         toolsSetting = sgd.PopUnsignedChar(); // Warning here
> ```
> 
> As you can see that not only is the warning bogus, it doesn't also trigger in the code directly before. Any chance you can reach out to however is responsible for that GCC 10.2.1 you are using and check back with them?

Thank your for showing the minimal amount of code within the sources of ``s25client``.

Is it eventually possible to provide an example without the sources of ``s25client`` which leads to an compile
error, too?
I've tried to create such a minimal ``toy-example``, but it compiles successfully with ``g++ -std=c++11 ./bug-gcc.cpp -o ./bug-gcc``
[bug-gcc.cpp.txt](https://github.com/Return-To-The-Roots/s25client/files/5772202/bug-gcc.cpp.txt)

Or am i wrong, that your provided code snippet is in "pure" ``C`` (instead of ``C++``)?

**Comment by Flamefire** [comment]
Make sure you enable `-Wall -Wextra -Werror` to enable all warnings and make them an error.
if the attached example doesn't error, try 

```
#include <stdint.h>
#include <array>

constexpr unsigned NUM_TOOLS = 12;
using MSettings=std::array<uint8_t, 8>;
using TSettings=std::array<uint8_t, NUM_TOOLS>;
MSettings militarySettings_;
TSettings toolsSettings_;

uint8_t PopUnsignedChar();

void bar()
{
   for (uint8_t &militarySetting : militarySettings_)
      militarySetting = PopUnsignedChar();

   for (uint8_t &toolsSetting : toolsSettings_)
      toolsSetting = PopUnsignedChar(); // Warning here
}
```
(Not that this won't link, so compile with `-c`)

And if that doesn't help try making a class with the arrays as members and a member function to fill them. Sorry can't help much further as I'm only guessing here....

**Comment by JensUngerer** [comment]
> Make sure you enable `-Wall -Wextra -Werror` to enable all warnings and make them an error.
> if the attached example doesn't error, try
> 
> ```
> #include <stdint.h>
> #include <array>
> 
> constexpr unsigned NUM_TOOLS = 12;
> using MSettings=std::array<uint8_t, 8>;
> using TSettings=std::array<uint8_t, NUM_TOOLS>;
> MSettings militarySettings_;
> TSettings toolsSettings_;
> 
> uint8_t PopUnsignedChar();
> 
> void bar()
> {
>    for (uint8_t &militarySetting : militarySettings_)
>       militarySetting = PopUnsignedChar();
> 
>    for (uint8_t &toolsSetting : toolsSettings_)
>       toolsSetting = PopUnsignedChar(); // Warning here
> }
> ```
> 
> (Not that this won't link, so compile with `-c`)
> 
> And if that doesn't help try making a class with the arrays as members and a member function to fill them. Sorry can't help much further as I'm only guessing here....

Thank you for your help creating a kind of ``toy example``.

Unfortunatelly, I do not get compile errors for:
[gcc-bug-via-using-class.cpp.txt](https://github.com/Return-To-The-Roots/s25client/files/5773774/gcc-bug-via-using-class.cpp.txt)

using:
```bash
g++ -c --all-warnings --extra-warnings -Werror ./gcc-bug-via-using-class.cpp -o ./gcc-bug-via-using-class
```

It was just a kind of attempt / try: i am going to skip this ``toy example``.
The Debian developers should be able to make the compile bug reproducible with the code of your repository... .

**Comment by stefson** [comment]
confirmed with gcc-10.2.0-r5, that is patchlevel 6 on gentoo box amd64: 

```
[ 39%] Linking CXX executable ../../bin/Test_common
[ 39%] Built target Test_common
[ 39%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/SavedFile.cpp.o
[ 39%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/Savegame.cpp.o
[ 39%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/SerializedGameData.cpp.o
[ 39%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/Settings.cpp.o
[ 40%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/SignalHandler.cpp.o
[ 40%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/SoundManager.cpp.o
[ 40%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/TerrainRenderer.cpp.o
/tmp/s25client/libs/s25main/GamePlayer.cpp: In member function ‘void GamePlayer::Deserialize(SerializedGameData&)’:
/tmp/s25client/libs/s25main/GamePlayer.cpp:328:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  328 |         toolsSetting = sgd.PopUnsignedChar();
      |         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/tmp/s25client/libs/s25main/GamePlayer.cpp:328:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
/tmp/s25client/libs/s25main/GamePlayer.cpp:328:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
/tmp/s25client/libs/s25main/GamePlayer.cpp:328:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
[ 40%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/Timer.cpp.o
[ 40%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/TradePathCache.cpp.o
[ 40%] Building CXX object libs/s25main/CMakeFiles/s25Main.dir/Ware.cpp.o
cc1plus: all warnings being treated as errors
make[2]: *** [libs/s25main/CMakeFiles/s25Main.dir/build.make:356: libs/s25main/CMakeFiles/s25Main.dir/GamePlayer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1828: libs/s25main/CMakeFiles/s25Main.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
```

**Comment by Flamefire** [comment]
I may have a standalone: 
[GamePlayerPreprocessed.cpp.txt](https://github.com/Return-To-The-Roots/s25client/files/5774869/GamePlayerPreprocessed.cpp.txt)

It is basically a preprocessed version and should show the issue without anything else.

BTW: your gcc-bug-via-using-class.cpp.txt is different. I suspect that the compiler thinks the `for(char& militarySetting: ...) militarySetting=...` writes to a string while it clearly does not (its a char& not char*). So instead of `container->setMilitarySetting(PopUnsignedChar());` try `militarySetting = PopUnsignedChar();` (and the other one)

**Comment by JensUngerer** [comment]
> I may have a standalone:
> [GamePlayerPreprocessed.cpp.txt](https://github.com/Return-To-The-Roots/s25client/files/5774869/GamePlayerPreprocessed.cpp.txt)
> 
> It is basically a preprocessed version and should show the issue without anything else.

Thank you for your help!

I've just tried it:
```bash
g++ -c --all-warnings --extra-warnings -Werror ./GamePlayerPreprocessed.cpp -o ./GamePlayerPreprocessed
```
Unfortunatelly, I do not get any compile error... .

**Comment by JensUngerer** [comment]
> BTW: your gcc-bug-via-using-class.cpp.txt is different. I suspect that the compiler thinks the `for(char& militarySetting: ...) militarySetting=...` writes to a string while it clearly does not (its a char& not char*). So instead of `container->setMilitarySetting(PopUnsignedChar());` try `militarySetting = PopUnsignedChar();` (and the other one)

I've just adjusted the file as had you described it.
Unfortunately , I do not get a compile error, either:

```bash
g++ -c --all-warnings --extra-warnings -Werror ./gcc-bug-via-using-class.cpp -o ./gcc-bug-via-using-class
```

**Comment by Flamefire** [comment]
Gosh, seriously?
Ok next best thing: do a full compile of rttr with the Werror disabled. Then `touch GamePlayer.cpp` (adjust path), then `make VERBOSE=1`. You should get a long command somewhere ending in `-o CMakeFiles/s25Main.dir/GamePlayer.cpp.o -c .../GamePlayer.cpp`, this is what you need. if you replace that part by `-E > GamePlayerPreprocessed.cpp` you get what I sent but for your compiler and stdlib.
Then you can try again. If there is still no warning(!) then include the warning options from the command one by one (or in chunks) until you get there again. Then try the same options on the minimal example. This you can then further refine by removing options till you find out which option(s) show that.

Quick shot: Add `-fno-strict-aliasing` and try that together with the (all+extra) warnings.

**Comment by stefson** [comment]
I think I have a bit of a smoking gun here: 

on the gentoo side we had a bit of trouble with gcc concerning overly agressive optimization. In firefox, we had to disable tree-loop-vectorize function, which is part of -O3 optimization. You can see here for a source: https://github.com/gentoo/gentoo/blob/master/www-client/firefox/firefox-84.0.1-r1.ebuild#L773

I'm uncertain how to adjust the cflags and cppflags via cmake, but I simply took this command: 

```
cd /tmp/s25client/build/libs/s25main /usr/bin/c++  -DHAVE_STRUCT_TIMESPEC -I/tmp/s25client/libs/s25main -I/tmp/s25client/external/libsiedler2/include -I/tmp/s25client/external/libutil/libs/common/include -I/tmp/s25client/external/libendian/include -I/tmp/s25client/external/liblobby/include -I/tmp/s25client/external/libutil/libs/log/include -I/tmp/s25client/external/libutil/libs/network/include -I/tmp/s25client/external/mygettext/include -I/tmp/s25client/libs/common/include -I/tmp/s25client/libs/rttrConfig/src -I/tmp/s25client/libs/libGamedata -I/tmp/s25client/build/external/glad/include -I/tmp/s25client/libs/driver/include -I/tmp/s25client/libs/libsamplerate/include -I/tmp/s25client/build/_deps/libsamplerate-src/include -isystem /tmp/s25client/external/dev-tools/lua/include -isystem /tmp/s25client/external/kaguya/include  -O2 -DNDEBUG   -mfpmath=sse -msse2 -Wall -pedantic -Wextra -Werror -fno-strict-aliasing -pedantic-errors -Wcast-qual -Wdisabled-optimization -Wfloat-conversion -Wformat-nonliteral -Wformat-security -Wformat=2 -Wimport -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wpacked -Wparentheses -Wpedantic -Wpointer-arith -Wstrict-aliasing=2 -Wundef -Wunused -Wunused-parameter -Wwrite-strings -Wno-unknown-pragmas -Wctor-dtor-privacy -Wnoexcept -Woverloaded-virtual -Wstrict-null-sentinel -Wno-maybe-uninitialized -Wredundant-decls -Wsuggest-override -Wno-error=suggest-override -Wunreachable-code -o CMakeFiles/s25Main.dir/GamePlayer.cpp.o -c /tmp/s25client/libs/s25main/GamePlayer.cpp
```

and tried to disable certain parts of -O3 like tree-loop-vectorize with simply adding -fno-tree-loop-vectorize right after -O3 in the command, but it kept of failing. 

however, dropping the optimization to -O2 seems to do the job just fine. 

can you please provide me with some more information on how to allow -O2 globally where I just do this: 

```
git checkout --recursive && cd s25client && mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DRTTR_ENABLE_WERROR=OFF ..
make -jN 
```

**Comment by Flamefire** [comment]
So this happens in Release mode only? That was the missing peace, getting the same here now with GCC 10.2.0

**Comment by Flamefire** [comment]
This is the minimal code to reproduce the issue:
```
#include <stdint.h>
#include <array>
#include <cstring>

extern void* globalData;

class Container
{
public:

    std::array<uint8_t, 1> militarySettings_;
    std::array<uint8_t, 3> toolsSettings_;
    void bar();
};

void Pop(void* data, unsigned length){
    std::memcpy(data, globalData, length);
}
uint8_t PopUnsignedChar(){
    uint8_t i;
    Pop(&i, sizeof(i));
    return i;
}

void Container::bar()
{
    for (uint8_t &militarySetting : militarySettings_)
        militarySetting = PopUnsignedChar();

    for (uint8_t &toolsSetting : toolsSettings_)
        toolsSetting = PopUnsignedChar();
}
```
`g++-10 -O3 -Werror -c test.cpp`

**Comment by Flamefire** [comment]
On the GamePlayer.cpp the `-NDEBUG` is required to trigger this, on my example it is not. See godbolt.
You can set `CMAKE_CXX_FLAGS_RELEASE` via cmdline which should work

**Comment by JensUngerer** [comment]
> `g++-10 -O3 -Werror -c test.cpp`

excellent! I get the same error locally:

```bash
$ g++-10 -O3 -Werror -c test.cpp
test.cpp: In member function ‘void Container::bar()’:
test.cpp:32:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
   32 |         toolsSetting = PopUnsignedChar();
      |         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
test.cpp:32:22: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
cc1plus: all warnings being treated as errors
```

**Comment by stefson** [comment]
ok, I can confirm the minimal code test for gcc-10.2.0, and also confirm its a gcc-10 regression. gcc-9 doesn't show this error. Also -O2 on gcc-10.2.0 is fine. 

please do file a gcc bug upstream, I can later check out if gcc-11 is also affected.

**Comment by Flamefire** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98561 filed, GCC trunk is fixed

**Comment by stefson** [comment]
I think it's a good idea to fix this on your end, and linking back to this issue for reference. Given the lukewarm response and the four digits lines of code changed in the gcc-11 fix it may never be backported to the gcc-10 branch.
