### ISSUE TITLE
Sending goods: Games crashes when donkeys cross enemy territory or when alliance ends

### ISSUE THREAD

**Issue by jucs** [Return-To-The-Roots/s25client#1336]
Hello everyone,

I'm playing the current nightly and found the following bug: If an alliance ends while sending goods or if donkeys carrying goods cross territory that is captured by the enemy while crossing (i.e. they are then in enemy territory), the games crashes.

I have a save short before such a crash if required.

**Comment by Flamefire** [comment]
This shouldn't happen. Please attach the save and/or the replay

**Comment by jucs** [comment]
I'm attaching the saved game directly before the crash. In order to see the cause, navigate to the red player (in pause, crash is imminent). You'll find the following situation:

![Screenshot from 2021-01-08 03-18-22](https://user-images.githubusercontent.com/145247/103966626-867d4900-5160-11eb-8b27-168d6ff978ca.png)

Note the donkeys that are carrying goods to the red player are on red territory, but they are on enemy territory as soon as the castle is captured. This results in the crash.

Here is the [saved game](https://github.com/Return-To-The-Roots/s25client/files/5784883/bug1.1.sav.zip).
