### ISSUE TITLE
Optionsmenü nicht mehr erreichbar

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#134]
Wenn man das Spielstartet, dann im Hauptmenü die Auflösung + Anzeigemodus (in meinem Fall von 800x600 fenster zu 1920x1080 Vollbild) und dann im Spiel wiederum über das "Fortgeschritten" Menü gleiches noch einmal macht (in meinem Fall von 1920x1080 Vollbild zurück auf 800x600 fenster) ist das "Optionsmenü" im Spielhauptmenü nicht mehr erreichbar => man kann weder speichern noch beenden.

Der Wechsel von Auflösung oder Anzeigemodus alleine reicht nicht aus.

Weiterhin funktioniert nachdem dieser Bug auftritt auch der "X" button des Fensters (sofern man auf Fenstermodus wechselte) nicht mehr und man muss das CMD fenster schließen um das Spiel beenden zu können.

https://bugs.launchpad.net/s25rttr/+bug/849066

**Comment by Flow86** [comment]
kann ich nicht reproduzieren (weder mit WinAPI noch SDL)

der Fehler ist von 2011 - closing

**Comment by Spikeone** [comment]
Problem tritt weiterhin auf.
