### ISSUE TITLE
Network code broken

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#1340]
I think 

https://github.com/Return-To-The-Roots/libutil/compare/424edfa7e6aeedecbeee770a320c8b20b4433611...c9e02d57bb9fc8ae10ca5c5c036f95d7e4672050

broke the current network implementation on IPv4:

```
getaddrinfo: Der angegebene Host ist unbekannt.
Could not resolve 5.9.167.140:3664. Skipping...
Error connection to tyra.ra-doersch.de:3664
Sending Message to server failed
```

An older version without that commit included works, IPv6 also works

**Comment by Flow86** [comment]
I think its the part where you removed emptying the ports in line 849/854

thats why it shows the port in "Could not resolve ..."

**Comment by Flamefire** [comment]
> I think its the part where you removed emptying the ports in line 849/854

Interesting. While this seems to be true I carefully checked every resource I could find and nothing would tell me this, hence the removal.

**Comment by Flow86** [comment]
yes, interestingly this only made a problem on ipv4 code, ipv6 worked fine.
