### ISSUE TITLE
Can't play Lan games

### ISSUE THREAD

**Issue by Bagu** [Return-To-The-Roots/s25client#1342]
Hello,

I use the latest version of RTTR.
When i create a lan game, without password, with firewalls disabled, on a windows 10 20h2, the second player see the game in lan game list, but he get "Can't connect" error message. 

I try with firewall and without firewall enable.
I try to switch host and server (in hosting game)
I try trought lan game and direct ip game
I try using ipv6

Nothing work, i can't play lan game.
What is wrong ? What i miss ?

Thanks

**Comment by Flamefire** [comment]
You can check the log/console if there is any additional message that might help here. Are you both in the same LAN/network? Can you try over lobby instead (at least to test)?

**Comment by Flow86** [comment]
Hi, you can retry with latest nightly, we had some issues with a small change in the network code causing trouble, see #1340

**Comment by Bagu** [comment]
Hello,

We are on the same network. But this network is not able to access internet.
Here are the other messages : 
getaddrinfo: Hôte inconnu.
GameClient::Connect: ERROR: Connect failed!

I will try the latest nightly as soon as possible

**Comment by Bagu** [comment]
Version 20210109 work as expected ;)

Many thanks
