### ISSUE TITLE
Mapgenerator may generate invalid maps (missing players)

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1346]
The mapgenerator uses `PlaceHeadQuarter` (sidenote: typo, should be `PlaceHeadquarter`) which may fail. However this is not caught and a map is generated anyway.
This might lead to a real problem as I'm not sure how S2 would handle a HQ which is effectively set at `(-1,-1)`

I caught this problem in the improved test cases in https://github.com/Return-To-The-Roots/s25client/pull/1335 where a randomly sized water map which turns out small and with a lot of players fails to create enough islands (?) and therefore doesn't place all HQs.

@vader1986 Any idea how to handle this? It might be worth checking for valid points before writing those to the map header. (at least assert/check and throw). I'd say throwing an exception is acceptable if placing a HQ fails (you can decide if `PlaceHeadQuarter` should do that instead of returning false or maybe better the calling code as it could decide to use another location instead based on the return value). This can be caught and shown in the GUI (maybe simply: "Failed, try again or change settings"-style)

**Comment by vader1986** [comment]
Yeah, this is a bit of an annoying edge case. There're already thing to avoid this case (re-try placing HQs in different positions), however, it can still happen. Maybe throwing an exception in this place (and 2 more places, same file):
https://github.com/Return-To-The-Roots/s25client/blob/master/libs/s25main/mapGenerator/RandomMap.cpp#L288

Something like this:
`if(!PlaceHeadQuarters(map_, rnd_, map_.players))`
`{`
`    throw exception;`
`}`

We should probably catch it somewhere and display an error message like:
"Failed to generate map, please retry!"

**Comment by vader1986** [comment]
Sorry, I just read the last part of your message. Yes, makes sense what you suggest. Throwing the exception in `PlaceHeadQuarter` and catching it some more upper level to display a message in the GUI.

**Comment by Flamefire** [comment]
> re-try placing HQs in different positions

This is what I mean: This could happen outside `PlaceHeadQuarters` then it should return a bool or inside it, then it should throw and not return anything. But in both cases this should be handled. I guess this will very likely occur on a 64x64 island map with 8 players (of course this is on the user, but currently it silently fails to generate a "correct" map)

**Comment by vader1986** [comment]
Working on a PR for this.

**Comment by vader1986** [comment]
I think this one can be closed?

**Comment by Flamefire** [comment]
Yes. You can include a "Fixes #<nr>" in the PR or commit to auto-close such things :)
