### ISSUE TITLE
Ingame Swap Player Async Bug

### ISSUE THREAD

**Issue by JonathanSteinbuch** [Return-To-The-Roots/s25client#1370]
Hello,

when you swap players ingame in a multiplayer game (i.e. one player swaps with a dummy), very often (but not always) the game almost immediately asyncs.

I didn't find the problem in a quick analysis and since ingame player swapping is marked in the code as a replay and debug feature only I wasn't too inclined to continue looking.
I guess the most reasonable solution is to disable ingame player swapping (or dummies?) if neither replay or debug mode are active. What do you think?

For completeness I added savegames and logfiles. But any multiplayer game with at least two clients and at least one dummy seems to produce the bug when swapping around players a bit (not always on the first swap)

[player_swap_async.zip](https://github.com/Return-To-The-Roots/s25client/files/5975523/player_swap_async.zip)

Best Regards
Jonathan

**Comment by Spikeone** [comment]
Well, in a singleplayer it's fine as well, isn't it?

**Comment by JonathanSteinbuch** [comment]
True, the bug only happens in multiplayer. I was just going by a comment in the code that said that player swapping is meant only for debugging and replays.

**Comment by Flamefire** [comment]
Strange, I remember spending quite some time making sure it doesn't desync. But I guess there could still be issues when multiple players are involved. I don't think this is useful in multiplayer games so I'd just disable it instead of hunting that down. It is an undocumented feature anyway IIRC
