### ISSUE TITLE
game does not start in fedora and opensuse

### ISSUE THREAD

**Issue by bcoolumbo1** [Return-To-The-Roots/s25client#1374]
1 video drivers found!
/rttr/bin/rttr.sh: line 58:  1849 Aborted                 $cmd $DIR/../bin/s25client $*
An error occured: press enter to continue

or

(gdb) run
Starting program: /rttr/bin/s25client 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Return To The Roots v20210206-08db639f024853242481d208c51714397bed272d
Compiled with GNU C++ version 8.3.0 for linux 64 Bit
1 video drivers found!
Program received signal SIGABRT, Aborted.
0x00007ffff7a9f9d5 in raise () from /lib64/libc.so.6

no error message, even with debuginfo installed

Runs flawlessly in arch, debian, slackware, pld, void, gentoo

**Comment by Flamefire** [comment]
Not sure here, maybe libSDL2 or libSDL2_mixer is not installed?

Anyway added a PR to make sure the exception is shown instead of a plain crash

**Comment by bcoolumbo1** [comment]
sudo bash -c "dbus-uuidgen  >| /etc/machine-id"; /mnt/games/rttr/bin/rttr.sh noupdate

did the trick
