### ISSUE TITLE
Remove version from window title

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1378]
Issue from Discord:

> can you change the title of the game when running? So that my friends can see when I play it here on discord?  Now I can add the game, but the title is just the version
> so it shows like:
> AdamPodstavka
> Playing v0.8.2-0383c0c

I guess this only applies to the stable in that extend but IMO we don't need the version in the window title. I'd vote to remove it as it is already in the lower left corner of the menu

CCing @Flow86

**Comment by Flow86** [comment]
The idea is that the window title changes to the game bane the person is currently playing (if playing online), so Discord can pick it up and display it instead of only showing "Return To The Roots vX.Y.Z"

**Comment by Flamefire** [comment]
If I understand the request correctly the stable has a title consisting only of the version and the person wants the title to be "Return To The Roots" instead so Discord shows that the person is playing RttR
For the nightly this means simply removing the version from the title
