### ISSUE TITLE
[AI] Add ChatNote to allow AI to receive (and act on) chat messages 

### ISSUE THREAD

**Issue by jdoerfert** [Return-To-The-Roots/s25client#1381]

**Comment by Flow86** [comment]
No text?

**Comment by Spikeone** [comment]
I guessed he'd like to have a lua function like `onChatMessage(sender, team)` or something alike

**Comment by jdoerfert** [comment]
I want to have a ChatNote notification, like ShipNote, you can subscribe to. They should contain the message that would show on your screen.

**Comment by Flamefire** [comment]
This is a bit tricky. All other Notes are "synchronized" with the game, i.e. fully reproducible and happen at the exact same time on all clients. Chat messages don't. They are sent and shown ASAP.
Can you share a bit more what the AI should/could do with that?

**Comment by jdoerfert** [comment]
Right now, I cannot ask my AI teammate to send me a resources/troops, expand northeast, or synchronize an attack with me. All these things I'd like to do. So if a teammate uses the magic words in chat, I want the AI be able to parse them and change behavior accordingly. Any timing would be fine. Initially, I thought the moment you show it on a screen you would also send a notification. I'm also fine with some other timing behaviors, anything that allows the AI to read the chat really.

**Comment by Spikeone** [comment]
Would be better to have like a trade request option - that way noone needs to "know the magic words" in order to ask the AI.

**Comment by Flamefire** [comment]
I think the idea is good. My take would be to rather add a function to AIPlayer, similar to RunGF which AIs can overwrite. This will be called by the GameClient (ATM at least).
I think it also makes sense to add a general chat function to the AIPlayer or better AIInterface where chat messages are stored and the client can pull it from there. So the AI can talk with other players

**Comment by jdoerfert** [comment]
> I think the idea is good. My take would be to rather add a function to AIPlayer, similar to RunGF which AIs can overwrite. This will be called by the GameClient (ATM at least).

Works for me, especially if we can add commands.

> I think it also makes sense to add a general chat function to the AIPlayer or better AIInterface where chat messages are stored and the client can pull it from there. So the AI can talk with other players

I would like that in the long run.


> It might make sense to provide a "magic word" interface. E.g. something like `@AI_Foo /attack now` and if not understood the AI sends its supported commands.

Right, preferably, we can easily add commands.


> What I worry about though: This might lead to players controlling the AI to much. This would mean (good) players play with more than just their own player but also with all (team) AIs...

Maybe, you can disable player control or restrict it in the options if you really worry. However, right now we have the opposite problem, the AI does not coordinate with the players at all. You cannot organize resources, mountains, attacks, etc. in any way. The AI is not good right now, making it "too good" is something I would worry about once we get there.
