### ISSUE TITLE
Compress savegames and replays

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1383]
I think it makes sense to compress the data part of savegames and replays. The header should be stored uncompressed for fast access in the list but the game data (e.g. savegame, commands, ...) should be compressed.
For instance a normal replay of about 200k GFs is about 800kB. It can be easily compressed to about half the size.
For a replay starting from a savegame the size is about 4MB and can be compressed to about 400kB

I noticed that when creating the PR for testing replays for asyncs, because we really don't want large binary data in the repo.

**Comment by Flow86** [comment]
you mean for transfer between players (aka on game start?)? On disk I don't care to be honest?

**Comment by Flamefire** [comment]
No I meant for on disk. I know disk space is cheap and everything but the savegames and replays can pile up. And being able to "simply" reduce the size by a factor of 2-10 makes me feel guilty for wasting space. (Again, I have no problem with *using* space, just wasting it)
We already have a more or less simple way for compressing data so we could implement this. The only issue is, that this requires increasing the format version as we need to store a flag if the data is compressed. This means old savegames and replays can't be loaded anymore but at least we can drop all the compatibility workarounds, especially after #1367 is merged.

For replays it is a bit tricky because we need to have a compressed and uncompressed format. The latter is used for directly writing to disk so we have the replay even if the program is force-terminated/crashed. My idea was that on closing the file we simply copy the header and the compress the rest after setting the flag, that the data is now compressed.

**Comment by Flow86** [comment]
hmm its making everything so much more complicated, I don't like that
