### ISSUE TITLE
Crash when you click an allied HQ

### ISSUE THREAD

**Issue by jdoerfert** [Return-To-The-Roots/s25client#1392]
The latest version 20210309 crashes when you click an allied HQ:
``RttR crashed. Backtrace:
0x55ab4f810bed
0x55ab4f804912
0x55ab4f804cc9
0x7f06d6410f80
0x55ab4f93d012
0x55ab4f93d28a
0x55ab4f912cfc
0x55ab4fa002b8
0x55ab4f9935ce
0x55ab4f828fd5
0x7f06d693fe31
0x55ab4f85c4a5
0x55ab4f812239
0x55ab4f7fb35b
0x7f06d63fbb25
0x55ab4f80439a
RttR crashed. Please restart the application!

Press ENTER to close this window . . .
client state changed to stop
corrupted double-linked list
```

**Comment by jdoerfert** [comment]
Same if you click storehouses :(

**Comment by Flamefire** [comment]
Can't reproduce. Please attach savegame / replay.

**Comment by eluphay** [comment]
Same problem, seems to happen after you first save and reload a saved game, Not when you first start playing it works fine at that point. 
Basically...
Trade becomes useless after you load a saved game, but works until you save and reload the game that you started.
Seems to happen with all saves and all maps

**Comment by eluphay** [comment]
awesome, thank you

**Comment by Flamefire** [comment]
The crucial information here was that it needs a savegame to trigger this bug, so thank you for that!

**Comment by eluphay** [comment]
Your welcome

**Comment by jdoerfert** [comment]
Thanks for fixing this :)
