### ISSUE TITLE
[Seafaring] Wrong selection of "strong attacker"

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#14]
When playing with the latest nightly build and attacking an enemy harbour building by ship, you are able to select "strong attacker" like you can in a "normal" attacking window. Problem is, that it's not working correctly. In most cases my fortress with 6 generals was taken but when I sent 7 attackers, not my other fortress with 2+ generals was taken but an other military building with weak soldiers. Sometimes even my "main" fortress only sent 4 generals and 2 soldiers were taken from somewhere else.

Replay: (3bf7f23)
http://www.rfmonline.de/rttr/spike/2015-07-24_22-40-31.rar

**Comment by jhkl** [comment]
No replay attached / wrong link

**Comment by jhkl** [comment]
Please add savegame of situation where this is reproducible or state gameframe where this is happening in the replay.

**Comment by Spikeone** [comment]
http://www.rfmonline.de/rttr/spike/forjh.rar

New file Screen
