### ISSUE TITLE
Support for MP3

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#141]
- [x] 1. Please include mp3 support.

- [x] 2. Please include "Add directory" option. All of the oggs and mp3s would be added to the playlist from the directory.

off: I just converted and added the musics of Settlers 4, 10th Anniversary and Settlers 7... It is AWESOME now :)

OLiver (postfach-von-oli) wrote on 2010-05-04:
(1) difficult because of license restrictions...
(2) implemented. 

https://bugs.launchpad.net/s25rttr/+bug/574710

**Comment by Flow86** [comment]
1. SDL_mixer should support mp3, but it depends on the corresponding system if its built with mp3 support or without.

**Comment by MarcusSt** [comment]
Can be closed I guess, as mp3 support depends on the audio driver and 2. is already implemented.
