### ISSUE TITLE
KI Verbesserung 2

### ISSUE THREAD

**Issue by Star-Killer17** [Return-To-The-Roots/s25client#1413]
In der folgenden liste führe ich schwächen auf was die KI derzeit tud

- Goldmünsprägereien oder Lager direckt an die Gränzen bauen
- Bei Soldatenmangel verstärkt Festungen bauen ( die in der Regel nicht mehr besetzt werden oder wen nur mit einer person)
![Screenshot 2021-04-21 152249](https://user-images.githubusercontent.com/82950939/115561025-71fb3180-a2b5-11eb-8f30-10a21bec261b.png)

**Comment by Spikeone** [comment]
Die Festungen werden gebaut, in der annahme wieder Soldaten zu produzieren, das hat nichts direkt mit dem Mangel zu tun. 

Grundlegend ist das auch nicht falsch, schickt ein Verbündeter Soldaten, so können diese gleich Gebäüude besetzen.

Lager an der Grenze sind auch nicht falsch, warum sollten sie? Transportwege werden verkürzt, eingelagerte Soldaten können schneller zu Gebäuden gelangen.

Bin mir nicht so sicher ob man daran wirklich etwas ändern sollte, wie siehst du das @Flamefire ?

**Comment by Flamefire** [comment]
Genauso. Soldaten können nachproduziert werden. Militärgebäude abreißen/neu bauen ist doof.
Die KI könnte maximal etwas langsamer expandieren in solchen Fällen, aber das kann auch Probleme machen

**Comment by Star-Killer17** [comment]
Habe bis lang nicht einmal gesehen das verbündete verstärkung geschickt haben

**Comment by Spikeone** [comment]
Du kannst mit der KI zusammen spielen.

**Comment by Spikeone** [comment]
Wie beschrieben, sehen wir derzeit keinen Grund das Verhalten zu ändern.
