### ISSUE TITLE
Pineapple - trees cannot be harvested

### ISSUE THREAD

**Issue by ahasver-git** [Return-To-The-Roots/s25client#1414]
Since the pineapples can't be removed in s25client they are a nuisance to me.
1. It's looking weird if everything else is cleared and these trunks are still standing about.
2. When these plants come in one's way, while building straight roads, workarounds don't look nice either.

Can't they be treated as normal trees by the woodcutter?

**Comment by Spikeone** [comment]
This is correct. On some maps they are used for designing barriers.

See #921 which suggests an addon for that

**Comment by ahasver-git** [comment]
Even if they are useful in _SOME_ maps - they are still a nuisance in the bulk!

**Comment by Spikeone** [comment]
Not saying anything else, thats why I suggested an addon for chopping them down some time ago :)
