### ISSUE TITLE
updater calls non existing command

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1417]
the upder has given me the following message

```
Der Befehl "GPL-2.0-or-later" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

**Comment by Flow86** [comment]
rttr.bat is definitly wrong, the REM lines must come after @ECHO OFF

**Comment by Flow86** [comment]
ah that happens only once because the bat file changes
