### ISSUE TITLE
Support for clang-13 compiler

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1430]
hey there, I installed clang-13.0.0_rc1 and it fails to compile s25rttr with a bunch of errors: 

```
/var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/common/include/Point.h:27:15: error: definition of implicit copy assignment operator for 'Point<int>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
/var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/common/include/Point.h:27:15: error: definition of implicit copy assignment operator for 'Point<int>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
/var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/common/include/Point.h:27:15: error: definition of implicit copy assignment operator for 'Point<short>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
/var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/common/include/Point.h:27:15: error: definition of implicit copy assignment operator for 'Point<int>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
/var/tmp/portage/games-strategy/s25rttr-9999-r6/work/s25rttr-9999/libs/common/include/Point.h:27:15: error: definition of implicit copy assignment operator for 'Point<int>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
```

the compressed build log is attached

[clang-13.zip](https://github.com/Return-To-The-Roots/s25client/files/6946128/clang-13.zip)

**Comment by Flamefire** [comment]
Thanks for the report. However we cannot and hence will not unreleased compiler versions as everything which is not easily testable on CI and might even change until release is more work than it is worth.
Closing this for now. Feel free to reopen once Clang 13 is officially released and available in the ubuntu repos.

Thanks!

**Comment by stefson** [comment]
which ubuntu version do you use?

**Comment by Flamefire** [comment]
I don't thing this is true. I have clang 6-11 on my Linux Mint 20 (Ubuntu 20 IIRC)
And yes ppas are acceptable if they work on Gthub CI.
Major point: It must be officially released and testable on CI or else it is unsupported. Period. Otherwise we waste to much time

**Comment by stefson** [comment]
@Flamefire are you now able to have clang-13 on CI? 

apt.llvm.org does have packages for both 18.04 and 20.04

**Comment by Flamefire** [comment]
Yes. Working on a PR.
