### ISSUE TITLE
0.9.1 Can't join games

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1435]
It looks like a Linux player can not join a game hosted by a windows player.

Both players ran rttr.bat to make sure they have the same version - no luck, the game still greets with version missmatch

**Comment by Flamefire** [comment]
Could you post the begin of the log, i.e. the part where the version is stated? Should be something like 
> Return To The Roots v0.9.1-.... Compiled with ...

**Comment by Flamefire** [comment]
Looks like the linux version has the revision truncated:
Linux: 7273dd8c3fa98f3892af28d415aca77a
Windows: 7273dd8c3fa98f3892af28d415aca77a5d58fdd4

We need to double check that

**Comment by Spikeone** [comment]
yeah sorry, don't have linux and the player I played with didn't answer since

**Comment by stefson** [comment]
here is the output from my self compiled v0.9.1 binary:

s25client 
Return To The Roots v0.9.1-7273dd8c3fa98f3892af28d415aca77a5d58fdd4
Compiled with GNU C++ version 9.4.0 for linux 64 Bit

hope that helps

**Comment by Flamefire** [comment]
@Flow86 Still not sure where the shorter revision comes from.
If I do `git checkout v0.9.1 && cat .git/HEAD` I get the correct one on my Linux system. Something wrong with the build images?

**Comment by Flow86** [comment]
when I run it manually on the build images I also get the right version?

**Comment by stefson** [comment]
so have you ironed this one out? If not, I'm on linux and am willing to help you push out a stable 0.9.2 release. Just ping me with @

**Comment by Flamefire** [comment]
@stefson Feel free to try and build a stable linux version from current sources. If that works too, I'd say we go and try to tag a 0.9.2 and build it on Jenkins. The new check I added should catch the issue if it still occurs.

**Comment by stefson** [comment]
It's multiplayer, I can't test it alone man :-) 

(joining the lobby works)

**Comment by Flamefire** [comment]
Just check the revision on startup that it is indeed long enough. But if it compiles it will work due to the new check

**Comment by stefson** [comment]
Well, that part was never a problem with my checkout:

```
Return To The Roots v20210924-df0fe3ae7ef062245914360f6275fcadbb08d4b3
Compiled with Clang version 12.0.1  for linux 64 Bit
```

It was a problem for the binaries provided by your buildserver. Hence the fix is only in the updater, jenkins, and workflows, right?

**Comment by Spikeone** [comment]
@Flamefire isn't this one fixed by your commit?

**Comment by Flamefire** [comment]
I assume so. However I'd keep this open until @Flow86 creates a 0.9.2 so we have a working stable

**Comment by Flamefire** [comment]
Fixed in latest stable
