### ISSUE TITLE
near harbor flags off

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1436]
![grafik](https://user-images.githubusercontent.com/1276342/132755486-608d81a8-6b9b-4324-9810-20fd6e004413.png)

They are off, at least on barracks and guardhouses

**Comment by Flamefire** [comment]
Do you have a savegame? or replay?

**Comment by Spikeone** [comment]
[flags.zip](https://github.com/Return-To-The-Roots/s25client/files/7161014/flags.zip)

**Comment by Flamefire** [comment]
Ok found and fixed. Stupid C&P mistake.
@Flow86 That might be even worth a new bugfix release. Maybe together with https://github.com/Return-To-The-Roots/s25client/issues/1435 when we found the reason
