### ISSUE TITLE
Migrate Infrastructure and Code to C++11/14

### ISSUE THREAD

**Issue by lweberk** [Return-To-The-Roots/s25client#144]
As it says in the Issue Description. Kind of a bummer, that you see compiler constraint arguments popping up here and there. There is absolutely no reason why this project needs to stay in the past. There is no client interface towards customers and its a closed ecosystem. There must be a way to get this Issue out of the way.

Btw. Fixed width types require C++11. See issue #94. So again, ugh...
- [x] List reasons why we cant move on to current standards.
- [ ] Tackle them, and ensure we can continue moving with the standard. This should also be done in a way, that ensures this for the future too.
  - [ ] Get manual builds and crossbuilds running 
    - [x] GCC - Linux (x86_64/amd64)
    - [ ] GCC - Linux (x86_32/i686)
    - [ ] GCC - Windows (x86_64) (mingw libs via GCC triplet)
    - [ ] GCC - Windows (x86_32) (mingw libs via GCC triplet)
    - [ ] GCC - Mac (x86_64) (https://github.com/tpoechtrager/osxcross)
    - [ ] GCC - Mac (x86_32)
    - [ ] Clang - Linux (x86_64)
    - [ ] Clang - Linux (x86_32)
    - [ ] Clang - Windows (x86_64)
    - [ ] Clang - Windows (x86_32)
    - [ ] Clang - Mac (x86_64) (https://github.com/tpoechtrager/osxcross)
    - [ ] Clang - Mac (x86_32)
    - [ ] Clang - BSD (x86_64) (BSD switched to LLVM/Clang as default)
    - [ ] Clang - BSD (x86_32) 
  - [ ] Buildinfrastructure
    - [x] Get a buildserver running
    - [x] Linux Buildslave
    - [ ] BSD Buildslave
    - [ ] Windows Buildslave
    - [ ] Mac Buildslave
  - [ ] Switch over to another issue regarding build system cleanup

**Comment by MarcusSt** [comment]
It would be great, but as long as the cross compilers installed on the build server do not support C++11 (or later), we cannot use it. It does not help to use the newest C++ version at the expense of having only the source code available for players to "play" with.

Once the build server can manage to build binaries for all supported platforms from C++11 source, this shouldn't be a problem. Although there's only one person who can update the server and this issue is imho low priority compared to actual bugs (as in crashes) we are facing, it should be dealt with.

**Comment by lweberk** [comment]
Agreed. Goes without saying, that source code without distributable binaries is not worth much. 

What specs and compilers/cross-compilers are running on the build-server? Ive a ton of unused computing power at my workplace y can spare for as long as it is not required (probably longer/outliving the machines providing it). We could run a parallel, more updated buildserver taking us forward, while the current one continues to deliver a current stable.

**Comment by Flow86** [comment]
the computing power is not the problem. We have enough computing power ...

We only have the problem that the only apple cross compiler exists is the one I build years ago. newer odcctools are not existing. perhaps we could try to build a newer cross-gcc with those old "binutils" for apple (I tried it already, but failed) since apple modified a lot of the original gcc code.

There are 2 possibilitys: remove release support for macos and use c++11, or simply dont use c++11 since most compilers dont support them fully anyway. (I dont see any benefit using c++11)

current build server compiler versions:
- windows: mingw-gcc 4.4.5 (64+32bit)
- linux: gcc 4.6.3 (64+32bit)
- macos: gcc 4.2.1 (64+32bit and ppc)

**Comment by Flamefire** [comment]
Using C++11 greatly simplifies a lot of things. At the very least it supports std::array and std::unqiue_ptr and (greatest improvement ever): Moves (rvalues)
The current code is so trashed with pointers everywhere that there are many problems with leaks etc. C++11 would make them easier to handle. For example by allowing moves but no copies (returning unqiue_ptr beein one example)
@lweberk If you can set up a build system under linux, that builds the current source with C++11 support for all platforms, then flow can put this on the official build server. (I assume you have the knowledge (and time) to do that?)

One thing: VS2010 only supports a subset of C++11. I have VS2012 myself and even that does not support half of it: https://msdn.microsoft.com/de-de/library/Hh567368%28v=VS.120%29.aspx
So even beeing able to use C++11 I'd restrict ourselves to some basic features like static_assert, auto, nullptr, move.
Ok... Seeing this small list we can propably forget C++11... Not beeing able to use VS would exclude most windows devs.

**Comment by Flow86** [comment]
@Flamefire: exactly. 

Never change a running system. So, as few changes as needed.

Of course, unique_ptr etc are improvments, but: so many leaks arent there that need these. And we could use some of the boost stuff at the moment if you really need some things.

"auto" is perfect for iterators or something like that, but using auto excessivly is lowering the readability of the code significantly.

So: FIRST we try to get a good stable release again, THEN we can look if we can look if we should use new coding features

**Comment by Flamefire** [comment]
But IF we had move and auto, we can fix some of the bugs permanently. E.g. factories (and all other pointer-returning methods) should return unique_ptrs. So you can never forget to free them.
BTW: We got to replace most of the pointer stuff... Mostly it can be solved with references

**Comment by Flow86** [comment]
yes moving to references is better way to solve it

**Comment by lweberk** [comment]
@Flow86 
Yes, our machines run all Jessie x86_64. It would be really cheap to dish out LXC containers for the purpose.

Regarding the Compilers:
* Clang/LLVM is cross-compiling by default if you properly get the dependant system libraries reeled into the build. No experience with it but it should not be *thaaat* hard right? :S
* GCC is sensing the heat from that and has some improvements as of late (also trying to support the cross-compile triplets, like clang). Same constraints still valid here though. You need the system libraries reeled in.
Would be happy to try getting both tool chains to work. Would still need someone on the Mac side and someone on the Win side to test binaries though, have non of those systems around to do it myself.

So there are tools to be able to comply with the requirements. Unfortunately, cannot speak for Microsoft compilers (VS2010 should be able to use compilers newer that 2010?)

@Flow86 
Adding to the needs of C++11/14 ... remember <cstdint> is C++11, it implies deterministic type widths across arches, no fingers crossed and implicit trust anymore.

Regarding auto:
Fully agree with @Flow86. For iters and maybe uses like on make_unique/make_shared lines, yes... most other cases no. Explicit is always more readable and overall better than implicit. Types watch over your intentions, and other code-readers read that very same intentions too.

@Flamefire 
Be careful with pointer indirection. Smart handles cause indirection. Its all nice and fine, as long as you don't mess with linear memory for the game state vectors. It hurts performance in orders of magnitude.

**Comment by Flamefire** [comment]
I don't think you can use other compilers than the VS ones when using VS. So we would need to stick to a minimum of the features. But I think this is ok. Just shoot for C++11 not 14 (which is hardly available anywhere though)

What case do you mean? unique_ptr does not incur any overhead in speed or size. shared_ptrs are bad for both and intrusive_ptr is pretty good when you REALLY need a shared_ptr. But yes that one causes some overhead on copy. Not for moves though. I'd avoid shared/intrusive_ptr anyway. If someone uses that he got to have a good reason to do so. But unique_ptr should be the one to use where you want to pass a pointer (and therefore ownership)

**Comment by lweberk** [comment]
@Flamefire 
Do not know how smooth it works but MSVS can work with clang, but https://github.com/ishani/ClangVSx . I also heard about efforts to bring in native support for the clang toolchain.

About the support of stuff and compilers, you might be surprised how well things go. GCC and Clang have full support for both C++11/14. The MS and Intel compilers are a bit out of it though. The bigger problem are the C++ standard library implementations.
Details (fairly up-to-date) http://en.cppreference.com/w/cpp/compiler_support .

You might already see my slight bias towards Clang :D. It just integrates way better than GCC, even though they have done a incredible job at changing that.
Caveat is, that I heard about really shitty s25client performance coming out of clang... no idea what version, why and accuracy of the statement though.

Pointers: sure, if you are using a raw pointer it does not matter to switch that to a smart one (other than adding a refcounter overhead in case of the shared one). What I meant is the introduction of indirection (usage of pointer in general), specially when it comes down to the game state. Performance drops once the CPU can't tell what you are doing memory-wise, which is when you break linearity of memory. We are talking about jumps in orders of magnitude. That is why we should push away as much usage as possible of; list, map, <place anything non-contiguous here>. Or as a matter of fact; a vector of pointers (you fall through the cache all the time, because the actual objects are all over the place). Pointer to vector is fine though.
Do not overestimate the cost of copying a whole vector because you just outgrew it, relative to the cost of non-linearity. Performance bottleneck is in cache latency, not in actual crunching.

**Comment by Flamefire** [comment]
Using MSVS with anything else would still be bad. We need to keep the barrier to change anything in s2.5 low to not scare off anyone. That's why we have the contrib folder. Just clone, cmake and compile. Nothing else to do. And setting up VS with another compiler IS a huge barrier. But still: the features of C++11 supported by VS2012 (end even 2010) are already very good.

Pointers: Don't overestimate that. Processors are mode for that ;) And we need pointers as we often only store the base typed pointers (e.g. GameObject). Nothing that can be done there. And before you say that a specific use(!) is performing bad: Prove it (via profiling) before you change some nice design to something with a bit better performance. ;)
But yes using appropriate data structs IS important. Use a list when you need to sort, insert and delete. Use a set for something sorted and a vector for (almost) everything else. Don't judge on performance to much. Rather review the design: "Only append to a list used? --> Vector is better choice"

**Comment by lweberk** [comment]
@Flamefire 
Agreed, its a off-putting hassle.
True, quite nice support for it already.

Will do. Challenge accepted ;)

**Comment by Flow86** [comment]
okay I found https://github.com/tpoechtrager/osxcross which seems to be a nice start to create new debian packages for a clang/llvm compiler, but that will definitly take some time to integrate

**Comment by lweberk** [comment]
Let me have a look at it over the weekend.

**Comment by uqs** [comment]
One more vote to embrace C++11/14: the code does not compile as is under FreeBSD with clang, as std:abs is used on an integral type, so there are three different versions of std:abs that the compiler could choose from and it bails out with a warning. C++11 has std:abs for integral types and thus no type conversion needed.

So far, I got it to compile and link s25client, but now it's not finding any video drivers (will send pull request for all the portability issues).

**Comment by MarcusSt** [comment]
@uqs Could you try performance (frames/second in game, same area, clang vs gcc)?

**Comment by lweberk** [comment]
Will do.

**Comment by uqs** [comment]
So the code compiles fine with clang 3.6 and gcc 4.8 (both in -std=c11/c++11 mode). Getting both to run on the same system is way trickier though, as I can't use clang's libcxx11 and boost compiled with clang and then link that with a gcc compiled s25client. It crashes during startup. I'm working on a pure gcc setup to test things side by side (most likely with statically linked binaries).

1. How do I benchmark this most easily? Can I let the AI play against each other or what?
2. is there cmake magic to give me statically linked binaries
3. why are the video/audio drivers not linked in at link-time, but dlopen'ed during startup?

**Comment by Flamefire** [comment]
1) Yes, but the AI has some randomness in it. You'd better of taking a replay: Start a game with many AI, let it run (use jump) for a lot of GFs and then you have a replay, which will be always the same.
2) Yes, e.g. boost on windows is statically linked. Compiling static libs with CMake is e.g. `ADD_LIBRARY(siedler2 STATIC ${SRC_FILES})`
3) You can remove/replace drivers without recompiling. So you have a couple of dlls, the game looks for the dlls at runtime and loads them if it was selected in the settings. Only one dll is loaded at a time. You don't need e.g. VideoSDL and VideoWinAPI at the same time...

**Comment by susnux** [comment]
https://github.com/tpoechtrager/osxcross is really a great project and VS2013 should be available for the most C++ Windows devs (at least all I know have 2013 or 2015). Just an opinion of a visitor.

**Comment by Flamefire** [comment]
I'm using VS2012 and VS2015 myself. We just (kinda) dropped support for VS2010 but I think we should not drop support for VS2012 yet. More compilers which we can use to test the code on.

The project might be something for @uqs or @lweberk to play with

**Comment by Flow86** [comment]
well I'm also still using vs2010 ;-)

**Comment by Flow86** [comment]
found https://github.com/multiarch/crossbuild, which is a docker container for cross building different architectures (also osx)

I'll test that since it wont pollute my host system with the cross-compile stuff

**Comment by Flamefire** [comment]
Would love to finally have C++11 which simplifies a lot of things.

**Comment by Flow86** [comment]
yea hope I'll get it running, but it seems I have to install all dependencies for osx and mingw manually (or build updated debian packages like the old ones)

**Comment by Flamefire** [comment]
Well, doing so would be a great opportunity to install/update the used libraries. Some of them are quite ancient by now and can cause security issues.
We could also use travis/appveyor as build systems in which case we would need to push the artifacts to the server for the updater. Not sure, if this is easily possible (but should as a CI) but it would ease maintenance (easily update and test dependencies so less outdated libs), reduce the burden of your server (OSX generic builds are harder on travis) and we already use travis for testing etc.

**Comment by Flow86** [comment]
Who would have thought it - I have to recreate ALL library packages with the new gcc/clang compilers :/

but I'll do that

**Comment by Flamefire** [comment]
While you are on it: Could you also install SDL2 so it is usable too? Would be great if it is possible to transition to this in the near future to support features that are not possible ATM (advanced scrolling) and get rid of some known bugs (window resizing/fullscreen, resolution changes etc)

**Comment by Flow86** [comment]
to your statement "We could also use travis/appveyor as build systems" - yes we can do that, but we would get a lot problems with different versions on different architectures, also updater artefact creation and osx (depends on system libraries here) will be a lot of problems

**Comment by Flamefire** [comment]
Done in #1000
