### ISSUE TITLE
s25update.exe no longer working 

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1441]
At least on windows 10 the s25update.exe is broken since at least the 05.09.

Message: Diese Anwendung konnte nicht gestartet werden, da die Side-by-Side-Konfiguration ungültig ist. Weitere Informationen finden Sie im Anwendungsereignisprotokoll. Weitere Details können auch mit dem Befehlszeilentool sxstrace.exe angezeigt werden.

Ereignisanzeige: Fehler beim Generieren des Aktivierungskontextes für "F:\s25rttr_20210905\RTTR\s25update.exe". Fehler in Manifest- oder Richtliniendatei "F:\s25rttr_20210905\RTTR\s25update.exe" in Zeile 1. Ungültige XML-Syntax.

XML:
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="SideBySide" /> 
  <EventID Qualifiers="49409">59</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-09-21T10:35:11.7282783Z" /> 
  <EventRecordID>58455</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Spike-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data>F:\s25rttr_20210905\RTTR\s25update.exe</Data> 
  <Data>F:\s25rttr_20210905\RTTR\s25update.exe</Data> 
  <Data>1</Data> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
  ```

**Comment by Flow86** [comment]
did something change since then? thats weird.
