### ISSUE TITLE
Split development into stable and a dev branches

### ISSUE THREAD

**Issue by lweberk** [Return-To-The-Roots/s25client#145]
Since clients need to stay in sync, the maintenance of multiple version branches is not really an option. This means that we need a continuous and tagged (as it already is) release branch, that should not take new stuff that has not been properly tested in a dev release first.

Propose to partly approach the git flow model. 
* Stable master branch  with release tags
* Development branch in which stuff converges from feature branches

*develop* should always compile and run after merge ins.

The main rationale for this, is that I see bigger efforts rough up to much of the code to oversee as bug-less for a release without stretching releases virtually indefinitely. It makes it harder to bring in smaller increments at the same time without them being affected by bigger change's pace.

Comments and Suggestions?

**Comment by Flow86** [comment]
we already have these:

release branches (like 0.7, 0.8) and the current development branch (master). 

Sure as soon as we have a stable version again, we could create a new release (i.e 0.9) and reintegrate new stuff there soon as its stable enough.

I'm not a friend of having a "master"-stable branch. Its normally not meant this way.

**Comment by Flamefire** [comment]
I also think this is ok. We have a tagged "stable" version. everything else are nightlys. And we NEED users to test those. There are just not enough devs to do it alone.
