### ISSUE TITLE
32bit binaries for linux

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1453]
hey everyone, 

I just wanted to ask wether its possible to have a stable 32bit binary for linux avilable? Got an old IBM Laptop here running an i686 kernel. 

thanks

**Comment by Flamefire** [comment]
I think we stopped providing 32 bit versions as most computers are 64 bit anyway. CC @Flow86 
You can always build yourself of course which is likely the easiest option.

**Comment by Flow86** [comment]
Hi, we removed support for x86 linux due to the increased effort to set up proper toolchains for this, but you can of course build it for your x86 linux machine yourself from source.
