### ISSUE TITLE
Settings not saved when closing windows by ESC

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1455]
When closing windows by using ESC rather than right click, the settings are not saved but reset to their previous state.

Simply open the Tool Settings, set one to 100% that was not 100%, hit escape (closing the window), open it again and you see the previous value. When using right click everything is working as expected.

**Comment by Flow86** [comment]
I think this is expected. I'm not sure if this was the same in the original? (Like "OK"=Right click, "Cancel"=Escape)

**Comment by Spikeone** [comment]
It's still strange as: keep the window open for 30 minutes, hit escape, settings reset.

Doesn't feel intuitive, but not sure if its correct (as in the original) or not

**Comment by Flamefire** [comment]
Tested in DosBox: Seems to be Right-Click and ESC are the same, so settings saved for both.
Still strange: Settings should in any case be applied directly, i.e. no matter if the window is closed at all the settings should be changed.

So yes, this is a valid bug
