### ISSUE TITLE
"Aktionsfenster" doesn't close

### ISSUE THREAD

**Issue by triccle** [Return-To-The-Roots/s25client#1459]
Version 20211112 - 40d94b4 -Windows 10 and MacOS
Clicking on build icon and build some building. The cursor moves back to the upper left of the "Aktionsfenster"-frame like here:
![grafik](https://user-images.githubusercontent.com/94314265/141693324-bccdda94-90c9-4aeb-8ea1-224251e5496a.png)
Building gets build but frame doesn't close afterwards. Frame is not closeable through any other option. Rightclicking doesn't close it, the upper left button of the frame doesn't close it.

**Comment by lhofmanngmx** [comment]
Hi,
just want to add, I saw this behaviour also on Linux Mint, and I can say, the stable release does not behave like this, only the nightly builds.
