### ISSUE TITLE
In game Activity Window Won't Close

### ISSUE THREAD

**Issue by Beagledo** [Return-To-The-Roots/s25client#1461]
Hi,
I'm currently having an issue with trying to close the in game Activity windows as pictured bellow. I have tried everything ESC, Clicking the left hand top corner, and Alt+w. Nothing is working. The other game windows close fine I downloaded the game from Gog

Many Thanks.

![problem](https://user-images.githubusercontent.com/94128341/142073115-775c4d9f-7d48-4413-b593-605b5f5a407e.png)

**Comment by Flamefire** [comment]
Already fixed by #1460
Try the latest nightly (or maybe wait for the next)
