### ISSUE TITLE
[LUA] AddEnvObject crashes RttR if object visible

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1464]
When adding objects via AddEnvObject, the game crashes as soon as you could see them.

Example attached, the crash occurs in line 72. 

[WORLDS.zip](https://github.com/Return-To-The-Roots/s25client/files/7614460/WORLDS.zip)

**Comment by Flamefire** [comment]
Issue found: The texture used here is a player image without player colors and EnvObject only supports regular images.
Enhancing this and will also change the code so that the object fails to add if an invalid image is passed.
