### ISSUE TITLE
Crash (related to attack / nofPassiveSoldier)

### ISSUE THREAD

**Issue by MarcusSt** [Return-To-The-Roots/s25client#147]
Commit: f1929d0c6515f5ac721ee208e8d0da7096ec63cb (latest at the time of writing this)
Replay: https://dl.dropboxusercontent.com/u/11244516/RTTR/2015-08-03_07-53-43.rpl
Crashes reliably at GF 51894.

Building from which the attack starts is at x = 62, y = 111.

**Comment by Flamefire** [comment]
There is also a crash in the terrainrenderer when scrolling to point 0,0 (or very close) in one of your savegames (can you attach that for reference)
Nothing to do but scroll to 0,0 (even in pause modus)
I assume wrong offsets/counts in the texture

**Comment by MarcusSt** [comment]
This bug has nothing to do with the TerrainRenderer. It's some soldier/attack problem. Therefore it wouldn't make sense to talk about a second crash here.

**Comment by Flamefire** [comment]
--> https://github.com/Return-To-The-Roots/s25client/issues/148

**Comment by jhkl** [comment]
In GF 50014 an attack on a building at 39/114 is triggered. At least two soldiers from the fortress at 62/111 are being used. When removing the second soldier (Gefreiter) from the building something goes wrong when removing it from the SortedTroopsContainer nobMilitary::troops:
![unbenannt](https://cloud.githubusercontent.com/assets/2512962/9035609/e839ea62-39d9-11e5-8bd7-12d29ad3bdef.png)

I will continue my analysis, I'm just reporting this here now because maybe Flamefire knows something more as he just introduced the SortedTroopsContainer. :)

**Comment by MarcusSt** [comment]
Yes, I implemented a "workaround" which allows the game to continue:
- create new nobMilitary::SortedTroopsContainer
- copy everything from building->troops but the item to remove
- replace building->troops

I did it just to check this causes the problem, but something with the underlying data structure needs to be "wrong", as erase should remove an item that is on the list.

**Comment by Flamefire** [comment]
@jhkl The soldiers are removed based on their actual properties. If the soldier is deleted before then the properties are BS. So it won't find it. Can you check, that the not-deleted soldier has still valid values (e.g. vfptr in GameObject != 0)
What I assume: before the set was indexed by the pointer -> pass the same pointer to erase and it will be erased. Now the set is indexed by rank  and id. So the pointer must be dereferenced for the soldier to be removed. If it was deleted, on cannot dereference the object.

**Comment by MarcusSt** [comment]
@jhkl found out that it is most likely due to upgrades taking place in the building. This kills the order within the std::set. As there's a tree backing structure, erase will not find the item for removal.

Solution should be to remove soldiers on upgrade and insert them directly after that.

**Comment by Flamefire** [comment]
You are right... Soldiers are ordered by Rank AND Id --> Lower rank with higher id gets promoted --> wrong order. Btw: Do we actually need soldiers in the buildings? Why not just store something like "0 generals, 2 gefreiter" and create the soldiers once they leave the building? Or do they store any required data besides their rank?

**Comment by jhkl** [comment]
Hitpoints. Btw, it might be also a good idea to sort after hitpoints ;)
Rank -> hitpoints -> object ID

**Comment by Flamefire** [comment]
Easy: Just change the compare operator in the soldier class ;)
And yes after any change the soldier should be reinserted.
