### ISSUE TITLE
Can't close addon window with rightclick

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1471]
I was supprised when it was not possible to close the "addons" setting window with a right click but having to click abort

**Comment by Flamefire** [comment]
This is intentional and I'd keep it. You either want to keep the settings or not and that should be explicit. I know in S2 the settings are always applied but this window is an RTTR addition so we can choose to let user choose.

**Comment by Spikeone** [comment]
Oh, thats somewhat interesting, for me settlers 2 windows are always: 
- Right click = keep settings as visible (means this is an apply click)

So I'd personally expect that behavior from the addons window. If I change something and don't want to save it, I have to hit abort. I get what you mean but I think the behavior of settlers 2 windows is quite consistent by always saving what you see when right clicking. But thats just my opinion on that, don't know if we find someone else who has thoughts on that - and if it's worth the change

**Comment by Flamefire** [comment]
Well for S2 windows we still have that. That window is an RTTR extension and someone decided that you have to click one of the buttons  to close it.
So do we want to keep that? Which windows should NOT be closed by right-click? Are there any at all except the "Please wait..." window?

**Comment by Spikeone** [comment]
As said, your explanation sounds resonable so it's okay to keep it as is I think. I haven't thought about having this more explicit as messing up your settings could be quite frustrating.
Also this window isn't often used, most people preset their addon settings and merely change them.

Another, kinda, exception is the observation window which allows you to pan by right clicking into the view instead of closing it. Also those MessageBox windows should be closed by clicking ok, rather than a right click, to possibly force the user to read it instead of simply dismissing it.

So I'd expect the window to close by right clicking but I agree, that having to click abort or apply possibly is better in this case.  So, its okay to mark this one as invalid.

**Comment by Flamefire** [comment]
Yeah I think we just have to be consistent. E.g. IngameWindows (those IN the game) should be closed with right-click, except for message boxes and similar and our setting windows should just have the Apply/Discard buttons.
