### ISSUE TITLE
Only harbor building on harbor spots possible

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1473]
As the title says, it's currently not possible to place anything but a harbor building on a harbor spot which is incorrect.

**Comment by Flamefire** [comment]
Can't see anything wrong in the code. Maybe a lua script involved? Do you have a savegame?

**Comment by Spikeone** [comment]
You can use the Sea map "Dat Async" which has a harbor spot right in the beginning. When clicking on the harbor building spot, the build menu opens up as expected. One has any building for selection but selecting anything but the harbor building results in simply nothing happening. If you place a flag next to the spot (thus making it medium) you can select other buildings.

**Comment by Flamefire** [comment]
Ok. Not sure how it was on original S2, but we treat harbor spots as Castle+Harbor spots?

**Comment by Spikeone** [comment]
Yeah, the only difference is, that you get the additional option, don't know any other change (and that should be as it was in the original, at least I think that it is :D)
