### ISSUE TITLE
Jumping in paused replay buggy

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1474]
When jumping in a paused replay nothing happens but GFs are counted down. When playing any replay, it starts paused. If you open up the jump screen and enter a GF, the game seems to do nothing at all but count down the GF unto 5k left and then nothing happens.

**Comment by Flamefire** [comment]
Maybe you are looking at a point where nothing happens? Just tested and works fine. 1 Update every 5k GF with the countdown and then the jump stops at the requested GF. Replay is still paused as required.

**Comment by Spikeone** [comment]
Ah damn me - the pause isn't the problem, the problem is the mission statement. As I display the statement at GF 60, the game gets paused in the back. Duplicate of #944
