### ISSUE TITLE
Crash in terrainrenderer

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#148]
There is a crash in the terrainrenderer when scrolling to point 0,0 (or very close) in one of Maqs savegames (can you attach that for reference?)
Nothing to do but scroll to 0,0 (even in pause modus)
I assume wrong offsets/counts in the texture

**Comment by MarcusSt** [comment]
I cannot reproduce this, at least not with the save game I sent you (https://dl.dropboxusercontent.com/u/11244516/RTTR/maqs.sav).

**Comment by Flamefire** [comment]
Really? Maybe windows only? jh or Spike got the same.
Testing out of VS

**Comment by jhkl** [comment]
Yes, I had the same or a similar crash yesterday. Stack seemed to be corrupt, no information visible except that it was somewhere in a std::list of BorderTiles.

**Comment by Flamefire** [comment]
This matches my observations. More specifically it is the glDrawArrays call with a high offset and count.

**Comment by Flow86** [comment]
is it perhaps the same problem like the bug with "VBO" and pressing "B"?

**Comment by Flamefire** [comment]
Can you explain that one?

**Comment by jhkl** [comment]
https://github.com/Return-To-The-Roots/s25client/issues/7
It is possible. I think VBO was disabled when I experienced the crash yesterday.

**Comment by Flamefire** [comment]
https://github.com/Return-To-The-Roots/s25client/pull/151
