### ISSUE TITLE
Tracks seem to always play twice

### ISSUE THREAD

**Issue by Vinkdicator** [Return-To-The-Roots/s25client#1480]
I don't quite understand how the music player is supposed to work but there is a more/less repeats button. If I set it to 1, each track plays twice, but if I set it to 0, nothing plays at all! Surely this is not how it's supposed to work?

**Comment by Flamefire** [comment]
I can't really confirm the "1"= "play twice" from the code, and also the tests say it works fine.

Anyway: Currently thinking about how it should work. The number is currently how often a song is played, so "0" indeed means "nothing" which doesn't make sense. So options:
1. Disallow "0"
2. Make it mean "repeats", i.e. "0"="play once, no repeats"
3. Keep as current and make "0" mean "repeat endlessly", i.e. at the end of the playlist restart it.

I'm for 3., what do you say?

**Comment by Vinkdicator** [comment]
Thanks, I think 2 is the most intuitive.

**Comment by Spikeone** [comment]
@Vinkdicator - just asking, any reason for having a configurable repeat count? Because I don't see any, so always playing endless could be another option 4

**Comment by Vinkdicator** [comment]
I actually thought the number of repeats was for the tracks, not the playlist, although playlist would make more sense and either way it seems unnecessary to me, yes.

**Comment by Flamefire** [comment]
True: So additional options:
4. remove repeats and simply repeat the whole playlist when done, i.e. option 3 with forced setting 0
5. option 2, AND repeat the playlist when done

Explanation for option 5: When shuffling the repeats matter. I.e. the song is put into a list 1 or more times, then the list is shuffled. So it can happen that a song plays multiple times before the next song is played. Overall this may give the impression of a much longer playlist. Example with 1 repeat and 3 songs:
1,1,2,3,3,2 -END-RESTART- 3,2,2,1,3,1-END-RESTART....

**Comment by Flamefire** [comment]
Addressed in https://github.com/Return-To-The-Roots/s25client/pull/1487 by implementing Option 5: Repeats of "0" plays the song once and at the end of a playlist the playlist is repeated (and reshuffled if activated)
