### ISSUE TITLE
saved Multiplayer Game fails to load

### ISSUE THREAD

**Issue by cgroetsch** [Return-To-The-Roots/s25client#1482]
Error when loading game: 65280 is out of range. Maximum allowed value: 65
server state changed to stop
client state changed to stop

v0.9.1

[Der große See (Automatisches Speichern).sav.zip](https://github.com/Return-To-The-Roots/s25client/files/7799560/Der.grosse.See.Automatisches.Speichern.sav.zip)
)

**Comment by Flamefire** [comment]
I assume the same issue as #1457. So the savegame is corrupted and cannot be recovered. What you can try is load the replay, jump to almost the end (NOT the end or the same will happen) and save.

@Flow86 We need a new stable release!
