### ISSUE TITLE
Crash: invalid soldier?

### ISSUE THREAD

**Issue by fritzmg** [Return-To-The-Roots/s25client#149]
**Commit:** f1929d0c6515f5ac721ee208e8d0da7096ec63cb

**Repro:** Load the following save game: https://www.dropbox.com/s/902fr8jopz981jj/Die%20gr%C3%BCne%20Insel%20%28Automatisches%20Speichern%29.sav?dl=0 
Go to Grid 52:34, click on the fortress - you will see that the last soldier seems to be invalid and linked to random data. In the following screenshots, the soldier was an iron ore ;)

![s25rttrss1](https://cloud.githubusercontent.com/assets/4970961/9036551/dec4255c-39e2-11e5-838a-af600d9012ad.png)
![s25rttrss2](https://cloud.githubusercontent.com/assets/4970961/9036552/def00e38-39e2-11e5-94e5-3772cedd055c.png)

If you try to destroy the fortress, the game will crash. Also, if you let the soldiers move out of the castle in any way, the soldiers will behave weirdly and if you click on the fortress, the game will crash also.

**Comment by jhkl** [comment]
Might be related to issue https://github.com/Return-To-The-Roots/s25client/issues/147 
This could happen when multiple soldiers of same rank are present while gold coin is used.

Do you have replay? If yes, try replaying it with the newest version (or wait for the nightly build this evening).
The savegame probably cannot be fixed.

**Comment by fritzmg** [comment]
Yes, the new version seems to have fixed :)

**Comment by MarcusSt** [comment]
Perfect :-)
