### ISSUE TITLE
Join game problems with version 20220203 and  stable 9.4

### ISSUE THREAD

**Issue by ulabein** [Return-To-The-Roots/s25client#1492]
Today 4 people try to play game over lobby.
By version 20220203 when someone join a game rttr crashed.
`
RttR crashed. Backtrace:
0x55c2aee3e46d
0x55c2aee32092
0x55c2aee32449
0x7f8e7f564210
0x55c2af192d85
0x55c2af032960
0x55c2aeef7581
0x55c2aeef7126
0x55c2aee914c4
0x55c2aee91ec5
0x55c2af02dadf
0x55c2af023bad
0x55c2aee63d20
0x7f8e7faa0e51
0x55c2aeeba505
0x55c2aee3fc59
0x55c2aee286a2
0x7f8e7f5450b3
0x55c2aee31b1a
RttR ist abgestürzt. Bitte starten sie die Anwendung neu!
terminate called after throwing an instance of 'RttrExitException'
  what():  std::exception
/home/ulabein/s25rttr_20220203/bin/../bin/rttr.sh: Zeile 62:  3820 Abgebrochen             (Speicherabzug geschrieben) $cmd $DIR/../bin/s25client $*
`
Than we try stable 9.4. But there was always the message that the version not correct.
Workaround was to play on version 20220125, still we have fun.
Thanks for support this project

**Comment by Flamefire** [comment]
If all players use 9.4 it should work. If it does not check the logs please (of the host and the player unable to join), it works for me.

However I can reproduce the crash in the latest nightly. Will double check

**Comment by ulabein** [comment]
i think it was in this log marvin was starting the game with 9.4 and AHA and i try to conneted.
'
(21:21:21) <SYSTEM>: MarvinH91 created server MarvinH91s Spiel
<<< NMS_LOBBY_PLAYERLIST(3)
    0: 6.581 peylego v20220203 - 83c6f81
    1: 9.043 AHA v0.9.4 - 4bc7063
    2: 8.932 ulabein v0.9.4 - 4bc7063
<<< NMS_LOBBY_SERVERLIST(4)
    0: 448.329 Bachirou89s Spiel 93.239.48.75:3.665 v20220203 - 83c6f81 33 Through the Desert 7 7
    1: 448.339 DMM's Game 178.40.12.133:3.665 v20220203 - 83c6f81 62 Hochebene 1 6
    2: 448.340 MarvinH91s Spiel 217.252.62.91:3.665 v0.9.4 - 4bc7063 0 Der Eichenwald 0 4
'
[2022-02-03_21-14-39.log](https://github.com/Return-To-The-Roots/s25client/files/8004670/2022-02-03_21-14-39.log)

It is only the client log. Serverlog i will try to inform marvin . (I see don't know them.)

But still if you can find and fix problem in nightly it is fine!

**Comment by Flamefire** [comment]
This looks fine: `v0.9.4 - 4bc7063` is shown for all of you.

When exactly did it show the message about the wrong version? If you see me in Discord (now?) ping me, as I'd like to test this
