### ISSUE TITLE
Next same works wrongly

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1498]
It looks like the "Jump to next same" button for storehouses and military buildings jumps to the "next same type" rather than exact building. Thats not what this is used to be, is it? When trying to cycle through all my barracks I don't want to find a watchtower.

**Comment by Spikeone** [comment]
Oh well, looks like I've never used before then - was a bit confused. Maybe someone else has an opinion on that who maybe uses this more frequently. When using this with a harbor it was tedious as the buttons in the HQ are ordere differently and there is no expedition page so it switched pages. Maybe it's more about the harbor building in my case, thats where I first noticed it and then when the "next same" cycled to a building I had a window open for (which is not good to use as you have to move the mouse around, but I don't see any fix for that).

So yeah, long story short: I think it's not that good for harbor buildings, I can understand it kinda for military buildings

**Comment by Flamefire** [comment]
Then maybe we should make sure that button is always at the same position for "same" types? Could you check where this is not the case and provide screenshots of those windows and maybe a possible solution (modify the picture via paint or similar) if the button cannot be trivially placed at the same position e.g. due to other buttons being already there.

**Comment by Spikeone** [comment]
Okay, tested it out and looks like my mind tricked me. The buttons are actually at the same spot, even for storehouse alikes.

But while playing around a bit with the feature, I found out why it was annyoing for me: It also finds buildings which already have windows opened. This means your window gets closed (and moved therefore as well). Then you have to find the building again and open the correct page if it was a storehouse alike.

Therefore I think buildings with already opened windows should be skipped. It felt like buttons were jumping because I went through my harbors, one had an open window which was then removed. Same reason when using the feature on the barracks: I was confused because my watchtower windows has been closed, or rather moved and no new window opened.

So my proposition: next same should skip buildings which windows are open already (player usually knows where those are anyway)

**Comment by Flamefire** [comment]
Sorry but I think this would be very confusing/hard to explain: It jumps to the next building of the same type UNLESS you happen to have a window of that open already in which case that is skipped.   
This is IMO not intuitive and might make players miss buildings they are sure are there.

**Comment by Spikeone** [comment]
But with the current implementation it messes up the interface one builds while playing - which isn't as expected. So if one needs to implement it correctly, there need to be two windows opened for the same building then.

**Comment by Spikeone** [comment]
Closing since nobody else would like a change in that behavior and it's currently working as expected.
