### ISSUE TITLE
Missing carrier-frame

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#15]
When playing RttR, after one game a carrier frame is not rendered anymore. This causes blinking which looks really ugly and forces me to restart the game after each match.

Problem can be reproduced

**Comment by jhkl** [comment]
Can you please give instructions how to reproduce?

I simply started a game, waited some seconds, and started another game. Nothing obvious was failing: http://youtu.be/LxgklnlkTUk

**Comment by Spikeone** [comment]
Start a game (In my case I started a replay) end game (not client).
Start an other game (In my case replay, but also works with normal game) - Frame is missing.
You can clearly see those "blinking" carrier etc. when they walk east.

 http://youtu.be/rE2_EVGPaY8

**Comment by Flamefire** [comment]
I tested this and it is reproducible with 100%. The problem seems to only affect the direction to the right (dir == 3) and the animationFrame 0 (out of 8, so only the first one is missing)
Gonna dig deeper later
