### ISSUE TITLE
Social media

### ISSUE THREAD

**Issue by MarcusSt** [Return-To-The-Roots/s25client#150]
RttR facebook/twitter accounts should be maintained.

Twitter (https://twitter.com/s25RttR) has 67 followers, the facebook page (https://www.facebook.com/s25rttr) has 569 likes, but nothing new since 2012 and 2014 respectively.

I think it would be great to give RttR fans out there a sign of life.

**Comment by Spikeone** [comment]
http://www.moddb.com/mods/return-to-the-roots

This page is still maintained, nearly all news are posted, maps uploaded etc.

**Comment by Spikeone** [comment]
Done
