### ISSUE TITLE
Panning with mouse erratic

### ISSUE THREAD

**Issue by Homo-carbonis** [Return-To-The-Roots/s25client#1500]
I've just started playing the game after building from git and I'm getting an enormous input lag when panning with the mouse. The camera just whizzes around the map uncontrollably. Both the mouse cursor and moving the camera with the arrow keys work normally.

**Comment by phoenix147** [comment]
Same here, panning with mouse is almost unusable, although mine is stuck mostly and just moves very little
I'm using latest Manjaro Linux

Same problem was described here (in german): https://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1704&start=-1#last

Disabling smart cursor is a workaround

Is there anything we can do to track this down?

**Comment by Spikeone** [comment]
Hm, I have no idea, but hope @Flamefire has - Could this be related to high DPI mouses when using linux?

**Comment by chewi** [comment]
Same here with 0.9.5 on Gentoo. 0.9.1 worked fine last I checked. I don't have a high DPI screen or mouse.

**Comment by chewi** [comment]
Actually I've retested 0.9.1 again and it happens there too. Perhaps it's a change in SDL or Xorg. Disabling the Smart Cursor option does indeed help although the panning is much faster than I remember.

**Comment by Spikeone** [comment]
```
vsync=0
```
seems to work fine
```
vsync=1
```
seems to cause 1 FPS

**Comment by Spikeone** [comment]
this should be fixed and the vsync issue is not related to this one
