### ISSUE TITLE
Opened gate not animated

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1509]
A gate added by ```rttr:GetWorld():AddStaticObject(70, 72, 561, 0xFFFF, 2)``` is not animated anymore. Guess that happened when fixing the crash related to non player colors or something alike.

**Comment by ottml** [comment]
#1464 introduced this bug. The noStaticObject caches the texture at first draw call. This is correct for all objects not using an animation. But the open gate is animated and must update the texture dependent on the animation frame.
