### ISSUE TITLE
Gate object gets wrong size

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1516]
If you place a gate on the map it should be a large building. Currently it's not (closed gate).

Also spawning an object by using ```rttr:GetWorld():AddStaticObject(72, 28, 561, 0xFFFF, 2)``` doesn't result in a large building:
![grafik](https://user-images.githubusercontent.com/1276342/160649336-9b3fae32-a96b-4572-912d-e86fa64b78cb.png)

**Comment by wichern** [comment]
I cannot reproduce this issue.
![image](https://github.com/Return-To-The-Roots/s25client/assets/47030768/fd2236a6-5409-4813-83a4-dfe0c790e3e7)
Do you have a savegame?

**Comment by Spikeone** [comment]
fixed by #1647 - thanks to @wichern
