### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by Mailaender** [Return-To-The-Roots/s25client#1524]
This is a notification that I submitted a package to Flathub which is an alternative to #1078.

**Comment by zocker-160** [comment]
I just found this and your submission request for Flathub.

Couldn't you just add a simple start script, which checks if the games files are available and if not show a popup message, informing the user that the files are missing?

**Comment by zocker-160** [comment]
@Mailaender I created a small script template, which should do everything you need

```bash
#! /usr/bin/env bash

TARGET_DIRECTORY=`pwd`
FILE="${TARGET_DIRECTORY}/lool"

if [ ! -s $FILE ]; then
    echo "$FILE does not exist"
    
    zenity --title="s25client data check" --width=300 --question --no-wrap --text="Missing required game files!" --cancel-label="Exit" --ok-label="Open folder"
    
    if [ $? == 0 ]; then
        xdg-open $TARGET_DIRECTORY
    else
        echo "exiting"
    fi
    
else
    # start s25client normally
    echo "starting s25client...."
fi
```

you could just put that as the start script into the flatpak, zenity is part of the runtime iirc

**Comment by Mailaender** [comment]
I know how Zenity works. Checking for a single file is not sufficient here.

**Comment by Flow86** [comment]
you can look at the MacOS Launcher application we have exactly for this on MacOS: https://github.com/Return-To-The-Roots/s25client/blob/master/extras/macosLauncher/starter.cpp

**Comment by Mailaender** [comment]
https://flathub.org/apps/details/info.rttr.Return-To-The-Roots was already created months ago.
