### ISSUE TITLE
Cant Scroll with right Mouse

### ISSUE THREAD

**Issue by Blackpearl1** [Return-To-The-Roots/s25client#1526]
Hi,

I installed a fresh Garuda DE with KDE on my System.
Now I installed rttr, but, I cant scroll in the Game the Map with the right Mouse, it just scroll for for a part of a second and then it stops scrolling. If I click again it also scrolls for a small part of a second, again, and stops.

It makes no diferend if I play in windowed or fullscreen mode.
In Windows 10 I dont get sutch problems in rtttr.

Other games work like a charm(some Steam games like HL2, UT3, Skyrim, C&C Remaster, ect...) or Games like Widelands(also use the right Mouse for scrolling).

**Comment by stefson** [comment]
Good catch, I can confirm it - this must have been recently regressed.

**Comment by stefson** [comment]
@Flamefire are you able to confirm this on linux? 

I'm having trouble finding the commit that regressed this, downgrading up to 0.9.1 shows the same very choppy rendering if right mouse click is hold.

**Comment by Flamefire** [comment]
Possibly same issue as #1500
Not sure how to resolve this...

**Comment by Blackpearl1** [comment]
Dont sounds similar.
I have no problems with pointing. Only scrolling the map with rhight mouse button.

**Comment by stefson** [comment]
disabling smart cursour does help as a workaround, but I've got the impression that the acceleration of the scrolling is now a bit over the top (:

**Comment by qrzn** [comment]
I have the same issue on Manjaro, but on Bodhi Linux scrolling still works fine. The latter uses an older version of sdl

**Comment by sundance69** [comment]
unbuntu 21 and 22 are using the same sdl version, but only ubuntu 22 does not allow a smooth scrolling.
anybody working on a solution or has a better workaround ? right now rttr is not playable under ubuntu

**Comment by Flamefire** [comment]
I have a solution in mind but not actively working on it as it requires quite a bit of changes

**Comment by bmarwell** [comment]
Any news on this?

**Comment by dewaltz** [comment]
Bump ubuntu 22 not working : upgraded OS :( either this or buy "New allies" looks crap. ow canthey invest millions and screw up. you guys are keeping it alive thank you

**Comment by Flamefire** [comment]
Sorry nothing new here, to much else going on right now. I hope I'll find the time for this in the next 2-3 months.

**Comment by siredmar** [comment]
I can second that problem using Ubuntu 22.04.

**Comment by siredmar** [comment]
@Flamefire can you explain what your idea is you have in mind? Maybe someone else can try to work on this.

**Comment by siredmar** [comment]
Just for the record: i recompiled `s25client` on ubuntu 22.04 and everything works.

**Comment by Flamefire** [comment]
> @Flamefire can you explain what your idea is you have in mind? Maybe someone else can try to work on this.

The idea was to implement support for the relative mouse mode of SDL. Currently we do that manually: Scroll the map according to the distance the mouse was moved, then warp the mouse back to where it was.   
Maybe that was messing stuff up and using SDL to keep the mouse at a single position and only react to the relative movements (when map movement is activated) avoids those issues.

But an emulation of that would need to be implemented for WinAPI and it has to be used by the code making sure the relative mode is correctly activated **and** deactivated in all circumstances.

**Comment by Spikeone** [comment]
@Flamefire we have now at least 2 reports, that the latest nightly causes 1FPS issues - this PR might have broken something

**Comment by siredmar** [comment]
@Flamefire @Spikeone I can imagine that the FPS issues are sources by the fact, that now every
mouse move event will be handled instead of only the first one.
For me it could be a valid option to make this feature/Bugfix optional configurable (maybe even only with the config file) for the video driver. this way we woul keep the original behavior but allow testing with this bugfix.
what do you guys think about this?

**Comment by Spikeone** [comment]
Well it's strange, that disabling dynamic framerate seems to fix this for some people - although I have no problem with that option enabled.
