### ISSUE TITLE
Build dependencies for Arch Linux

### ISSUE THREAD

**Issue by ennokde** [Return-To-The-Roots/s25client#1528]
Hey, I'd like to work on this project. But I am having a bit of trouble configuring and building the project with CMake under Arch Linux. It looks like some modules are missing so I need a little help to find the corresponding Arch packages.

Can somebody that is able to build this under some other distribution please find out what provides the following CMake modules so I have an idea what to look for?
* CheckAndAddFlag
* EnableCCache
* EnsureOutOfSourceBuild

In case it helps this is the error message I get when running `cmake /path/to/sources`:
```
-- Using CMake 3.23.1
CMake Error at CMakeLists.txt:30 (include):
  include could not find requested file:

    EnableCCache


CMake Error at CMakeLists.txt:78 (include):
  include could not find requested file:

    EnsureOutOfSourceBuild


-- Configuring for native compiling to Linux-5.17.9-arch1-1 on x86_64
CMake Error at cmake/optimizations.cmake:14 (include):
  include could not find requested file:

    CheckAndAddFlag
Call Stack (most recent call first):
  CMakeLists.txt:112 (include)


CMake Error at cmake/optimizations.cmake:41 (CheckAndAddFlag):
  Unknown CMake command "CheckAndAddFlag".
Call Stack (most recent call first):
  CMakeLists.txt:112 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by Flow86** [comment]
Hi, you probably forgot to fetch the git submodules. (i.e you need to use `--recursive` on `git clone` or a `git submodule update --init --recursive` afterwards)

**Comment by Flamefire** [comment]
Exactly: A `git submodule update --init` is missing. The files you are missing are here: https://github.com/Return-To-The-Roots/libutil/tree/16c51cf15e046309e537920f5f2866f7355a2c5b/cmake

Side note: The `--recursive` is only required on the `git clone` and not needed for `git submodule` although doesn't hurt AFAIK.

**Comment by ennokde** [comment]
Thanks for the quick help. That fixed it.

Next up: CMake refusing to find Lua, which is partially fixed by `-DLUA_INCLUDE_DIR=/usr/include/lua5.2`. Configuration finished but the build failed with a wall of text from the linker complaining about undefined references.

I assume that it is trying to link against the 5.4 version and thus that I need to manually override some other variables. I'll figure this one out tonight (I hope).

**Comment by Flamefire** [comment]
You can check the cmake cache and/or output on what it found, e.g. in `CMakeCache.txt` there should be some variables starting with `LUA_`. Overriding stuff shouldn't be required, we have a quite smart find module at https://github.com/Return-To-The-Roots/libutil/blob/master/cmake/FindLua.cmake

You can configure with `-DLUA_Debug=ON` to get some more output on what it tries to find and maybe even `-DCMAKE_FIND_DEBUG_MODE=ON` or `--debug-find` in CMake 3.17+

Please attach the output of the (initial) configure (i.e. start over with an empty build dir) if that still doesn't work.

**Comment by ennokde** [comment]
Good news bad news situation :-)

Everything works now but I don't know why. I cannot reproduce the Lua problem after nuking the build dir and starting over so case closed.
