### ISSUE TITLE
[Build server] Merges should trigger builds as well

### ISSUE THREAD

**Issue by MarcusSt** [Return-To-The-Roots/s25client#154]
Merging something should trigger a build as well. At the moment, only commits seem to trigger those.

**Comment by Flow86** [comment]
Can't see the problem, and cant fix it:

Build #73: Started by GitHub push by MarcusSt

**Comment by MarcusSt** [comment]
Strange. I remember no build being triggered for one of the last merges.

**Comment by Flow86** [comment]
yes sometimes it seems not to trigger, but thats the jenkins plugin and or the github web hooks which seem not to trigger always
