### ISSUE TITLE
game cannot detect files

### ISSUE THREAD

**Issue by 1Feanor** [Return-To-The-Roots/s25client#1541]
Game cannot start.
I have tried and capitalizing all the words. out of ideas and forums to find solution! 

Return To The Roots v20220922-0537322eb59cd418697ceeb35f21564150f0bdf4
Compiled with GNU C++ version 8.3.0 for linux 64 Bit

Starting in "/home/ao/s25rttr_20220922"
Searching for drivers in "/home/ao/s25rttr_20220922/lib/s25rttr/driver/video"
1 video drivers found!
Loaded video driver "(SDL2) OpenGL via SDL2-Library"
OpenGL 4.5 supported
Searching for drivers in "/home/ao/s25rttr_20220922/lib/s25rttr/driver/audio"
1 audio drivers found!
Loaded audio driver "(SDL2) Audio via SDL2_mixer-Library"

Starting the game
Loading "/home/ao/s25rttr_20220922/share/s25rttr/RTTR/assets/base/splash.bmp": done in 3ms
Exception caught: File or directory does not exist: "/home/ao/s25rttr_20220922/share/s25rttr/S2/GFX/PALETTE/PAL5.BBM"

Failed to load "/home/ao/s25rttr_20220922/share/s25rttr/S2/GFX/PALETTE/PAL5.BBM"

ERROR: Some files failed to load.
Please ensure that the Settlers 2 Gold-Edition is installed 
in the same directory as Return to the Roots.
Clearing textures: Finished in 0ms

**Comment by Spikeone** [comment]
@1Feanor can you please provide a full dir (or ls on linux?) of your share folder?

**Comment by 1Feanor** [comment]
I know I have doubled folders, but I was trying to make it work.
sorry for the mess 
this is the flatpak loading folder

-rw-------  1 ao   ao    708 Dec 15 11:26  CONFIG.INI
-rw-r--r--  1 root root  532 Dec 14 21:16  convcase.sh
-rw-------  1 ao   ao   1255 Dec 15 11:26  IngameOptions.ini
drwxr-x---  2 ao   ao   4096 Dec 15 11:26  LOGS
drwxr-x---  3 ao   ao   4096 Nov 15 14:31  LSTS
drwxr-x---  2 ao   ao   4096 Nov 15 14:31  MAPS
drwxrwxr-x  2 ao   ao   4096 Nov 15 16:16  playlists
drwxr-x---  2 ao   ao   4096 Nov 15 14:31  REPLAYS
drwxrwxr-x 14 ao   ao   4096 Dec 15 20:18  s2
drwxr-xr-x 13 ao   ao   4096 Dec 15 20:18  S2
drwxr-x---  2 ao   ao   4096 Nov 15 14:31  SAVE
drwxrwxr-x  2 ao   ao   4096 Nov 15 16:16  screenshots
drwxrwxr-x 10 ao   ao   4096 Dec 13 21:45 'Settlers 2 GOLD'
drwxrwxr-x  2 ao   ao   4096 Nov 15 16:16  WORLDS

**Comment by Spikeone** [comment]
not sure how it works on linux - on windows this is the saved games folder and not where the game files are (e.g. where the s25client is located and the RTTR folder(s)).

If this is the correct folder on linux, you have to copy the DATA and GFX folders there, not an s2 folder

**Comment by 1Feanor** [comment]
I have reading a lot about the this because it looks to be a problem that keeps appearing in several folders that some people claim that is fixed with an update from time to time. so not sure what is causing the problem  
 
also from the path of the error 
Failed to load "/home/ao/.s25rttr/S2/GFX/PALETTE/PAL5.BBM"
I can use explorer or terminal to access the file no problem the game loader cannot

**Comment by 1Feanor** [comment]
Managed to get to load the game finally.

flatpak installation from POP os app store does not work under any circumstance.

A fresh installation managed to resolve the issue but requires that the S2 folder is put in 2 places.

one in the root folder of the game and another inside 
./share/S25rttr

**Comment by Spikeone** [comment]
@Flow86 @Flamefire any Ideas? I got none :s

**Comment by Flamefire** [comment]
> Failed to load "/home/ao/.s25rttr/S2/GFX/PALETTE/PAL5.BBM"
> I can use explorer or terminal to access the file no problem the game loader cannot

Then it looks like a permission issue.

> A fresh installation managed to resolve the issue but requires that the S2 folder is put in 2 places.

This hints that whoever build your RttR made a mistake. I can't see how this can happen with the "normal" builds.

Also there seems to be 2 errors as you wrote:

> Failed to load "/home/ao/s25rttr_20220922/share/s25rttr/S2/GFX/PALETTE/PAL5.BBM"

and 

>  Failed to load "/home/ao/.s25rttr/S2/GFX/PALETTE/PAL5.BBM"

Maybe you are mixing up different installations.

**Comment by 1Feanor** [comment]
you are correct I had a mix up. I was trying several installations in tandem
I will try the flatpak again and change the permission settings and run it again just to confirm.
At first I tough flatpak was not installing the correct loading libraries so I have been trying several solutions

**Comment by Spikeone** [comment]
@1Feanor so, this issue can be closed, can it?

**Comment by Spikeone** [comment]
Closing since there has been no response since over a year.
