### ISSUE TITLE
Babylonians override charburner graphics

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1545]
there is a
```"\RTTR\assets\nations\Babylonians\charburner.LST"```
which contains old charburner graphics and overrides the correct files if babylonians are used. The file should be removed since the babylonian charburner is in the base folder as well

**Comment by Flamefire** [comment]
I just extracted this and the base lst and they both seem to be the same (the images look the same to me even though the archives are different). What do you mean by "old" and "correct"?

As for fixing this: The base one should contain the base images and  "\RTTR\assets\nations\Babylonians\charburner.LST" should only contain the babylonian images. But of course we first need to know which files to keep and then split them into 2 archives.

**Comment by Spikeone** [comment]
![grafik](https://user-images.githubusercontent.com/1276342/218833200-5f051846-20df-493c-8f0f-ebb4845bcaaf.png)
well, they are different (see the wheelbarrow). The files on the left (assets\base\charburner.lst) are correct

I just had the feeling, that using babylonians on wintermaps also causes the mine working animation bug. will check this later
