### ISSUE TITLE
[Addon] Strawberryfarm

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#155]
(Original by Demophobie: https://bugs.launchpad.net/s25rttr/+bug/372783)
There should be a strawberry farm, those strawberrys may be used to improve soldier strength (Like in Settlers III gold) or enhance mining speed.

Version 1:
![demo](https://cloud.githubusercontent.com/assets/1276342/9069863/389d2f7e-3aec-11e5-8630-2d5fb2eb191b.png)

Version 2:
![erdbeerfarmv2](https://cloud.githubusercontent.com/assets/1276342/9069869/3e9c66ec-3aec-11e5-8a13-6a5776a44f25.png)

Version 3:
![erdbeerfarmv3](https://cloud.githubusercontent.com/assets/1276342/9069873/42e8abca-3aec-11e5-9333-93d95a6ee737.png)

**Comment by Spikeone** [comment]
I don't think we should add this building - should be vinery for a temple or something. Just like it was in s4

**Comment by Flamefire** [comment]
@Spikeone If you close on issue as wont-fix, add the corresponding label and remove it from the milestones. If it may be implemented leave it open but add it to the milestone. Closed issues will never again be checked
