### ISSUE TITLE
[Addon] Temple

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#156]
(Original idea by Krugslayer: https://bugs.launchpad.net/s25rttr/+bug/1394129)
Temple should require as much building materials as Fortress
should be classified as a 'big' building
only one temple can be build
How it should work:

to 'activate' Temple, you should sacrifice 9 pigs or/and also 9 beers or/and something new (new production line, undecided yet)
Temple can be activated for 10 minutes (for example)
Temple should boost your soldiers:
a)
When 'activated' it could increase the number of 'hit points' of all of your soldiers. For example private must be hit 3 times to die and general must be hit 7 times to die. With temple 'activated' private will have to be hit 4 times to die and general 8 times to die

OR

b)
When 'activated' it could increase (by few %) the chance of each of your soldiers to hit enemy soldiers or decrease (by few %) the chance of enemy soldiers to hit your soldiers (doesn't matter if private or if general).

OR

c)
When 'activated' you are able to create 2x more soldiers than normally:

you need only sword + beer or only shield + beer to create soldier
OR

you need sword + shield + beer to create 2 soldiers instead of 1
How to enable this addon:

this addon should be optional. Should be available like other RttR addons (in options).
Why this addon:
Religion is something that should be implemented in this game for historical reasons. Religion was present in many cultures from the beginning. Besides I wanted to:

find an alternative way to boost soldiers
find a second purpose for pig farms
find a second purpose for brewery
create a new production line

Vineyard (for Settlers III and IV like version): 
![vy03](https://cloud.githubusercontent.com/assets/1276342/9069969/edc099f4-3aec-11e5-9e1f-96cea6d909a9.png)

**Comment by sjoblomj** [comment]
@Spikeone: I suppose this issue can be closed since #1673 is now merged :)
