### ISSUE TITLE
vsync = 1 causes 1 FPS

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1566]
In the latest nightly people only get 1 FPS if vsync is enabled (which seems to be the default case often). Setting the value in the config to 0 seems to fix the problem, although it sometimes enables itself.

This maybe is related to the fix: https://github.com/Return-To-The-Roots/s25client/pull/1557

**Comment by Xellzul** [comment]
Forcing refresh rate in-game (from dynamic to fixed number e.g. 60) seems to fix it also, although it doesn't seem persistent.
