### ISSUE TITLE
macOS: libminiupnpc not found

### ISSUE THREAD

**Issue by MLipfert1** [Return-To-The-Roots/s25client#1573]
After macOS 13.3 solved the terminal problem I was able to start RTTR again under macOS Ventura for a few days. Unfortunately, after the latest updates for RTTR that were automatically downloaded by starting the app bundle, the client is broken and crashes on startup:

`/tmp/rttr.command
Using directory "../../../"
Requesting current version information from server...
Parsing update list...
Updating folder structure...
Creating symlink "./s25client.app/Contents/Frameworks/SDL2_mixer.framework/Versions/Current"
Creating symlink "./s25client.app/Contents/Frameworks/SDL2_mixer.framework/SDL2_mixer"
Creating symlink "./s25client.app/Contents/Frameworks/SDL2_mixer.framework/Resources"
Creating symlink "./s25client.app/Contents/Frameworks/SDL2.framework/SDL2"
Creating symlink "./s25client.app/Contents/Frameworks/SDL2.framework/Versions/Current"
Creating symlink "./s25client.app/Contents/Frameworks/SDL2.framework/Resources"
Creating symlink "./s25client.app/Contents/MacOS/libminiupnpc.dylib"
Creating symlink "./s25client.app/Contents/MacOS/libminiupnpc.17.dylib"
dyld[3982]: Library not loaded: @rpath/libminiupnpc.17.dylib
  Referenced from: <4644CE82-4410-35DE-B804-9C7766E8A340> /Applications/s25client.app/Contents/MacOS/s25client
  Reason: tried: '/usr/local/lib/libminiupnpc.17.dylib' (no such file), '/usr/lib/libminiupnpc.17.dylib' (no such file, not in dyld cache)
`

**Comment by mtoensing** [comment]
I can confirm that.

First run: 
<img width="872" alt="Screenshot 2023-04-09 at 14 48 31" src="https://user-images.githubusercontent.com/136737/230773443-3ebc1f33-9dcc-4e2d-a6d4-2b7f1a234d51.png">

next run
<img width="872" alt="Screenshot 2023-04-09 at 14 48 41" src="https://user-images.githubusercontent.com/136737/230773438-8c9107a4-6ffe-44fb-88dd-2c9e1307a736.png">

**Comment by Flow86** [comment]
The RPATH was wrong due to a bug in our cross toolchain detection. Now it should work again.

**Comment by mtoensing** [comment]
Okay, where is the new release available?

**Comment by MLipfert1** [comment]
Just run the app bundle again and it will update to a working state automatically. 🙂
