### ISSUE TITLE
Wiki Linux Install Guide missing  libsdl2-mixer-2.0-0

### ISSUE THREAD

**Issue by sd2k9** [Return-To-The-Roots/s25client#1593]
For version  0.9.5 (and I guess all later versions) the following library is missing from the installation guide:
  libsdl2-mixer-2.0-0 (Debian).

It replaces libsdl-mixer1.2, which can be removed.

URL: https://github.com/Return-To-The-Roots/s25client/wiki/How-to-install-RttR

I also had trouble extracting the files from the Siedler 2 (Gold) ISO edition, because in Debian all files are mapped to lower cases. Which does not sits right with RTTR and leads to "file not found" errors.

I had to manually give the mount parameter "map=off" to have the files show up in UPPERCASE:
`sudo mount -o map=off,ro siedler_2_gold.iso /mnt`

Would this be worth mentioning, or is this too much detail?

**Comment by Spikeone** [comment]
Hey, this is a good point - can you perhaps write it in a way... I can just copy paste it? I sadly have no idea what that exactly means (how to install libsdl2-mixer-2.0-0) :D

**Comment by sd2k9** [comment]
Perfect - Thanks!
