### ISSUE TITLE
[addon] Extension: Flexible recruitment

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#16]
The soldiers should be recruited by the player like in "The Settlers III" if there is a sword, shield and the beer, means the player say's when and how much soldiers are recruited. Maybe the button could be included in the good allucation menu where on one side the required goods are listed and then on the other a button calling "Recruit" or "Recruit now".

**Comment by jhkl** [comment]
Just a question: Why?
In S3 there is a limited number of settlers (and you need to build houses to increase that number) and if you produce to much soldiers you run out of carriers.
In S2 there is an unlimited number of auto regenerating settlers. Why would you want to limit the soldier recruitment rate?

**Comment by Spikeone** [comment]
I really have no idea why that was an request. I first thought maybe for tactics (not recruiting at all and then recruiting a lot) but you can already do that.

In my opinion this addon can be closed as I see no use for it. I guess it's only a problem if you have only your HQ and expand fast so you have no carriers but then you can already set 0 and anything between 0% and 100% makes no sense in any case I think.
