### ISSUE TITLE
Create milestones

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#160]
We should create a couple of milestones and assign issues to them so we can schedule releases.

E.g. current version works pretty well. A couple of things are still missing (e.g. huge Memory leaks) But we could release it as stable 0.8.2 to replace the very old 0.8.1

0.8.3 Could include the memory leak fixes and pointer replacements.

0.9 The new serialization

1.0 The "dynamic nations" via XML

**Comment by Flow86** [comment]
sounds good
