### ISSUE TITLE
[Maps] Reorganize them 

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#163]
Currently there are:
- Old maps
- New maps
- Own maps
- Continents
- Campaign
- RttR
- Other
- Sea
- Played

I personally think we should reorganize that strutcture and thats my idea how:
- Original Maps (including Old maps and New Maps
- Original Mission (including Campaign and Continents
- RttR Maps (Same as RttR)
- RttR Sea (Same as Sea)
- RttR Mission (Including lua missions, I still think those would be a great enhancement for RttR. Already uploaded some here: https://github.com/Spikeone/rttr_maps)
- Played (Same as played at the moment)

(- Other ( I still think this folder can be removed, maybe we should quick-pick some maps which do not look that bad on first sight))

**Comment by Flow86** [comment]
sounds good

**Comment by Spikeone** [comment]
Subdirectorys, to organize maps would be great, so we could have for example the RttR Maps folder and divide "our" maps into multiplayer and singleplayer or seafaring and non seafaring. Maybe there is an even better way how we could categorize all maps, I should have a look at most "other" maps, could save some size.

**Comment by Spikeone** [comment]
https://docs.google.com/spreadsheets/d/1wGWtR06GYmrEJmn5Tt_uYij8J44CVj6EPmmiHIFUU3s/edit?usp=sharing

Just reviewed every map currently ingame.
- Red = Should be removed
- Yellow = If the Other folder still exists, they can be kept here
- Green = Could be added to "RttR" but may also include Singleplayer maps
