### ISSUE TITLE
path and filenames for lua files are case sensitive

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#1636]
both folders have to be created/installed with capital letters only: 

```
/usr/share/s25rttr/RTTR/CAMPAIGNS/roman/
/usr/share/s25rttr/RTTR/CAMPAIGNS/world/
```
for the indivual campaign files, all these files have to be renamed to .lua instead of .LUA: 

```
MISS200.lua  MISS202.lua  MISS204.lua  MISS206.lua  MISS208.lua  campaign.lua
MISS201.lua  MISS203.lua  MISS205.lua  MISS207.lua  MISS209.lua
```

likewise for the WORLD folder

**Comment by Flamefire** [comment]
Indeed it makes sense to have lowercase here. At least for the lua files,maybe even the folders could be named in lowercase or TitleCase.
@ottml

**Comment by ottml** [comment]
I changed the extension to lower case lua and renamed the folder to campaigns lower case. Adjusted the path for lua folder in the campaign.lua to lower case. Adjusted global path in files.h to lower case. I am currently testing it on linux and i will potenially extend the test for checking case sensitivity.
