### ISSUE TITLE
can no longer start on Osx High Sierra 10.13.6 (17G14042)

### ISSUE THREAD

**Issue by KristofKlein** [Return-To-The-Roots/s25client#1643]
Hi,

after a while wanted to play the game again ( and it also used to work) but lately this happens:

Dyld Error Message:
  Symbol not found: __ZTINSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
  Referenced from: /Applications/s25client.app/Contents/MacOS/starter (which was built for Mac OS X 13.1)
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/s25client.app/Contents/MacOS/starter

I bet this is sourced on an Update of the osx platform, while I don't get the "built for Max OSX 13.1" might get from.... 
is it worth to try to compile for my own?

**Comment by Flamefire** [comment]
Yes, looks like your OS is too old now. Compiling it yourself will fix it.

**Comment by KristofKlein** [comment]
thanks for the answer. but I never updated the s25 ... but maybe an osx updated killed it... I will give the build myself a try. thanks for the answer!
