### ISSUE TITLE
Integrate optional upscaling model

### ISSUE THREAD

**Issue by abergmeier** [Return-To-The-Roots/s25client#1645]
Optimally, there would be LODs for different zoom levels.
I wonder whether as a first step, perhaps an Upscaling model (upscayl?) can be shipped, that creates different LODs on the fly.

**Comment by Spikeone** [comment]
I think this requires quite some work - because lowering the LOD would be easy, sadly we already have the lowest LOD and can't scale down.

What is this required for anyway? Could you describe the use case in detail?

**Comment by Spikeone** [comment]
closing since no response from OP
