### ISSUE TITLE
Remove BOM

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#165]
It was mentioned (https://github.com/Return-To-The-Roots/mygettext/pull/2#issuecomment-128312774) that BOM causes more problems than it solves. So they should be removed again.

**Comment by uqs** [comment]
Are there any reports were the BOM was necessary?

**Comment by Flow86** [comment]
not really, bom was added since most of the german umlauts in the comments were corrupted.

**Comment by uqs** [comment]
But who corrupted them and how? Was this before the files were UTF-8?

**Comment by Flow86** [comment]
yes they were corrupted some years ago (haha sounds funny but its correct) and were never corrected. now they're fixed and the BOM was some kind of protective measure, but if its creating more problems then they solve ...

**Comment by lweberk** [comment]
UTF8 has intrinsic byte ordering. Contrary to UCS (which is probably what they where encoded in the first place (in the best case...). So BOM has no value on systems that default to UTF8 but it *might* have a value in telling editors on systems that don't, that they are looking at a UTF8 file (yeah Microsoft I'm glancing in your direction).

For the UNIX/Linux world absolutely of no worth and a no-brainer; remove.
For Windows; dunno. Would be the only immediate reason that would come to mind to keep them.

**Comment by uqs** [comment]
So do we have a windows-based developer that would like to test-drive a patch for this?

**Comment by Flamefire** [comment]
I'm using VS2012 and can test. But I'd also want to test it with eclipse in linux which messed some stuff up too.

**Comment by Flow86** [comment]
codeblocks corrupted the files with umlauts and ASCII encoding, but that was simply wrong usage. 

Every VS I used can handle utf-8 files correctly.

**Comment by Flamefire** [comment]
We should, however, replace all German comments anyway. So it (hopefully) won't be a problem in the future. Until then the merger got to quick-check for these issues.

**Comment by Flow86** [comment]
that should have removed all boms
