### ISSUE TITLE
[Maps] Add new Seamaps

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#168]
I just finished three new seamaps which should be included in RttR by default:
https://github.com/Spikeone/rttr_maps/tree/master/rttr_sea

**Comment by Flow86** [comment]
please also add a preview png/jpg for each map?

**Comment by Spikeone** [comment]
![s25client 2015-08-08 12-38-06-69](https://cloud.githubusercontent.com/assets/1276342/9150155/8a06b87c-3dca-11e5-874d-614ee8837d59.png)
![s25client 2015-08-08 12-38-44-09](https://cloud.githubusercontent.com/assets/1276342/9150156/8c84c260-3dca-11e5-9c1f-af3230018272.png)
![s25client 2015-08-08 12-38-45-49](https://cloud.githubusercontent.com/assets/1276342/9150157/8e1cfc96-3dca-11e5-9af3-97938d88a5aa.png)

**Comment by Spikeone** [comment]
Added with: #199
