### ISSUE TITLE
Add support to compile under FreeBSD/clang

### ISSUE THREAD

**Issue by uqs** [Return-To-The-Roots/s25client#171]
I have a bunch of patches to send out for this. This issue is to track progress, some start was made in:
https://github.com/Return-To-The-Roots/libutil/commit/5b884840e0946ae71d8b67bd9517bbc0841e5bc1
and
https://github.com/Return-To-The-Roots/mygettext/commit/5c04ec82efc92fd3e24ffc96649f5885d2fc3d73

**Comment by Flow86** [comment]
feel free to send PRs
