### ISSUE TITLE
New Build does not run - DeleteCriticalSection in api-ms-win-core-localization-l1-2-0.dll not found.

### ISSUE THREAD

**Issue by VFederau** [Return-To-The-Roots/s25client#1716]
Hello, i would test this Build 20241112 but i got a startup Error:
![image](https://github.com/user-attachments/assets/3d4b8180-b1fc-43a4-8f35-051d19ef3d9c)

Installed on System are these VC++ Runtimes:
![image](https://github.com/user-attachments/assets/4c2166dc-8bc3-43bc-913b-9ca6081014ed)

Thankfully the Old (Stable) Version did work!

Maybe you find time to check this?
Greetings Victoria

**Comment by Flow86** [comment]
Hi,
please reinstall the vcredist - e.g the newest one (version 14.42....):

https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

that should resolv the issue.

**Comment by VFederau** [comment]
Hello,
yes this works! Thank you very much!
