### ISSUE TITLE
Update NOT working if RTTR is to old

### ISSUE THREAD

**Issue by BestNoob** [Return-To-The-Roots/s25client#1717]
update via rttr.bat is NOT working if the RTTR version is to old like 0.8.1 or 0.9.0 if those files and others are missing

libminiupnpc.dll
libstdc++-6.dll

**Comment by Flamefire** [comment]
Sorry but what exactly is not working? When running `rttr.bat` the updater will be executed and the mentioned files, among others, should be downloaded.

**Comment by BestNoob** [comment]
Ok it happen with 0.7.2 and 0.8.1 but not with 0.9.0 but you can simply overwrite the files manually with the recent version.
![Screenshot 2024-11-22 152909](https://github.com/user-attachments/assets/c5b89327-082c-4ee6-9c6f-f08c70c4aafb)
![Screenshot 2024-11-22 152942](https://github.com/user-attachments/assets/02f34f74-d47f-4fc7-9a52-4d59af0fcf24)
![Screenshot 2024-11-22 152955](https://github.com/user-attachments/assets/c9952ba8-895d-4bfc-a121-001369a778ee)

**Comment by Flamefire** [comment]
I guess there was some corruption. Anyway as it works in recent versions there is nothing to do here for us.
