### ISSUE TITLE
[WWW] 3 Zeichen Suchbegriff zu kurz

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#188]
Leider ist es so, dass man auf der homepage nicht nach einem Suchbegriff suchen kann der 3 Zeichen lang ist. Angesichts von "Lua" und "Map" leider sehr schade, zumal 3 Zeichen nicht kürzer als 3 zeichen ist.

![3zeichen](https://cloud.githubusercontent.com/assets/1276342/9155592/b474ad74-3ebc-11e5-8463-cd87013f6e67.png)

**Comment by Spikeone** [comment]
I don't think anybody will need this anymore

**Comment by Flamefire** [comment]
Hm, wouldn't abandon it. @Flow86 How hard is that change? Do you have access to the forum source and can change the min length to 1 or so?

**Comment by Flow86** [comment]
changed
