### ISSUE TITLE
Texture transmission missing

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#190]
If you view any coordinate including a 0: or :0 (e.g. 100:0 or 0:100) some texture borders are just missing. Those are not 0:0 nodes, but most likey around 1-10 nodes away (e.g 7:10 or 20:3).

![tooclose](https://cloud.githubusercontent.com/assets/1276342/9157380/abfcf0b8-3efb-11e5-95a9-555c7db8c85c.png)

Using Windows and WinAPI

**Comment by Flamefire** [comment]
Does this still happen with latest nightly? There have been some fixes to the terrainrenderer lately that also fixes crashes

**Comment by Spikeone** [comment]
Well, looks like I used the wrong version, sorry for any inconvenience.
