### ISSUE TITLE
Lobby server down / not responding

### ISSUE THREAD

**Issue by MarcusSt** [Return-To-The-Roots/s25client#193]
see title

**Comment by Flow86** [comment]
lobby server seems to run into some kind of life-lock, I'll try to find out why

**Comment by Flamefire** [comment]
Already had a problem, where a game was not deleted and thus no new game could be created by the same user. Might be related

**Comment by Spikeone** [comment]
The same user can create an other name, he may read the error message telling him, that there is already a game with that name, not by that user.

**Comment by Flow86** [comment]
yes I added a check now, but it seems still be buggy (at least it doesnt lock up anymore, but crashes :X)

**Comment by Spikeone** [comment]
Crash = lobby restart = ghost game away? :D

Well, I have no deep knowledge but since every player has a unique name, that could be used as identifier, if a player wants to create a game, that already exists, but has the same host identifier he could kick his old game, maybe

**Comment by Flow86** [comment]
thats normally the way it goes. one player can only host one game

**Comment by Spikeone** [comment]
Okay, I guess that's what you were working on then :)

**Comment by uqs** [comment]
Question: is the lobby supposed to be reachable via IPv6 (doesn't work on FreeBSD)

**Comment by Flow86** [comment]
the lobby server? yes it should be possible to reach it via ipv6.

**Comment by uqs** [comment]
Verbinde mit 2a01:4f8:192:242a:600:46:212:227:3664
Verbindung fehlgeschlagen
Fehler: Connection refused
Fehler beim Verbinden mit tyra.ra-doersch.de:3664
Sending Message to server failed


% telnet -6 tyra.ra-doersch.de 3664
Trying 2a01:4f8:192:242a:600:46:212:227...
telnet: connect to address 2a01:4f8:192:242a:600:46:212:227: Connection refused
telnet: Unable to connect to remote host
(1)% ping6 tyra.ra-doersch.de
PING6(56=40+8+8 bytes) 2001:1620:b6e:0:a60:6eff:fe6c:e6c6 --> 2a01:4f8:192:242a:600:46:212:227
16 bytes from 2a01:4f8:192:242a:600:46:212:227, icmp_seq=0 hlim=52 time=28.668 ms
16 bytes from 2a01:4f8:192:242a:600:46:212:227, icmp_seq=1 hlim=52 time=28.644 ms
16 bytes from 2a01:4f8:192:242a:600:46:212:227, icmp_seq=2 hlim=52 time=28.963 ms
^C
--- tyra.ra-doersch.de ping6 statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 28.644/28.758/28.963/0.145 ms


It's not listening on the advertised IP and port :(

**Comment by Flow86** [comment]
its currently not listening on ipv6, only v4

**Comment by Flamefire** [comment]
Is this fixed? Any update on this issue?

**Comment by Flamefire** [comment]
Still seems to be an issue according to some users. @Flow86: If you don't have time to look into this, is it possible to run a local copy of that to check how and why it crashes, deadlocks or whatever? Any chance to see, why the server is failing? (At least, if it crashed or just deadlocked) Maybe run a debug version of it (should not need that much performance) to get possible assertions or so?

**Comment by MarcusSt** [comment]
From what I can see recently, the server seems to be running pretty stable in the last weeks.

Please reopen if problem still appears.
