### ISSUE TITLE
Framelimit in menus doesn't work in windows

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#194]
Sadly, this feature seems disabled in current nightly builds, it was enabled (upper right corner showing 31 FPS) but now RttR consumes 100% CPU again.

**Comment by Flow86** [comment]
that does work for me (build 9.8.2015, 641419d)

**Comment by Spikeone** [comment]
![nope](https://cloud.githubusercontent.com/assets/1276342/9201742/d6f94c36-404e-11e5-8ff1-cde07464c122.png)
Not for me anymore, when it was first implemented, it worked for me.

![nope2](https://cloud.githubusercontent.com/assets/1276342/9201750/e5da1eb0-404e-11e5-9a11-e73e5d05e94e.png)
Also this happens with the latest versions again.

**Comment by Spikeone** [comment]
Okay, I did some testing (as Flamefire advised)
If I build RttR on my own everything works fine (CMD closes, Framelimit works)
Latest nighty 641419d: none of both work
Nighly 1073cd0: Frameratelimit works, CMD doesn't close

**Comment by Flamefire** [comment]
I narrowed it down a bit further: 9387c0e1c9bc97167195e2de425c86c4d8ce1d30 broke this.
I suspect this was due to 511b21299c14d0390458b8d5c0ebf8d4a49e7029 which might have caused a bug on the build server.
