### ISSUE TITLE
Can reset screensize when i setted it up to high

### ISSUE THREAD

**Issue by YunaBraska** [Return-To-The-Roots/s25client#195]
Hi, when i applyed the wrong screen size yesterday, than i had much troubles to reach the bottom to set the size back again. i needed to connect my notebook to my TV for reaching the graphic settings...

Would be nice if there would be a config file or something for these emergencies :P

**Comment by Flow86** [comment]
there is a config file, you can simply delete/edit

``` 
Saved Games\Return To The Roots\config.ini
```

on windows, or on unix

```
$HOME/.s25rttr/config.ini
```

**Comment by YunaBraska** [comment]
oki
