### ISSUE TITLE
Doesn't start if default shell is "fish"

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#20]
Version: 0.8-8744 (Mac)

I am a Mac user with fish as default shell (http://fishshell.com) and I get an error on startup:

"The file '/tmp/rttr.command' is marked as an executable but could not be run by the operating system."

If I change the default shell to bash ("chsh -s /bin/bash") everything works as expected. Could the run script somehow try to open with bash instead of the default shell

Spike (fvv1) wrote on 2013-08-08:	#1
Well, it's sad, that I can't say anything about this :-/

https://bugs.launchpad.net/s25rttr/+bug/1184875

**Comment by uqs** [comment]
Hey Spikeone, how exactly do you start it (from a terminal?)? Also, can you confirm that there's a /bin/sh on your system?

**Comment by Spikeone** [comment]
Oh, I forgot to link the original reporter: https://bugs.launchpad.net/s25rttr/+bug/1184875

By: Bug #1184875 reported by Raphael Fetzer on 2013-05-28
So that bug may be invalid, but I'm not using Linux so I can't decide. If you think this is an invalid bug, let me know, I'll close this issue.

**Comment by uqs** [comment]
The bug is 2 years old, does it still happen? Can you still reproduce and how exactly do you try to start it?

**Comment by Flow86** [comment]
Since we cant reproduce -> close

**Comment by uqs** [comment]
@Flow86 please reopen this issue, I think I see what the problem is and the fix should be trivial.
