### ISSUE TITLE
Metalworks produces even if all tools set to 0%

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#207]
Unlike the original Settlers2, I saw that the default value in rttr is "0%" for all individual tools to be produced in the metalworks. I liked this because every game needs different quantities of tools.
But the metalworks is producing random(?) tools anyway. It would be nice if it would stop if all tools are set to 0%. This would free the player from enabling/disabling the metalworks manually.

**Comment by Flow86** [comment]
yes I too think thats a bug. those quantities should be on the standard S2 setting

**Comment by Spikeone** [comment]
Duplikate of #80

**Comment by Flow86** [comment]
original distribution: 
![tool settings](https://cloud.githubusercontent.com/assets/656249/9275622/a48484a8-429e-11e5-832f-aceb1227a923.png)

**Comment by Spikeone** [comment]
Oh, so 0% was not possible at all?

**Comment by Flow86** [comment]
nope, if everything was set to 0%, a random ware was produced. in old s2 no ware was produced

**Comment by Spikeone** [comment]
Oh really? Impressive - but that shows how long I'm playing rttr instead of s2. Great work then, sorry for any useless comments caused by false knowledge!

**Comment by jhkl** [comment]
In the original S2 a random ware was produced when everything was set to 0%:
https://youtu.be/MP6cRVknUH4

**Comment by Spikeone** [comment]
Then again: please make this an Addon, I can totally understand new players (casuals) that they kinda dislike such behaviors, but from a (not meant to insult anybody) skilled player perspective this takes a lot from the code management you have to do when playing which is, as you always have to do the same and only your management decides weather you win or lose, takes core gameplay away.
So please add this to the tool ordering addon, if tools ordered == 0 and the sum of all percentages is also 0, then stop production.
Hopefully you understand my concerns

**Comment by Flow86** [comment]
really O.o I tried it yesterday and it produced nothing on 0% O.o

**Comment by Flamefire** [comment]
I'd consider it a bug if everything is at 0% and something is produced. If that happened in old S2 then its a bug there. So I think 0% = nothing is ok

**Comment by Flow86** [comment]
no its not a bug - if you think about it longer - its logical.

if everything is on 0%, or 10%, or 20%, ... none of the items has priority. so its randomly selected.

if you want to stop production, you had to stop the metalworks at all.

But, I created an addon for that, and made the "new" (0%=stop) behavior default now.

**Comment by Flamefire** [comment]
Well its a mathematical issue:
0% of the produced wares should be item X --> 0 item X are produced
If all are 0% but 1 item is produced you got a problem ;)

**Comment by Flow86** [comment]
No its not percent of produced wares - its % of which ware should be selected!

**Comment by Flamefire** [comment]
Then left side is not 0% otherwise the issue persists

**Comment by Flow86** [comment]
yes of course its not 0 - its 0%!

the amount produced is always 1! 

if you have 12 tools - everything with a priority of 0% - then no item of the 12 tools have a higher priority than the others -> so every item has the SAME priority. old S2 used a random algo then - but you could also simply produce each one each time.

its not a mathematical bug in there. its logical

**Comment by MarcusSt** [comment]
It's about weighting. With everything having the same weight, the mean amount of tools produced should be the same over a (longer) period of time. A weight of 0 is perfectly okay, as well as negative weights would be.

**Comment by Flamefire** [comment]
Ok, so its not percent is weight. Then any help should also phrase it like that. Although the normal expectation is, if nothing is selected, nothing is produced.

**Comment by sonchusarvesis** [comment]
There is something wrong with wetalworks. I don't undestand how it behaves. "Produce nothing ..." has no effect, it produces nevertheless.

**Comment by Flamefire** [comment]
This should not be possible. Are you sure you set this in the addon settings?
If so, please attach a savegame/replay, where this behaviour is visible (with some notes, where to look at)

**Comment by sonchusarvesis** [comment]
You're right. But it is too complicated. It produces nothing, even if you request a tool - until you increase the bar for that tool. But then, it produces one after the other, and before you can say knife, you got 20 hammers or so - regardless of the requested amount.

**Comment by Flamefire** [comment]
Requesting the amount works best with the addon-setting "produce nothing on all 0%" as then it will produce only the requested amount. If you increase the bar to above 0% it will correctly produce the tools set by the bar. Read through this issue if you don't understand why.

If you still have a bug, please attach a savegame and/or replay with descriptions what to do and look for.

**Comment by Spikeone** [comment]
It sounds like he actually found a bug - I'm going to check that when I'm home.

**Comment by sonchusarvesis** [comment]
Yes, works. The metalworker waits a minute before he begins to produce. Because of that I was totally confused.

**Comment by Flamefire** [comment]
Just so I get it right:

- Addon set to: produce nothing on 0%
- All Tools set to 0%
- No tool ordered

=> Nothing should be produced. Does this work?

- Addon set to: produce nothing on 0%
- All Tools set to 0%
- Tool ordered

=> Tool should be produced. Does this work?

**Comment by sonchusarvesis** [comment]
Yes and yes, just the delay confused me.

**Comment by Flamefire** [comment]
Ok. BTW: Almost all buildings have this delay. Try to stop production of some building and enable again. Mostly it will take some time till you see something happening. This is due to preparation work done by the worker in the building, e.g. gathering all resources in his house etc ;) Has been like that in original S2 too
