### ISSUE TITLE
"v" key to accelerate game doesn't work reliably

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#209]
I noticed that pressing the "v" key to accelerate the game doesn't work right. Sometimes it works, sometimes it doesn't and I've to press is for some time.

**Comment by Flow86** [comment]
hi,
you can only accelerate in single player games.

you can set different speeds with it, so one press only sets the next speed.

you can see it on the top (frame length)

**Comment by kyromaster** [comment]
Now I understand how this works. I just looked at the speed indicator from settlers2 and not the infos on the upper left side. Perhaps there could be a graphic speed indicator on the right side both for slower and faster speeds. This would it make clearer for new players, It's rather difficult to interpret e.g. "GF=50ms" as default speed.

**Comment by Spikeone** [comment]
Maybe a visual bar with that settler with a default speed marker and if you hasten up the game he turns right (as he already does) and moves away from the default and via versa the other other direction? Overlay hot key could be v and increase/decrease by + / -

**Comment by Flamefire** [comment]
Fixed in #419
