### ISSUE TITLE
Grafikfehler: Alle Bodentexturen schwarz, Maus zieht schlieren.

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#21]
Version: 0.8-8596 (i386)

Tritt gleich nach dem Laden der Karte auf. Hauptmenu alles normal. Hab alle Grafikmodi durchprobiert.

Nvidia GeForce GT 520 512MB (PCI-Version)

NastX (jtrampe) wrote on 2013-03-16: Re: [Bug 1155915] [NEW] Grafikfehler: Alle Bodentexturen schwarz, Maus zieht schlieren.
Auch bei verschiedenen Maps?

FloSoft (flosoft) wrote on 2013-03-17:
VBO ausschalten, bei manchen Karten haben die Probleme

**Comment by MarcusSt** [comment]
Still valid?

**Comment by Flamefire** [comment]
To old so should be fixed.
