### ISSUE TITLE
Update readme.txt

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#213]
The readme.txt file is not up to date anymore. The file is dated "2010.01.17" and v0.7.2 is the latest stable build.
This file should be updated (Information on "how to install" maybe)

**Comment by Flamefire** [comment]
Which readme.txt are you referring to? I can't find one in the repo

**Comment by Spikeone** [comment]
https://github.com/Return-To-The-Roots/s25client/tree/master/RTTR/texte
