### ISSUE TITLE
Change metalworks behavior not working

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#214]
This new addon is not working at all, set it to "Produce nothing" (well, it already was as default) but the metalworks still produced some tools.

**Comment by kyromaster** [comment]
What I wrote in a duplicate report (sorry for that) still applies: When clicking "use settlers2 defaults" the value isn't set to "produce random ware" which is s2-default.

**Comment by Spikeone** [comment]
Does that also apply to seafaring which is not set to "no sea attacks" (which I guess is the case) because then this should be an independent bug

**Comment by kyromaster** [comment]
Yes it does. I opened a seperate bug report.
