### ISSUE TITLE
Soldaten beim auseinanderlaufen im Kampf falsch gezeichnet

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#22]
Der Bug gehört noch dazu, dass soldaten die im Waiting status sind falsch gezeichnet werden. Der Fehler ist auch behoben, jetzt ist nur übrig geblieben, dass die Soldaten sofern sie Kämpfen ja erstmal zusammen auf einen Node laufen, dann ein Stück auseiander gehen und anfangen zu kämpfen. Nun ist es so, dass genau dieses Auseianderlaufen noch falsch gezeichnet wird - hier scheint die Reihenfolge wieder falsch zu sein.

**Comment by jhkl** [comment]
Wie kann man das reproduzieren? Ist mir noch nie aufgefallen.

**Comment by Spikeone** [comment]
War als ich es reportet hab aufjedenfall immer so - jetzt weiß ich es nicht mehr 100% bin mir aber 90% sicher, dass es noch so ist. Werde es bei Gelegenheit im replay überprüfen.

**Comment by Spikeone** [comment]
Grad erneut getestet, Bug besteht weiterhin.
Oben beim auseinanderlaufen hat der blaue Soldat keine grüne Rüstung an, unten im Kampf hat der rote Soldat seine Rüstung korrekt an.

![stillpersistent](https://cloud.githubusercontent.com/assets/1276342/13379778/eeede8b8-de2f-11e5-8d4f-32d6b9701627.png)

**Comment by Flamefire** [comment]
Found it. This is a long standing bug caused by the glSmartBitmap. Creating a fix...
