### ISSUE TITLE
Caravan dies

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#223]
It can happen, that a caravan still takes a route that possible leads to death. Either they just walk into Water/Lava/Snow or anything else and then die.
This can also happen due to finished building which were not blocking when the caravan started.

**Comment by Flamefire** [comment]
Is it possible to create a replay for this?

**Comment by Flamefire** [comment]
It should be impossible, that the caravan walks into lava. However it will die if it can't find a path anymore. Especially for the case where the territory the caravan is walking on, is captured by an enemy. Then they will die as it is not allowed to walk on enemy territory. I think we should replace this by a regular "wandering" instead that will most probably also lead to death, but there is a small chance, that they find a players flag. Especially when trading near enemys border. Maybe they can also just walk out of the enemys territory and continue the trade, or they should be allowed to cross enemys territory if nothing else is possible during a started trade. This adds some more complexity but eases the trade. However "capturing" trades could also be a strategy. so maybe we should leave it as is. Ideas? @MarcusSt @jhkl @Spikeone

**Comment by Spikeone** [comment]
Gonna do some games with maps that may not have correct highways.
Just imagine a caravan that uses a path which uses a road over 1 water node (they can only be passed if there is a road, without this path can't be used)

**Comment by Spikeone** [comment]
Oh there is no edit button (at least with a mobile version).
I still have post an idea for a reworked trade system.

**Comment by Flamefire** [comment]
Currently you have waypoints. The waypoint graph forms the highways- You search a path through the waypoints and then start walking by searching paths from one waypoint to another. So you always have a valid path once you start walking. It can only die, if the caravan gets trapped (e.g. by an enemy conquering the territory they are walking on or everything around it.

**Comment by Flamefire** [comment]
PS: What do you mean with "I still have post an idea for a reworked trade system. "?

**Comment by Spikeone** [comment]
We talked about reworking the trade system, that's what I meant.

**Comment by Flamefire** [comment]
Yes, but that was mainly GUI related and an addon for the handling of the carriers/donkeys, wasn't it? If this is not an issue yet, can you open one and summarize the proposed changes so we can all discuss them?

**Comment by Spikeone** [comment]
Oh - I thought we could change the interface and the system - maybe with different part addons (like disable donkeys, 1 dokey for 1 caravan, 1 donkey each ware or can/cant pass enemy controlled land etc.)
I think a trading GUI should support all those setting which means when should first discuss a trade system and then build a GUI that supports all features - and stop adding buttons somewhere which looks bad.

**Comment by Flamefire** [comment]
Closes by https://github.com/Return-To-The-Roots/s25client/pull/360
