### ISSUE TITLE
Caravan uses strange "highways"

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#224]
Some time ago highways have been added for any caravan when trading. This leads to sometimes really strange routes as a caravan walks back first and then to it'S destination.

**Comment by Flamefire** [comment]
This can only be changed if the "highways" are removed. Those were added for faster performance as the pathfinding needs only to search the highwaypoints
Removing this would allow smooth, optimal pathes but probably with a slight performance hit. We should test it on a large map

**Comment by jhkl** [comment]
Could the effect be reduced by also checking the path to the second highwaypoint and compare the distance to the distance of the first highwaypoint? If the distance is lower, just discard the first highwaypoint. Should only be one additional path check. (Or two if also applied to the end of the route).

Possible?

**Comment by Flamefire** [comment]
This was also my idea. But you would need to check for distance to first wp+to 2nd wp against to 2nd wp directly.
I'm currently refactoring and optimizing the freepathfinding/trade graph search as it is kinda slow. Tried to time the pathfinding from1 point to all others: 2.2s on my (mid-high-end pc). I'm also going to compare this against using the free path finder alone, which would give best results and avoids impossible pathes (a player can capture a full tradegraphnode but this is not represented in the graph -> Path is found but local path won't -> abort during trade although a (longer) path might exist)

**Comment by Flamefire** [comment]
I just compared the new pathfinding with the old tradegraph-pathfinding and it is roughly the same speed (map is 122x144). Probably we can just remove the tradegraph and have nice and smooth pathes :)
