### ISSUE TITLE
Improved alliances crash on catapult strike

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#227]
When two allied players get land from a building that was destroyed by a catapult, the game crashes.

**Comment by Flamefire** [comment]
Can you further descripe this or back it with a savegame/crashlog?

**Comment by Spikeone** [comment]
No savegame because reinstalled anything since then.
P1(T1) and P2(T1) both have a border with P3(no team).
Now the catapult of P1 strikes on a military building of P3 and destroys it. This causes P1 AND P2 to gain more "land" but then the game crashes.

I guess it's caused by giving land to two allied players at the exact same time which causes the crash.

**Comment by jhkl** [comment]
I can confirm the crash. Tested with 3 local clients on map "Totecke". One of the three clients crashed on destruction of a building by a catapult. Unfortunately, the replay seems not to crash. Adding it anyway: 
https://dl.dropboxusercontent.com/u/1589203/rttr/crash-in-1-of-3-clients.rpl

**Comment by ikharbeq** [comment]
I tried to reproduce this for a bit but can't get a client to crash in a 3 player setup in any reliable way.
I do have a replay that crashes after a building is lost to a catapult hit - didn't have the time to check yet but the crash seems to occur when one of the soldiers attached to that building has to be drawn after the building has been lost. gf ~195800 at position 105,68.
https://dl.dropboxusercontent.com/u/83471767/2015-11-27_15-48-59.rpl

This crash is without improved alliances though so it might be a different bug, still worth looking into.

**Comment by Flamefire** [comment]
Thanks. I have a lot of fixes in the pipeline and am currently cross testing the assumptions (assertions) etc. I'll check this replay too so maybe I can find it that way.

**Comment by Flamefire** [comment]
I think I fixed that. Commit is coming later.  Issue seems to be, that a soldier was ordered but waiting in a warehouse at the time, the building was hit by a catapult stone. This is likely to happen for a player beeing attacked by 2 others at the same time. So strictly nothing with improved alliances but in situations where you want improved alliances the bug is more likely to occur
