### ISSUE TITLE
Carriers feared into water and die

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#228]
It can happen, that a carrier who occupies a road connected to a harbor spot (means in most cases, that the road as water on one side) that a soldier fears that carrier. But then the carrier can possibly not go anywhere so he walks straight into water and dies, which creates strange corpses on water.

Visible in this video:
https://youtu.be/Rfw3K4l3WXE?t=2m20s

**Comment by K4T** [comment]
Pretty funny bug :D
