### ISSUE TITLE
Add option for disabling shadows

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#231]
Well, I might be wrong but drawing shadows with transparency consumes just as much processing as normal entity's do. That's why it could be helpfull for slower PCs if you were Able to gain some more performance.
Also this could be forced when the average Fps amount drops below 20.

If this won't help - please close this issue :)

**Comment by MarcusSt** [comment]
That's already taken care of (mostly) by glSmartBitmaps. They merge the graphics for images and shadows into just one that needs to be drawn. We need the alpha channel for the "normal" graphics as well, as they don't have rectangular shape.

-> Won't help. :(
