### ISSUE TITLE
Metalworks extention doesn't work

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#236]
The metalworks extention "produce nothing if all tools set to 0%" has multiple problems.
First, it has no effect. The metalworks still produces a random ware even if set to "produce nothing" and all settings are 0%.
And also, it's IMHO unlogical. The tooltip says "rttr-default on, s2 default off". When I press the "use settlers2 defaults" it will not change to off. Also IMHO the default settings should be s2 compatible, as it is with the other options. Best would be to be off by default and have the player change it to on when he needs it. This would be consistent with all the other options.

**Comment by Spikeone** [comment]
#214
