### ISSUE TITLE
Incompatible default settings for extentions

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#237]
The two extentions "change metalworks behavior on zero" and "sea attack settings" have default values which differ from the settlers2 defaults. Even when pressing "use settlers2 defaults" they won't switch to "produce random ware" and "no sea attacks".

IMHO the default settings should be s2 compatible, as it is with the other options. The player can still change it when he needs it.

**Comment by Flow86** [comment]
we should add some kind of "RttR-Defaults" besides the "S2-Defaults"

**Comment by Spikeone** [comment]
Hard do decide what RttR Defaults are - I would recommend different settings than you may do or maqs or anybody else

**Comment by Flamefire** [comment]
--> #238
