### ISSUE TITLE
Wrong trading route -> Donkeys die

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#24]
Hallo Zusammen

Mir ist aufgefallen, dass es bei der Option "Handeln" immer wieder vorkommt, dass die Esel in die falsche Richtung laufen und dann irgend wo sterben.
Würde mich freuen wenn man das mal korrigieren könnnte.
Version war: 20140724

Spike (fvv1) wrote on 2014-12-02:
Welche Revision ist das? Gibt es Replays?

Benjamin Wettstein (beni-wettstein) wrote on 2014-12-08:
Die Raute (Automatisches Speichern).sav Edit (1.4 MiB, application/octet-stream)
Hier ist die Spieldatei.
An der Stelle des Spielers Shorts(Orange) muss man einsteigen. Dann muss man beim verbündete Spieler Burton1224(Türkis). Auf das erste Lager drücken das direkt an der Grenze liegt. Wenn man nun z.B. Siedler sendet gehen die vom Hauptquartier in die falsche Richtung und danach zurück in das Hauptquartier. Aber nicht ins Lager zum Türkisfarbenen Spieler

Benjamin Wettstein (beni-wettstein) wrote on 2014-12-08:
Auch in der aktuellen Revision und Version funktioniert es nicht!!
Revision war aber glaube ich 9484 als wir spielten

**Comment by Flamefire** [comment]
Kann das jemand mit nem aktuellem savegame/replay reproduzieren? Also gerade das in die falsche Richtung laufen... Das Savegame hier existiert ja leider nicht mehr bzw wäre auch nicht mehr kompatibel.

**Comment by mrumler** [comment]
Habe ein paar Maps kurz im SP angespielt. Pathfinding funktionierte in allen Fällen, außer einem.
Auf "Hochebene" wird kein Weg zum Gegenüberliegenden Verbündeten gefunden (Link anbei, GF ~7500). Mag an der großen Steinfläche liegen.
Bislang aber keine übers Wasser laufenden Jesusesel, oder welchen die gegen Bauernhoftüren rennen und verschwinden...
http://grex-lycanum.de/s25rttr/2015-10-13_11-03-19.rpl

**Comment by Flamefire** [comment]
Ok. Auch seltsame/falsche Wege wären interessant.
Wenn du oder jmd anderes Zeit hast, könntest du versuchen, das originale Problem in der aktuellen Version nachzustellen. Savegame (gerade gefunden): https://bugs.launchpad.net/s25rttr/+bug/1398256/+attachment/4276094/+files/Die%20Raute%20%28Automatisches%20Speichern%29.sav von Version 20140724

Vielleicht ist es aber auch schon durch einen der anderen Fixes behoben...

**Comment by Spikeone** [comment]
Schau in mein Video zu Trade - da waren die Wege aufjedenfall komisch.
Auch fertige Gebäude oder neue Baustellen sind vmtl noch komisch

**Comment by Flamefire** [comment]
Hab ein paar Kleinigkeiten gefunden. Hauptproblem ist aber der Tradegraph: https://www.youtube.com/watch?v=PIwP7o-7hzk
Was im Prinzip passiert ist: Er sucht in einem groben Raster nach dem Weg (20x20 Quadrate). In dem Raster hat er dann feste Punkte, die er nutzt (jeweils 1) und die werden dann Gnadenlos angesteuert. Daher rennen die auch erst mal alle nach unten zum Stein, weil da der Punkt ist. Das ist auch der Grund, warum das Pathfinding dort failen kann, obwohl es einen Pfad gibt: Der Punkt liegt einfach ungünstig.
Ich würde also vorschlagen, den Tradegraph rauszunehmen und nur das normale Pathfinding zu nutzen. Um Performance zu liefern kann man einen globalen Cache anlegen, der die Trade-Routen speichert, nachdem die gesucht wurden. Da Trades nur von Warehouse zu Warehouse gehen und häufig die gleichen Verbindungen genutzt werden könnte man schon mit 20 Einträgen eine extrem hohe Trefferquote haben.
@jhkl @MarcusSt @Flow86 Meinung dazu?

**Comment by Flamefire** [comment]
The cache would also need an expiration time that could depend on the quality of the route. So the closer the route is to the "best possible" one the longer is the expiration time. This allows for reaction on changed conditions (buildings destroyed, player lost land...)
