### ISSUE TITLE
Fix VS build for x64

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#243]
Currently we only support VS compilation for x86 but not for x64.
So we need to compile all contrib libraries for x64:

- [x] Compile contrib libraries with VS2012 (normal lib folder)
- [x] Compile contrib libraries with VS2015 (VS2015/lib folder)
- [x] Test compilation under VS2012 for x64
- [x] Test compilation under VS2015 for x64

(Note that VS2012 and VS2015 libraries cannot be used interchangeable as the stdout/stderr... implementations have changed. You'll get a linker error on linking the executable)

**Comment by Flamefire** [comment]
Made a first 64 bit build with VS 2012
However the sound is not working yet.

**Comment by Flow86** [comment]
yes mostly libsdl which has the wrong architecture?

**Comment by Flamefire** [comment]
Correction: Everything works. I just had the rttr sound disabled in windows :D
