### ISSUE TITLE
cmake problems with make preinstall vs. CMAKE_INSTALL_PREFIX=

### ISSUE THREAD

**Issue by uqs** [Return-To-The-Roots/s25client#246]
On FreeBSD with cmake 3.2.3

we run cmake with the following in build/cmake.sh

$CMAKE_COMMAND -G "$GENERATOR" -DCMAKE_INSTALL_PREFIX= $PARAMS "${SRCDIR}"

this ignore --prefix set via the script, *AND* more importantly, sets CMAKE_INSTALL_PREFIX=  so to the empty string.

I need to run at least 'make preinstall' to get the video drivers linked, then this happens:

## Installing S2 placeholder
creating ./share/s25rttr/S2/put\ your\ S2-Installation\ in\ here
-- Done
CMake Error at driver/video/SDL/src/cmake_install.cmake:31 (file):
  file cannot create directory: /./share/s25rttr/driver/video.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  driver/video/SDL/cmake_install.cmake:32 (include)
  driver/video/cmake_install.cmake:34 (include)
  driver/cmake_install.cmake:33 (include)
  cmake_install.cmake:35 (INCLUDE)

And from that cmake file, the problem is the empty CMAKE_INSTALL_PREFIX, see:

  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/./share/s25rttr/driver/video" TYPE SHARED_LIBRARY FILES "/data/src/s25client/build/driver/video/SDL/src/CMakeFiles/CMakeRelink.dir/libvideoSDL.so")      

This now always tries to install things into the / directory, under /share/s25rttr which can only work with root, but is also the wrong destination.

This whole setup frightens and confuses me, can someone please draw a picture of how build, install, and release packaging is supposed to happen?

**Comment by Flamefire** [comment]
--prefix is assigned to "PREFIX" which is used throughout the other scripts
I don't know why we don't use CMAKE_INSTALL_PREFIX (--> @Flow86 ?) but also could not find the line you are referring to. CMAKE_INSTALL_PREFIX should never be used...

Besides: It should not be required to run preinstall for linking, if I remember correctly. Have you tried with the steps described in the README? (cd build && ./cmake.sh --prefix=. && make) What is the problem?

**Comment by uqs** [comment]
So, it works totally fine on Ubuntu, it seems. This bug is then specific to FreeBSD somehow.
But if I grep -r CMAKE_INSTALL_PREFIX . on an Ubuntu build, I get tons of hits that show how this prefix is used and why that can be trouble some.

As for make vs. make install (actually, make preinstall). This is how it looks on FreeBSD:

cd build && ./cmake.sh --prefix=. && make
...
[100%] Building CXX object src/CMakeFiles/s25client.dir/ogl/glArchivItem_Music.cpp.o
4 warnings generated.
Linking CXX executable s25client
[100%] Built target s25client

% src/s25client
lade "/home/uqs/.s25rttr/CONFIG.INI": fertig (0ms)
searching for drivers in ./share/s25rttr/driver/video/*.so
0 video drivers found!
Video driver couldn't be loaded!

Which is strange, because it looks exactly like on Ubuntu:
% find . -name libvideo\* -ls
 64149      529 -rwxr-xr-x    1 uqs                              wheel                              131520 Sep  3 11:48 ./driver/video/SDL/src/libvideoSDL.so
 64100       97 -rw-r--r--    1 uqs                              wheel                               46800 Sep  3 11:48 ./driver/src/libvideodrv.a

Running make preinstall will link some more stuff:
% make preinstall
[  0%] Built target version
       version: started
                source directory: "/data/src/s25client/"
                build  directory: "/data/src/s25client/build/"
                build_version.h is unchanged
       version: finished
[  0%] Built target updateversion
[  1%] Built target audiodrv
[  2%] Built target videodrv
[  3%] Built target videoSDL
[  5%] Built target endian
[  6%] Built target audioSDL
[  6%] Built target mygettext
[ 19%] Built target siedler2
[ 22%] Built target s25util
[ 24%] Built target lobby_c
[ 25%] Built target resample-sndlib-20
[ 26%] Built target s-c_resample
[ 27%] Built target sound-convert
[ 28%] Built target s25update
[ 95%] Built target s25client
[100%] Built target translations
Linking CXX shared library CMakeFiles/CMakeRelink.dir/libvideoSDL.so
Linking CXX shared library CMakeFiles/CMakeRelink.dir/libaudioSDL.so
Linking C executable CMakeFiles/CMakeRelink.dir/s-c_resample
Linking CXX executable CMakeFiles/CMakeRelink.dir/sound-convert
Linking CXX executable CMakeFiles/CMakeRelink.dir/s25update
Linking CXX executable CMakeFiles/CMakeRelink.dir/s25client

It's still not working though, running make install then copies a bunch of RTTR directories and stuff, but dies with:

## Installing additional documents
./../RTTR/texte/readme.txt -> ./share/s25rttr/../doc/s25rttr/readme.txt
./../RTTR/texte/keyboardlayout.txt -> ./share/s25rttr/../doc/s25rttr/keyboardlayout.txt
## Installing S2 placeholder
creating ./share/s25rttr/S2/put\ your\ S2-Installation\ in\ here
-- Done
CMake Error at driver/video/SDL/src/cmake_install.cmake:31 (file):
  file cannot create directory: /./share/s25rttr/driver/video.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  driver/video/SDL/cmake_install.cmake:32 (include)
  driver/video/cmake_install.cmake:34 (include)
  driver/cmake_install.cmake:33 (include)
  cmake_install.cmake:35 (INCLUDE)


Please take special note about what a) s25client is trying to open b) cmake tries to copy and c) what is actually there:

(master↓☠) % ll share/s25rttr/driver/video
total 0
(master↓☠) % ll share/driver/video
total 48
drwxr-xr-x  2 uqs  wheel     4 Sep  3 11:48 CMakeFiles/
drwxr-xr-x  4 uqs  wheel     6 Sep  3 11:48 GLFW/
-rw-r--r--  1 uqs  wheel  5662 Sep  3 11:48 Makefile
drwxr-xr-x  4 uqs  wheel     6 Sep  3 11:48 SDL/
drwxr-xr-x  4 uqs  wheel     6 Sep  3 11:48 WinAPI/
-rw-r--r--  1 uqs  wheel  1174 Sep  3 11:48 cmake_install.cmake
lrwxr-xr-x  1 uqs  wheel    22 Sep  3 11:48 videoSDL.so@ -> SDL/src/libvideoSDL.so


So the problem seems to be the underlying mess of symlinks pointing to itself. IIRC there's a difference in ln(1) -s semantics between Linux and *BSD when the target is an existing directory or something like that.

If I use --prefix=/tmp/doener *AND* pass -DCMAKE_INSTALL_PREFIX=${PREFIX} in the cmake.sh script, then I get a working copy under /tmp/doener just fine.

**Comment by Flow86** [comment]
the reason why I didnt use CMAKE_INSTALL_PREFIX and use PREFIX is, that CMAKE_INSTALL_PREFIX is always an absolute path, which would result in non portable pathing inside rttr

**Comment by Flamefire** [comment]
@Flow86 This is right. But we should always use absolute paths. You can always get an absolute path from a relative one and CMake might cause problems with not using CMAKE_INSTALL_PREFIX.
E.g. INSTALL() is defined like: "for relative paths, use CMAKE_INSTALL_PREFIX". Other functions are similar

@uqs It seems the postbuild event is not executed. Check the CMakelists.txt of the sdl driver: ADD_CUSTOM_COMMAND(TARGET videoSDL POST_BUILD COMMAND ln -fvs SDL/src/${SL_PREFIX}videoSDL${CMAKE_SHARED_LIBRARY_SUFFIX} ../../videoSDL${CMAKE_SHARED_LIBRARY_SUFFIX})

besides that the install is supposed to fail: LIBDIR is a relative directory (./share/s25rttr) and install is called with LIBDIR as destination which is (correctly) relative to CMAKE_INSTALL_PREFIX

So I'd suggest to remove PREFIX and replace it with CMAKE_INSTALL_PREFIX. Probably some pathes got to be adjusted. Relying on relative paths is bad practice anyway. We have CMake for everything with CURRENT_SOURCE_DIR/CURRENT_BINARY_DIR etc so relative paths can go.

**Comment by Flow86** [comment]
the problem are not the relative paths while installing, but that they will be hardcoded into the game

**Comment by Flamefire** [comment]
For those that go into header files via install etc. one can use "file(RELATIVE_PATH variable directory file)" before configuring these files. Probaly call the CMake variables like RELATIVE_RTTR_DIR (e.g.)

**Comment by uqs** [comment]
@Flow86 Hmm, post_build seems fine, that symlink is there.

The line is
ln -fvs SDL/src/${SL_PREFIX}videoSDL${CMAKE_SHARED_LIBRARY_SUFFIX} ../../videoSDL${CMAKE_SHARED_LIBRARY_SUFFIX}

and that link does exist, in build/driver/video, but s25client looks for it in s25rttr/driver/video :(

**Comment by uqs** [comment]
... aaaaand the problem is gone. I did carefully compare the tree post-build between FreeBSD and Ubuntu, saw only trivial differences, and after rm -rf build and a clean checkout, things are back to finding  their drivers. Very weird ...
