### ISSUE TITLE
Limit Framerate does not work.

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#25]
First of all: Thank you so much guys, you are doing an amazing Job!

There's one little issue I am having. Somehow the framerate limitation doesn't work. I set it to 30 frames but it still goes up to 80/90. This particularly happens if I increase the resoltuion or the size of the window.

I play on a retina MacBook with the scaled resolution of 1920.

I run the latest nightly

**Comment by MarcusSt** [comment]
Can this still be reproduced?

**Comment by Flow86** [comment]
dont know - works for me here on windows

**Comment by Spikeone** [comment]
Looks like I forgot the original post - But will close it for now as current Mac players can re-report this.
