### ISSUE TITLE
Neuem Spiel beitreten

### ISSUE THREAD

**Issue by Burton1224** [Return-To-The-Roots/s25client#251]
Wollte heute mit meinem Kollegen spielen. Jemand hatte schon online ein Spiel erstellt an dem gespielt wurde. Ich öffnete ein neues und es kam in der Liste. Doch konnte mein Kollege nicht beitretten. Immer wenn er auf mein Spiel klickte wollte das Siedler dem Spiel beitretten das von jemand anderem erstellt wurde.
Er bekam immer die Meldung seine Version sei nicht die Selbe wie die des anderen Spielers.
Wir hatten beide die selbe Version 20150903 der andere der schon ein Spiel auf hatte hatte 20150601. So konnten wir nicht onlinen gegeneinander spielen.....

**Comment by Flow86** [comment]
Hallo,

das ist klar, man kann nur mit der gleichen version spielen. d.h beide sollten immer die gleiche version verwenden. (z.b die aktuelle nightly mit "rttr.bat" gestartet, damit das update durchläuft)

**Comment by Burton1224** [comment]
Ich glaube du hast ich falsch verstanden. Mein Kollege hat 20150903 ich habe 20150903.
Eine fremde Person hatte ein Spiel offen mit 4/4 Spieler die fremde Person hat 20150601.

Ich habe ein Spiel eröffnet damit mein Kollege und ich spielen können. Er wollte meinem Spiel beitretten doch hat Siedler immer ins Spiel der fremden Person verbinden wollen. Er konnte meinem Spiel nicht beitretten obwohl er auf mein Spiel geklickt hatte.

**Comment by Flow86** [comment]
ah okay das ist natürlich was anderes. klingt nach einem fehler, das stimmt. werden wir uns ansehen. danke

**Comment by Spikeone** [comment]
Per Doppelklick oder Auswahl und verbinden klick?

**Comment by Burton1224** [comment]
Beides haben wir ausprobiert.

**Comment by Flamefire** [comment]
Im code habe ich keine Fehler gefunden, die das verursachen könnten. Hab mal einen Check eingebaut, der die einzige Möglichkeit des Fehlers eliminieren sollte. Wenn Log-Einträge über "duplicate ids" auftauchen, ist ein Fehler im Lobby-Server. Aber das joinen sollte jetzt klappen.

@Burton1224 Könnt ihr das nochmal testen?

**Comment by Flamefire** [comment]
Closing for now. Feel free to report, if this happens again
