### ISSUE TITLE
Cannot start on Windows 10 after installation

### ISSUE THREAD

**Issue by flyx** [Return-To-The-Roots/s25client#256]
I downloaded the current nightly (20150905) for Windows (64bit) and put it in my Settlers 2 Gold folder. When I try to start s25client.exe, I get the following error:

![sound-convert](https://cloud.githubusercontent.com/assets/791710/9703782/81f0e33a-548e-11e5-8e17-a140b30fbd2c.png)

This is the terminal output:

![rttr](https://cloud.githubusercontent.com/assets/791710/9703787/9208cd8c-548e-11e5-8066-34f7479c6899.png)

I then tried to download the 32-bit binary instead. It didn't work, but I didn't get the error message for sound-convert.exe. Instead, this was the terminal output:

![rttr32](https://cloud.githubusercontent.com/assets/791710/9703796/cb6cd636-548e-11e5-823c-67b0e1a18deb.png)

The file `DATA/SOUNDDAT/SOUND.LST` exists, but in lower case. Fixing the casing of folder and file name did not change anything. I made sure that the file can be opened by opening it in notepad.

**Comment by Flow86** [comment]
okay thats definitly a bug, s-c should not crash.

You can temporarily copy the "DATA\SOUNDDAT\SOUND.LST" to "C:\Users\flyx\Saved Games\Return To The Roots\LSTS\SOUND.LST", so the game should start (but the sounds are choppy then)

We'll try to fix this as fast as possible

**Comment by K4T** [comment]
I can confirm that bug. For me it appear on Windows 10 x64 and Windows 7 x86.

**Comment by Flamefire** [comment]
Found. Fix is in the works

**Comment by flyx** [comment]
If I just copy SOUND.LST like Flow86 suggested, s25client.exe crashes on loading it.

**Comment by Flamefire** [comment]
Problem will be fixed in next release (later today)
