### ISSUE TITLE
Unify folder structure

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#257]
I'd like to start a discussion why we need all that PREFIX, LIBDIR, etc. pathes in build_paths.h (and CMake) and examine if it would be possible to remove those.

Are there any reasons why we need that flexibility and cannot just create a folder structure that is consistent between all systems or at the very least fixed on a single system (so a simple ifdef in the code itself would suffice)?

This would probably avoid problems like #255 and would also make maintenance easier as it is clear, where what is put

**Comment by Flow86** [comment]
because we should support the LHS layout for linux, and we need a different one for apple

**Comment by Flamefire** [comment]
Ok, but is there any reason to use that in CMake? If we know the layouts, can't we just do that in the header(s) itself?

**Comment by Flow86** [comment]
it should be configurable if someone wants a different layout
