### ISSUE TITLE
Add documentation about shared boost libs

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#260]
A user had problems running RTTR in linux because of missing boost libs.

@Flow86 Is it possible to use static libs also for linux? Then nothing needs to be installed on the users system.

Otherwise the installation manual (and website) should be updated to tell, that boost 1.55 libs "system", "filesystem" and "iostreams are required and should be installed

**Comment by Flow86** [comment]
well I had problems building a static version of boost for 32bit linux (via cross-compiling ...), so we perhaps simply add the dependencies in the README, or deploy the libraries in our package (like some others too)

**Comment by Flamefire** [comment]
Ho serious are those? Would be great if that can be solved.
What about 64bit linux and MacOSX? If that works, we can use static libs at least there. And I'd rather add it to the readme then shipping with those cross-compiled shared libs. Every linux user should be able to install a library from the package manager ;)

**Comment by Flow86** [comment]
x64 linux is (also) static, 
apple is dynamic only (here we should ship the binaries, thats not a problem since its inside the app then)

**Comment by Flow86** [comment]
oh, I looked into the wrong path: both linux variants are dynamic and static available

**Comment by stefson** [comment]
I have a problem with this. On my system, there is boost-1.56.0 installed, and I am not willig to downgrade to 1.55.0. The result would be a broken system and incompabilities with other binary packages. It is neither slotted, so I cannot install two versions of boost at the same time (my system is  gentoo linux-x86_64). 

So, please include the needed boost libraries somehow in the precompiled tar balls.

**Comment by Flamefire** [comment]
They will be in the next release

@Flow86 Please check my PR #262

**Comment by Flow86** [comment]
should be static now

**Comment by Flow86** [comment]
okay the x86_64 linux boost static libraries seem to not compiled with -fPIC, so we get a problem here

**Comment by Flamefire** [comment]
If this is the only platform-arch that is causing problems, can you compile it manually with fPIC? Shouldn't be to hard as it is native (I guess build server is x64 linux)

**Comment by Flow86** [comment]
If I find the wrong line in that 1000 lines debian/rules, I'll do it

**Comment by Flow86** [comment]
okay works now, but we still have to add the boost dylibs to the apple package

**Comment by stefson** [comment]
x86_64 is working, thank you.

**Comment by stefson** [comment]
I am currently using the precompiled binaries. But I would like to make the code compile again on my system which could be difficult, as I am not a programmer. So my question - is there an easy way to upgrade the boost libraries? It is really a bummer that at the moment that 1.55.0 is a build dependency. May I search and find all entries of boost in the CMkefiles.txt files and replace it with 1.56.0 ; or how is supposed to work?

**Comment by Flow86** [comment]
Hi,

cmake should find newer boost versions too


see CmakeLists.txt
```
SET(Boost_ADDITIONAL_VERSIONS "1.55" "1.56" "1.57" "1.58" "1.59")
```

you have to install the "-dev" package of boost to build it yourself against your system boost version

**Comment by stefson** [comment]
well, aren't there are various lines where boost_1.55 is explicitly wanted? 

src/CMakeLists.txt has, for instance 

FIND_PACKAGE(Boost 1.55.0 COMPONENTS filesystem iostreams system REQUIRED)

**Comment by Flamefire** [comment]
the 1.55 is the MINIMUM required version. So newer versions should work fine. I even added compatibility checks (e.g. we need some headers from boost 1.58 which we supply directly but use the original headers when 1.58 or higher is found.)

**Comment by stefson** [comment]
please have a look into #270

**Comment by Flamefire** [comment]
Boost libs 1.55 are distributed with rttr now
