### ISSUE TITLE
LANG.GER is outdated

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#261]
the LANG.GER file is outdated - perhaps we should simply switch to an ini file?

**Comment by Flamefire** [comment]
I'd strongly support that. No need to use proprietary file formats for storing our data

**Comment by Flamefire** [comment]
@Flow86 I made the changes. Is there anything that needs to be done first so that the update recognizes the new file? Or will it detect it once it is in git?

**Comment by Flow86** [comment]
well, an update will not remove an existing file, so you have to test what happens if both files exist

**Comment by Flamefire** [comment]
Should work... Got no issues here

**Comment by Flow86** [comment]
ah you renamed the file completely, yes that should work

**Comment by Flow86** [comment]
you should remove the file from git then too (the lang.ger)

**Comment by Flamefire** [comment]
The file is removed from git in the above commit

**Comment by Flow86** [comment]
ah yes havent seen it :+1:

**Comment by Flamefire** [comment]
This is not closed yet. We need to update the ini file (you wrote it is outdated, I have not checked that, but just replaced the GER by the INI)

**Comment by Flamefire** [comment]
BTW: I was thinking about putting more RTTR config stuff in the ini file. E.g. the lobby servers adress and port. So we have a rttr.ini and just a section "Languages"
