### ISSUE TITLE
error while loading shared libraries: libboost_filesystem.so.1.55.0

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#265]
While trying to reproduce what went wrong in #255 I ran into a different problem on *Ubuntu 14.04.3 LTS x86_64* with ```libsdl-mixer1.2``` and ```libsdl1.2-dev``` installed. I attempted to install RTTR as follows:

```
mo@freebird-ubuntu:~/s2test$ wget http://www.siedler25.org/uploads/nightly/s25rttr_20150910-e3ca9b26d2a67c8b915947a518d8a8696798617f_linux.x86_64.tar.bz2
mo@freebird-ubuntu:~/s2test$ tar xvf s25rttr_20150910-e3ca9b26d2a67c8b915947a518d8a8696798617f_linux.x86_64.tar.bz2
mo@freebird-ubuntu:~/s2test$ cp -avr ~/s25rttr/share/s25rttr/S2 ~/s2test/s25rttr_20150910/share
mo@freebird-ubuntu:~/s2test$ cd s25rttr_20150910/
mo@freebird-ubuntu:~/s2test/s25rttr_20150910$ bash -x bin/rttr.sh
```

Where ```~/s25rttr/share/s25rttr/S2``` is the ```S2``` directory copied from the S2 installation CD.

This leads to the following output:

```
++ cd bin
++ pwd -P
+ DIR=/home/mo/s2test/s25rttr_20150910/bin
+ chmod 0755 /home/mo/s2test/s25rttr_20150910/bin/../bin/rttr.sh /home/mo/s2test/s25rttr_20150910/bin/../share/s25rttr/RTTR/s25update /home/mo/s2test/s25rttr_20150910/bin/../bin/s25client /home/mo/s2test/s25rttr_20150910/bin/../share/s25rttr/RTTR/sound-convert
+ '[' /home/mo/s25rttr/bin/../lib = '' ']'
+ export LD_LIBRARY_PATH=/home/mo/s25rttr/bin/../lib:/home/mo/s2test/s25rttr_20150910/bin/../lib
+ LD_LIBRARY_PATH=/home/mo/s25rttr/bin/../lib:/home/mo/s2test/s25rttr_20150910/bin/../lib
+ cmd=
+ noupdate=0
+ updateonly=0
+ '[' 0 -eq 0 ']'
+ '[' -f /home/mo/s2test/s25rttr_20150910/bin/../share/s25rttr/RTTR/s25update ']'
+ echo 'checking for an update ...'
checking for an update ...
+ cp /home/mo/s2test/s25rttr_20150910/bin/../share/s25rttr/RTTR/s25update /tmp/s25update.15366
+ chmod 0755 /tmp/s25update.15366
+ /tmp/s25update.15366 --verbose --dir /home/mo/s2test/s25rttr_20150910/bin/../
/tmp/s25update.15366: error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory
++ diff -q /tmp/s25update.15366 /home/mo/s2test/s25rttr_20150910/bin/../share/s25rttr/RTTR/s25update
+ '[' -z '' ']'
+ PARAM=noupdate
+ /home/mo/s2test/s25rttr_20150910/bin/../bin/rttr.sh noupdate
/home/mo/s2test/s25rttr_20150910/bin/../bin/s25client: error while loading shared libraries: libboost_filesystem.so.1.55.0: cannot open shared object file: No such file or directory
An error occured: press enter to continue

+ exit 1
```

**Comment by Flamefire** [comment]
You don't have boost installed. This is what it is telling you.
Try to redownload rttr from the web site. It has static boost so you don't need to install it

**Comment by mplatt** [comment]
I have downloaded the RTTR nightly about 10 minutes ago. The above output is the result of the steps described.

**Comment by Flamefire** [comment]
@Flow86 Can you check if the build server really uses the static libs? I assume that once it found the (shared) boost libs it does not look for any others again even when static libs are requested.

@mplatt You have 2 solutions: Install boost 1.55 (system, filesystem, iostream) or wait till the issue on the build server is resolved in an update then redownload.

**Comment by mplatt** [comment]
OK -- It would be awesome if this could be added to the install instruction if this is in fact a dependency that is meant to be installed manually. So far the only dependencies mentioned are libsdl1.2 and libsdl-mixer1.2.  Otherwise this feels like a bug.

**Comment by Flamefire** [comment]
There is already an open issue to that: #260 
I added the enhancement label, as the "bug" is already fixed (at least should be) and only the setup (build server) was not using it correctly.

**Comment by Flow86** [comment]
I reset the workspace so it should research the libraries

**Comment by Flow86** [comment]
okay the x86_64 linux boost static libraries seem to not compiled with -fPIC, so we get a problem here

**Comment by Flow86** [comment]
since this is a duplicate, I close it here
