### ISSUE TITLE
Error compiling RelWithDebInfo with VS2010

### ISSUE THREAD

**Issue by jhkl** [Return-To-The-Roots/s25client#266]
Cloned newest (8eca5927cdd406a18e5d241eb7da2072501a4c28) version into new directory, added submodules, extracted contribs, ran Cmake, compiled full project with "RelWithDebInfo". "Debug" works fine.

Output:

<pre>1>------ Erstellen gestartet: Projekt: updateversion, Konfiguration: RelWithDebInfo Win32 ------
2>------ Erstellen gestartet: Projekt: s25update, Konfiguration: RelWithDebInfo Win32 ------
1>Der Buildvorgang wurde am 13.09.2015 21:53:17 gestartet.
2>Der Buildvorgang wurde am 13.09.2015 21:53:17 gestartet.
1>InitializeBuildStatus:
1>  "Win32\RelWithDebInfo\updateversion\updateversion.unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
2>InitializeBuildStatus:
2>  Aktualisieren des Timestamps von "s25update.dir\RelWithDebInfo\s25update.unsuccessfulbuild".
2>CustomBuild:
2>  Alle Ausgaben sind aktuell.
1>CustomBuild:
1>         version: started
1>                  source directory: "D:\Ehemals-E\cleans25\s25client/"
1>                  build  directory: "D:\Ehemals-E\cleans25\s25client\build/"
1>                  build_version.h is unchanged
1>         version: finished
2>ClCompile:
2>  Alle Ausgaben sind aktuell.
1>FinalizeBuildStatus:
1>  Die Datei "Win32\RelWithDebInfo\updateversion\updateversion.unsuccessfulbuild" wird gelöscht.
1>  Aktualisieren des Timestamps von "Win32\RelWithDebInfo\updateversion\updateversion.lastbuildstate".
1>
1>Das Erstellen war erfolgreich.
1>
1>Verstrichene Zeit 00:00:00.18
2>ResourceCompile:
2>  Alle Ausgaben sind aktuell.
2>LINK : warning LNK4075: /INCREMENTAL wird aufgrund der Angabe von /OPT:ICF ignoriert.
2>LINK : fatal error C1900: Inkompatibilität zwischen "P1", Version "20100826", und "P2", Version "20081201"
2>LINK : fatal error LNK1257: Fehler bei Codegenerierung.
2>
2>Fehler beim Erstellen
2>
2>Verstrichene Zeit 00:00:00.23
3>------ Erstellen gestartet: Projekt: translations, Konfiguration: RelWithDebInfo Win32 ------
4>------ Erstellen gestartet: Projekt: s25client, Konfiguration: RelWithDebInfo Win32 ------
3>Der Buildvorgang wurde am 13.09.2015 21:53:17 gestartet.
4>Der Buildvorgang wurde am 13.09.2015 21:53:17 gestartet.
3>InitializeBuildStatus:
3>  "Win32\RelWithDebInfo\translations\translations.unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
3>FinalizeBuildStatus:
3>  Die Datei "Win32\RelWithDebInfo\translations\translations.unsuccessfulbuild" wird gelöscht.
3>  Aktualisieren des Timestamps von "Win32\RelWithDebInfo\translations\translations.lastbuildstate".
3>
3>Das Erstellen war erfolgreich.
3>
3>Verstrichene Zeit 00:00:00.11
4>InitializeBuildStatus:
4>  Aktualisieren des Timestamps von "s25client.dir\RelWithDebInfo\s25client.unsuccessfulbuild".
4>CustomBuild:
4>  Alle Ausgaben sind aktuell.
4>ClCompile:
4>  Alle Ausgaben sind aktuell.
4>ResourceCompile:
4>  Alle Ausgaben sind aktuell.
4>LINK : warning LNK4075: /INCREMENTAL wird aufgrund der Angabe von /OPT:ICF ignoriert.
4>LINK : fatal error C1900: Inkompatibilität zwischen "P1", Version "20100826", und "P2", Version "20081201"
4>LINK : fatal error LNK1257: Fehler bei Codegenerierung.
4>
4>Fehler beim Erstellen
4>
4>Verstrichene Zeit 00:00:01.65
========== Erstellen: 2 erfolgreich, Fehler bei 2, 16 aktuell, 0 übersprungen ==========
</pre>

**Comment by Flamefire** [comment]
This is really strange: https://msdn.microsoft.com/de-de/library/ks07be9f.aspx

Can you try to do a full rebuild? Or even delete everything and do a relWithDebInfo build first (no other build before) in case it tries to reuse something from the debug build. Still looks like a bug in VS or it does not like, that the output path from the builds is the same. In that case we need post-build copies.

**Comment by Flow86** [comment]
Hi,
you have to install Vs2010 SP1, otherwise it can't link to the libraries provided by us

**Comment by jhkl** [comment]
Full rebuild did not change anything. 

Again: "Debug" works fine. What is the difference?

I have "Microsoft Visual Studio 2010 Version 10.0.40219.1 SP1Rel".
Sounds like SP1.

**Comment by Flamefire** [comment]
Seems to be a VS bug. My VS2012 is working fine with Debug and RelWithDebInfo. Try CMAKE_VERBOSE_MAKEFILE=1 (use e.g. the graphical cmake to set) to see, what it is actually doing. Looks to me like it is using an old VS2008 compiler somewhere.

**Comment by Flamefire** [comment]
Can you retry this with a fresh checkout of s2 and close if it works?

**Comment by jhkl** [comment]
Checked out 7c19a005124b22b07bd3573956781a0530254107 into a clean directory. Still the same error.

<pre>1>------ Erstellen gestartet: Projekt: updateversion, Konfiguration: RelWithDebInfo Win32 ------
1>Der Buildvorgang wurde am 14.11.2015 21:21:54 gestartet.
2>------ Erstellen gestartet: Projekt: translations, Konfiguration: RelWithDebInfo Win32 ------
1>InitializeBuildStatus:
1>  "Win32\RelWithDebInfo\updateversion\updateversion.unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
1>CustomBuild:
1>         version: started
1>                  source directory: "D:\Ehemals-E\cleans25\s25client/"
1>                  build  directory: "D:\Ehemals-E\cleans25\s25client\build/"
1>                  build_version_defines.h is unchanged
1>         version: finished
1>FinalizeBuildStatus:
1>  Die Datei "Win32\RelWithDebInfo\updateversion\updateversion.unsuccessfulbuild" wird gelöscht.
1>  Aktualisieren des Timestamps von "Win32\RelWithDebInfo\updateversion\updateversion.lastbuildstate".
1>
1>Das Erstellen war erfolgreich.
1>
1>Verstrichene Zeit 00:00:00.16
2>Der Buildvorgang wurde am 14.11.2015 21:21:54 gestartet.
2>InitializeBuildStatus:
2>  "Win32\RelWithDebInfo\translations\translations.unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
2>FinalizeBuildStatus:
2>  Die Datei "Win32\RelWithDebInfo\translations\translations.unsuccessfulbuild" wird gelöscht.
2>  Aktualisieren des Timestamps von "Win32\RelWithDebInfo\translations\translations.lastbuildstate".
2>
2>Das Erstellen war erfolgreich.
2>
2>Verstrichene Zeit 00:00:00.09
3>------ Erstellen gestartet: Projekt: s25client, Konfiguration: RelWithDebInfo Win32 ------
3>Der Buildvorgang wurde am 14.11.2015 21:21:54 gestartet.
3>InitializeBuildStatus:
3>  Aktualisieren des Timestamps von "s25client.dir\RelWithDebInfo\s25client.unsuccessfulbuild".
3>PreBuildEvent:
3>         version: started
3>                  source directory: "D:\Ehemals-E\cleans25\s25client/"
3>                  build  directory: "D:\Ehemals-E\cleans25\s25client\build/"
3>                  build_version_defines.h is unchanged
3>         version: finished
3>CustomBuild:
3>  Alle Ausgaben sind aktuell.
4>------ Erstellen gestartet: Projekt: s25update, Konfiguration: RelWithDebInfo Win32 ------
4>Der Buildvorgang wurde am 14.11.2015 21:21:54 gestartet.
4>InitializeBuildStatus:
4>  Aktualisieren des Timestamps von "s25update.dir\RelWithDebInfo\s25update.unsuccessfulbuild".
4>CustomBuild:
4>  Alle Ausgaben sind aktuell.
4>ClCompile:
4>  Alle Ausgaben sind aktuell.
4>ResourceCompile:
4>  Alle Ausgaben sind aktuell.
4>LINK : warning LNK4075: /INCREMENTAL wird aufgrund der Angabe von /OPT:ICF ignoriert.
4>LINK : fatal error C1900: Inkompatibilität zwischen "P1", Version "20100826", und "P2", Version "20081201"
4>LINK : fatal error LNK1257: Fehler bei Codegenerierung.
4>
4>Fehler beim Erstellen
4>
4>Verstrichene Zeit 00:00:00.18
3>ClCompile:
3>  Alle Ausgaben sind aktuell.
3>ResourceCompile:
3>  Alle Ausgaben sind aktuell.
3>LINK : warning LNK4075: /INCREMENTAL wird aufgrund der Angabe von /OPT:ICF ignoriert.
3>LINK : fatal error C1900: Inkompatibilität zwischen "P1", Version "20100826", und "P2", Version "20081201"
3>LINK : fatal error LNK1257: Fehler bei Codegenerierung.
3>
3>Fehler beim Erstellen
3>
3>Verstrichene Zeit 00:00:01.64
5>------ Erstellen übersprungen: Projekt: INSTALL, Konfiguration: RelWithDebInfo Win32 ------
5>Für diese Projektmappenkonfiguration wurde kein zu erstellendes Projekt ausgewählt. 
========== Erstellen: 2 erfolgreich, Fehler bei 2, 16 aktuell, 1 übersprungen ==========
</pre>

**Comment by Flamefire** [comment]
Strange... Can you check this: http://stackoverflow.com/questions/20754451/why-visual-studio-generates-two-versions-of-obj

**Comment by jhkl** [comment]
I switched to Visual Studio 2015. I would suggest closing this as no one else seems to use such old stuff. ;)
Reopen if you think otherwise.
