### ISSUE TITLE
Multiplayer fault

### ISSUE THREAD

**Issue by Burton1224** [Return-To-The-Roots/s25client#267]
Not possible to go in to the Internet-Lobby.
Mehrspieler ---> click
Internetlobby ---> click
Mit Internet Lobby verbinden
Verbinde... ---> click
Warten auf Antwort...steht da.
Warte schon sehr sehr lange geht nichts.

Gruss

**Comment by Flow86** [comment]
funktioniert bei mir, habe aber vorsichtshalber mal den lobbyserver neugestartet. geht es nun?

**Comment by Burton1224** [comment]
Ja bestend Dank geht jetzt
