### ISSUE TITLE
stepping into a massive amount of compile errors with boost_1.56.0 

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#270]
I am playing around with the source code from the master branch. Therefore, I tried different versions of boost than 1.55.0. The results are rather unpleasant. The build.log is too long, so I uploaded it here in the hope that it might be helpfull. 

https://bpaste.net/show/993321c6bd07

for your information, this is how my boost-1.56.0 is configured. 

 * abi_x86_64.amd64: running multilib-minimal_abi_src_compile
b2 --user-config=/var/tmp/portage/dev-libs/boost-1.56.0-r1/work/boost_1_56_0-abi_x86_64.amd64/user-config.jam gentoorelease -j3 -q -d+2 -sICU_PATH=/usr --without-mpi --without-context --without-coroutine pch=off --boost-build=/usr/share/boost-build --prefix="/var/tmp/portage/dev-libs/boost-1.56.0-r1/image/usr" --layout=system threading=multi link=shared,static --without-python

**Comment by Flow86** [comment]
thats a strange cmake version you use

**Comment by stefson** [comment]
do you think you could explain yourself a bit further? this is not really helpfull.

**Comment by Flow86** [comment]
try to run cmake with "-Wno-dev" and repost - it seems that gentoo sets some strange things in there

**Comment by Flamefire** [comment]
@stefson There are a lot of CMake warnings. Looks like you use a rather old CMake version, is this possible? Which one are you using?

About boost: We use headers from boost 1.58 for compatibility of some stuff. I checked that it works with boost 1.55 and 1.58 by conditionally using the compatibility stuff or the original ones. Check the contrib/backport folder. What you can try is creating a similar folder for 1.56 by removing the existing one, check which includes are missing and try to adjust the layout in a way, that it works for boost 1.56. If you can't get it to work, tell me and I'll have a look. If you can: Add a commit. Best way: Rename the current backport/boost_1.58 to backport/boost_1.55, add yours as backport/boost_1.56 and make CMake use either one depending on the detected version.

**Comment by stefson** [comment]
I am using cmake-3.2.2 , so it is rather up to date. As far as I understand the build system checks for boost-1.55 and uses it, but if boost is newer than 1.55 it falls back to the contribed 1.58? 

And yes, I am not a programmer at all. Just hacking some ebuilds here, so thank you for having a look into it :)

**Comment by Flamefire** [comment]
Ok, then it's to new and we need to set that policy...

Not quite. The build system checks for ANY boost >= 1.55. If boost < 1.58 is found, some headers copied from 1.58 are used (only those that are really required) Goal was to provide only that much as absolutely required.

**Comment by stefson** [comment]
could you tell me which cmake version you are using then? it is not a big deal for me to downgrade it.

**Comment by Flamefire** [comment]
No need to. These are only warnings and I'll fix them this evening.

**Comment by stefson** [comment]
ok, cool :) 

just for the record, could you tell me which c-flags and/or c++-flags you are using for the boost libraries on your build system? the reason for this question is that I had build failures with boost-1.55 and by appending -fPIC to boost, s25rttr compiles just fine.

**Comment by Flamefire** [comment]
That is something @Flow86 must answer.
-fPIC is required due to use in dynamically loaded libraries.
