### ISSUE TITLE
Strange texture transitions 

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#274]
I just noticed that somehow RttR has some quite strange texture problems lately:
![s25client 2015-09-23 22-04-50-92](https://cloud.githubusercontent.com/assets/1276342/10057224/6c9858c4-623f-11e5-8b48-818b0dc5e727.png)
![s25client 2015-09-23 22-04-57-10](https://cloud.githubusercontent.com/assets/1276342/10057226/6cd01700-623f-11e5-84d2-95a352e11c3c.png)
![s25client 2015-09-23 22-05-02-37](https://cloud.githubusercontent.com/assets/1276342/10057228/6de539d6-623f-11e5-8083-1de5a5cf6ff7.png)
![s25client 2015-09-23 22-05-05-09](https://cloud.githubusercontent.com/assets/1276342/10057229/6eed5c6e-623f-11e5-932c-c4e76164ad04.png)

When moving the mouse or any window over sand the edges seem to break, but just moving the screen around (by holding right mouse button) fixes the problem quite well.

**Comment by Flamefire** [comment]
Does this only apply to sand? Can you check if any other texture is affected as well? And only inside the sand or also on the edge to other textures?

**Comment by Spikeone** [comment]
Flower Meadow,
Swamp
Snow
Desert

![s25client 2015-09-24 18-34-42-20](https://cloud.githubusercontent.com/assets/1276342/10079644/7d1fc8ce-62eb-11e5-8aa8-ce7672b41eab.png)

VBO: On
WinAPI
OT On

**Comment by Spikeone** [comment]
Caused by custom texture which seems to be bugged somehow...
