### ISSUE TITLE
Metalworker/Iron Founder is buggy - Assertion failed 

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#276]
the game crashes with the following output

s25client: /var/tmp/portage/games-strategy/s25rttr-9999-r1/work/s25rttr-9999/src/figures/nofMetalworker.cpp:223: virtual void nofMetalworker::HandleDerivedEvent(unsigned int): Assertion `state == STATE_WAITINGFORWARES_OR_PRODUCTIONSTOPPED' failed.
[New Thread 0x7ffff0297700 (LWP 20113)]

Program received signal SIGABRT, Aborted.
0x00007ffff62d6e67 in raise () from /lib64/libc.so.6

save game : https://www.sendspace.com/file/cdv6zy
replay: https://www.sendspace.com/file/1augsw

the crash is reproducable at #33611 

It seems as af if the red cpu player is causing all the trouble. First of all, there is no Iron in his warehouse anymore. So for a strange reason when the Iron founder is out of coal for melting but still has iron ore, and eventually the Metalworker requests Iron from the Iron founder, the game crashes. Could this be the possible reason for crashing the game?

**Comment by Flamefire** [comment]
Stefson:
> I guess s25rttr is broken with system-boost-1.56.0 ; the bug is not occuring when upgrading to system-boost-1.58.0

**Comment by stefson** [comment]
against which boost are you linking for the nightly binaries on the build server?

**Comment by Flamefire** [comment]
1.55

**Comment by stefson** [comment]
this is really strange. 

I compiled in a chroot against system-boost-1.55.0 and provided the three needed .so files from there to my main system. But the bug is still there and exactly the same, 100% reproduceable. 

If using the nightly-binaries to load the save game nothing happens. No crash, no nothing.

**Comment by jhkl** [comment]
Another replay with probably the same crash: https://dl.dropboxusercontent.com/u/1589203/rttr/crash_by_assertion.rpl
Appears at the end of the replay (~50000 gfs). Jump until the end and continue the game (P) -> instant crash

**Comment by stefson** [comment]
Hit on this again while testing #280 

s25client: /var/tmp/portage/games-strategy/s25rttr-9999-r1/work/s25rttr-9999/src/figures/nofMetalworker.cpp:229: virtual void nofMetalworker::HandleDerivedEvent(unsigned int): Assertion `state == STATE_WAITINGFORWARES_OR_PRODUCTIONSTOPPED' failed.
[New Thread 0x7fffeffa2700 (LWP 9881)]

Program received signal SIGABRT, Aborted.
0x00007ffff62d6e67 in raise () from /lib64/libc.so.6

replay: https://www.sendspace.com/file/cp704z

**Comment by Flamefire** [comment]
Damn. I was sure this is fixed... I'll try to find what was going wrong.

**Comment by Flamefire** [comment]
Sorry but I cannot reproduce this with the given replay. It happens neither on windows nor on linux with the current build and would actually surprise me if this still happens. Can you try a full recompile and check if it is still happening?

**Comment by stefson** [comment]
Actually I am cross checking with the nightly binaries before reporting anything here. I am at 73aa18e8d5d5e9efba220e13c1d46b580b237c77 with the binaries and the self compiled as well. 

Steps to reproduce are: load the replay, fast forward till the end at #52937 , press play > instant crash. This goes for both versions in linux/amd64 

Though I will try to recompile, takes 10 Minutes.

**Comment by stefson** [comment]
meanwhile the backtrace from the nightly binaries: https://bpaste.net/show/29584a0ea58a

**Comment by Flamefire** [comment]
Ok got it too now. Thanks :)

**Comment by stefson** [comment]
you're welcome! :-)
