### ISSUE TITLE
RttR Crashs after quitting

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#277]
Everytime I quit RttR now the game gives me a message "RttR Crashed would you like to send... "

Latest rev
Win7 x64 Ultimate

**Comment by stefson** [comment]
I just stepped into this with system-boost-1.58 - still testing with 1.56 

crash from a replay https://bpaste.net/show/9e544ebf9370
crash from a normal game https://bpaste.net/show/c0ccef3b1051

**Comment by Flamefire** [comment]
Thanks. This helps a lot:

> #8  0x00007ffff62cabad in vfprintf () from /lib64/libc.so.6
> #9  0x00007ffff637a4cb in __vfprintf_chk () from /lib64/libc.so.6
> #10 0x00000000007a82fa in Log::vwrite(char const*, __va_list_tag*) ()
> #11 0x00000000007a8375 in Log::lvprintf(char const*, __va_list_tag*) ()
> #12 0x00000000007a8407 in Log::lprintf(char const*, ...) ()
> #13 0x000000000059dce9 in GameClient::Stop() ()

I'd really would weed out all these *printf functions as they easily cause problems and worse...

**Comment by stefson** [comment]
system-boost-1.56 is not affected. but the crash only occurs when using the [x] to close the game or replay while running - not when going through the menus (you know what I mean?)

**Comment by stefson** [comment]
system-boost-1.55 is affected, errors are slightly different. 

game crash log https://bpaste.net/show/038d1300bb69
replay crash log https://bpaste.net/show/6d42003a4d2b

**Comment by Flow86** [comment]
propably a bug inside the Logger, I will provide a better logger soon, I already have something better in mind

**Comment by stefson** [comment]
uhm, which directory is the logging directory and where is it supposed to be found at? (Linux x64 multilib)

**Comment by Flow86** [comment]
~/.s25rttr/LOGS

**Comment by stefson** [comment]
I have read + write access to it. So this not the problem :)

**Comment by Flamefire** [comment]
Found the problem: The Log singleton is freed before the client is freed. This causes access to invalid values...

**Comment by Flow86** [comment]
how come that the singleton is freed before the client O.o

**Comment by Flamefire** [comment]
Better question: How come the client was freed before the log?
Both are singletons. Their creation and therefore destruction order are not specified. We should certainly avoid using them. I'm currently implementing a dead-reference check for the singletons...
