### ISSUE TITLE
Assertion `soldier_count > 0' failed

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#280]
the game crashes with the following output

s25client: /var/tmp/portage/games-strategy/s25rttr-9999-r1/work/s25rttr-9999/src/GameClientPlayer.cpp:1424: void GameClientPlayer::NewSoldierAvailable(const unsigned int&): Assertion `soldier_count > 0' failed.
[New Thread 0x7ffff0297700 (LWP 4766)]

Program received signal SIGABRT, Aborted.
0x00007ffff62d6e67 in raise () from /lib64/libc.so.6

replay: https://www.sendspace.com/file/zj26cj

**Comment by stefson** [comment]
I'm kind of sorry, but I played the same map and still get a crash as before. 
I am at 88f67b935fae89fd39ea08c85c681e305299a1fc , the fix should be included. 

s25client: /var/tmp/portage/games-strategy/s25rttr-9999-r1/work/s25rttr-9999/src/GameClientPlayer.cpp:1424: void GameClientPlayer::NewSoldiersAvailable(const unsigned int&): Assertion `soldier_count > 0' failed.
[New Thread 0x7fffeffa2700 (LWP 9210)]

Program received signal SIGABRT, Aborted.
0x00007ffff62d6e67 in raise () from /lib64/libc.so.6

replay: https://www.sendspace.com/file/6q2jjj

it seems as if one of the soldiers of the red cpu player is about to enter the harbour warehouse at the point where the crash occurs.

**Comment by Flamefire** [comment]
Intresting... Thanks for the replay, will look on this again.
