### ISSUE TITLE
AI after loading not  allied anymore

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#286]
Hi!
After loading a game, it seems that the AI (didn’t check with humans, maybe the same) are not allied anymore. I did not have teams locked (if that would have helped I don’t know). But for sure, before loading everything was o.k. After loading one AI immediately started attacking the other one.
Regards
David 
![einstellungen](https://cloud.githubusercontent.com/assets/14259828/10386649/47cd77aa-6e5a-11e5-8174-611a73bd4aee.PNG)
Version: Latest nightly (20151004-b1144f9) 

Savegame:
https://fil.email/1gRKfb

**Comment by Flamefire** [comment]
Thanks for reporting. Bug is found and fix will be released later today.
