### ISSUE TITLE
Rework charburner graphics

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#288]
The charburner building overlaps the adjacent road/worker on near roads.

- [x] Building graphics: 5/5 (summer)
- [x] Building graphics: 5/5 (winter)
- [x] Building shadows: 5/5
- [x] Building doors: 5/5 (summer)
- [x] Building doors: 5/5 (winter)
- [x] Building scaffolding: 5/5
- [x] Building scaffolding shadows: 5/5
- [x] Building icons: 5/5
- [x] Recheck building positions: 5/5
- [x] Recheck stop sign positions: 5/5 (R: X+8,Y-12, B: X+4,Y-4, N: X+3,X+3, J: X-21, Y-5)
- [x] Recheck smoke positions: 5/5 (N: X+5,Y-5 J: X+1,Y-2)
- [x] Recheck enter building positions: 4/5 (V: +3 distance J: +2 distance)

Buildings old - new
![oldnew](https://cloud.githubusercontent.com/assets/1276342/14941587/f8c0cef8-0fa0-11e6-8be4-753bc0842530.png)

**Comment by Flamefire** [comment]
Draft from @Spikeone : https://img5.picload.org/image/woipgdl/17.rle.nx61.ny61_03.png

**Comment by Spikeone** [comment]
I think I'm going to remove that charcoal... pile and add a small fence, that pile looks childish. Going to replace Romans first, add them for testing and if everything is fine I'm going to redraw other nations.

**Comment by Spikeone** [comment]
so, thats the new roaman version:
![nechar](https://cloud.githubusercontent.com/assets/1276342/13199652/ae25715c-d82b-11e5-88a9-8481651e24b9.png)

**Comment by Spikeone** [comment]
http://www.rfmonline.de/rttr/spike/charburner.rar

finished graphics packed into charburner.lst - I unpacked them and had no "black color" bug (out of palette). 

Please note: The positional changes are meant for a normal coordiante system (guess you just have to multiply x by -1).

**Comment by Spikeone** [comment]
As Maqs suggested I tried to change thoses constants on my own, yet I failed either installing boost correctly or using CMake.

I ran into a couple of thoses errors:

`Make Error at CMakeLists.txt:325 (ADD_SUBDIRECTORY):
  The source directory

    E:/s25client/version

  does not contain a CMakeLists.txt file.`

As well as this error:

`Unable to find the requested Boost libraries.

  Boost version: 1.61.0

  Boost include path: C:/Users/Spike/Desktop/boost_1_61_0/include/boost-1_61

  Could not find the following static Boost libraries:

          boost_filesystem
          boost_system

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  driver/audio/SDL/src/CMakeLists.txt:9 (FIND_PACKAGE)`

I just used the tutorial on our frontpage and added the BOOST_ROOT entry when cmake told me, that it couldn't find boost anyway.

**Comment by Spikeone** [comment]
fixed by 6f8d5146cfdfcd85a1504d79c9e5fc0bac8ad3cd

**Comment by Flamefire** [comment]
@Spikeone Found your compilation/CMake issues?
For reference: "No CMakeLists.txt found" -> Execute `git submodule update --init` as submodules are not initialized (folder is empty)
Boost needs to be compiled first. See the boost docu (basically: `bootstrap.bat && b2.exe`)

**Comment by MarcusSt** [comment]
Yes, all up and running on his computer now.

**Comment by Spikeone** [comment]
* for now
