### ISSUE TITLE
Connection Failed DirIP/Lobby

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#29]
I've been trying to play S2 RTTR over Direct IP and Network Lobby with my girlfriend and we just get 'Connection Failed!' errors. I don't have access to our router at the moment so I can't see if 3665 is open. I suspect the problem is that we are sharing the same Internet connection, (she's at my house on her laptop, I'm on my desktop) and that's maybe causing complications?

Do you think that might be the case? Is there any hope of LAN play on the horizon?

FloSoft (flosoft) wrote on 2011-07-31: Re: [Bug 818703] [NEW] Connection Failed DirIP/Lobby	#1
Hi,

if you're in the same LAN, you should use your lan-ip to connect to -
connection via lobby won't work - most routers dont implement the
forwarding correctly :(

**Comment by MarcusSt** [comment]
From what I see, this is not a problem with RTTR but with port forwarding.
