### ISSUE TITLE
Need Wait-for-Author label

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#292]
@Flow86 We need a label to indicate that an issue/PR is not yet complete and one should wait for the author to implement suggested changes or provide additional information so e.g. a PR is not accidentally merged.

**Comment by Flow86** [comment]
"incomplete"

**Comment by Flamefire** [comment]
Thanks. But I'd rather have it called something like wait-for-author as e.g. in a PR "incomplete" sounds a bit rude. Don't want to scare of new contributors. ;)
