### ISSUE TITLE
Unable to find the requested Boost libraries

### ISSUE THREAD

**Issue by seb321** [Return-To-The-Roots/s25client#293]
Hi,
(sorry for my English),
I'm linux newbie and i don't know how to build a RTTR. I'm a using instruction, but i got errors.

console:

seb321@seb321-K54HR:~/s25client$ cd build/
seb321@seb321-K54HR:~/s25client/build$ sudo ./cmake.sh --prefix=.
[sudo] password for seb321: 
Directory 'S2' missing!
Direct debugging from this directory will not work then!
Setting Path-Prefix to "."
Setting Binary Dir to "./bin"
Setting Data Dir to "./share/s25rttr"
Setting Library Dir to "./share/s25rttr"
Disabling build of ""
Activating release build
Running "cmake -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX=  -DPREFIX=. -DBINDIR=./bin -DDATADIR=./share/s25rttr -DLIBDIR=./share/s25rttr -DCMAKE_BUILD_TYPE=Release './..'"
-- Configuring for native compiling to Linux-3.13.0-61-generic on x86_64
-- Using platform config cmake/linux.cmake
-- Linking against boost static libraries
-- Boost version: 1.55.0
-- Boost version smaller than 1.56 detected. Using backport 1.55-1.56
-- Boost version smaller than 1.58 detected. Using backport 1.56-1.58
-- Performing Test CXX_OVERRIDE_OK
-- Performing Test CXX_OVERRIDE_OK - Failed
-- Performing Test CXX_OVERRIDE_FAIL
-- Performing Test CXX_OVERRIDE_FAIL - Failed
-- Boost version: 1.55.0
-- Boost version: 1.55.0
-- Found SDL: /usr/lib/x86_64-linux-gnu/libSDLmain.a;/usr/lib/x86_64-linux-gnu/libSDL.so;-lpthread
-- Found SDL: /usr/lib/x86_64-linux-gnu/libSDLmain.a;/usr/lib/x86_64-linux-gnu/libSDL.so;-lpthread
CMake Error at /usr/share/cmake-3.0/Modules/FindBoost.cmake:1199 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_filesystem
          boost_system

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  driver/audio/SDL/src/CMakeLists.txt:9 (FIND_PACKAGE)

-- Found SDL_mixer: /usr/lib/x86_64-linux-gnu/libSDL_mixer.so
-- Found Iconv: /usr/lib/x86_64-linux-gnu/libc.so
-- Boost version: 1.55.0
CMake Error at /usr/share/cmake-3.0/Modules/FindBoost.cmake:1199 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_system
          boost_filesystem

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  libutil/src/CMakeLists.txt:1 (FIND_PACKAGE)

CMake Error at /usr/share/cmake-3.0/Modules/FindBoost.cmake:1199 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path: /usr/include

  Could not find the following static Boost libraries:

          boost_iostreams
          boost_system
          boost_filesystem

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  s-c/src/CMakeLists.txt:4 (FIND_PACKAGE)

CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindCURL.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  s25update/src/CMakeLists.txt:2 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/seb321/s25client/build/CMakeFiles/CMakeOutput.log".
See also "/home/seb321/s25client/build/CMakeFiles/CMakeError.log".
An error occured - please check above!
seb321@seb321-K54HR:~/s25client/build$ 

Help!

**Comment by Flamefire** [comment]
Try to install curl and libboost through your package manager and check if you have the boost libs in your path (probably /usr/lib or /usr/lib64)
Maybe you also have only the dynamic boost libs. So after running the (failed) cmake.sh open cmake-gui or ccmake in the build folder and look for "USE_STATIC_BOOST" and change that to disabled (checkbox in the gui) Then press configure and generate again.

Besides that: Don't run that cmake command with sudo. This is almost always a bad idea.

**Comment by seb321** [comment]
I have curl and libboost(1.55-all-dev) installed. Boost libs are in /usr/include. Disable USE_STATIC_BOOST don't change anything.

**Comment by Flamefire** [comment]
You need to look for the libraries, not the headers. These have the *.a or .so extension in linux

**Comment by seb321** [comment]
Ok ill search.

**Comment by seb321** [comment]
I found:
/usr/lib/x86_64-linux-gnu/libboost_random.a
/usr/lib/x86_64-linux-gnu/libboost_random.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_log.a
/usr/lib/x86_64-linux-gnu/libboost_wserialization.a
/usr/lib/x86_64-linux-gnu/libboost_chrono.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99l.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_mpi_python.so
/usr/lib/x86_64-linux-gnu/libboost_math_tr1f.a
/usr/lib/x86_64-linux-gnu/libboost_mpi_python-py33.a
/usr/lib/x86_64-linux-gnu/libboost_python-py34.so
/usr/lib/x86_64-linux-gnu/libboost_mpi_python-py34.a
/usr/lib/x86_64-linux-gnu/libboost_python-py27.a
/usr/lib/x86_64-linux-gnu/libboost_graph.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_timer.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_math_tr1.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_signals.so
/usr/lib/x86_64-linux-gnu/libboost_python-py34.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_date_time.so
/usr/lib/x86_64-linux-gnu/libboost_system.a
/usr/lib/x86_64-linux-gnu/libboost_math_tr1l.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_graph.a
/usr/lib/x86_64-linux-gnu/libboost_random.so
/usr/lib/x86_64-linux-gnu/libboost_python.so
/usr/lib/x86_64-linux-gnu/libboost_wave.so
/usr/lib/x86_64-linux-gnu/libboost_log_setup.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_math_tr1f.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_iostreams.a
/usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_atomic.so
/usr/lib/x86_64-linux-gnu/libboost_mpi.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_timer.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99f.so
/usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_filesystem.so
/usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_program_options.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99l.so
/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.a
/usr/lib/x86_64-linux-gnu/libboost_python-py33.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_signals.a
/usr/lib/x86_64-linux-gnu/libboost_mpi_python-py34.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_graph_parallel.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_mpi_python-py27.so
/usr/lib/x86_64-linux-gnu/libboost_exception.a
/usr/lib/x86_64-linux-gnu/libboost_chrono.a
/usr/lib/x86_64-linux-gnu/libboost_python-py33.a
/usr/lib/x86_64-linux-gnu/libboost_log_setup.a
/usr/lib/x86_64-linux-gnu/libboost_system.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_regex.so
/usr/lib/x86_64-linux-gnu/libboost_filesystem.a
/usr/lib/x86_64-linux-gnu/libboost_graph_parallel.so
/usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_mpi_python-py27.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so
/usr/lib/x86_64-linux-gnu/libboost_wave.a
/usr/lib/x86_64-linux-gnu/libboost_thread.a
/usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_graph_parallel.a
/usr/lib/x86_64-linux-gnu/libboost_math_c99f.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_python.a
/usr/lib/x86_64-linux-gnu/libboost_regex.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_log.so
/usr/lib/x86_64-linux-gnu/libboost_test_exec_monitor.a
/usr/lib/x86_64-linux-gnu/libboost_mpi.a
/usr/lib/x86_64-linux-gnu/libboost_math_c99l.a
/usr/lib/x86_64-linux-gnu/libboost_python-py33.so
/usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99.so
/usr/lib/x86_64-linux-gnu/libboost_signals.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_math_c99.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_mpi.so
/usr/lib/x86_64-linux-gnu/libboost_locale.so
/usr/lib/x86_64-linux-gnu/libboost_context.a
/usr/lib/x86_64-linux-gnu/libboost_timer.a
/usr/lib/x86_64-linux-gnu/libboost_locale.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.a
/usr/lib/x86_64-linux-gnu/libboost_wserialization.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_serialization.a
/usr/lib/x86_64-linux-gnu/libboost_math_tr1f.so
/usr/lib/x86_64-linux-gnu/libboost_mpi_python-py34.so
/usr/lib/x86_64-linux-gnu/libboost_context.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_mpi_python-py33.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_math_tr1l.so
/usr/lib/x86_64-linux-gnu/libboost_context.so
/usr/lib/x86_64-linux-gnu/libboost_program_options.a
/usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_math_tr1l.a
/usr/lib/x86_64-linux-gnu/libboost_python-py34.a
/usr/lib/x86_64-linux-gnu/libboost_wave.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_regex.a
/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_graph.so
/usr/lib/x86_64-linux-gnu/libboost_math_c99.a
/usr/lib/x86_64-linux-gnu/libboost_math_c99f.a
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so
/usr/lib/x86_64-linux-gnu/libboost_mpi_python-py33.so
/usr/lib/x86_64-linux-gnu/libboost_wserialization.so
/usr/lib/x86_64-linux-gnu/libboost_atomic.a
/usr/lib/x86_64-linux-gnu/libboost_math_tr1.so
/usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_date_time.a
/usr/lib/x86_64-linux-gnu/libboost_log.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_regex.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_locale.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_thread.so
/usr/lib/x86_64-linux-gnu/libboost_system.so
/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so
/usr/lib/x86_64-linux-gnu/libboost_mpi_python-py27.a
/usr/lib/x86_64-linux-gnu/libboost_log_setup.so
/usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.54.0
/usr/lib/x86_64-linux-gnu/libboost_math_tr1.a
/usr/lib/x86_64-linux-gnu/libboost_serialization.so
/usr/lib/x86_64-linux-gnu/libboost_mpi_python.a
/usr/lib/x86_64-linux-gnu/libboost_locale.a
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0
/usr/lib/x86_64-linux-gnu/libboost_coroutine.a
/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.54.0

**Comment by Flamefire** [comment]
You need to add `-DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu` to the cmake.sh call. Probably executing `export CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu` before calling cmake would also work

**Comment by seb321** [comment]
Thanks,
it's working , but

I got error with curl:

>CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindCURL.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
 s25update/src/CMakeLists.txt:2 (FIND_PACKAGE)


So i installed libcurl4-gnutls-dev and now "could not find BZip2"(i have 1.0.6-5 installed)

>Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.35.0") 
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindBZip2.cmake:54 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  s25update/src/CMakeLists.txt:3 (FIND_PACKAGE)

Help!
