### ISSUE TITLE
RttR still crashs after leaving

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#294]
This time not a "RttR has crashed do you want to..." window appears just the windows message "s25client.exe doesn't work anymore".

Last message in the cmd:
Saeubere Texturspeicher: fertig (nach 0ms)
terminate called after throwing an instance of 'std::runtime_error'
 what(): Access to a dead singleton detected!

r2b2871e
Win7 x64

**Comment by Flamefire** [comment]
Thats my dead singleton check that kicks in. Otherwise the game would to unpredictable things. Can anyone reproduce this in linux and/or provide a backtrace so we can see which singleton this is?

**Comment by Spikeone** [comment]
well, if you give me the command to update my local version to the current version (and then using cmake to create a msvc13 project) I could test it further.

**Comment by Spikeone** [comment]
Problem was caused by replacing the sdl.dll with one provided by the rttr editor.
