### ISSUE TITLE
Lobby games impossible

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#295]
Currently it's somehow nearly impossible to open a game by internetlobby players just randomly disconnect before the game starts.
Flamefire wrote he could reproduce the problem and Ping is not the problem.

**Comment by Flamefire** [comment]
I fixed that yesterday. The first time a player tried to join a game in the lobby he was disconnected due to an uninitialized variable. Trying again without closing the game solved that but with the fix from yesterday this should not be an issue anymore. Can you confirm that?

**Comment by Spikeone** [comment]
"Trying again without closing the game solved that"
well, this wasnt the case yesterday - but next time I play only I'll check if its working again

**Comment by Flamefire** [comment]
Fixed
