### ISSUE TITLE
Can't run on Mac

### ISSUE THREAD

**Issue by byr1al** [Return-To-The-Roots/s25client#299]
I'm getting the following error on a Mac running Yosemite 10.10.5:

```
DBH$ /tmp/rttr.command
dyld: Library not loaded: libboost_system.dylib
  Referenced from: /Users/DBH/Desktop/./s25client.app/Contents/MacOS/share/s25rttr/RTTR/s25update
  Reason: image not found
/Users/DBH/Desktop/s25client.app/Contents/MacOS/rttr.command: line 57:  5115 Trace/BPT trap: 5       ./s25client.app/Contents/MacOS/share/s25rttr/RTTR/s25update -d $PWD
lade "/Users/DBH/Library/Application Support/Return To The Roots/CONFIG.INI": fertig (0ms)
searching for drivers in ./share/s25rttr/driver/video/*.dylib
0 video drivers found!
Video driver couldn't be loaded!


ERROR: Das Spiel konnte nicht gestartet werden
/Users/DBH/Desktop/s25client.app/Contents/MacOS/rttr.command: line 61:  5117 Abort trap: 6           ./bin/s25client
```

As far as I can understand the code above, there are missing video drivers. But when I check the video driver folder, there is one file - libvideoSDL.dylib.

The version of the app is 0.8.1-9016 (universal)

**Comment by Spikeone** [comment]
Does this also happen with the latest nightly builds?

**Comment by byr1al** [comment]
I initially tried with the nightly version - when I'm using that one, the game can't even start the terminal. I just get this message from Finder:
![skaermbillede 2015-10-24 kl 09 06 55](https://cloud.githubusercontent.com/assets/5563022/10709433/9c77e2a6-7a2e-11e5-966d-91705803dd18.png)
The text roughly translates to: "The program 's25client' cannot be opened"

**Comment by KalteWoschtsupp** [comment]
Ran into the same Problem myself. Working on a Mac with OSX 10.11 El Capitan. First tried the stable 0.8.1 got the same Error. Tried again with starting the 20151022 and 20151023 nightlys. Both wont neither start from the app or the s25client file in the containers. As I said, same Problem as byr1al.

**Comment by Flamefire** [comment]
Does your OSX give any further information on that? A "cannot be opened" does not really help in finding the cause...
The error you showed suggests that the boost-libraries are missing. You can try to install them via the package manager.

@Flow86 Any ideas?

**Comment by Flow86** [comment]
hmm okay,
perhaps the contents of the application (rttr.app/Contents/MacOS/*) are not executable anymore, I'll set them via f1b84c4f1ae2d2c2aba42e46a5f023d204901367 now, and hopefully fix the "image not found" problem of the updater too

**Comment by KalteWoschtsupp** [comment]
Yup, newest nightly (20151025) seems to be working. Update's working fine and I was able to start a game and play it for a while. So seems to be fixed! Nice work! Thanks!

**Comment by Flow86** [comment]
perfect!

**Comment by byr1al** [comment]
I too can confirm that it is now working. I haven't had the time to play yet, but the application loads and I can start a new game.
Good work and thank you!
