### ISSUE TITLE
Saving in Replay causes crash

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#3]
We just played a game and it crashed at GF 274999 (Autosaving was enabled) so I tried to create a savegame by playing the replay to GF 274750 but it also crashed the game. As far as I tested, the game does not crash if you save at GF 272000 or before, but after that (273000 tested) the game crashes.

Replayfile: http://www.rfmonline.de/rttr/spike/2015-04-14_22-21-19.zip

**Comment by jhkl** [comment]
Unfortunately I cannot play the replay that long. It asyncs at GF 10385. Possible due to the changes since April.... Sorry...

I close this to Won't fix, please reopen with newer replays if it happens again.
