### ISSUE TITLE
ALL sounds are distorted (sea, wind, birds): white noise with clipping

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#30]
I've installed RTTR three days ago, but the sound issues make the game almost unplayable for me.

I'm using RTTR v0.8.1 which seems to be the most recent one (disregarding nightly builds) at the time of this writing.

Every single sound effect, that isn't music (music sounds fine) is practically just white noise. Especially winds and sea sounds make the game almost unbearable, since this seems to be at full volume and clipping. I have to turn off sound effects (the white noise overpowers things like message notification anyway, so that's not even helpful right now).

I'm using RTTR on Linux Fedora 20, relevant `uname` output:
   Linux 3.13.10-200.fc20.x86_64 #1 SMP Mon Apr 14 20:34:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I have multiple issues with the UI, too, (some menu items aren't clickable/selectable), but that's for another bug report.

I'm willing to help as much as I can. Please let me know, if I should have a look at some code or anything.

Steps to reproduce:
  - Start game
  - Make sure sound effects are activated
  - Load game state or create new game.

**Comment by MarcusSt** [comment]
We would need the original bug reporter for that. I'm running Linux (x86_64) and don't have any problems with sound effects. This could have a lot of reasons, but I think it's unlikely to be a bug in RTTR.

**Comment by Flamefire** [comment]
I had these kind of sound problems when sound-convert was not found/working. Maybe check/require this?

**Comment by Flow86** [comment]
yes perhaps you should remove your sound.lst (in ~/.s25rttr/ ) and look if the sound-convert is run correctly

**Comment by fguzm** [comment]
This is exactly the sound issue I have on two different debian 64 machines since a week or so.
Purging pulseaudio helped on one pc, but not on the other.

**Comment by fguzm** [comment]
Cannot write to tmp?

Target sampling-rate set to 44100.000000.
Writing output to "/tmp/tmp.P".
mus-sound-open-input can't open /tmp/tmp.P: No such file or directory
resample: Could not open input file "/tmp/tmp.P"

Resampling failed, using original item
Can't open temporary file "/tmp/tmp.P" for reading
Starte Sound-Konverter ...lade "./share/s25rttr/S2/DATA/SOUNDDAT/SOUND.LST": fertig (4ms)
lade "./share/s25rttr/RTTR/MUSIC/SNG/SNG_0004.OGG": fertig
lade "./share/s25rttr/RTTR/MUSIC/SNG/SNG_0006.OGG": fertig
lade "./share/s25rttr/RTTR/MUSIC/SNG/SNG_0010.OGG": fertig
lade "./share/s25rttr/RTTR/MUSIC/SNG/SNG_0014.OGG": fertig

**Comment by Flow86** [comment]
interessant O.o

**Comment by fguzm** [comment]
Completely removed the following packages:
timgm6mb-soundfont

Installed the following packages:
musescore-soundfont-gm

Now the sound is fine

**Comment by Spikeone** [comment]
https://bugs.launchpad.net/s25rttr/+bug/848090

The Yippie of the Geologists sounds choppy

I've just played S2.5 for the first Time and I notized that the Sound of the Geologists sounds incomplete. It stopps and isn't fully pronounced. I really liked it in the Original so it would be great if this is gonna be fixed. ;-)

i wold think the game version is s25rttr_20110909. I don't know ^^


FloSoft (flosoft) wrote on 2011-09-12:	#1
Hi,

there are two possibilities here:

the first one is: you have an old sound.lst in your rttr-directory (I dont think that this one applies here, because you say you play rttr for the first time)

the second one is that the sound-convert did not run properly. Do you use windows? Can you rerun the game and post the console output here?

You could try to use the 0.7.2 to generate the converted sound.lst - the 0.7.2 sound-convert does work more reliable. (please use a different directory!)

Xenowar (starflyer11) wrote on 2014-02-24:	#2
I have the same problem in the stable version 0.8.1 as well as in the Nightly revision 9192. I tried deleting the sound.lst and reconverting it, but it didn't solve the problem. I'm using windows 7 64bit.

**Comment by Flamefire** [comment]
Need more input if this is still an issue
