### ISSUE TITLE
Compile problems with Visual Studio 2013

### ISSUE THREAD

**Issue by jhkl** [Return-To-The-Roots/s25client#304]
Spike had two problems while building with VS2013:

`Fehler  13      error C3861: "snprintf": Bezeichner wurde nicht gefunden.       C:\s25client\src\GameClient.cpp 1932    1       s25client `
According to http://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010 the identifier without underscore works only from VS2015
-> solved with commit 20625ce4c1ce8b7eb4475ce29f4cb1b62aad3afe

`Fehler  2       error C2228: Links von ".select_on_container_copy_construction" muss sich eine Klasse/Struktur/Union befinden. (C:\s25client\src\TerritoryRegion.cpp)   C:\s25client\contrib\boost_1_55_0\boost\intrusive\detail\has_member_function_callable_with.hpp  200     1       s25client`

Found https://svn.boost.org/trac/boost/ticket/9369 
Don't know how to fix.

**Comment by Flow86** [comment]
seems to be a bug in boost (in the ticket you mentioned there is a patch for boost)

**Comment by Flamefire** [comment]
Problem is solved in boost 1.56: https://svn.boost.org/trac/boost/ticket/9332
