### ISSUE TITLE
Crash of programm

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#309]
Hi!
I have another Crashing-savegame. This time it is not related to where the screen is. I attached the save. Just load it and wait 30s and you will see the crash…
Version 20151107 (Latest nightly)
 
Downloadlink (7days)
https://fil.email/1YpL3o?&showconfirmation=true

Regards
David

**Comment by jhkl** [comment]
Short analysis:
Assertion assert(e->obj->GetObjId() < GameObject::GetObjIDCounter()); in EventManager::NextGF is triggered.
Obj ID is 3452816640, looks like some unintialized/overwritten junk?
ObjIDCounter is 2015210.

**Comment by jhkl** [comment]
It looks like the destroyed harbour at 36/82 orders new wares for an expedition while being destroyed. (Look at creation of GameObject with ID 2007191)

**Comment by jhkl** [comment]
Should be fixed with cc15d43a09fc7ab7f962cd3d71290ada8bc3d73a
