### ISSUE TITLE
Loading a (big) savegame is difficult when host has a slow internet connection

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#31]
I have a pretty slow internet connection (45 kib/s) and when I try to load a big savegame, the other players often can't connect or can only connect after several tries.

FloSoft (flosoft) wrote on 2009-07-31:	#1
perhaps we have to add some kind of connection-speed selection, so we can modify the data packets to a smaller size if connection's slow

ECC_OK (prometheus-unterderbruecke) wrote on 2009-08-02:	#2
The problem happend again yesterday, after a ~200000 GF game when one of the players had his 24h Internet disconnect. It seems like the timeout is just set to low, the host kicks the player becaus of this.

Maybe you should raise the timeout value?

ECC_OK (prometheus-unterderbruecke) wrote on 2009-08-02:	#3
Setting the timeout from 30 to 120 seconds solves the problem

**Comment by MarcusSt** [comment]
Hasn't this been "fixed" (as in increase of timeout)?

**Comment by Spikeone** [comment]
Was neither marked as won't fix, fix committed nor fix released and still assigned to flosoft - that's why I copied it as well.

**Comment by Flow86** [comment]
I thought that whas been fixed
