### ISSUE TITLE
Make Logger more typesafe

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#311]
The logger class still uses the printf-like functions which especially require care for string/object passing. So you need to pass str.c_str() to them which is some overhead and will cause problems when forgotten.

I'd change the Log class to use `boost::format` which is pretty neat. Usage will be like this:

    LOG.log("Value: %1%, Name: %2%\n") % value % nameStr;

Also the names should be changed. I always wonder which function to call... Why not call them logConsole, logBoth, logConsoleClr, logBothClr or so?

**Comment by Flow86** [comment]
:+1:

**Comment by Flamefire** [comment]
Fixed now
