### ISSUE TITLE
Crash - sea map 

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#313]
Hi!
I loaded with the latest nightly version my savegame from:
https://github.com/Return-To-The-Roots/s25client/issues/309
and continued playing. Now the first harbour attack was without a crash possible. I think the new crash is from the 2nd harbour attack (Left island). At the same time of the crash the ship quintia arrives on my island, but just delivering a scout and meat. So I don’t think that there is a relation… 
I attached again the savegame.
https://fil.email/18aHYM

Regards
David 
PS: I wanted to say a big thank you to the developing team! The support and fix time is amazing, with the last issues I reported!

**Comment by jhkl** [comment]
Seems you are a good tester ;)

Actually, the problem looks quite similar. Again the crash is triggered by an assertion checking for a valid object ID. Object ID of event is 2181910.

Stack on creation of Event with ID 2181910:
```
 	s25client.exe!GameObject::GameObject()  Zeile 61	C++
 	s25client.exe!EventManager::Event::Event(GameObject * const obj, const unsigned int gf, const unsigned int gf_length, const unsigned int id)  Zeile 51 + 0x16 Bytes	C++
 	s25client.exe!EventManager::AddEvent(GameObject * obj, const unsigned int gf_length, const unsigned int id)  Zeile 74 + 0x44 Bytes	C++
	s25client.exe!nobHarborBuilding::OrderExpeditionWares()  Zeile 557 + 0x16 Bytes	C++
 	s25client.exe!nobHarborBuilding::WareLost(Ware * ware)  Zeile 566	C++
 	s25client.exe!Ware::NotifyGoalAboutLostWare()  Zeile 261 + 0x19 Bytes	C++
 	s25client.exe!noShip::HarborDestroyed(nobHarborBuilding * hb)  Zeile 1048	C++
 	s25client.exe!GameClientPlayer::HarborDestroyed(nobHarborBuilding * hb)  Zeile 2260 + 0x1d Bytes	C++
 	s25client.exe!nobHarborBuilding::Destroy()  Zeile 116	C++
 	s25client.exe!nofAttacker::Walked()  Zeile 287 + 0x15 Bytes	C++
```

**Comment by Flamefire** [comment]
I'm going to look at that too, but it is possible, that the savegame is already corrupted by the bug you reported in #309. The bug there led to some objects referencing invalid (possibly destroyed) objects. When this is in the savegame the savegame is unfortunately lost and cannot be continued. But lets check...

**Comment by BlOedsin** [comment]
As there was quite a long playtime in-between I would not expect it but I know that this could be. I started again from the first save without doing an attack. This game didn’t crash…. 
If the savegame is lost its not a major problem for me. I just would like to ensure that when I start a new game, it is not crashing again ;-)

**Comment by Flamefire** [comment]
Ok thanks for mentioning that. I'll look at this later today and see what the cause is.
The main cause for crashes are attacks (or more precise: The destruction of buildings especially multiple ones at once) because this shows flaws in the system.

**Comment by jhkl** [comment]
I tried the thingy with pull requests. Did I do it right? 

Btw: Why are these crashes emerging just now? Were there any changes? Or are there more checks now?

**Comment by Flamefire** [comment]
Jep, PR is correct. Will post comments there.

Don't know. I guess the checks just catch more of those bugs or kinda random... The bug causes undefined behaviour so no one knows what might happen. Maybe just nobody bothered to report them.

**Comment by BlOedsin** [comment]
Just let me know, when you finished  this bigger bugfix for sea maps (#314), and I will test it again.

**Comment by Flamefire** [comment]
Looking into this right now. However the savegame is no longer available. I'd suggest to use an other hoster. I often use sendspace.com which does not have an expiration date on the files...

**Comment by BlOedsin** [comment]
Hi I just uploaded the savegame again on sendspace.com

https://www.sendspace.com/file/0shkkf

**Comment by Flamefire** [comment]
Almost done with the changes. PR will come later today (after I slept) for @jh to review. I double-checked the whole seafaring system and found a few loose ends and dead code which could cause all kinds of problems. Now it looks right, but I'll do some final tests. Unfortunately it won't be save to load savegames created with earlier versions then the one after that PR, so I'm going to disable that, which means you won't be able to continue your saved game. If you want, you could edit the savegame version and still try it, but it *might* then fail without any chance of recovery. New savegames will be fine of course.

**Comment by BlOedsin** [comment]
o.k. so I will update tomorrow the latest nightly and start the same map again. Not a problem if my old savegame is lost! Cause otherwise in case of a crash we don't know if it is related to the old savegame or if it is a new bug.
