### ISSUE TITLE
Display of HitPoints

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#316]
![screenshot](https://cloud.githubusercontent.com/assets/14259828/11438472/66fc9ac2-94f5-11e5-89de-9e98b3a3f139.PNG)
I think the string in the Fortress (maybe also in other buildings) the hit points string is shifted by one character. 
I assume in my picture it should be 74/77/77/77/73. So the first number belongs to the last solder. Furthermore it would be nice, if the solders would be sorted by their hit points In case of an attack the solders should be selected depending on strong or weak defense.

**Comment by Flamefire** [comment]
@Ribosom Can you check and fix this please? Seems like the fields are to narrow, so maybe displaying the current HP (without max) will be enough. But it's your addon so I'd leave the decisions for you :)

**Comment by Ribosom** [comment]
Ok, I am going to remove the max value. The  colour of the hitpoints will be red, if a soldier has not the maximum hitpoints.
