### ISSUE TITLE
soldiers getting stuck while attacking

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#335]
![2015-12-24-022823_1680x1050_scrot](https://cloud.githubusercontent.com/assets/14232936/11987883/608382ee-a9e7-11e5-8159-e370663e4440.png)

[2015-12-24_02-23-27.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/71374/2015-12-24_02-23-27.rpl.zip)

I made a screenshot and uploaded a replay. The soldier stands roughly in the mid of the north-western part of the most north island. 

P.S. How do I give coordinates properly?

**Comment by stefson** [comment]
if you want to move fast forward, it is happening roughly around frame #205800

**Comment by Flamefire** [comment]
You can press F3 to show coordinates. Thanks for the replay. Will check that.

**Comment by Flamefire** [comment]
Reproduced. Will dig into it to find the reason.

**Comment by jhkl** [comment]
Bug should be kept as homage to the original ;)
(http://jh-isch.de/s2/tipps/t_einfrieren.php)

**Comment by BlOedsin** [comment]
I have a frozen solder as well. But my game crashes a view frames after that happens (not sure if it is related at all).
Position 77;65
In the Replay it happens around 136800. It might be related to the hit by the catapult. 
Version 20151224

![frozensolder](https://cloud.githubusercontent.com/assets/14259828/12003704/bd76cc7c-ab09-11e5-8bf7-a83dd71346e7.PNG)

I attached the savegame and the replay:
https://www.sendspace.com/filegroup/e4aEQhJpH8JRzdeRsLFlEg

**Comment by Flamefire** [comment]
Perfect thanks. Will check those tomorrow. 
With save games and replay it should be pretty easy to find

**Comment by Flamefire** [comment]
@BlOedsin: I tested the replay and I do not get the crash. I get the stucked soldier though. Do you have any more information on that crash? Exact code location, debugger output, your OS?

**Comment by Flamefire** [comment]
@BlOedsin Should be fixed with last commit. The crash could probably occur when a very specific soldier was killed (this is a random event) at a bad time although I don't think this is your crash as the time for that is to short for the soldier beeing killed. More probable is that the soldier is killed somewhere later and saving the game triggers the crash.

At the very least there should be no more stuck soldiers :)
