### ISSUE TITLE
s25client hangs up while attempting to kill the process on linux

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#336]
minor issue in my opinion 

on linux, when running s25client from console through gdb and while trying to kill it via Strg + C from within the console, the following is happening. Expected would be that the program either closes immediately or that there is an additional querey wether you really want to stop this programm (this is what the binary version is doing at least) 

any additional informations required? 

**^C**[New Thread 0x7fffeffad700 (LWP 30007)]

Program received signal SIGINT, Interrupt.
0x00007ffff636c12d in poll () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff636c12d in poll () from /lib64/libc.so.6
#1  0x00007ffff7947814 in ?? () from /usr/lib64/opengl/nvidia/lib/libGL.so.1
#2  0x00007ffff5292c89 in ?? () from /usr/lib64/libnvidia-glcore.so.355.11
#3  0x00007ffff51c532e in ?? () from /usr/lib64/libnvidia-glcore.so.355.11
#4  0x00007ffff793edcd in ?? () from /usr/lib64/opengl/nvidia/lib/libGL.so.1
#5  0x00007ffff28dea19 in VideoSDL::SwapBuffers() ()
   from /usr/games/lib64/s25rttr/video/libvideoSDL.so
#6  0x00000000004d56b2 in ?? ()
#7  0x00000000004241f5 in ?? ()
#8  0x00007ffff62ad7b0 in __libc_start_main () from /lib64/libc.so.6
#9  0x00000000004c3e99 in ?? ()

**Comment by stefson** [comment]
and I just learned that when typing continue from gdb after having created the backtrace, the game continues as if nothing had happend, haha :)

**Comment by Flow86** [comment]
yes, Ctrl+C (SIGINT) will be catched by gdb and not processed by the application itself when run inside debugger

https://sourceware.org/gdb/onlinedocs/gdb/Signals.html

**Comment by Flamefire** [comment]
Can't see anything bad... Strange. Are you able to dig into this yourself so somehow get the point where it hangs? Probably by attaching after it is hanging...

**Comment by stefson** [comment]
Well, a normal case would be that the programm exits normally, wouldn't it? 
Like this? 

**^C**[Thread 0x7fffeb7a9700 (LWP 6056) exited]
[Inferior 1 (process 6050) exited normally]
(gdb) **q**

Actually I don't consider this to be a nasty one, just ran into it and wanted to let you know.

**Comment by Flamefire** [comment]
It seems to be a bug but I cannot reproduce it here. I'll probably have to try in my Linux vm

**Comment by Flow86** [comment]
> Well, a normal case would be that the programm exits normally, wouldn't it? 
no, if you run inside the debugger, the debugger will catch the Ctrl+C (SIGINT) and will not give it to the application itself. you have to disable the ctrl+c processing inside the gdb ("handle sigint nostop") then the ctrl+c is passed to the application

**Comment by Flamefire** [comment]
There was a bug when you press CTRL+C at the exit screen ("Press ENTER to close") which is fixed now
