### ISSUE TITLE
Garbage in enemies terrain 

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#339]
[bug westgrenze.zip](https://github.com/Return-To-The-Roots/s25client/files/72725/bug.westgrenze.zip)
In this savegame, look at the south-west border with the green player.
A mine is displayed with some border-stones. This is wrong since the border stones don't form a circle and also since the green player's territory is a bit more to the right.

**Comment by Flamefire** [comment]
This is not a bug although it looks funny. The mine is NOT there, it is only a FoW object. So I assume the mine was discovered earlier (when it was there), then the territory of green shrinked destroying the mine. Later just the terrain around the mine was reexplored leaving this artifact. Check the replay and turn the FoW of, then you'll see that there is no spoon (aehm, mine)
