### ISSUE TITLE
Join game via internet lobby

### ISSUE THREAD

**Issue by ongaku86** [Return-To-The-Roots/s25client#340]
Hey there,

I'd like to ask you for some help with the following issue:

I am trying to set up a game via internet. Both me and my game partner can sometimes log in, sometimes not (we're using the same router today). But even when I manage to set up a game, we both always lose connection to the lobby before the other player can join the game. Can you help me with that?

Thx for all the good work

Astrid

**Comment by MarcusSt** [comment]
Try to use direct IP if the lobby server is down. There were some times it was not too stable, but it should be now. Please reopen if the problem persists.
