### ISSUE TITLE
Soldiers get stuck after winning a building

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#341]
We have encountered several of these situations (both in player vs player and player vs bot settings):
 
![screenshot from 2015-12-28 12 25 31](https://cloud.githubusercontent.com/assets/1663386/12018459/223dbdf4-ad63-11e5-80ba-67a908025e94.png)

Soldiers do not enter a building after winning it. The building can't be attacked or teared down. It can however be catapulted. This situation does not get resolved for a while. Only at the very end of the game it is resolved.

Save game (ca. GF 94K)
[attack_impossible.sav.zip](https://github.com/Return-To-The-Roots/s25client/files/73172/attack_impossible.sav.zip)

Replay:
[2015-12-28_11-32-49.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/73173/2015-12-28_11-32-49.rpl.zip)

**Comment by Flamefire** [comment]
Thanks for the report. I'll look into that :)

**Comment by danielplatt** [comment]
Another issue in the same game: In the later part of the game, when more than one road leads to the HQ of the red player, helpers are constantly moving in and out of the building. Check the replay from gameframe 1346500 onwards.

**Comment by Flamefire** [comment]
Please only 1 thing per issue. Makes managing easier --> #343

**Comment by Flamefire** [comment]
Issue is fixed with 54353b7c4ddcde1a1fe61d2044f365d4e1c9c817
Thanks for reporting! Your tests and reports really help making the game better :)

**Comment by mplatt** [comment]
Thank you @Flamefire for fixing this so fast!

**Comment by Flamefire** [comment]
Well I introduced the bug while fixing another one and did not run the tests as I was short in time ;)
