### ISSUE TITLE
Tadaa sound wrongly followed by dove sound

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#342]
This is a bug report I got per mail:

> The 'tadaa' sound is to loud in comparison to the other sounds.
> Meanwhile I have to lower the volume to fit the loudest sound and then I can't hear the other sounds  anymore.
> When I raise the volume to be able to hear the more gentle sounds, then TADAAAAA my neighbour knocks on the wall after the settlers have entered a barrack.
> Regards

Perhaps we should review all of the sound volumes

**Comment by jhkl** [comment]
I don't really see this as a bug. The next player will complain that it is too silent and might be missed...

**Comment by Flamefire** [comment]
Maybe he has set the music player volume to low? Wouldn't change these too as this this are the S2 sounds...

**Comment by Flow86** [comment]
okay then lets make it an enhancement to review those volumes

**Comment by MarcusSt** [comment]
@Flamefire Making those sounds play at volume 100 seems okay to me. This would require changes in dskGameInterface.cpp lines 733 and 1143. Another problem is that the dove sound should not be played in addition to the 'tadaaa' one, which is the case atm. The other volumes seem to be fine (and are tuned to some value).

**Comment by MarcusSt** [comment]
The dove 'effect' is not supposed to play for occupied military buildings together with the tadaa sound. This is a bug.

**Comment by Flamefire** [comment]
Is it possible, that every PostMessage category has its own sound? Then we could play all the sounds in the OnNewMessage method (2nd you changed) but depend on the category. But I guess the occupied sound is the only special sound for messages, correct? Maybe pass a sound-enum value to each post message with a default (dove sound)

**Comment by MarcusSt** [comment]
At the moment, the tadaa sound is played by the notification, maybe we should just add a sound parameter (enum) to the post messages and remove the tadaa sound from the notifications.

**Comment by Flamefire** [comment]
Another idea I had: Game change notifications (like building occupied etc) are also sent as messages to subscribed classes. We could remove the post message sending from the game object classes and let the game interface do that (or the players postBox)

However: Fixed for now
