### ISSUE TITLE
Helpers constantly moving in and out of HQ

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#343]
Another issue in the same game: In the later part of the game, when more than one road leads to the HQ of the red player, helpers are constantly moving in and out of the building. Check the replay from gameframe 1346500 onwards.

https://github.com/Return-To-The-Roots/s25client/files/73172/attack_impossible.sav.zip

https://github.com/Return-To-The-Roots/s25client/files/73173/2015-12-28_11-32-49.rpl.zip

**Comment by Flamefire** [comment]
@danielplatt The issue is, that a carrier wants to go to the flag at 26,86 but there is only a water road there which people can't use. Somehow this is not detected earlier.

**Comment by Flamefire** [comment]
Bug is found and will be fixed with the next version. Thanks for reporting! :+1:

**Comment by danielplatt** [comment]
Wow, thanks a lot for fixing it so fast! :) You and the others on the team are doing an awesome job!

**Comment by Flamefire** [comment]
But we rely on testers like you. We cannot check everything unfortunately :+1:
