### ISSUE TITLE
Remove async replays from the internet

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#345]
Automatically uploaded async replays can be accessed via the internet at the hostname shown in the console after a async/crash. Please remove these from the internet, or at least make them password protected, as not only the replay but also the in game chat message are extractable.

**Comment by Flow86** [comment]
Hi,
shouldnt be visible on the website, access is now denied to it. 

@Return-To-The-Roots/support I will add password auth for it

**Comment by mplatt** [comment]
Thanks :smile:
