### ISSUE TITLE
Game crash after Catapult hit

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#346]
Hi!

The last Autosave is a bit before that crash, but I hope you can reproduce with the replay. The game crashed after the catapult hit the building. 

Downloadlink:
https://www.sendspace.com/filegroup/%2FeVWaR43XScmtkhLJL7h9A

![crashaftercatapulthit](https://cloud.githubusercontent.com/assets/14259828/12072803/af98adc8-b0db-11e5-8d1d-5ed1266b9b04.PNG)

**Comment by Flamefire** [comment]
The link is broken. Can you fix that? You can also zip the file(s) and upload the zip here

**Comment by Flamefire** [comment]
Probably fixed. Cam you check that too?

**Comment by BlOedsin** [comment]
Sorry was without internet the last days.
With the latest version the crash did not happened, but it is also a bit tricky to reproduce the timing...

I get the errormessage (If I drag and drop a *.ZIP) in here; don't know why.
Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. 

Thats why I uploaded it again to; don't know why the old link broke :-(: https://www.sendspace.com/file/xfs3pu

**Comment by Flamefire** [comment]
You can only upload zips here. So you'd have to zip the file, then you can drop them
Will check your file now

**Comment by BlOedsin** [comment]
I was trying to upload a zip file, when I got that error message!
I continued playing the savegame above, and I got another crash. That time easy to reproduce. Just load the savegame. It always crashes with me a view seconds after loading.

In the console I had the following error message (by the first crash).
An error occured while saving which was suppressed!
<scv> Saving game...
An error occured while saving which was suppressed!
<scv> Saving game...
An error occured while saving which was suppressed!
<scv> Saving game...

The last happening before the crash was conquering that building
![crash2](https://cloud.githubusercontent.com/assets/14259828/12091141/cc3aeab6-b2db-11e5-82b4-000949d33d8e.PNG)

Attached savegame + replay

https://www.sendspace.com/file/cbf252

**Comment by Flamefire** [comment]
Thanks. Will check that :)

**Comment by Flamefire** [comment]
Ok the savegame got corrupted. There is an invalid ware somewhere which is why it crashes and show before by the error message during save
I hope the savegame is able to tell the reason for that crash

**Comment by Flamefire** [comment]
Interesting. We got a Heißenbug here: Sometimes the bug occurs at GF 251013 and sometimes not. No async replay... This is kinda impossible :/ Will see how this could happen

**Comment by Flamefire** [comment]
Ok found, thanks for reporting!
