### ISSUE TITLE
[LUA] Restricted area not working as described

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#35]
"rttr.SetRestrictedArea(player, x1,y1, ...)
This restricts the area a player may have territory in. If called without any x/y-values, the restrictions are lifted. Otherwise, the coordinates specify one or multiple polygons the player may have territory in. A polygon inside a polygon will create a hole in it. To specify multiple polygons, start with a 0,0-pair followed by the first polygon, another 0,0-pair, the second polygon etc. and a final 0,0-pair at the end. For multiple polygons, each polygons first point has to be repeated at the end of it."

If you try to only specify an area where you shouldn't be able to build you have to enable first the complete map as allowed for building (e.g. 0,0 256,0 256,256 0,256) and then you may add any polygon in the described way.
It nearly works BUT it looks like the inside polygon also uses 0,0 as point - even if you use 1,1 1,256 256,1 instead of 0 this problem appears.

**Comment by Flamefire** [comment]
I don't quite understand the problem. Do you mean if you want to specify a region where you SHOULD be able to build so you first need to disable the whole map?
Could you create a small example for testing?

**Comment by Spikeone** [comment]
Problem is: You specify the whole map as "allowed" by setting 0,0 , 0,256, 256,256 , 256,0 now you want one are to be forbidden, lets say 30,30 30,50 50,50 
=> 0,0 0,0 0,256 ,256,256, 256,0 ,0,0, 30,30 30,50 50,50, 0,0

**Comment by Flamefire** [comment]
But isn't this function about forbidding a region? So 0,0 0,0 0,256 ,256,256, 256,0 ,0,0, 30,30 30,50 50,50, 0,0 would forbid the whole map and allow only the small region inside it, right? This is at least how I understand the first paragraph.

Besides: I think the function design is bad. Using 0,0 as the delimiter makes it quite hard to write. Why not just say all polygons must be closed? Specifying multiple polygons is than trivial (0,0 pairs mean 0,0 points, no delimiters) @MarcusSt ?

Oh and BTW: it seems the correct syntax would be:
0,0, // Start
0,0 0,256, 256,256, 256,0, 0,0, // 1st polygon
0,0, // Delimiter
30,30 30,50, 50,50, 30,30, // 2nd polygon
0,0 // Delimiter

I guess the function should detect this wrong usage...

**Comment by Spikeone** [comment]
You are right about my fault but even if doing it that way it didn't work (answered by phone and quite hard to keep all numbers correctly)

Also you misunderstood the function just like me: if you create a polygon, let's say a square with function(20,20, 30,20, 30,30, 20,30) you are allowed to build WITHIN this area and not as you may expect first anywhere but that square.

That's the reason why, if I want to fake an enemy's military building, have to enable the complete map first and then have to disable a small area.

Maybe one could set the default state "enable all" or "disable all" and create multiple polygons by multiple function calls who change the state at those points to the opposite?

**Comment by Flamefire** [comment]
Ah ok... Then I'd change it into 2 functions: EnableArea and DisableArea. Default is all enabled.

**Comment by MarcusSt** [comment]
The idea is to use a function that is able to use polygons to check for enabled areas.

"Restrict" should be the right name to use, as it restricts the otherwise "unlimited" area you can use to whatever you specify, so I think the name is okay. EnableArea/DisableArea sounds confusing, because it sounds like you can call it multiple times to place polygons.

For the algorithm used, see http://www.ecse.rpi.edu/Homepages/wrf/Research/Short_Notes/pnpoly.html (also referenced within the source code) There's also a description how this should be used.

There may be some problem with the implementation I guess.

**Comment by Flamefire** [comment]
Why should one not be allowed to call it multiple times? Enable/Disable area is much more flexible. You can say e.g.: Player 1 can't build outside of a circle. After he reaches a specific goal he is allowed to build in a corridor towards the gate.
So basically you can adjust the current "state" of allowed/dissallowed fields. This makes the usage much easier IMO

**Comment by Flamefire** [comment]
@Spikeone Can you create a test-case for the RestrictedArea function which also shows the wrong behaviour?
@MarcusSt What do you think about 2 functions that are repeatably callable as outlined above?

**Comment by Spikeone** [comment]
Created a test-case
Tested the scenario
Everything was working as expected
