### ISSUE TITLE
Crash (after harbour destruction?)

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#352]
Hi!
I updated to the latest nightly and started with a savegame about 10000GF before the last crash and could continue playing for quite a while. I had two crashes in between which I could not reproduce, but now I have a reproducible again. I destroyed a harbour building shortly before that crash. Maybe related to that?!?
Replay and savegame:
https://www.sendspace.com/file/37lyed

**Comment by Flamefire** [comment]
You can also include the replays of the crashes you cannot reproduce (just state that here so we don't get confused) Sometimes those help in finding undetected bugs as we can run it in debug builds which have excessive checks on many parts

**Comment by BlOedsin** [comment]
I uploaded the replays of the two crashes before, which I could not reproduce (After loading the latest autosave before, the game did not crash again, although I tried to act in the same way...).
https://www.sendspace.com/file/2gkgob

**Comment by Flamefire** [comment]
If you play the replay and that crashes, then it is enough to reproduce that, although a savegame that is crashing is better. For the replay: It is recorded till the GF BEFORE the crash. So you have to run it till the end and press "P" once it is finished to run it further (which should instantly crash)

**Comment by Flamefire** [comment]
I found at least 1 Bug: A ship with attackers was driving to the harbor, then it got destroyed and the ship starts to return to its original harbor. The attackers were still thinking they were going to their target. Finally the attackers are wrongly added to the start harbor and when their home building was destroyed, it could not find the soldiers -> crash.
