### ISSUE TITLE
Crash – Road building

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#353]
I have the feeling there is a bug in the calculation of paths. I had a couple of crashes already in the last game, when I was trying to build a road. It can not always be reproduced. After loading the same building of the road is working….

![pathfinding](https://cloud.githubusercontent.com/assets/14259828/12217279/127755a4-b6fc-11e5-9fda-e69c5c8c81be.PNG)

I attached replay and savegame.
https://www.sendspace.com/filegroup/uUPHIP7UdFmz9TnuWCbwqjZfF6VKs4Xe

**Comment by BlOedsin** [comment]
With this savegame it is a bit easier to reproduce. Try to build a road from the fortress which is covered by the cancel road building screen. Maybe even click e.g. into the swamp. My first crash was, when I was trying to connect to the flag above the fortress. Latest after a view tries I get a crash.
Savegame: https://www.sendspace.com/file/t4un7j


![pathfinding2](https://cloud.githubusercontent.com/assets/14259828/12217370/6866afbc-b6fe-11e5-8ba0-a052eb8dbc5c.PNG)

**Comment by Flamefire** [comment]
Crash originates in the change in the closing of windows. Closing potentially multiple windows with the same id results in an iterator corruption. I could easily reproduce it by trying to build an invalid road, not closing the window and trying to build the road again.
