### ISSUE TITLE
Message when changing video/audio drivers always appears

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#356]
When ever I enter the Options menu and leave it, the game tells me that I have to restart the game in order to change my video or audio driver.
This message should be only displayed if the driver was actually changed.
Version: F8F0B89

**Comment by Flamefire** [comment]
Thanks, will test and fix that. Didn't had that myself though...

**Comment by Spikeone** [comment]
Maybe only if you have an invalid driver - I've got an other SDL.DLL (which is not recognized in the menue) but I selected WinAPI so thats still strange somehow
