### ISSUE TITLE
RttR crash when a buildinginfo window is open and the building is finished

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#358]
When you keep the buildinginformation window of a building open (tested with a fortress) and that building is finished, RttR crashes.
I could reproduce that crash anytime.

Version: F8F9B89
OS: Win 7 x64

**Comment by Flamefire** [comment]
Should be fixed in latest release. There was a bug with closing windows. Can you recheck?

**Comment by Spikeone** [comment]
Yeah, sorry :-/
