### ISSUE TITLE
[LUA] - rttr.DisableBuilding() not working correctly (with fortresses?)

### ISSUE THREAD

**Issue by lvanderwall** [Return-To-The-Roots/s25client#361]
Revision: v20160110 - 29e329fc

AI builds fortresses even though they are disabled by *rttr.DisableBuilding()*. 

Mission file, lua file and replay (jump to GF 67150), AI builds first fortress after GF 6750:
[rttrr01.zip](https://github.com/Return-To-The-Roots/s25client/files/87909/rttrr01.zip)
[logfile.zip](https://github.com/Return-To-The-Roots/s25client/files/89340/logfile.zip)

**Comment by Spikeone** [comment]
There is no rttr.AIConstructionOrder() for a fortress?

**Comment by Flamefire** [comment]
So if the AI builds fortresses, then this is a bug. Will check that

**Comment by lvanderwall** [comment]
@Spikeone You're correct, I'm not sure what I saw in the lua-file, sorry ;) There isn't any fortress in the *rttr.AIConstructionOrder()*, and I updated the issue.

**Comment by Flamefire** [comment]
Found the bug. Will be fixed
