### ISSUE TITLE
Wrong byte ordering in message header

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#363]
In https://github.com/Return-To-The-Roots/libutil/blob/6c3d14e10c354772dc65924a5ccb9d8bd543a1b9/src/Message.cpp#L49-L50 the id and length of a message are set directly via pointers. This will lead to fatal issues once different byte orders are used (e.g. client little endian, host big endian)

This issue is not easy to fix as the lobby server also uses this code, so the lobby server would need to be updated too and all prior versions won't be able to connect anymore.
My best shot: At least fix the byte order of those to be little endian.

I'm currently reworking the message system (add usual Serialize/Deserialize) so this can be added there too.

@Flow86 Any suggestions?

**Comment by Flow86** [comment]
you're right, should be network byte order

**Comment by Flamefire** [comment]
How should we fix this? Implement it correctly by using network byte order which basically requires you to update the lobby server and everyone to use the latest nightly, or just fix those as little endian (noop on most systems) so it is at least consistent

**Comment by Flow86** [comment]
yea I think we should "force" them to little endian now, perhaps change it before we release the next stable

**Comment by Flamefire** [comment]
Fixed with https://github.com/Return-To-The-Roots/libutil/commit/3ae2d984ceb5ea1d606dc64a30068ec1b0009a62
