### ISSUE TITLE
Crash after changing game speed (pressing “v”)

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#366]
I just had a very odd crash, created by changing the gamespeed.

>terminate called after throwing an instance of 'std::range_error'
>  what():  Out of range during deserialization

I can reproduce it, by loading the attached savegame and press one time v to change the gamespeed.
Not reproduceable in the replay, only with savegame.
Version 2016-01-15
https://www.sendspace.com/file/4xb7ic
![screenshot](https://cloud.githubusercontent.com/assets/14259828/12371513/2e866de0-bc36-11e5-82fe-f19b65dde63d.PNG)

**Comment by Flow86** [comment]
@Flamefire we should add a general try-catch in the main to get the exception logged via our debug info

**Comment by Flamefire** [comment]
Good idea. Better: put it in the log, rethrow and upload log+replay+save game+trace as a zip (we have bzip2 already) 
This bug is probably due to the changes of the packet handling. Good thing I added range checks to the serializer so it will be easy to find

**Comment by Flamefire** [comment]
Yep. Bug was a copy&paste error where I copied the log instead of the actual serialization. Tahnks for reporting! :+1:
