### ISSUE TITLE
CMake error when compiling

### ISSUE THREAD

**Issue by susnux** [Return-To-The-Roots/s25client#368]
When compiling on openSUSE I get this CMake error:

> [  540s] cd /home/abuild/rpmbuild/BUILD/s25rttr-0.8.1+g1942.b0a35b7/build/s-c/resample-1.8.1/src && cp -v s-c_resample ../../../RTTR/s-c_resample
> [  540s] 's-c_resample' -> '../../../RTTR/s-c_resample'
> [  540s] cp: cannot create regular file '../../../RTTR/s-c_resample': No such file or directory
> [  540s] s-c/resample-1.8.1/src/CMakeFiles/s-c_resample.dir/build.make:176: recipe for target 's-c/resample-1.8.1/src/s-c_resample' failed
> [  540s] make[2]: *** [s-c/resample-1.8.1/src/s-c_resample] Error 1
> [  540s] make[2]: *** Deleting file 's-c/resample-1.8.1/src/s-c_resample'
> [  540s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/s25rttr-0.8.1+g1942.b0a35b7/build'

If the RTTR directory in CMAKE_SOURCE_DIR is meant then the ../../.. in the CMakeLists.txt should be replaced with ${CMAKE_SOURCE_DIR}, if RTTR should be placed in CMAKE_BINARY_DIR then make sure to create it.

**Comment by Flamefire** [comment]
Seems like you did not use the cmake.sh to create this. The cmake.sh creates a symlink `RTTR` in the build folder.

**Comment by susnux** [comment]
Oh you are right, missed that.

**Comment by Flamefire** [comment]
I moved the commands from the shell script to the cmake script. If this works, this problem can be avoided in the future

**Comment by susnux** [comment]
ok that sounds good :+1:

**Comment by Flamefire** [comment]
Fix is in the current dev (see commit). It should be enough to run cmake alone for a native build (cmake.sh not required anymore for this)
