### ISSUE TITLE
Missing original textures

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#37]
There are some original textures missing at the moment - for example buildable water, no ship water, buildable desert, buildable mountain. Although they were not available in the original editor some textures were used - for example buildable water - which still causes problems in rttr.

Please refer: http://settlers2.net/documentation/world-map-file-format-wldswd/

**Comment by MarcusSt** [comment]
Could you give me the name of the map (with that textures) again?

**Comment by Spikeone** [comment]
Island of Hills, OMAP1.WLD - or something alike

**Comment by Flamefire** [comment]
I'm currently doing that and found a couple of issues there. Walkable terrain check checks t1 twice but not t2 (maybe that makes settlers walk into water) and AI checks might not be complete. But I'll need @jhkl to review that later
