### ISSUE TITLE
Port to SDL 2

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#372]
@Flow86: Is it possible to use SDL 2.0 on the build server? According to their homepage there are pre-made builts for OSX and MingGW and Linux versions should be available through the package manager.
Migration does not seem to be that hard so if the build server is able to handle it, I'd go to SDL 2.0 and hope, that this fixes the problems with OSx (best guess is, that SDL 1.2.14 might not be compatible with the newer OSx and before going through issues upgrading the build server to 1.2.15 first I'd go directly to 2.0)

This helps #333 #138 #89

**Comment by Incubbus** [comment]
Maybe also try to upate the Build Server to a C++11-capable cross-compiler during the run...
