### ISSUE TITLE
Video driver couldn't be loaded

### ISSUE THREAD

**Issue by fguzm** [Return-To-The-Roots/s25client#38]
"searching for drivers in ./share/s25rttr/driver/video/*.so"
"0 video drivers found!"
"Video driver couldn't be loaded!"

Game doesn't start since nightly from 28.7.

**Comment by Flow86** [comment]
can you provide on which platform do you play, and how do you start rttr?, can you also post the contents of ./share/s25rttr/driver/video?

**Comment by Flamefire** [comment]
I have the same in my VirtualBox. Unfortunately no full Linux system available. One may need to check the current path (using relative paths like "." is awful and should be removed anyway)

**Comment by fguzm** [comment]
I always forget to mention this: debian amd64 testing.
Content of video folder is libvideoSDL.so

**Comment by Flow86** [comment]
found the problem: 826cce296b417f4dcafedc6cb6f9bfc0f3d9cd8b added thos chdir to bin-directory, which will f** up all paths

**Comment by fguzm** [comment]
Now I got "radeon: The kernel rejected CS, see dmesg for more information"
dmesg:
"[drm:radeon_cs_ioctl [radeon]] *ERROR* Failed to parse relocation -12!"
Sound distorsed, game crashes after a few seconds with graphical artefacts.

**Comment by fguzm** [comment]
After a dist-upgrade to unstable the crash is gone, but still the sound is distorsed. On my other pc I could fix this by removing pulseaudio, not so here.
