### ISSUE TITLE
Pathfinding Start==Dest warning

### ISSUE THREAD

**Issue by jhkl** [Return-To-The-Roots/s25client#381]
Noticed while testing AI (3x AIs, + me)

> WARNING: Bug detected (GF: 34882). Please report this with the savegame and replay (Start==Dest in pathfinding 26,49)

Replay ~~attached~~ here:
https://dl.dropboxusercontent.com/u/1589203/temp/2016-01-29_22-18-19.zip

**Comment by Flamefire** [comment]
This replay is from 20151219. The bug is probably already fixed.
