### ISSUE TITLE
Storage behaviour - displaying wrong

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#382]
I tried the storage behavior again (in the debug version)
I can report the following:
1.) I open the storehouse
![1](https://cloud.githubusercontent.com/assets/14259828/12701337/ea4f1a50-c806-11e5-965f-ebc77c23d8d0.PNG)

2.) I set collect 
![2](https://cloud.githubusercontent.com/assets/14259828/12701338/ebf83fe4-c806-11e5-9a42-9a7761b8cfe2.PNG)
3.) I close and open again
Result: collect is not shown, but I think the storehouse is still collecting
![3](https://cloud.githubusercontent.com/assets/14259828/12701339/ee09b592-c806-11e5-8a7c-2140af495d49.PNG)
Furthermore if stop storage is set, it is not shown, if you open the storehouse, but if you click e.g. collecting once, it suddenly appears. If you want to say stop storage you always need to click twice till it is active.

**Comment by Flamefire** [comment]
Which version is this? Try the one from today please. There was a bug a few days ago...

**Comment by mplatt** [comment]
I guess same problem as in #349...?

**Comment by Flamefire** [comment]
This is fixed now. Please retest (especially @mplatt )
