### ISSUE TITLE
Scouts are not sent

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#383]
After trying to send a scout to the location shown in the following screenshot no scout is being sent out even though there are scouts in the nearby warehouse:

![screenshot from 2016-01-31 20 38 21](https://cloud.githubusercontent.com/assets/1663386/12704754/e94ed3a6-c861-11e5-8a0d-d94d47c2218d.png)

[no_scouts.sav.zip](https://github.com/Return-To-The-Roots/s25client/files/111498/no_scouts.sav.zip)

[2016-01-31_19-47-52.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/111500/2016-01-31_19-47-52.rpl.zip)

**Comment by Flamefire** [comment]
Confirmed. Thanks for reporting

**Comment by Flamefire** [comment]
Fixed now. Please report if there are still some problems.
