### ISSUE TITLE
Soldiers in HQ do not get released

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#385]
I have some solders, which are not leaving the HQ (Are not sent to the watchtowers), although I do not have any solders requested as reserve.
Savegame attached.
https://www.sendspace.com/file/lbksm1
![picture 1](https://cloud.githubusercontent.com/assets/14259828/12872063/bf694e56-cd96-11e5-8181-f7cce356b649.PNG)
![picture 2](https://cloud.githubusercontent.com/assets/14259828/12872064/c1a7026c-cd96-11e5-9f54-6a87127d4055.PNG)

**Comment by Flamefire** [comment]
Can you attach the replay too? So we can see how this happened

**Comment by jhkl** [comment]
Happens some time after loading the savegame.

Quick analysis: The numbers in nobBaseWarehouse::Goods.people are wrong. GameClientPlayer::FindWarehouse() checks the number of soldiers being > 0, but they are 0, Line 465 in GameClientPlayer.cpp.

Probably have to track the origin of the wrong number in the inventory...

**Comment by Flamefire** [comment]
The origin is before the savegame. When you load it, there are only some soldiers shown, but they are not really there. So we need the replay from @BlOedsin

**Comment by jhkl** [comment]
Yep, that is what I wanted to say :)

**Comment by BlOedsin** [comment]
Replay: https://www.sendspace.com/file/qlc4r2
(It is before the savegame, but as the solders are already in the HQ, I assume it happened during this phase.)

**Comment by Flamefire** [comment]
Fixed with 6d0181194e6f4e396636f1960d3c6f8032a9e3ac

Thanks for reporting. The replay really helped in finding this difficult bug
