### ISSUE TITLE
Feature Request: Tool Ordering

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#387]
I would recommend changing the parameter “Change metalworks behavior on zero” and “Tool ordering” into one parameter called metalworks.
This parameter has 3 options:

- Standard s2 behavior
- Activate tool ordering
- Activate tool ordering and produce nothing if no orders
- No tool ordering but produce nothing if no percentage (I am not sure if anybody is really using this combination; I would remove it, but it is for sure a point for discussion ;-) )

Best Case: If Activate tool ordering and produce nothing if no orders is activated, the tool ordering screen has automatically 0% for all tools.

As far as I know, the functionality that with activated tool ordering the percentage is 0, is not possible. Therefore I would like to request a button, like the one set to default, with which all tools get 0% (see example screen).

![tool ordering](https://cloud.githubusercontent.com/assets/14259828/12872131/95971f56-cd99-11e5-9214-b17397923201.PNG)

**Comment by Flamefire** [comment]
Won't do that. These are 2 orthogonal features: Ability to order tools and produce nothing on 0%. Putting both in 1 setting is possible, but actually this means you have 4 options, which is the same as 2 settings with 2 options each.

No tool ordering and produce nothing is actually what many might use: You only produce something, when you set it to more than 0%. So an improved S2 behaviour.

Regarding your last case: Tool ordering + all set to 0% means: Produce tools that you order and else randomly or nothing depending on the other setting.

BTW: Settlers 4 is similar: You can set a percentages but also order tools/weapons.


So unless there is a really good reason to have 1 setting or there are more who want this, I'll close this as I don't see any advantage.

**Comment by BlOedsin** [comment]
I think I tried to add to many ideas and assumptions into one post. 
My assumption was not at all to remove the functionality of percentage! 
I agree that most players will use “No tool ordering and produce nothing” as it is a huge increase in the comfort. This is also my preferred setting.
If you do that, the first thing, before you build a metalworks is set all percentage values to 0%. Which means, that you need to do that for each tool once. Cause as soon as at least one value is bigger than 0% the metal worker is producing and not stopping.

**Therefore I would like to have a 2nd button, which sets all percentage values to 0%. The existing button for s2 default values shall stay!** ( see picture)

![tool_order_button](https://cloud.githubusercontent.com/assets/14259828/13032496/526de65e-d2f5-11e5-9258-b5d5d6f14c3d.jpg)


This idea was than extended, that if I have “No tool ordering and produce nothing” activated, I do that because I want to have the control over my production. Therefore an additional increase of comfort would be:
“No tool ordering and produce nothing” is activated the percentage values are set by default to 0%. If I increase at least one tool above 0%, the tools are again produced by percentage, as it is now.

Last idea was the parameters list: It happened to me already a couple of times, that I forgot to select some of the parameters, as the list is already quite long. As the parameters “No tool ordering and produce nothing” are linked and for most players changed together (and one is at the top of the list and one at the bottom) I had the idea of combining this two values, to have a shorter list.

Note: I do not see that features in the next release, cause 0.8.3 is in my opinion almost ready to be considered as a “stable version” and new features might have new side effects…

**So what I would really ask you is this button, for setting all values to 0%. All the other things are just an extension of that idea.**

**Comment by Spikeone** [comment]
I'd really like a "Set to 0 button"
