### ISSUE TITLE
Feature Request: Coins by default on conquered buildings

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#388]
I would appreciate, if there is a 2nd option for the deactivate cons by default. Changing the Boolean value no coins by default to:
- Coins by default allowed
- Coins by default not allowed
- Coins by default not allowed even on conquered buildings

Cause if you conquered a building, it would be nice, if it automatically changes to no coins. So you do not need to double check, if coins is really deactivated, before connecting the road to it.

**Comment by Spikeone** [comment]
If you connect the building you will see if coins are activated or not, rttr actually stops coins even when they are already sent (s continued).
But hey, if it's an addon - there should be an option which also auto enables coins for conquered buildings, so it's a bit more difficult ;)

**Comment by alfakr0ll** [comment]
If you conquer a building, the building keep the coin settings.

The addon setting (it should get it's own independent of the other). It could be:

"When conquering a building the coin setting should be:
-same as before (keep the setting the opponent had on that buiding)
-auto disable
-auto enable 
"

**Comment by Shawn8901** [comment]
@Flow86 @Flamefire i thin you could close the issue, as #820 is now merged and implements the requested logic.

**Comment by Flamefire** [comment]
Closed by #820 
@Shawn8901 : Put a 'Closes #<number>' or 'Fixes #<number>' into your commit message (last line) to have this closed automatically
