### ISSUE TITLE
(AI?) soldiers walking from military building to flag and back

### ISSUE THREAD

**Issue by MarcusSt** [Return-To-The-Roots/s25client#39]
Another bug from 20150728:

(AI?) soldiers are walking from the military building to the flag and back.
Not (always) reproducible from saved game or replay, since replay becomes async sometimes (see separate bug) and doesn't reappear after loading.

Video: https://www.youtube.com/watch?v=j4aKGMfrl7w&feature=youtu.be

Replay: https://dl.dropboxusercontent.com/u/11244516/RTTR/2015-07-29_08-47-50.rpl

**Comment by jhkl** [comment]
The flag of the fortress is at y == 0, the fortress itself is at y == 255. The attacked goal is at y == 236 (reason for leaving the building). Probably there is something wrong with the crossing of the "border".

**Comment by jhkl** [comment]
Ah, it is also strange that the attack seems to be called multiple times. Otherwise this should happen only once.

**Comment by jhkl** [comment]
Actually all attacks were made impossible by commit 8148166dc1ce561d2dc22a614cdd79c74d50cf6d
