### ISSUE TITLE
Sea map – no expedition possible

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#390]
As on non-sea map I did not have any issues in the last games, I was optimistic, to test a sea map again… 

![screenshot2](https://cloud.githubusercontent.com/assets/14259828/13001211/c41b0090-d163-11e5-9474-59cda0a28bc1.PNG)

-	I cannot send my ship anywhere to build a harbor. 
AI players are able to send ships there.
-	The watchtower north of my harbor building was not replaced for quite a long time
Attached:
savegame and replay
https://www.sendspace.com/filegroup/IYJYux8OawolPzBX2Pm3%2BQ

**Comment by Flamefire** [comment]
Ok, thanks for testing. Will validate this later today

Can you explain a bit more what you mean with your 2nd point: "was not replaced..."? Do you mean, that soldier did not enter it? If so, can you get the GFs of interest? So when was it empty and until which GF did new soldiers enter? Should be easier for you to find the right time as you know the game and it saves us quite some time :)

**Comment by BlOedsin** [comment]
At GF 40.000 there is an atack

![attack](https://cloud.githubusercontent.com/assets/14259828/13002214/014ceb8c-d16d-11e5-9768-17962cf5f330.PNG)

After that attack, the tower is being replaced. I do not remember to send more than one atacker there. furthermore, the two other ships are empty. so if there would be further attacks, the other ships should also transport solders.... My feeling is, that something went wrong between 30.000 and 35.000

**Comment by Flamefire** [comment]
Ok, I found the bugs. This will be fixed as soon as the build server comes back on.

**Comment by BlOedsin** [comment]
but this is only the fix for part 1 right?
did you find an explanation for the part 2 as well?

**Comment by Flamefire** [comment]
Forgot to push the 2nd commit. Yep I found it: The military building did not order new soldiers when some where sent out. So new soldiers just arrive at some events (e.g. road constructed, soldier returned/recruited)

**Comment by BlOedsin** [comment]
:-)
