### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by MarcusSt** [Return-To-The-Roots/s25client#40]
Bug only happens sometimes: I have been able to load the replay several times without the game becoming async, at other times it becomes async.

Replay: https://dl.dropboxusercontent.com/u/11244516/RTTR/2015-07-29_08-47-50.rpl
Nightly 20150728

**Comment by jhkl** [comment]
When "should" the async happen? Just to know how long I have to wait :)

**Comment by MarcusSt** [comment]
This should hopefully not happen any more.
