### ISSUE TITLE
GameClientPlayer::GetBuidingSitePriority: ERROR: BuildingSite or type of it not found in the list!

### ISSUE THREAD

**Issue by maximiliankaul** [Return-To-The-Roots/s25client#402]
Hi,
I'm getting the following message when playing:

> GameClientPlayer::GetBuidingSitePriority: ERROR: BuildingSite or type of it not found in the list!

I play on linux using a version I compiled myself (gameversion=77ddfc87169a59556f77bf4da352056222cad4b9).
The game doesn't crash or shows any weird behavior I noticed.
This error happend while playing with a friend ("Direktes IP Spiel").
Feel free to ask if you need additional information.

**Comment by Flow86** [comment]
Hi,

please upload replay and or savegame of it, so @Flamefire can take a look

**Comment by maximiliankaul** [comment]
Unfortunately I only have an auto-save from the end of the game. The issue occurred after approximately 1/3 of the save-game I uploaded. Does this help?

[rttr.zip](https://github.com/Return-To-The-Roots/s25client/files/160358/rttr.zip)

**Comment by Flamefire** [comment]
Without the replay it is almost impossible. But I found something: Did you use custom build orders and build a charburner (or someone else) at that point?

**Comment by maximiliankaul** [comment]
Yes, I did.
I'm new to this project (it's amazing - thanks!) so I wasn't aware that the replays are automatically saved.
[replay.zip](https://github.com/Return-To-The-Roots/s25client/files/160390/replay.zip)
Jumping to GF 46000 reproduces the error.

**Comment by Flamefire** [comment]
Ok. Problem was caused by bad coding: Using integers instead of enum values in https://github.com/Return-To-The-Roots/s25client/blob/master/src/GameClientPlayer.cpp#L135

Commit is prepared and will be there later today. Unfortunately this will change the savegame version
