### ISSUE TITLE
Improve speed changes

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#406]
From #404: Pressing 'v'  multiple times will ignore some of them. So it should be improved, so that the client sends the speed he wants, not only a speed change.
Also the icon is only shown on high speed settings but we have 6 levels of speed which make it seem as speed is not changed.

**Comment by shadowvzs** [comment]
did u checked videos from previous thread about terminal?

**Comment by Flamefire** [comment]
The behaviour is absolutely expected. See my comment: https://github.com/Return-To-The-Roots/s25client/issues/404#issuecomment-193871067

**Comment by Spikeone** [comment]
Should we add some graphics with indicators or something for all speeds?

**Comment by Flamefire** [comment]
I thought about writing something like "1.5x" into the runner. But maybe extra graphics would be nice

**Comment by shadowvzs** [comment]
Number sub runner would be enough: 1.5x, 2x, 3x, 5x etc, I like that and faster to do I guess to u
