### ISSUE TITLE
Geologist found nothing on mountain

### ISSUE THREAD

**Issue by shadowvzs** [Return-To-The-Roots/s25client#407]
(ubuntu 14.04 64bit)
hi, i dont know it's because the update from 20160213 => 20160307/8 or i checked out the infinite mine/granite mines/fish deposits in addon but geolgist doesn't found any mine anymore, i can send how many i want, they show animation about searching with hammer but no result (that little picture what show if coal/iron/gold or stone) then geologist go back to warehouse, without any mine deposit notification.

**Comment by Flamefire** [comment]
Can you check the latest version? There was a bug yesterday.
Do they put there any signs? Or are the signs just empty?

**Comment by shadowvzs** [comment]
today work, seems fixed (was problem with sign post yesterday but today only now was able to test and seems now work)

**Comment by Flamefire** [comment]
Ok, then I'll close this. If you see this again, please tell us

**Comment by bcoolumbo** [comment]
again

**Comment by Flamefire** [comment]
Ok, could you attach the replay, savegame and map (or what you have of them) and explain where it happens?
