### ISSUE TITLE
Invisible Ships and Main Menu Problems

### ISSUE THREAD

**Issue by xasz** [Return-To-The-Roots/s25client#408]
I had some invisible ships and transportation standing on the harbor they where invisible. 

Somehow the main menu (ingame)act weirds aswell, if i open the menu and close it, all subwindows are gone (dunno if feature or bug) and if i 
open u subwindow and then press another button in the main menu the window closes aswell.

Version: v20160308-b912e72

**Comment by Flamefire** [comment]
Do you have a savegame and replay and a better description for the ships?

**Comment by mrumler** [comment]
I can confirm menu problems in v20160308-b912e72.
Main Menu: To reproduce open main menu, open inventar window via main menu click, try to open craft tools window via main menu click -> it will trigger inventar button again and close it.
Disable gold delivery button: If I open a couple of military building windows and close the one on the highest layer, of course the next top one gets the focus. Clicking on the gold delivery button didn't trigger the button. Clicking it twice or clicking anything else to ensure the focus (optical it was already focused) will do the job.
Have not tried any ship things.

**Comment by xasz** [comment]
Yeah i will try to reproduce the ship behaviour, but i probely cannot do it today

**Comment by Flamefire** [comment]
Already found. Thanks :)
