### ISSUE TITLE
The Game is not in sync.

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#41]
Rev 34ada31 / Async after 4730 GFs

Players: 6x AI + 2x Human, no Human actions

http://www.rfmonline.de/rttr/spike/async_001.rar

https://dl.dropboxusercontent.com/u/11244516/RTTR/2015-07-29_18-51-58.rpl
https://dl.dropboxusercontent.com/u/11244516/RTTR/2015-07-29_18-43-46.log

**Comment by MarcusSt** [comment]
Every test game so far led to asyncs after only a few thousand GFs, which renders the game unplayable. :-(

**Comment by Flamefire** [comment]
Should be fixed
