### ISSUE TITLE
Loading game

### ISSUE THREAD

**Issue by shadowvzs** [Return-To-The-Roots/s25client#410]
yesterday night played and overwrited a old savegame file then quit from game (was some error at saveing in terminal, i guess with version difference but i don't thinked its serious because was unable to see old save file few day ago)

today i wanted load the game with resume last game and unable to load

> SavedFile::Load: ERROR: Old file version (version: 30; expected: 31)!
> SavedFile::Load: ERROR: Old file version (version: 30; expected: 31)!
> SavedFile::Load: ERROR: Old file version (version: 30; expected: 31)!
> SavedFile::Load: ERROR: Old file version (version: 30; expected: 31)!
> loading aijh: Computer 1 (AI) (easy) 
> Connection to 127.0.0.1:3665
> Sucessfully connected to localhost:3665
> Loading settings...Done.
> SERVER: Using gameframe length of 40ms
> SERVER: Using networkframe length of 6 GFs (240ms)
> Error when loading game: Invalid GameObjectType 0 for objId=3439329280 found!
> client state changed to stop
> server state changed to stop

**Comment by Flamefire** [comment]
Please attach replay and savegame so we can investigate it.

**Comment by shadowvzs** [comment]
http://1drv.ms/1M4yR4U
save&load folder
i uploaded auto-save too

**Comment by shadowvzs** [comment]
Yesterday started same map with same add-on, different start place (red) less conquered island&buildings (less harbour,ship,mines,units etc earlier game) and morning this newer game was able to load. I curious when I go back to home still can load save from morning

**Comment by Flamefire** [comment]
I found an issue in your replay. The replay starts around GF 189000. Do you happen to have the replay before that? Need to find, what let to this bug

**Comment by shadowvzs** [comment]
previous replay was 1 day before, so at march 8th (this was 9th), i uploaded these too if needed with all existing replay

**Comment by shadowvzs** [comment]
i guess addon's make this error, atleast its wrote after/before addon loading in log file, but now loaded succesfully still was this error i logs 4x
SavedFile::Load: ERROR: Old file version (version: 30; expected: 31)!

used inexhaustable granite mine, mine, fish, half soldier cost, sea fight with harbour not block,..

same error at saveing

> >>> Addon Status:
> 	0x00300001=0
> 	0x00500000=1
> 	0x00300000=0
> 	0x00200000=0
> 	0x00000007=0
> 	0x00200003=0
> 	0x00200002=0
> 	0x00100000=0
> 	0x00400000=0
> 	0x00900006=1
> 	0x00100001=0
> 	0x00000003=0
> 	0x00900007=1
> 	0x00900005=0
> 	0x00900002=1
> 	0x00800000=1
> 	0x00000001=1
> 	0x00000000=0
> 	0x00000005=0
> 	0x00700000=0
> 	0x00900008=0
> 	0x00B00000=0
> 	0x00900003=5
> 	0x00000006=1
> 	0x00000002=4
> 	0x00000004=0
> 	0x00900001=0
> 	0x00900004=0
> 	0x00900000=0
> 	0x00200001=1
> 	0x00A00000=3
> 	0x00600001=0
> 	0x00100002=0
> <<< Addon Status:
> 	0x00300001=0
> 	0x00500000=1
> 	0x00300000=0
> 	0x00200000=0
> 	0x00000007=0
> 	0x00200003=0
> 	0x00200002=0
> 	0x00100000=0
> 	0x00400000=0
> 	0x00900006=1
> 	0x00100001=0
> 	0x00000003=0
> 	0x00900007=1
> 	0x00900005=0
> 	0x00900002=1
> 	0x00800000=1
> 	0x00000001=1
> 	0x00000000=0
> 	0x00000005=0
> 	0x00700000=0
> 	0x00900008=0
> 	0x00B00000=0
> 	0x00900003=5
> 	0x00000006=1
> 	0x00000002=4
> 	0x00000004=0
> 	0x00900001=0
> 	0x00900004=0
> 	0x00900000=0
> 	0x00200001=1
> 	0x00A00000=3
> 	0x00600001=0
> 	0x00100002=0
> >>> Addon Status:
> 	0x00300001=0
> 	0x00500000=1
> 	0x00300000=0
> 	0x00200000=0
> 	0x00000007=0
> 	0x00200003=0
> 	0x00200002=0
> 	0x00100000=0
> 	0x00400000=0
> 	0x00900006=1
> 	0x00100001=0
> 	0x00000003=0
> 	0x00900007=1
> 	0x00900005=0
> 	0x00900002=1
> 	0x00800000=1
> 	0x00000001=1
> 	0x00000000=0
> 	0x00000005=0
> 	0x00700000=0
> 	0x00900008=0
> 	0x00B00000=0
> 	0x00900003=5
> 	0x00000006=1
> 	0x00000002=4
> 	0x00000004=0
> 	0x00900001=0
> 	0x00900004=0
> 	0x00900000=0
> 	0x00200001=1
> 	0x00A00000=3
> 	0x00600001=0
> 	0x00100002=0
> SavedFile::Load: ERROR: Old file version (version: 30; expected: 31)!
> <<< Addon Status:
> 	0x00300001=0
> 	0x00500000=1
> 	0x00300000=0
> 	0x00200000=0
> 	0x00000007=0
> 	0x00200003=0
> 	0x00200002=0
> 	0x00100000=0
> 	0x00400000=0
> 	0x00900006=0
> 	0x00100001=1
> 	0x00000003=0
> 	0x00900007=0
> 	0x00900005=0
> 	0x00900002=0
> 	0x00800000=0
> 	0x00000001=1
> 	0x00000000=0
> 	0x00000005=0
> 	0x00700000=0
> 	0x00900008=0
> 	0x00B00000=0
> 	0x00900003=5
> 	0x00000006=0
> 	0x00000002=4
> 	0x00000004=0
> 	0x00900001=0
> 	0x00900004=0
> 	0x00900000=0
> 	0x00200001=1
> 	0x00A00000=2
> 	0x00600001=0
> 	0x00100002=0
> <<< Addon Status:
> 	0x00300001=0
> 	0x00500000=1
> 	0x00300000=0
> 	0x00200000=0
> 	0x00000007=0
> 	0x00200003=0
> 	0x00200002=0
> 	0x00100000=0
> 	0x00400000=0
> 	0x00900006=1
> 	0x00100001=0
> 	0x00000003=0
> 	0x00900007=1
> 	0x00900005=0
> 	0x00900002=1
> 	0x00800000=1
> 	0x00000001=1
> 	0x00000000=0
> 	0x00000005=0
> 	0x00700000=0
> 	0x00900008=0
> 	0x00B00000=0
> 	0x00900003=5
> 	0x00000006=1
> 	0x00000002=4
> 	0x00000004=0
> 	0x00900001=0
> 	0x00900004=0
> 	0x00900000=0
> 	0x00200001=1
> 	0x00A00000=3
> 	0x00600001=0
> 	0x00100002=0
> SavedFile::Load: ERROR: Old file version (version: 30; expected: 31)!
> <<< Addon Status:
> 	0x00300001=0
> 	0x00500000=1
> 	0x00300000=0
> 	0x00200000=0
> 	0x00000007=0
> 	0x00200003=0
> 	0x00200002=1
> 	0x00100000=0
> 	0x00400000=0
> 	0x00900006=0
> 	0x00100001=0
> 	0x00000003=0
> 	0x00900007=1
> 	0x00900005=0
> 	0x00900002=1
> 	0x00800000=1
> 	0x00000001=1
> 	0x00000000=0
> 	0x00000005=0
> 	0x00700000=0
> 	0x00900008=0
> 	0x00B00000=0
> 	0x00900003=5
> 	0x00000006=0
> 	0x00000002=4
> 	0x00000004=0
> 	0x00900001=0
> 	0x00900004=0
> 	0x00900000=0
> 	0x00200001=1
> 	0x00A00000=3
> 	0x00600001=0
> 	0x00100002=0
> SavedFile::Load: ERROR: Old file version (version: 30; expected: 31)!
> <<< Addon Status:
> 	0x00300001=0
> 	0x00500000=1
> 	0x00300000=0
> 	0x00200000=0
> 	0x00000007=0
> 	0x00200003=0
> 	0x00200002=0
> 	0x00100000=0
> 	0x00400000=0
> 	0x00900006=1
> 	0x00100001=0
> 	0x00000003=0
> 	0x00900007=1
> 	0x00900005=0
> 	0x00900002=1
> 	0x00800000=1
> 	0x00000001=1
> 	0x00000000=0
> 	0x00000005=0
> 	0x00700000=0
> 	0x00900008=0
> 	0x00B00000=0
> 	0x00900003=5
> 	0x00000006=1
> 	0x00000002=4
> 	0x00000004=0
> 	0x00900001=0
> 	0x00900004=0
> 	0x00900000=0
> 	0x00200001=1
> 	0x00A00000=3
> 	0x00600001=0
> 	0x00100002=0
> SavedFile::Load: ERROR: Old file version (version: 30; expected: 31)!

**Comment by Flamefire** [comment]
Addons are not the problem. The log only shows when loading them, so the error exists after Addons are loaded but that does not tell anything about when the error happens.

In this case a builder was wrongly scared by a harbor attack and left its buildingsite without notifying it.

This is now fixed. Please start a new game to make sure, no errors exist in a savegame
