### ISSUE TITLE
Scout recruit

### ISSUE THREAD

**Issue by shadowvzs** [Return-To-The-Roots/s25client#412]
Serf need any tool to became scout?
Built 4 tower on islands totally and after ~20 min still nobody occupied them, also was no scout for explorations expedition, they aren't only from normal serfs?
Or can't be recruited in harbour? Addons block the makeing scouts? 
In s2 never felt problem with scouta, allways was enough but somehow here in island maps I feel they allways missing or too lesz from them

**Comment by Spikeone** [comment]
You need a bow for each scout you recruit. The amount of bows/scouts is depend ant on start resources but they are the same as in original settlers 2.

Seafaring also needs 3 scouts for an exploration expedition, maybe your scouts are on an exploration expedition or you started one but only 2 scouts were left so they keep waiting in a harbor.

**Comment by shadowvzs** [comment]
I clicked to more not just one but neither started..... I guess 2-2 stucked
So sea exploration make huge difference even its not even started.... Can't be expedition with 1scout or 1scout+10serf?

**Comment by shadowvzs** [comment]
Or more bow if sea fight enabled

**Comment by shadowvzs** [comment]
I play with  sea fight+animal respawn 1000% and with 'a lot' starting resource still insufficient bow, maybe add +1 bow for each 100% respawn or 0.5 bow and 6scout for 'a lot' what sufficient for 1 expl. expedition and few tower, for normal start 4 scout if sea fight enabled or reduced scout requiment for sea exp. , what do you think? 
Without sea expedition scout isn't problem, like in s2

**Comment by Flamefire** [comment]
I would not change the current settings. If you need more bows, produce some more. This is how the game works...
You possibly started multiple expeditions. So if you have 4 scouts and start 2 expeditions it might happen that they get each 2 scouts and neither of them starts. Just abort 1 expedition and all is fine. Or produce some bows.

**Comment by shadowvzs** [comment]
Then at least in addons can't make option for this? (More bow or scout or less scout for ahip)
Because really alot more needed the scout on maps where there 10+ island and playing with ' a lot'  isn't sufficient so if possible option in addons that would awasime for island msps

**Comment by Spikeone** [comment]
You can, suggest an addon, maybe it will be added.

**Comment by Flamefire** [comment]
Then maybe just set the required scouts for an exploration expedition to 1 for all games? This would also avoid deadlocks (4 scouts, 3 required per expedition, 2 waiting on each)
I would avoid such an addon if possible as this might be an "always chosen" addon so we can as well integrate it in the game.

**Comment by shadowvzs** [comment]
that would be nice, because really huge difference if on map have 2 harbor place or nothing or have ~15-20 harbor place like insland maps like one in Sea maps (ex. wasserwegen or what, best map ever) there only 1 island have 4 harbor place and 4 island have 2 and if i remember well then another 4-6 island also have harbor places, so its 4+8+(4 or 6)

to be honest i love this kind of map because enough balanced for both 4 player and alot of fun aswell but need alot expedition, really alot with random exploration exp. but still alot fun (even comp very fast start build harbors - [this isnt problem just hard to keep up with comp because who take more island and take more granite will win])

**Comment by Flamefire** [comment]
@Spikeone: What do you think? Only 1 scout for expeditions?

**Comment by Spikeone** [comment]
Nope. Exploration expeditions are quite strong in seafaring games, those are mobile lookouttower you can't even destroy.
In this case I think an addon idea is better. 1 scout for easy , 3 normal, 5 hard. 
A maximum wait for scout time for each exploration expedition (if scouts are on their way eg with a ship this timer should be stopped) and if the timer exceeded the expedition should be cancelled with a message.

IMPORTANT: We should add an addon to disable those exploration expeditions at all (not in the original and should be used only if sea fights are enabled)

**Comment by shadowvzs** [comment]
A little difference is tower I place but sea exploration is random, sometimes need more expedition for reach a island (map depend I guess , more island on map make harder to reach a desired island.
So  this is huge difference between map with 2 harbour place or where 15 and computer at easy take minimum half island before you wake up (more island with faster stone gathering win in long term game)
My view point is good if add-on or if depend from hogy much harbor place on map or how many island on map or built in normal game, only important be somewhere if possible :)) 

Disabling expl. expedition is OK if sea fight is off.

**Comment by Spikeone** [comment]
Yeah that's what those maps are made for, further harbor spots might require further exploration expedition which might require more bows so you need a better economy and therefore be a better player than your oponents.

That's why a simple 1,3,5 ad found would be good enough.
