### ISSUE TITLE
What happen with building materials at 100% refund?

### ISSUE THREAD

**Issue by shadowvzs** [Return-To-The-Roots/s25client#413]
At 100% refund if we destroy a castle kind building then it's more stone+plank than max limit what can be at flag at front of buildings...
Or difference between building cost and Max storeable stuff at road flag go directly to HQ? Or 100% not 100%?

**Comment by Flamefire** [comment]
Everything that cannot be put at the flag is lost. This is the behaviour throughout the game (road with carrier destroyed -> Ware lost)

**Comment by shadowvzs** [comment]
I see, so this is how it must work, 100% but max 5 item (if I remember well)

**Comment by Flamefire** [comment]
8 Items is the max for a flag
