### ISSUE TITLE
Add simple map format

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#415]
The original game uses maps with 14 blocks. As we don't need most of them (rsu, usd, obj, objtype, animals, resources, heights) we could add a map format where those blocks aren't included at all. That way we could save a lot of space and network traffic for big maps.

That'd be great - this is not a new map format but reading maps would be much faster and building a converter quite easy.

**Comment by Flamefire** [comment]
We should in general consider using better formats. E.g. I'd like to move away from the terrain specific stuff and make everything available in all maps.
For your request: Each block has a header containing id, NULL, used, width, height, length
We could implement a logic, that actually checks the used byte and skips the block if it is 0.
That way the change is within the format itself (probably even allowed in the original) but map size is much reduced. Before maps are sent, I'd load them, save without these unrequired blocks and transfer this reduced ones. Would make it already much smaller...

**Comment by Spikeone** [comment]
Sounds good, map headers could be expanded if needed and we could save some space to decrease our archive size a bit.
This would also solves other request.
A rttr map format should be added but change a lot.

**Comment by Spikeone** [comment]
The used byte is... http://settlers2.net/documentation/world-map-file-format-wldswd/ 01 00 ? => 00 00 = unused?

**Comment by Flamefire** [comment]
Yes. And length etc should be 0 too. So all 0 in the header except the 0x1027

**Comment by Spikeone** [comment]
Okay, thanks :)
