### ISSUE TITLE
Inexhaustable mine addon

### ISSUE THREAD

**Issue by shadowvzs** [Return-To-The-Roots/s25client#416]
Have inexhaustable mines and inexhaustable granite mine, first is coal, iron and gold only so ore mines?

Just a idea but u can make 4 option each with combo box:

-gold mine behavior: off, on, unlimited, iron, coal, granite
Coal mine behavior: on, off, unlimited
Iron mine behavior: on, off, unlimited, gold, granite, coal.
Granite mine behavior: on , off, unlimited, gold, iron, coal

If gold mine behavior is coal but coal is off then coal mine behavior have priority so no coal&gold on map(exhausted at start)

If no iron on map then disable ironsmelter&armoury&metalworks
If no any gold then disable mint
If no coal and either charcoal is  off then no mint&iron smelter&armour y&metal works

If mine on then have map default amount ore.

U can remove 4 add-on option for this 4 so add-on list length will same,.

What do you think?

**Comment by Spikeone** [comment]
I think most maps aren't made for such settings - I'd like to have a s4 like setting instead.

**Comment by shadowvzs** [comment]
This idrea just make options for make funnier, ex most of map got most from coal then iron then gold, if we swap mines then it's slow down or force player to use different strategy (ex no coal mine, charcoal burner need different resource so player must setup different economy)

To be honest it's just idea, because I noticed if u do 4 mine option separate then no need another 4, ex gold mine behavior or coin disabling, granite mine option and global mine option because it's do same or similar if we see the effect.

I not real

**Comment by shadowvzs** [comment]
Ly played s4, my favorite is s2 then was s3, but after that not really played, lost  the trully settler feeling, how the s4 option work?

**Comment by Spikeone** [comment]
Resources slowly decrease when mined but never deplete. Eg with 100% resources left you have a 100% chance to get the resource, when you mined 50% of underlying resources you have a 50% chance, when only 1 ore is left at each spot you still have a small chance to get ore but most likely not.

Everything else is part of map design and... IMHO we should not change nearly everything that is Mel dependant as it might cause more false bug reports than anything else (eg a map that is balanced could be imbalanced by most of those addons, including existing).

**Comment by shadowvzs** [comment]
I understand, that mine system at low % just poor food eater, like a whale :)))

**Comment by Spikeone** [comment]
I'll close this issue for now, we might add an mining overhaul addon or something like that so that would create a new issue.
