### ISSUE TITLE
Harbour defence / military expedition

### ISSUE THREAD

**Issue by shadowvzs** [Return-To-The-Roots/s25client#417]
I am just curious are u planing improve the newly built harbour defense?

Why I ask? Because I am island map fun, it's most exciting the island maps but often happen when I or computer build a harbour then come a weak soldier and burn up, this going vice-versa till one of us have no granite or have too much advantage.
Could have 30 ship still not enough to send soldiers in time.

I just ask do u want change this? 
Absolutely not about changes current  expedition, maybe make a new expedition like military expedition ex. Same than normal + 5shield/sword/beer or 5 free soldier, ship wait till building done and unload items or soldiers.
Or a button what request harbour defender soldier(that much how much setted in harbour page3) highest priority soon if a ship is empty, so ready to this.

What do you think?

**Comment by Flamefire** [comment]
We should probably include like 3 soldiers or so in the expeditions, but this is hard, logic wise (where are they during the construction)
You can set the reserve once the harbor is build and the harbour should request this reserve so soldiers get shipped there. This should already do what you want. If not, this might be a bug
I think other changes would be to intrusive for the game (changing to much)

**Comment by shadowvzs** [comment]
About reserve in harbour yes it possible now but isn't top priority to transport troop from your island to colony island and till this happen the harbor kind install lost by even 1 weakest soldier without fight, you can be sure enemy can send faster a attacker ship or simple attack than you your reservist soldier to harbour if it is between you and enemy (honestly it's same if enemy build harbour, it's free kill to u without fight)

About your 1st comment part, they could stay in ship till it's built? I mean sea attacker ship also wait till target building occupied by units then ship bring back your soldier to their place, could be done similar with this military expedition?
Of course without remove the original, because player can choose between unsafe expedition but ship not busy till harbour done or safer but ship required harbour construction (I think fair trade also it's not huge advantage if only 3 soldier will be at harbour, still occupieable but at least with fight)

Or this too hard to do?
To be honest I am really glad about your job with s2 and improvements like sea fight, this just ideea

**Comment by Spikeone** [comment]
Reserve is not and should not be requested.

That problem is map and setting dependent! Currently it isn't perfect at all - but there aren't that much options to make seafaring good enough for multiplayer in a logic way.

Just at the moment I think about something like attack your own harbor in order to ship soldiers.
Otherwise the seafaring system should be changed completely in order to have a good combat version.

**Comment by shadowvzs** [comment]
That idea sound good, will just with regroup text not attack title but really is sound good because attack the highest priority thing.

I like current sea fight, how can attack enemy.

**Comment by Spikeone** [comment]
Just search our wiki, I added an article and tutorial videos.

**Comment by shadowvzs** [comment]
I meant I like the current method and I know how I can attack, I am in love vs wasserwegen map, every time I play only that.

How can u make attackable the own harbour because when we click then it's open like warehouse

**Comment by Spikeone** [comment]
You can't. That was an idea how we could possibly solve the problem. As you can be only attacked if you harbor is spotted by an enemy you should be faster. Otherwise you may not occupy that island until you have weakened your enemy. Also you should only use fow, not s2 like or everything scouted.
