### ISSUE TITLE
Game doesn't launch anymore

### ISSUE THREAD

**Issue by sonchusarvesis** [Return-To-The-Roots/s25client#420]
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
xxx/bin/rttr.sh: line 60:  1289 Aborted                 $cmd $DIR/../bin/s25client $*
An error occured: press enter to continue

**Comment by Flamefire** [comment]
Which system are you on? Which language is your system language?
Does this happen before the main menu?

**Comment by Flamefire** [comment]
I just pushed another version that checks for obvious problems and showing a bit better help on that issue. I assume your locale setting is wrong (check the new version and your `LC_ALL` env variable)

**Comment by sonchusarvesis** [comment]
Yes, there was indeed a suspicious environment variable, thank you!

**Comment by Flamefire** [comment]
Closed as resolved

**Comment by sonchusarvesis** [comment]
Now I got
Loading settings...Addon 0x8 not found!
Addon 0x9 not found!
Addon 0xa not found!
Addon 0xb not found!
Addon 0xc not found!
Done.
Addon 0x8 not found!
Addon 0x9 not found!
Addon 0xa not found!
Addon 0xb not found!
Addon 0xc not found!
Connection to 127.0.0.1:xxxx
Connection failed
Error: Connection refused
Error connection to localhost:xxxx
GameClient::Connect: ERROR: Connect failed!
and it still doesn't start

**Comment by Flamefire** [comment]
What system do you have? What language is your system? Did you censor the port? Did you use a save game? Which map?

**Comment by sonchusarvesis** [comment]
Any map, firewall disabled, debian, en_US.UTF-8

**Comment by Flamefire** [comment]
Found something. Try again

**Comment by sonchusarvesis** [comment]
Now it starts again, thanks a lot!
