### ISSUE TITLE
Show coordinates in Multiplayer [F3]

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#424]
I Liked it when it was possible to show coordinates in multiplayer as this is quite nice for communication.
Thats why I'd still like to have this, I don't see any abuse for coordinates so.

**Comment by Flamefire** [comment]
It is still there and even advanced. But it only works for replays and singleplayer games to avoid cheating

**Comment by Spikeone** [comment]
But it should still display coordinates in Multiplayer - as this is quite usefull for tactics. I don't like explaining "The forester next to the quarry who is currently working", insteand I'd like to say "The building at 123:456". I know the "notify" message we have but thats good for showing an area, not a specific point.

**Comment by MarcusSt** [comment]
I think it would be a compromise to change F3 for multiplayer to just show the coordinates and nothing more. It should not open the map debug window then.

**Comment by Spikeone** [comment]
That'd be okay, just the way it was before, maybe add F4 for non multiplayer which displays both.

**Comment by Flamefire** [comment]
@MarcusSt The window is responsible for the overlay in the current design. I would not like to use the coordinates for multiplayer coordination, as this is quite intrusive. Rather implement #427 and/or a shortcut for this (SHIFT+click ?)
We could however use that window but make it only display coordinates in multiplayer games.

**Comment by MarcusSt** [comment]
Coordinates have been quite useful for reporting bugs in the past. Maybe we could do something less intrusive by just adding the cursor coordinate somewhere at the top or bottom of the screen. I think #427 makes sense independently from showing coordinates.

**Comment by Flamefire** [comment]
Good idea. Probably where the GFs are shown? I'd also add a toggle to show these data (GF#, time, position) there only when this is on, as it is useless to the average user
