### ISSUE TITLE
Observation window zoom

### ISSUE THREAD

**Issue by shadowvzs** [Return-To-The-Roots/s25client#425]
can't zoom in observation windows, if i click to magnifier nothing happen, in normal s2 was zoom, here changed or just not work?

**Comment by Dpunkt** [comment]
Zoom for full game is missing, too.
In the DOS game you had to press "z".
Using RTTR with HD-Displays is nearly unplayable without zoom.

**Comment by depate** [comment]
I can confirm, that this issue is (still) there. On high resolution displays it's hard to determine small icons or e.g. the colour of mining signs, coal or iron. 

Maybe there is a general zoom-option needed...?

**Comment by Spikeone** [comment]
Hm - fullscreen and use a low resolution?

But linear scaling would be nice.

**Comment by Flamefire** [comment]
Actually using a lower resolution is already the solution, as a zoom would do the same thing...
With SDL2 zooming will be much easier to implement. But at least for the observation window it should work.

**Comment by Dpunkt** [comment]
Zooming could be with a correct aspect ratio and independent for gameworld and game windows

**Comment by Spikeone** [comment]
Also I like playing windowed where to fullscreen thing isn't working.

**Comment by Flamefire** [comment]
This is now implemented and will be available with the next release
