### ISSUE TITLE
locale error on os.x

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#429]
```
Liebes SF-Team,

leider erscheint folgende Fehlermeldung, wenn ich den s25client unter OS.X EL Capitan starten möchte.

locale: cannot set lc_ctype to default locale: no such file or directory

Können Ihr da weiterhelfen?

Gruß
Maximilian
```

**Comment by Flamefire** [comment]
Scheint keine Fehlermeldung von RTTR zu sein, also muss es ein system-problem sein. --> Google

**Comment by Flow86** [comment]
ja die meldung kommt bei linux z.b wenn das locale nicht existiert das versucht wird zu setzen

**Comment by Flamefire** [comment]
Eine Idee wäre, die Zeile zu löschen: https://github.com/Return-To-The-Roots/s25client/blob/master/src/main.cpp#L232 wo das locale auf "" gesetzt wird. Ich denke, dass das nicht nötig ist und ggfls den Fehler erzeugt. Ich probier das mal und schließ den Issue damit. Wenn das nicht hilft, ist es ein Systemproblem.

**Comment by Flamefire** [comment]
BTW: Does anyone have the possibility to test, whether non-latin locales work correctly (especially filenames with non-latin characters and text input)
