### ISSUE TITLE
Red eyes.

### ISSUE THREAD

**Issue by Bad-ptr** [Return-To-The-Roots/s25client#430]
The settlers somehow always caused eyestrain for me. I guess I'm not alone.
Does anyone have ideas or recipes of how to fix this?)

**Comment by Flamefire** [comment]
Can you post discussions like this in the forum? This does not seem to be a bug which we can fix ;)

**Comment by Bad-ptr** [comment]
Ok, sorry.
Just thought that this might be a technical peculiarity of the game engine. (But more probably this is caused by the original settlers graphics/animation and many small moving objects on the screen).
