### ISSUE TITLE
Feature Request:  SaveGame-Version-Update-Warning

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#431]
It would be nice, in case that the new version is not compatible with old savegames, that the bat script is giving you a warning with the question if you are sure that you want to update, cause you will lose your old save games. (So only in case the old savegames are not compatible, you get that questions, otherwise it is automatically updating as it is done now)

**Comment by Spikeone** [comment]
Isn't there always some info in the changelog? I think I always read something like "Savegame version increased"

**Comment by BlOedsin** [comment]
To be honest I just double click rttr.bat each time to start 25client.exe.
So, yes manually it would for sure be possible to figure it out, but that means I first need to check the website, what is my version, what is the up2date version, was there a change of the savegame version….

**Comment by Spikeone** [comment]
In my opinion we may just show, that one is using a nightly build and that changes are likely and may break something, especially savegames.
But a message each time the savegame changes brings some problems: Commit changes savegameversion, message is shown, 1 day later a commit doesn't change the savegameversion so no message is shown. Maybe while updating but... yeah well.
Maybe just a nightly hint and regular stable versions

**Comment by Flow86** [comment]
features changing the stable savegame version should be a different stable version ;-)

nightlies are subject to be changed, so ...

**Comment by Flamefire** [comment]
Well, it should not be to hard to implement this. We'd need some simple server support that features a file where it extracts the savegame and replay version out of the 2 cpp files. Might still be worth it

**Comment by Flow86** [comment]
why not simply putting the current savegame revision into the config, and if its different to the new one, print the warning?

**Comment by Flamefire** [comment]
This is what I meant. However the first part must be done server-side I guess as the checksum list of the files to update is generated there, isn't it?

**Comment by Flow86** [comment]
yep, but its inside the repo: https://github.com/Return-To-The-Roots/s25client/blob/master/release/create_release.sh#L188

**Comment by Flamefire** [comment]
So just create the file and move it to `$ARCHNEWDIR/updater/links` to have it uploaded?
I'm currently working on the tests so I don't get to do this shortly, but if you or @jhkl got some time...?

**Comment by Flow86** [comment]
hope you do not overwrite "updater/links" ;-) but "$ARCHNEWDIR/updater/savegame-version" works

**Comment by jhkl** [comment]
How should we store the current savegame version of the installed rttr? Write it the the config.ini would require some the s25updater lib to know something about the config file :) Or just at a simple file just containing the savegame version of the currently installed rttr?

**Comment by Flamefire** [comment]
Good question... Easiest would be to simply update the file containing the savegame version that is already on the server and use that file for checking before updating.
Better would be to store the file versions (savegame + replay) in a separate compilation unit and use that in the updater too (link together)
Best would be to search the savegame/replay dirs for savegames that can be loaded by current version, but not with the new version. But this might be to hard...

**Comment by Flow86** [comment]
no since the updater could download the "savegame-version" file too, it could compare it with the last "updated" one

**Comment by Flamefire** [comment]
Jep. This is exactly my option 1 ;)
I added the other options to avoid having to store that file in the users files... It is kinda duplicated information as it already exists in binary.

**Comment by jhkl** [comment]
Ok, then I will just add the new file to the downloaded files and check that file against the newly downloaded one in the updater.

**Comment by Flow86** [comment]
@Flamefire youre right that its duplicated information, but I think thats the easiest way to implement it

@jhkl okay perfect!

**Comment by Flow86** [comment]
(download) location of savegameversion file at least for macosx is wrong.

**Comment by jhkl** [comment]
Where should it be? . for windows, ./share for linux and ./s25client.app/Contents/MacOS/share/s25rttr/RTTR/ for Mac?

**Comment by Flow86** [comment]
the best place would be where the s25update "exe" is

**Comment by Flamefire** [comment]
Fixed with https://github.com/Return-To-The-Roots/s25client/commit/27038f5a306bd6a0df1eba68fd218e187b8f1feb
Thanks @jhkl
