### ISSUE TITLE
S25updater doesn't work properly with newer libcurl versions

### ISSUE THREAD

**Issue by depate** [Return-To-The-Roots/s25client#433]
Due to security [concerns](https://bugs.archlinux.org/task/28252), the upstream libcurl got rid of the curl_openssl3 lib/dependency/whatsoever. 
This leads to update errors when starting rttr.sh on my Arch Linux system (and I expect this error to occur on any other system with newer curl version) because the updater explicitly wants to use the old encryption.  One can find the error report [here](http://pastebin.com/ajtcvcts).

I rechecked this issue in Linux Mint Debian Edition which uses an older version of (lib)curl and it works properly. As the windows version of rttr comes with an prebuild libcurl within itself(?), the issue never showed up.

I would like to hear your opinion on that and recommend to update the s25updater to the newer libcurl.

**Comment by Flamefire** [comment]
Sure. We just need to make sure it runs on either version. I suspect, that simply compiling against the new version would probably break on systems using the older version.
Is anyone familiar enough with that issue to implement a solution?

**Comment by Spikeone** [comment]
I can only add that starting the s25udate.exe always downloads everything and throws it into the sub folder where the s25update.exe is located....

**Comment by depate** [comment]
Spikeone;

On windows the problems doesn't show up because the attached library is compatible to those needed. Windows does not come with these libs itself, so they won't update and cause any issue.

**Comment by Flamefire** [comment]
@Spikeone Good find. I was wondering why updates were not working. This is however a different issue. Can you open another one for this, please?

**Comment by Flamefire** [comment]
@Flow86 I think it would be the best idea to update the libCurl on the server for all builds. The affected version of libcurl is pretty old and got some security problems. The windows builds e.g. use 7.21.4 which is more than 5 years old. Current version is 7.48.
Curl is even on git (https://github.com/curl/curl) so we might as well add the source as another submodule and build it too. But I fear that this might have some dependencies, that are not to easy to deal with. So an update from time to time should be enough.

**Comment by depate** [comment]
Hello @Flow86,

Is there any progress on that issue? 

Sadly, I am not familiar (enough) with git, the code of this game, the structures etc. or implementing stuff yet for trying to branch and help the team with this issue.

**Comment by depate** [comment]
This issue was fixed a long time ago. Updating s25rttr works like a charm for me.
