### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#435]
We need a good and documented way for updating translations. In some PRs we get new strings that need translations and also filenames/linenumbers change.
However there is no documentation how the translation files are to be updated and how the main pot file should be updated. Even translating via launchpad is not hard. I did not find how we get the translations back into the project.

From what I found:
### Update translations
- Download from launchpad https://translations.launchpad.net/s25rttr
- Commit to git

### Add new strings
- Regenerate pot file with PoEdit
- Update po files from launchpad translations https://translations.launchpad.net/s25rttr (Committing to branch would otherwise overwrite done translations)
- Rebuild (-> Updates po files)
- Commit to git

Is this correct?

**Comment by Flow86** [comment]
Yes, but you dont need to rebuild the po files to add new strings, thats done automatically by launchpad

**Comment by Flamefire** [comment]
So basically: Only thing to ever do is: Download all (*.po, *.pot) from LP and commit.
Am I right, that e.g. committing only the pot file will make LP import all *.po files overwriting the pending translations? Or is this handled by LP?

**Comment by Flow86** [comment]
re-importing a pot file is handled correctly by LP

**Comment by Flamefire** [comment]
Ah ok. So we still need to generate the pot file. What happens if we update the pot file only and commit this? Will LP overwrite the *.po files or will it merge them?

I also found that the LP *.po files generate a huge diff. Rebuilding rttr (sorting the pos) helps for all but German (which is not sorted like all the others)
So I'd suggest we commit the sorted po files which has the advantage that a rebuild will most likely not alter them again even if there were no changes (like it is now the case...)

**Comment by Flow86** [comment]
it will merge them, but the local po will be sorted different than the one launchpad creates, I also would simply commit them

**Comment by Flamefire** [comment]
Closed with updated readme in: https://github.com/Return-To-The-Roots/languages/commit/e4ee3a7f6fa27d3d0d23972934dcc60654bfc00a and https://github.com/Return-To-The-Roots/languages/commit/e12260c931cefe48761ed0515663b1d5ced113a3
