### ISSUE TITLE
cmake.sh: error on mac with xcode resulting to wrong hint

### ISSUE THREAD

**Issue by jonathan-reisdorf** [Return-To-The-Roots/s25client#438]
Not so sure if that's important at all, but
https://github.com/Return-To-The-Roots/s25client/blob/master/build/cmake.sh#L238
is supposed to find out what the right build command is for mac (make or xcodebuild), but instead it fails in case you have Mac / Xcode combo:
```
./cmake.sh: line 238: [Xcode: command not found
Now type "make" to build project
```

The line in the sh file should be something like
```
if [[ ("$(uname -s)" = "Darwin" && $GENERATOR = "Xcode") ]]; then
```
right?

**Comment by Flow86** [comment]
there are some quotes around $GENERATOR missing

**Comment by jonathan-reisdorf** [comment]
But the quotes are exactly the problem: They execute the variable's value leading to the error.

**Comment by Flamefire** [comment]
There is a space missing in front of `$GENERATOR`
BTW: We could improve the default with `which xcodebuild; if $? -> makefiles else xcodebuild`
