### ISSUE TITLE
cannot start new game

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#444]
hey there, 

on recent s25rttr bad1a0f4fd39462138f3647074469c3b7c35b7ed I cannot start a new game. s25client hangs when selecting a map from the list of available ones. The "please wait" box is all that is shown. 

Here is the output from console, the snd_pcm_recover warnings are not a problem I guess. 

Lade LST,BOB,IDX,BMP,TXT,GER,ENG,INI Dateien aus "/home/tim/.s25rttr/LSTS/GAME/"
fertig in 17ms
client state changed to stop
Loading settings...Done.
Connection to 127.0.0.1:3665
Sucessfully connected to localhost:3665
client state changed to stop
server state changed to stop
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.0.29/work/alsa-lib-1.0.29/src/pcm/pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.0.29/work/alsa-lib-1.0.29/src/pcm/pcm.c:7905:(snd_pcm_recover) underrun occurred

**Comment by Spikeone** [comment]
I can confirm that on win 7 x64

**Comment by Flamefire** [comment]
Sorry for that. Found a typo. Will be fixed with #445 once the tests are passed (green mark)
