### ISSUE TITLE
Observation window max zoom bug

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#446]
The Observation window now has the zoom function, but if you zoom with the max. factor there are some strange bugs (especially with big height differences)

![observationwindowbug](https://cloud.githubusercontent.com/assets/1276342/14406784/161ff7d4-feb3-11e5-9a89-c9dfb9e4b447.png)

**Comment by Flamefire** [comment]
Hm. Which map?

**Comment by Spikeone** [comment]
dv016rmp.swd (Demo V016 rmp)

Okay, This seems to only happen if you maximize the Observation window size and use the max zoom factor.
