### ISSUE TITLE
Recurring crash around 20000GF

### ISSUE THREAD

**Issue by byr1al** [Return-To-The-Roots/s25client#447]
I've been experiencing a recurring crash on all maps around 20000GF. It doesn't matter if it is a map with searoutes or without it. Also, it doesn't seem to matter what settings I'm playing with.
It says this in the terminal:
```
Sucessfully connected to debug.rttr.info:4123
Sending replay...
- Replay length: 42114
- Compressing...
- Sending...
-> success
Will now send 27 stack frames
/Users/David/Desktop/s25client.app/Contents/MacOS/rttr.command: line 63: 53707 Abort trap: 6           ./bin/s25client
```
I'm on OSX 10.11.4
EDIT: I just noticed bug #333 - mine seems to be related, as it is the same console output

**Comment by Flamefire** [comment]
The output is just from sending the debug data. So it is after the crash and tells nothing about the crash itself.
What would be interesting to know: Do you have autosave enabled? Does the replay crash on the same position every time? Which GF is shown last before it crashes?

**Comment by Flamefire** [comment]
Ok I could reproduce this with the replay send in `20160410_105743...` which goes to GF 9181 and crashes on the very next GF.

The stacktrace is this:

>

**Comment by Flamefire** [comment]
So it seems to be a problem with the build-server. This is something @Flow86 should work out. What I found is some differences in the loaded libraries:

Buildserver:

>	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 12.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	@executable_path/../Frameworks/SDL.framework/Versions/A/SDL (compatibility version 1.0.0, current version 1.0.0)
	libminiupnpc.5.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 227.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 476.19.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 34.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 677.26.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 949.54.0)

Native Build:

> 	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/local/opt/sdl/lib/libSDL-1.2.0.dylib (compatibility version 12.0.0, current version 12.4.0)
	/usr/local/opt/miniupnpc/lib/libminiupnpc.15.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)

	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1256.14.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 600.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1256.1.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1404.34.0)
    

Besides the version differences we have ApplicationServices instead of CoreGraphics in the build server version. Maybe it is also caused by the old Cocoa version.

**Comment by Flow86** [comment]
the library differences should not be the problem - any "align-double"-problematic (aka compiler flags) again?

**Comment by Flamefire** [comment]
Good idea. I've seen the build server disables optimizations with `-O0`. Done this locally -> Crash
