### ISSUE TITLE
Credits-Bilder sind falsch

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#448]
Hi,

mir ist aktuell aufgefallen, das die Credits-Bilder nicht (mehr) korrekt sortiert sind, d.h bild und Text passen nicht zusammen.

Evtl beim umbauen des Loaders passiert?

**Comment by Flamefire** [comment]
Kann ich nicht besätigen. Bei mir (Win64, aktuellste nightly) stimmt alles...
Welches System und wie sieht es denn aus?

**Comment by Flow86** [comment]
windows, latest nightly.

geladen werden sie in dieser reihenfolge:
```
Lade "./RTTR/LSTS/CREDITS.LST/flosoft.bmp":fertig in 0ms
Lade "./RTTR/LSTS/CREDITS.LST/nastx.bmp":fertig in 15ms
Lade "./RTTR/LSTS/CREDITS.LST/oliverr.bmp":fertig in 0ms
Lade "./RTTR/LSTS/CREDITS.LST/spikeone.bmp":fertig in 16ms
Lade "./RTTR/LSTS/CREDITS.LST/z-stef.bmp":fertig in 0ms
```
jedoch ist mein bild bei dem von demophobie und auch die anderen sind nicht an der richtigen stelle

**Comment by Flamefire** [comment]
Hm. Da fehlen 2 bilder... (jh und demophobie) Dadurch verrutscht der Rest.
Ich bau mal was ein, dass er die Bilder anhand des Namens lädt. Guckst du mal bitte, was mit den 2 fehlenden Bildern ist?

**Comment by Flow86** [comment]
die gibt es nicht ;-)

**Comment by Flamefire** [comment]
Dann mal fix wieder einfügen und dann geht auch alles ;) Die Bilder sind jedenfalls im Repo: https://github.com/Return-To-The-Roots/s25client/tree/master/RTTR/LSTS/CREDITS.LST

-> Not a bug

**Comment by Flow86** [comment]
hmm interessant warum die dann nicht im release sind

**Comment by Flamefire** [comment]
Im aktuellen Win64 sind die

**Comment by Flow86** [comment]
ah und ich weiß auch wieso:
es sind "s25update" und "sound-convert" (ohne .exe) im nightly build. ich vermute da geht was im cmake schief

**Comment by Flamefire** [comment]
Interessanterweise aber zusätzlich zu den mit .exe...

**Comment by Flow86** [comment]
ja genau

und ich kenn den fehler:

```
92dd477605108096c600093b7c986164  ./RTTR/LSTS/CREDITS.LST/z-stef.bmp
92dd477605108096c600093b7c986164  ./RTTR/LSTS/CREDITS.LST/demophobie.bmp
92dd477605108096c600093b7c986164  ./RTTR/LSTS/CREDITS.LST/jh.bmp
```

files mit gleichem hash läd der updater nicht runter!

see: https://github.com/Return-To-The-Roots/s25update/blob/master/src/main.cpp#L461

**Comment by Flamefire** [comment]
Interessant... Also vector of pairs würde ich sagen :)

**Comment by Flow86** [comment]
oder files und hashes umdrehen ;-)

**Comment by Flamefire** [comment]
Map ist aber völlig unnötig an der Stelle...

**Comment by Flow86** [comment]
jop vector of pairs klingt gut
