### ISSUE TITLE
Info-Windows "help" buttons not working

### ISSUE THREAD

**Issue by stR1Pe** [Return-To-The-Roots/s25client#456]
Hey guys great work so far !  settlers 2 is still alive :) thanks alot i'm impressed ! 

but, i have a little issue with the information button in the buildings menu. The game performs a CTD by clicking this button so i would appreciate that if you could fix that.

By the way, when you start a endless game, is there a way to use one's own favourite rttr settings ? 
like, loading profiles or something ? that would be nice ! so you don't have to adjust this every time new

rev f5c91bf

**Comment by Spikeone** [comment]
What language are you using? Which building or any building?

Yes, in the options menu (before you start a game)

**Comment by stR1Pe** [comment]
Thanks for your response. I´m always using nightly builds. But I recognized this issue in other versions before so i think it´s a general problem. My language setting is German.

**Comment by stR1Pe** [comment]
![crash](https://cloud.githubusercontent.com/assets/18495653/14583141/0a3e90a4-0419-11e6-95af-52f13b01be4f.jpg)

**Comment by Spikeone** [comment]
Thanks for your report, it's not language dependant and I can reproduce that crash.

None of the help buttons in any info window is working (e.g. stock, transport, tools etc.). If you hit the info button in the "buildings" (as shown above) the game crashs, all other buttons just do nothing.

Building information are working fine.

**Comment by jhkl** [comment]
Funny, it seems that all these help buttons just never have been implemented. Nobody has ever clicked on the one in the Buildings window? :D

**Comment by Flamefire** [comment]
@jhkl Any chance, that you'll implement this? Would be great to not have useless buttons on the next release ;) @Spikeone could probably help gathering the correct texts?

**Comment by jhkl** [comment]
I'll try ;)

**Comment by MarcusSt** [comment]
@jhkl added the help texts for English. German translations are now in launchpad as well.

Everybody else: feel free to add translations to your language. Thanks! :+1:
