### ISSUE TITLE
Well can't be built

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#457]
Look at the attached savegame. There's a well which can't be built. Something is wrong with the roads leading to it. Also strange is that if you delete one of the two connecting roads they will both be deleted.
After rebuilding the roads the well gets built correctly.

[bug brunnen.zip](https://github.com/Return-To-The-Roots/s25client/files/233590/bug.brunnen.zip)

**Comment by jhkl** [comment]
I haven't looked into it, but I saw that there is only a savegame attached. A replay might be helpful if you are describing a state that was created *before* the savegame.

Please always attach the replay aswell!

**Comment by jhkl** [comment]
There is no road connected to the well. It is hidden behind the tower. :smile: 

![1](https://cloud.githubusercontent.com/assets/2512962/14797617/eeccdf34-0b33-11e6-8649-4286f6c9f755.png)
![2](https://cloud.githubusercontent.com/assets/2512962/14797624/f268aff6-0b33-11e6-97ee-ca72a5673db0.png)

**Comment by kyromaster** [comment]
You're right!
Sorry for posting this here as a bug
