### ISSUE TITLE
Winapi + Options menu = strange resize

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#467]
Setting: Windowed mode 1024x768
First action: Double click on the window headbar (game is now resized to the desktop resolution)
second action: Go to the options menu and press back

With SDL: Game is correctly resized to 1024x768
With WinAPI: Game is somehow resized but the fullscreen version is still visible in the background.

Maybe this is somehow related to #375

![wiauo](https://cloud.githubusercontent.com/assets/1276342/14938982/1b46d28a-0f36-11e6-9760-3b48704c13ff.png)

**Comment by Flamefire** [comment]
I'd vote to remove the different drivers/backends and only use SDL. I don't see any advantage in using/maintaining WinAPI and I'm pretty sure GLFW wasn't updated in a while and might be broken by now.
Also having multiple backends adds complexity (we need an abstraction of the abstraction) and requires more testing (backends# multiplied with OS#, well actually GLFW runs only in (some?) linux and WinAPI only in Windows, so why have it?)

**Comment by Spikeone** [comment]
If RttR uses a s25edit compatible version of SDL  that'd be okay but currently I'm always using WinAPI as I overwrite the SDL.DLL with the version included in the s25edit.
This bug isn't really a problem, just a finding when I was testing for a blackscreen.

**Comment by Flamefire** [comment]
Then one would need to update s25edit. Should not be hard...
Why is it not part of RTTR (at least the git repos)? Licensing?

**Comment by Spikeone** [comment]
Compability.
s25edit runs fine with windows, not so fine with linux (until you build it on your own) and as far as I know the editor doesn't run on mac. So flo said we can't support win/lin/mac with rttr but only support win/(lin) with an editor.

**Comment by Flamefire** [comment]
Hm. But this means now we don't have any editor. Why not put s25edit on Github but separate? So we can fix things like e.g. when we change the drivers, but don't include it in RTTR itself?

**Comment by Flamefire** [comment]
Is this still an issue with the latest version?

**Comment by Spikeone** [comment]
in v20160507 (latest the updater gave me) it is still a problem yes.
Minimizing and maximizing resolves that "issue" anyway.

**Comment by Flamefire** [comment]
Should be fixed :)
