### ISSUE TITLE
linking fails on amd64

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#469]
the last working version has been c563256b6576f7963abe7221b49c830cb5856a3d 

I'm using gcc 4.9.3 , glibc-2.22 , system boost libraries , anything else that might be helpfull? 

full build log is here [s25rttr-failed-to-link.log.zip](https://github.com/Return-To-The-Roots/s25client/files/244868/s25rttr-failed-to-link.log.zip) 

[ 99%] Linking CXX executable s25client
cd /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/s25client.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-g++   -march=core2 -O2 -pipe  -ggdb -g   -Wl,-O1 -Wl,--as-needed CMakeFiles/s25client.dir/main.cpp.o  -o s25client  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libsiedler2/src  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/mygettext/src  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libutil/src  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/liblobby/src  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libendian/src -rdynamic libs25Main.a -ldl -lpthread ../libsiedler2/src/libsiedler2.a ../liblobby/src/liblobby_c.a ../libutil/src/libs25util.a -lminiupnpc ../mygettext/src/libmygettext.a ../libendian/src/libendian.a -lc -lbz2 -lGL -Wl,-Bstatic -llua5.2 -Wl,-Bdynamic -lboost_filesystem-mt -lboost_iostreams-mt -lboost_system-mt -lboost_program_options-mt 
/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/src/test/main.cpp:54:32: warning: extra ‘;’ [-Wpedantic]
 BOOST_GLOBAL_FIXTURE(TestSetup);
                                ^
cc1plus: warning: unrecognized command line option "-Wno-c99-extensions"
cc1plus: warning: unrecognized command line option "-Wno-c++11-extensions"
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register"
[100%] Linking CXX executable Test
cd /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build/src/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/Test.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-g++   -march=core2 -O2 -pipe  -ggdb -g   -Wl,-O1 -Wl,--as-needed CMakeFiles/Test.dir/testMap.cpp.o CMakeFiles/Test.dir/testGameEvents.cpp.o CMakeFiles/Test.dir/testPostBox.cpp.o CMakeFiles/Test.dir/main.cpp.o  -o Test  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libsiedler2/src  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/mygettext/src  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libutil/src  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/liblobby/src  -L/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libendian/src -rdynamic ../libs25Main.a -lboost_unit_test_framework-mt ../../libsiedler2/src/libsiedler2.a ../../liblobby/src/liblobby_c.a ../../libutil/src/libs25util.a -lminiupnpc ../../mygettext/src/libmygettext.a ../../libendian/src/libendian.a -lc -lbz2 -lGL -Wl,-Bstatic -llua5.2 -Wl,-Bdynamic -lboost_filesystem-mt -lboost_iostreams-mt -lboost_system-mt -lboost_program_options-mt 
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: ../libs25Main.a(DriverWrapper.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/test/CMakeFiles/Test.dir/build.make:188: recipe for target 'src/test/Test' failed
make[2]: *** [src/test/Test] Error 1
make[2]: Leaving directory '/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build'
CMakeFiles/Makefile2:1360: recipe for target 'src/test/CMakeFiles/Test.dir/all' failed
make[1]: *** [src/test/CMakeFiles/Test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build'
[100%] Built target s25client
make[1]: Leaving directory '/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Flamefire** [comment]
I have just seen that too. Will be fixed later today

**Comment by Flamefire** [comment]
Fixed with 9fad20633d3387fb3321d76177b39d9970f90788
