### ISSUE TITLE
World editor

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#470]
Discussion started in #467:

There is the (quite old) s25edit which works at least on windows. However it uses an outdated `SDL.dll` which makes it impossible to have it run from the same directory as RTTR. Also it does not get improvements/bug fixes made in the underlying libsiedler2.

I'd suggest, that we add s25edit to https://github.com/Return-To-The-Roots on Github. I'd also introduce support for building it along with RTTR, but do not add it as a submodule. Only set up CMake in a way, that it is possible to compile it along RTTR (e.g. `RTTR_BUILD_EDITOR=ON`, with `OFF` beeing the default and a check, if the folder exists) One can then checkout the editor into the build-tree of RTTR, set the CMake flag and compile it.

@Spikeone mentioned that the reason this was not done yet is that it is only supported on windows. But if it isn't in Git it might get harder and harder to support it even on windows with the new libraries. And some programmers with some spare time and mapping ambitions might be able to do the required changes to have it work on linux/Mac OSX. So I'd just add the statement, that the editor is not supported on all platforms and make it optional as described above.

Are there probably any licensing issues? Or can it be released under GPL too?

**Comment by jhkl** [comment]
I think the owner just does not want it on Github (yet).
Are we talking about this editor? -> http://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1310&start=4

**Comment by Flamefire** [comment]
I meant the old one by Xaser: https://code.launchpad.net/~xaserle/s25rttr/s25edit

According to the readme it is GPL, so I see no reason not to put it on Github for future work

**Comment by Flow86** [comment]
I'll import it tomorrow

**Comment by Flamefire** [comment]
Where is the import? ;-)

**Comment by Flow86** [comment]
oops :dancer:  

https://github.com/Return-To-The-Roots/s25edit
