### ISSUE TITLE
Tool's ordering don't work

### ISSUE THREAD

**Issue by zagent** [Return-To-The-Roots/s25client#476]
Hi all!

After the updates ceased to work correctly order the tools.Settings are correct, but not working.

Version 20160515 - 7f4a7d4

Use online translator. Sorry for my English:) Hello from Russia!

**Comment by Flamefire** [comment]
Thanks, there were some changes so this is possible. What exactly is not working? Is it simply not producing ANY tools or the wrong ones? If you can attach a short replay/screenshot to show what you mean, than that would make the process faster.

**Comment by zagent** [comment]
In settings I set the ordering tool. In the game, put all tools 0%. Set the quantity to produce and nothing is done. If some kind of tool to set % it to be produced.

**Comment by Flamefire** [comment]
Alright, thanks. Will look into this later today
