### ISSUE TITLE
Multiplayer causes client to crashes when opening the minimap

### ISSUE THREAD

**Issue by simplay** [Return-To-The-Roots/s25client#481]
First off, thanks for fixing issue #480 :+1: 

I managed to host a game and tried to play with two friends. However, after being a few minutes in-game, the client of one of my friends always crashes.

He got the following console output:

```
 <>: You have 3 seconds until game starts
 <>: Vergiss nicht deine Einstellungen fÃ¼r Erweiterungen zu Ã¼berprÃ¼fen
 <>:
 <>:  3
 <>:  2
 <>:  1
 <>: Starte Spiel, bitte warten...
Lade "./DATA/CBOB/ROM_BOBS.LST":fertig in 53ms
...
Lade "./RTTR/LSTS/GAME/map_new.LST/20000.rle.nx0.ny0.bmp":fertig in 1ms
fertig in 122ms
Lade LST,BOB,IDX,BMP,TXT,GER,ENG,INI Dateien aus "G:/Userprofiles/koru/Saved Gam
es/Return To The Roots/LSTS/GAME/"
fertig in 1ms
Saeubere Texturespeicher: fertig (nach 0ms)
Connection to 5.9.167.129:4123
Sucessfully connected to debug.rttr.info:4123
Sending replay...
- Replay length: 27280
- Compressing...
- Sending...
-> success
Reading stack frame 0
...
Reading stack frame 142
Will now send 143 stack frames
```

One thing we noticed (we could **reproduce** it like 10 times) was that his game always crashes after 1000 GF **when opening the minimap and keeping it open**. When not opening the minimap, while playing a multiplayer match, it works perfectly fine. Again, this error only occurs in multiplayer matches (,when he tried the same use-case in singleplayer game and not crash occurred).

His system Specs:

```
NVIDA GeForce GTX 750 Ti
Windows 7 Professional
s25client v4f9606c
```

**Comment by Flamefire** [comment]
First thanks for reporting. We are currently in the process of updating the codebase to make it easier to test and maintain. During that this kind of bugs can occur (and sometimes should, as additional checks are added, that detect invalid states before they "destroy" the game)
2 remarks for future reports: You can shorten the log a bit (I've done that for you) to strip repetitive entries, which makes it easier to read.
Also you can always try to reproduce the bug with a replay. If this is possible, tell us and attach the replay. It makes the bug-finding process much faster as replays are fully deterministic, so no guessing there.
In this case your description already helped and I found something. Looking into it...
