### ISSUE TITLE
Can't write in Chat

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#482]
In the initial in-game view, no messages can be sent or received:

![chat-broken](https://cloud.githubusercontent.com/assets/1663386/15450531/124a734e-1f9e-11e6-8994-ef6ef65686b9.png)

Both players are on windows.

**Comment by Flamefire** [comment]
I think the lobby bot is not there. Assigning @Flow86 to check this

**Comment by mplatt** [comment]
same goes for ingame chat though

**Comment by Flamefire** [comment]
Got it: Ingame chat was transparent xD
Lobbychat was filtered to much. Works now.
