### ISSUE TITLE
Small Road in the nothing

### ISSUE THREAD

**Issue by Dpunkt** [Return-To-The-Roots/s25client#483]
![s2 bug](https://cloud.githubusercontent.com/assets/17601021/15451084/9658a17e-1fb2-11e6-9f5a-b4f827e0ee31.png)
![s2 bug2](https://cloud.githubusercontent.com/assets/17601021/15451085/96594dd6-1fb2-11e6-8775-c1f583376a53.png)

[strassenbug.zip](https://github.com/Return-To-The-Roots/s25client/files/276074/strassenbug.zip)

See Screenshot. Bug occured in 2vs 2Ai LAN-Multiplayer.
i attached a savefile, i hope you can see why this is Happening.
I don't know how to Show coordinates, the place is the lower left corner. 
The Road is displayed in a area i concored before.

 This "Road" is clickable, a "remove road" Dialog opens and nothing happens if i try to remove it.
 

Version 20160521 on Win 7

**Comment by jhkl** [comment]
Thanks for reporting! Can you add a replay in which this road is created?

**Comment by Dpunkt** [comment]
[2016-05-21_21-54-31.zip](https://github.com/Return-To-The-Roots/s25client/files/276127/2016-05-21_21-54-31.zip)

**Comment by Dpunkt** [comment]
The Road is the Road of Yellows Headquarter

**Comment by Flamefire** [comment]
Interesting. This originates in a destruction around GF 109k where this road is exactly at the border.
