### ISSUE TITLE
Compiling under Mac

### ISSUE THREAD

**Issue by hashier** [Return-To-The-Roots/s25client#485]
Hej!

So I tried to compile the game under Mac and experienced some problems and spend some time (well, I admit hours) into trying to get this compiled on Mac. Mostly my lack of understanding all the CMakeFiles.txt is making me struggle so before I dump even more hours into trying to get this working I wanted to get some feedback if this is actually something that you are interested in? As I understand you cross compile right now and that works.

**Comment by Flow86** [comment]
Hi,

I had no problems compiling it natively on a el-capitan mac with xcode installed, and cmake via homebrew (like stated in the README)

**Comment by hashier** [comment]
wow that's interesting. The only thing that I did differently than stated in the README was that I didn't force link gettext (and therefore had to change CMake slightly) (It's not a good idea to link keg-only formulas from brew). But some problems I ran into:

- Couldn't find SDL (was installed through home-brew (1 & 2)
- C++11 code wouldn't compile since -std=c++11 wasn't set for clang
- Boost installs 64bit only lib through home-brew by default but rttr want's to build 32bit by default and therefore linking fails

(Right now with only some fixes I managed to get s25main compiled. What seems to be missing is just SDL code (which I commented out since I thought it would fallback to something else since it isn't marked as REQUIRED))

**Comment by hashier** [comment]
Ok, it compiles but now crashes on start:

```
$ src/Debug/s25client                                                                                                                                                        
Starting in /private/tmp/s25client/e
Loading "/Users/chl/Library/Application Support/Return To The Roots/CONFIG.INI": done in 0ms
Searching for drivers in ./share/s25rttr/driver/video
Skipping ./share/s25rttr/driver/video/videoSDL.dylib: Failed to load library. Check dependencies!0 video drivers found!
Video driver couldn't be loaded!


ERROR: Failed to start the game


Press ENTER to close this window . . .


[1]    6922 segmentation fault  src/Debug/s25client
```

or if I try to C-c 

```
[...]
ERROR: Failed to start the game


Press ENTER to close this window . . .

^CWollen Sie das Programm beenden (j/n) : j
[1]    6993 segmentation fault  src/Debug/s25client
```

**Comment by Flamefire** [comment]
We have 3 video drivers, although SDL is the preferred one and the only one available on Mac IMO. If you can debug and fix the segmentation fault you get after the failure, that would really help. Cannot reproduce it here.
gettext: Is there another solution so CMake easily and portably finds gettext? Did not find any and internet suggests just linking it in this case (although you are generally right) Probably setting up environment variables is also possible (linking it is only the example in the docu)
SDL: Please try to find, why it cannot be found. SDL 1.2 and SDL_mixer is required and on my clean mac install simply installing it through homebrew was enough to find it. This would help future users fixing this.
C++11: RttR is C++98 code with C++11 compatibility. But it works completely without C++11! It is **not** required to turn on C++11 to compile and run it. Travis builds ensure that it works with both, so there must be another problem here. If there is, let's fix it.
Boost: RttR builds natively by default. I find it very strange, that it tries to build in 32bit mode but installs 64bit libraries. Is the system 64bit? Can you check why it tries a 32bit compiler then?

And yes we are interested in having this work on all systems: We have jenkins builds for releases on Linux(32/64), windows(32/64) and apple(universal) and travis builds and tests for linux(debug/release, C++11/C++98), apple(64bit): https://travis-ci.org/Return-To-The-Roots/s25client/builds/132059781
Also I build myself on Windows with VS2015, Linux x64 and a Mac test system (aperiodically for checking) but ATM there are no Mac devs and hence the testing there is quite sparse. So we welcome new devs that try this and improve the system :+1:

**Comment by hashier** [comment]
For gettext I just added the path to the prefix path, something like this:
 `src/CMakeLists.txt`
```
list(APPEND CMAKE_PREFIX_PATH "/usr/local/opt/gettext/")
```

I don't know why SDL couldn't be found, I managed to get it build by using:
```
SDLDIR=/usr/local/opt/sdl ./cmake.sh --prefix=.
```

If I didn't activate C11 I got the following build errors:
```
/tmp/s25client/src/gameData/MilitaryConsts.h:78:6: error: non-aggregate type 'const Point<int>' cannot be initialized with an initializer list
    {{ -24, -36}, {9, -62}, { -2, -80}, {23, -75}},
     ^~~~~~~~~~~
```
a lot of them which all disappeared the moment I added in
`src/CMakeLists.txt`:
```
+SET(CMAKE_CXX_FLAGS "-std=c++11")
```

I didn't fully understand why CMake always tried to build 32bit libraries but it always put something out along this line:
```
$ SDLDIR=/usr/local/opt/sdl ./cmake.sh --prefix=.
Setting Path-Prefix to "."
Setting Binary Dir to "./bin"
Setting Data Dir to "./share/s25rttr"
Setting Library Dir to "./share/s25rttr"
Activating release build
Generating files for "Xcode"
Running "cmake -G 'Xcode' -DCMAKE_INSTALL_PREFIX=  -DRTTR_PREFIX=. -DRTTR_BINDIR=./bin -DRTTR_DATADIR=./share/s25rttr -DRTTR_LIBDIR=./share/s25rttr -DCMAKE_BUILD_TYPE=Release './..'"
-- Configuring for native compiling to Darwin-15.4.0 on x86_64
-- Using platform config cmake/darwin.cmake
-- Possible architectures:x86_64;i386
-- Building architecture i386
-- Building architecture x86_64
-- Linking against boost dynamic libraries
-- Boost version: 1.60.0
[...]
```

If I now run `xcodebuild` I end up with link errors like:
```
ld: warning: ignoring file /usr/local/Cellar/sdl/1.2.15/lib/libSDL.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/Cellar/sdl/1.2.15/lib/libSDL.dylib
Undefined symbols for architecture i386:
  "_SDL_EnableKeyRepeat", referenced from:
      VideoSDL::Initialize() in VideoSDL.o
  "_SDL_EnableUNICODE", referenced from:
```

I then changed the following (because I have no idea what I am actually doing):
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2021fa1..4f81625 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -68,7 +68,7 @@ ENDIF (CMAKE_CROSSCOMPILING)

 #Include generic platform config
 MESSAGE(STATUS "Using platform config cmake/${PLATFORM_NAME}.cmake")
-INCLUDE("cmake/${PLATFORM_NAME}.cmake")
+#INCLUDE("cmake/${PLATFORM_NAME}.cmake")

 ################################################################################
 # Default boost libs are static on self-build msvc versions and dynamic in the linux package repos
```

```
$ vi ../CMakeLists.txt
$ rm -rf CMakeCache.txt s25client.build s25client.xcodeproj/ CMakeScripts/ # important!!!
$ SDLDIR=/usr/local/opt/sdl ./cmake.sh --prefix=.
Setting Path-Prefix to "."
Setting Binary Dir to "./bin"
Setting Data Dir to "./share/s25rttr"
Setting Library Dir to "./share/s25rttr"
Activating release build
Generating files for "Xcode"
Running "cmake -G 'Xcode' -DCMAKE_INSTALL_PREFIX=  -DRTTR_PREFIX=. -DRTTR_BINDIR=./bin -DRTTR_DATADIR=./share/s25rttr -DRTTR_LIBDIR=./share/s25rttr -DCMAKE_BUILD_TYPE=Release './..'"
-- Configuring for native compiling to Darwin-15.4.0 on x86_64
-- Using platform config cmake/darwin.cmake
-- Linking against boost dynamic libraries
-- Boost version: 1.60.0
-- Set boost library directory hint to:
-- Boost 106000 detected. No backport required
-- Performing Test CXX_OVERRIDE_OK
-- Performing Test CXX_OVERRIDE_OK - Success
-- Performing Test CXX_OVERRIDE_FAIL
-- Performing Test CXX_OVERRIDE_FAIL - Failed
CMake Warning at CMakeLists.txt:302 (message):
  Directory '/tmp/s25client/S2' missing!
Call Stack (most recent call first):
  CMakeLists.txt:315 (symlinkFolder)


-- Boost version: 1.60.0
-- Boost version: 1.60.0
-- Found SDL: /tmp/s25client/macos/libSDLmain.a;/usr/local/Cellar/sdl/1.2.15/lib/libSDL.dylib;-framework Cocoa
-- Found SDL: /tmp/s25client/macos/libSDLmain.a;/usr/local/Cellar/sdl/1.2.15/lib/libSDL.dylib;-framework Cocoa
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   filesystem
[...]
$ xcodebuild
[...]

```

MAYBE! (wild guess) the 32bit has todo something with old lingering project files that are checked into git (that shouldn't be)? Don't have time to test it... might do it after work.

Last thing: There seems to be always a missing dir S2 (maybe because of case insensitivity on HFS+?)

**Comment by hashier** [comment]
I'm on a 64bit MacBook Pro with El Cap and use on branch
```
$ git rev-parse HEAD
6cf574881c643079e65c4a7285edb10e45b2908e
```

**Comment by Flamefire** [comment]
Gettext: Probably adding the bin path to your `PATH` is enough. Otherwise setting that option during the cmake call works without modifying the cmake files (`cmake.sh ... -DCMAKE_PREFIX_PATH=...`
SDL: I think this should have been set by SDL. Maybe because you also installed SDL2 it gets set to SDL2 dir?
C++11: This is already fixed and was a regression in one revision. The current master works w/o C++11. (VS has some C++11 features so thinks might slip through)
Compilation: Aaah! The solution is here: `Possible architectures:x86_64;i386` CMake finds that you can compile a fat binary with multiple architectures and tries to do so. So it compiles for 32 AND 64 bit. We have a switch to disable this: `-no-arch i386` We should probably enable this only for cross-compilation and have native compilation compile only for a single target. @Flow86 ?

This "missing" dir is a directory where you can put your Settlers2 files to have it picked up during run. It is optional though. (TODO: Document this)

**Comment by Flow86** [comment]
Hi,

you can run ./cmake.sh with -DCMAKE_PREFIX_PATH="/usr/local/opt/gettext" (no trailing slash!) to get gettext into the cmake-scope,

and try to run cmake.sh with --no-arch=i386 to avoid the homebrew "bug" with non universal SDL libraries

**Comment by Flamefire** [comment]
@Flow86 What about my proposition to use single-target compilation for native mode on Mac and multi-target only for cross-compiling? This would remove this kind of trap and when compiling natively one mostly wants to compile for oneself anyway.

**Comment by hashier** [comment]
Yes I was just reading through the CI build logs and found `$ export ADDITIONAL_CMAKE_FLAGS="--no-arch=i386"` so this explains why the CI isn't building 386.

I don't see why -DCMAKE_PREFIX_PATH is a better way of providing these information than to put it into the CMakeFiles.txt since then it is easier accessible by everyone.

SDL2: Nope that isn't happening, if I provide the sdl2 path on the command line CMake runs through and says it found SDL but building/linking will complain about it.


So what I did now was:
```
$ cd s2
$ git checkout .  # I still have some small modifications to CMakeFiles.txt in sound-converter and s25update
$ git pull
$ git rev-parse HEAD
3671b1c87011a7ae5b923d2f6fd7b4d8cd55dd5c
$ cd build
$ git clean -dfx  # don't want any old config/cache/project files laying around
$ SDLDIR=/usr/local/opt/sdl ./cmake.sh --prefix=. --no-arch=i386  -DCMAKE_PREFIX_PATH="/usr/local/opt/gettext"
[...]
$ xcodebuild
->
** BUILD SUCCEEDED **
```

Here are the changes to s25update and s-c
```
git --git-dir=../s25update/.git diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 2cda4f0..4c742d6 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -58,7 +58,7 @@ IF ( "${CMAKE_SYSTEM_NAME}" STREQUAL "Windows" AND NOT MSVC)
 ENDIF ( "${CMAKE_SYSTEM_NAME}" STREQUAL "Windows" AND NOT MSVC)

 IF (NOT MSVC)
-	ADD_CUSTOM_COMMAND(TARGET s25update POST_BUILD COMMAND cp -v s25update ../../RTTR/)
+	ADD_CUSTOM_COMMAND(TARGET s25update POST_BUILD COMMAND cp -v Debug/s25update ../../RTTR/)
 ENDIF()

 INSTALL(TARGETS s25update RUNTIME DESTINATION ${RTTR_DATADIR}/RTTR/)
```

```
$ git --git-dir=../s-c/.git diff
diff --git a/resample-1.8.1/src/CMakeLists.txt b/resample-1.8.1/src/CMakeLists.txt
index a6b6c46..52ccfb1 100644
--- a/resample-1.8.1/src/CMakeLists.txt
+++ b/resample-1.8.1/src/CMakeLists.txt
@@ -18,7 +18,12 @@ IF (MSVC)
 		RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_CURRENT_BINARY_DIR}/../../../RTTR/"
 	)
 ELSE()
-	ADD_CUSTOM_COMMAND(TARGET s-c_resample POST_BUILD COMMAND cp -v s-c_resample ../../../RTTR/s-c_resample)
+	#ADD_CUSTOM_COMMAND(TARGET s-c_resample POST_BUILD COMMAND cp -v s-c_resample ../../../RTTR/s-c_resample)
+	ADD_CUSTOM_COMMAND(TARGET s-c_resample POST_BUILD COMMAND env > /tmp/a.env)
+	ADD_CUSTOM_COMMAND(TARGET s-c_resample POST_BUILD COMMAND echo "TTEST ${TARGET_BUILD_DIR}")
+	ADD_CUSTOM_COMMAND(TARGET s-c_resample POST_BUILD COMMAND echo "TTEST ${CONFIGURATION_BUILD_DIR}")
+	ADD_CUSTOM_COMMAND(TARGET s-c_resample POST_BUILD COMMAND echo "TTEST ${BUILT_PRODUCTS_DIR}")
+	ADD_CUSTOM_COMMAND(TARGET s-c_resample POST_BUILD COMMAND cp -v Debug/s-c_resample ../../../RTTR/s-c_resample)
 ENDIF()

 INSTALL(TARGETS s-c_resample DESTINATION ${RTTR_DATADIR}/RTTR)
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 6372882..4a0fd7f 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -19,7 +19,7 @@ IF (MSVC)
 		RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_CURRENT_BINARY_DIR}/../../RTTR/"
 	)
 ELSE()
-	ADD_CUSTOM_COMMAND(TARGET sound-convert POST_BUILD COMMAND cp -v sound-convert ../../RTTR/sound-convert)
+	ADD_CUSTOM_COMMAND(TARGET sound-convert POST_BUILD COMMAND cp -v Debug/sound-convert ../../RTTR/sound-convert)
 ENDIF()

 INSTALL(TARGETS sound-convert DESTINATION ${RTTR_DATADIR}/RTTR)
```

**Comment by Flamefire** [comment]
I made a commit that:

- Fixes the 3 folder issues with xcodebuild you found (based on your changes)
- Makes the default arch the current arch of the host system and all available archs for cross-compilation (no more `-no-arch` required)

The other 2 issues (SDL/gettext) are now documented in the FAQ, as this is not a bug (https://github.com/Return-To-The-Roots/s25client/wiki/[FAQ]-Compiling#mac-os-x)
What happens with SDL: There are links in `/usr/local` and `/usr/local/include` to SDL2 so CMake does not find the 1.2 one. Gettext needs to be in the path or added to `CMAKE_PREFIX_PATH`. (This is better than putting it into the CMakeLists.txt as this is a system specific setting. On another system it is/might be different. That is the reason those flags exist. The CMakeLists is generic.)

**Comment by hashier** [comment]
The SDL problem is a different one. If I set SDLDIR to point to SDL2 cmake runs through without problems and accepts SDL2. If I don't set SDLDIR I get SDL warnings that it can't be found.

For gettext -> Since it's just adding a search path I don't see any harm. It feels still generic just to add an additional path for searching. And since the code more or less already assume home-brew has to be installed for some deps it would be perfectly ok to have home-brew by default in the search path.

**Comment by hashier** [comment]
That's crazy. To double check with SDL I removed SDL2 and lo and behold... it works (cmake without giving a path to SDL). That's strange since cmake worked perfectly with SDL2 path given without complaining. Anyway, here is what I did

On clean checkout (on f37475):
```
$ brew uninstall sdl2 sdl2_image sdl2_mixer
$ ./cmake.sh --prefix=. -DCMAKE_PREFIX_PATH="/usr/local/opt/gettext" && xcodebuild
-> 
** BUILD SUCCEEDED **
```

Great!

**Comment by Flamefire** [comment]
It is simply against portability to give absolut paths in a portable CMake file. CMake already has means to find libraries on a given system. Putting those paths in there might e.g. interfere with cross-builds where it would chose wrongly the host library. And no there is no dependency on home-brew. Home-brew is simply one way to install libs. You could also download, compile and install them from source, if you like. You only have to either put them into common paths or include their path in environment variables.

SDL: Would need to dig further but in the end there were simply some paths set different so it did not pick up the right ones

**Comment by hashier** [comment]
Ok last comment:

I reinstalled SDL2 and everything still works. (Even after git clean -dfx). Oh well... I guess I just accept SDL as a mystery

**Comment by Flamefire** [comment]
I'd just check for the paths that were used. Check cmake-gui or ccmake for this. Most likely `/usr/local/include/SDL` and `/usr/local/lib` or the like. Especially the first one might have gotten linked to SDL2 before (I guess first come wins)
