### ISSUE TITLE
Compile errors (sprintf undefined) on Lubuntu 16.04 32bit

### ISSUE THREAD

**Issue by MelTraX** [Return-To-The-Roots/s25client#489]
I recently updated to Lubuntu 16.04 (32 bit). The nightly from the site won't start because it wants `libminiupnpc.so.5` and I only have `libminiupnpc.so.10`, so I compiled RTTR myself using these commands on a Lubuntu 16.04 32 bit live CD:

```
sudo apt-get install git cmake libboost-filesystem-dev libboost-test-dev libboost-iostreams-dev libboost-program-options-dev libsdl1.2-dev libsdl-mixer1.2-dev libcurl4-openssl-dev libbz2-dev libminiupnpc-dev liblua5.2-dev gettext
git clone --recursive https://github.com/Return-To-The-Roots/s25client s25client
cd s25client/build
./cmake.sh --prefix=.
make
```

These two files told me that `sprintf` is not defined:

```
s25client/src/ingameWindows/iwTrade.cpp
s25client/src/ingameWindows/iwBuildings.cpp
```

After inserting `#include<stdio.h>` into both of them it compiled and started just fine. You probably know better than I do what causes stuff like that.

**Edit:** I'm stupid. The nightly works just fine. I called s25client directly before. Doesn't change the compile errors though.

**Comment by Flamefire** [comment]
Fixed with  33eb80a

Thanks!
