### ISSUE TITLE
[addon] Chicken farm

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#49]
One more building to get food. But this just should be a middle building and is only one building do gain food. To get bread you need to buildings as example.

Spike (fvv1) wrote on 2009-05-02:   #1
Grafiken evtl

Demophobie (demophobie) wrote on 2009-05-02:    #2
Spike macht Grafiken :-P

https://bugs.launchpad.net/s25rttr/+bug/367192

Version 1: 
![huhnerstall](https://cloud.githubusercontent.com/assets/1276342/9070080/a013809e-3aed-11e5-8a61-400c438b4d0e.png)

**Comment by MarcusSt** [comment]
Would need graphics.

**Comment by Spikeone** [comment]
There is already one for the smaller building part but I think we should combine all wishes for new buildings
