### ISSUE TITLE
Tool ordering is not working 100% correct

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#495]
hey there, 

I recently noticed that the tool ordering does not work relieable. It is possible to commit a certain amount of tools, but if these jobs are done the metal worker continues to work with randoom tools as a result. Although I checked this specific option that he should not do anything at all when his queue is finished while configuring the game beforehand. 

This can be triggered by starting a new game, choose tool ordering and the option that the tool worker should not do anything when he has finished the commited tools. A replay is attached. 

[2016-07-10_11-30-10.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/355973/2016-07-10_11-30-10.rpl.zip) 

I'm on edfaac5bec2cb3352c1b7f8c4b1b5e811b6d1350 , if that helps

**Comment by Flamefire** [comment]
Do you have all tool settings set to 0%? "Produce nothing" does only kick in if nothing is orderer **and** you have all sliders set to 0%

**Comment by stefson** [comment]
No, those tool settings were set to their default values. Set them to 0% and the stop works as it should. This is not really self explaining in my opinion!?

**Comment by Flamefire** [comment]
Well it has a tooltip with a complete description: https://github.com/Return-To-The-Roots/s25client/blob/master/src/addons/AddonMetalworksBehaviorOnZero.h#L12
You can't put to much in the option itself or it would be to long. There is now even a button for setting all to 0% at once.
I don't think this can be made much better, as this addon can be activated with disabled tool ordering. So it can only relate to the sliders.
