### ISSUE TITLE
Wrong help icons

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#496]
Most Main menu windows (ingame) have the wrong help icon. They use the '!' instead of the correct '?'.

![wrongicons](https://cloud.githubusercontent.com/assets/1276342/16738984/61e55226-4798-11e6-9f79-4ca3d7d95891.png)

**Comment by Spikeone** [comment]
![formaqs](https://cloud.githubusercontent.com/assets/1276342/16739259/80a779ae-4799-11e6-9070-84e2f39a0b34.png)

**Comment by MarcusSt** [comment]
Seems to be related to the exact version. For me, it's only 'i', no '?' at all. Strange...

**Comment by Spikeone** [comment]
I guess it's more like the german "Information" and the englisch "Help" - so I would choose one of those icons depending on are those texts just information or do they help to understand?

**Comment by MarcusSt** [comment]
I'd also opt for consistent icons. But without the button doing anything, the icons don't really help at all.

**Comment by Spikeone** [comment]
I'd vote for the question mark, because most people who hit such a button are seeking for help => '?' seems to fit better.
