### ISSUE TITLE
S25update fails on updating zero-length files

### ISSUE THREAD

**Issue by yallie** [Return-To-The-Roots/s25client#497]
When a file is empty, s25update.exe crashes with a message like this:

```
...
Updating "libvideoSDL.dll":                  100.00% - ok
Updating "libvideoWinAPI.dll":               100.00% - ok
Updating "put your S2-Installation in here": -1.#J% - decompression failed: download failure?
```

Also, why updating an empty file in the first place? :)

**Comment by MarcusSt** [comment]
Please let us know what version you are using. This should not happen with recent versions. Empty files are updated as well, because not updating them would need more checks than not to. ;-)

**Comment by Spikeone** [comment]
should be fixed, see #2

**Comment by yallie** [comment]
>Please let us know what version you are using. 

Version 0.8.1, seems to be the latest stable version.

>not updating them would need more checks than not to. ;-)

Ok then :)

>should be fixed, see #2

Is it available in the nightly build?

**Comment by MarcusSt** [comment]
Yes. The stable version is comparably unstable.

**Comment by yallie** [comment]
Wow, nightly build seems to work much better than the stable 0.8.1 version!
