### ISSUE TITLE
build failure on amd64 in src/desktops/dskGameInterface.cpp:1143:23: error: switch quantity not an integer

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#500]
the last working version has been edfaac5bec2cb3352c1b7f8c4b1b5e811b6d1350

I'm using gcc 4.9.3 , glibc-2.22 , system boost libraries , anything else that might be helpfull?

[build.log.zip](https://github.com/Return-To-The-Roots/s25client/files/367269/build.log.zip)

[ 57%] Building CXX object src/CMakeFiles/s25Main.dir/drivers/AudioDriverWrapper.cpp.o
cd /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build/src && /usr/bin/x86_64-pc-linux-gnu-g++  -DBOOST_PP_VARIADICS=1 -DHAVE_MEMCHECK_H -Doverride=""   -march=core2 -O2 -pipe  -ggdb -g -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/contrib/backport/boost_1.56-1.58 -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999 -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/liblobby/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libutil/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/mygettext/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libsiedler2/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libendian/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/src -isystem /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/contrib/kaguya/include -I/usr/include/lua52 -isystem /usr/include/lua5.2    -Wall -pedantic -Wno-long-long -Wno-deprecated-register -Wno-unknown-pragmas -Wno-c++11-extensions -fno-strict-aliasing -Wno-variadic-macros -Wno-c99-extensions -o CMakeFiles/s25Main.dir/drivers/AudioDriverWrapper.cpp.o -c /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/src/drivers/AudioDriverWrapper.cpp
/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/src/desktops/dskGameInterface.cpp: In member function ‘void dskGameInterface::NewPostMessage(const PostMsg&, unsigned int)’:
/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/src/desktops/dskGameInterface.cpp:1143:23: error: switch quantity not an integer
     switch(soundEffect)
                       ^
[ 57%] Building CXX object src/CMakeFiles/s25Main.dir/drivers/DriverWrapper.cpp.o
cd /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build/src && /usr/bin/x86_64-pc-linux-gnu-g++  -DBOOST_PP_VARIADICS=1 -DHAVE_MEMCHECK_H -Doverride=""   -march=core2 -O2 -pipe  -ggdb -g -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/contrib/backport/boost_1.56-1.58 -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999 -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/liblobby/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libutil/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/mygettext/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libsiedler2/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/libendian/src -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/src -isystem /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/contrib/kaguya/include -I/usr/include/lua52 -isystem /usr/include/lua5.2    -Wall -pedantic -Wno-long-long -Wno-deprecated-register -Wno-unknown-pragmas -Wno-c++11-extensions -fno-strict-aliasing -Wno-variadic-macros -Wno-c99-extensions -o CMakeFiles/s25Main.dir/drivers/DriverWrapper.cpp.o -c /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/src/drivers/DriverWrapper.cpp
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-c99-extensions"
cc1plus: warning: unrecognized command line option "-Wno-c++11-extensions"
cc1plus: warning: unrecognized command line option "-Wno-deprecated-register"

**Comment by Flamefire** [comment]
Strange that this is never caught on travis... Fix is pretty easy though. osoon.
