### ISSUE TITLE
Lua: DisableBuilding() does the opposite

### ISSUE THREAD

**Issue by lvanderwall** [Return-To-The-Roots/s25client#510]
Version: v20160721 - d3ce5ec

DisableBuilding() does not disable buildings.

I guess the error is in [LuaPlayer.cpp - L83](https://github.com/Return-To-The-Roots/s25client/blob/d3ce5ec/src/lua/LuaPlayer.cpp#L83) - it calls `player.EnableBuilding(bld)`

**Comment by Flamefire** [comment]
Ah yes, thanks for catching this :)

**Comment by lvanderwall** [comment]
Your're welcome!
