### ISSUE TITLE
Add zoom indicator

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#511]
Just as we have an idicator for speed one for the current zoom would be nice as well.

**Comment by Flamefire** [comment]
Hm, really? Where and what should it be? If at all, I would only show it for a few seconds after zooming

**Comment by Spikeone** [comment]
IO.IDX number 36.
Why only for a few seconds? We have the gamespeed and the sanil icon in the upper right, why not display the magnifier in the upper right (maybe with zoomfactor) as well?

**Comment by Flamefire** [comment]
And if we add 5 other icons for other things we won't see anything else anymore ;) The snails are just alerts shown for a short time when there is an error. I actually dislike the permanent runner.

**Comment by MarcusSt** [comment]
Original:
![zoom out](https://dl.dropboxusercontent.com/u/11244516/RTTR/original-zoom-out.png)
![zoom in](https://dl.dropboxusercontent.com/u/11244516/RTTR/original-zoom-in.png)

Die Lupe wird bei Zoom permanent angezeigt.
