### ISSUE TITLE
Add shortcuts for zoomout and slowdown

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#512]
In multiplayer there is only the "V" button to increase gamespeed, as we have 7 stages (70ms - 10ms) this is quite... bad designed as you cant's slow down but only hasten the game.
When playing replays you can use the +/- keys, which aren't working in multiplayer. Either we should use in both gamestates the same shortcuts (keep V as it is the original key) or add another key for multiplayer (like SHIFT+V).

Same for zooming, you have to cycle through all states. Instead we should add a shortcut to zoom out (like SHIFT + Z)

**Comment by Flamefire** [comment]
Agreed. +/- should be used for all speeds. `SHIFT + Z` seems like a good choice

**Comment by MarcusSt** [comment]
Should have been shift+z in the commit message, my bad.
