### ISSUE TITLE
Doubled console message when deleting old replays

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#514]
If you have one old replay in your replay folder, and you delete them by pressing the "delete old" button (or however it's called) you get the "warning" message again in the console output.

rev 3671b1c

**Comment by Flamefire** [comment]
A bit hard to fix and not that critical... Logging should not be done in the replay class itself.

**Comment by Spikeone** [comment]
Agreed that it's just minor(²) - but still an existing bug.

**Comment by MarcusSt** [comment]
For deleting all invalid replays, we need to scan all replays again. Therefore you'll get the message again. I would not call this a bug, but I don't see why we need the path of every invalid replay file in the logs either.

**Comment by Flamefire** [comment]
The replay should not print any output. It should rather return an error code instead. Printing can then be done by the outermost caller if at all. Then we can print that e.g. only once at startup or initial filling of the table.
