### ISSUE TITLE
Reset "teamView" and "fow" via LUA

### ISSUE THREAD

**Issue by lvanderwall** [Return-To-The-Roots/s25client#516]
`ResetAddons()` resets all addons to mimic the original S2 settings. It might be convenient if it also sets teamView and exploration to _off_ and to _classic_ respectively (their original S2 settings)

**Comment by MarcusSt** [comment]
As documented, it just resets the Addons, which are different from the other settings. It would be confusing if it were to reset teamView and fow as well.

**Comment by lvanderwall** [comment]
Agreed, that makes sence.

**Comment by Flamefire** [comment]
I renamed this and would keep this as an enhancement as this totally makes sense

**Comment by Flamefire** [comment]
We currently have the default for exploration set to FogOfWar. I believe the correct S2 default should be "Classic", but I also think FoW should stay the default.
So questions:

1. What should be the default?
2. To what value should the ResetGameSettings function set it?

**Comment by Spikeone** [comment]
Well, if we could save those options for the user as well I'd say we should change it to classic by default. Sadly those settings aren't saved so you have to set them any time you play again which is quite... not good.
As we already nearly always change the gamespeed and one also has to change the exploration (hand has to start the whole match again if he forgot that cause you can't change it on load) we should keep it FoW as long as we don't save those settings.

**Comment by Flamefire** [comment]
I could implement saving for those :)

**Comment by Spikeone** [comment]
Just do it! ;)

After you implemented that, we should set the default to classic in my opinion.
