### ISSUE TITLE
Cannot break up with team with option `lockedTeams=false`

### ISSUE THREAD

**Issue by lvanderwall** [Return-To-The-Roots/s25client#517]
**Version:** 20160725 - 1ac0870

If `lockedTeams=false`, I expect that I could break up with my team members.

But players who start in the same team (in the settings dialogue) still cannot change their diplomacy settings.

Example settings:
![settings](https://cloud.githubusercontent.com/assets/16540971/17098228/91905e34-5261-11e6-97aa-574b735e4890.png)

Diplomacy: Can change alliances with AI2, but not with AI1:
![diplomacy](https://cloud.githubusercontent.com/assets/16540971/17098264/baab28ee-5261-11e6-948b-d7485b5aea34.png)

**Comment by MarcusSt** [comment]
The other party needs to agree to cancel a pact prematurely. At the moment, the AI does handle any diplomacy, so it won't agree to cancel the pact. Human players will get message "The player '%s' want to cancel the '%s' between you both prematurely. Do you agree?". Only if both parties agree, the pact is cancelled.

**Comment by lvanderwall** [comment]
Ok, I'll bear that in mind. Perhaps an easy AI diplomacy model might be that the AI will always agree to cancel a pact, but never to sign new treaties. That should resemble the original game:

- the AI respects pacts predefined by the settings
- the AI becomes hostile as soon as the human player attacks

**Comment by Flamefire** [comment]
Maybe a Lua event would be good so you can decide that in missions: onContractCancel: Accept/Deny

**Comment by lvanderwall** [comment]
An interesting idea! I would still like to have the AI model above as default diplomacy behavior (to stay as close to S2 as possible), but you could override that with onContractCancel() if you want your own settings.

E.g. you could set a time frame in which players are allowed to attack the AI...

**Comment by Shawn8901** [comment]
@Flamefire @lvanderwall can some one please check if the pushed code (#773) fixes this issue?

**Comment by Flamefire** [comment]
Fixed
