### ISSUE TITLE
Add mission goal to post messages

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#522]
The current mission goal should be added in the last category of the post box (briefing paper) which is currently used for diplomacy messages.

See http://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1443&start=-1#14233

**Comment by MarcusSt** [comment]
![Mission](https://dl.dropboxusercontent.com/u/11244516/RTTR/mission-post.png)

Clicking that icon opens the mission diary. The icon is only shown during missions.

**Comment by MarcusSt** [comment]
I'd call this a bug, as it is completely different from the original game's behaviour.
