### ISSUE TITLE
Enhance Singleplayer menu

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#525]
When you press "Singleplayer" you get a menu which is quite similar to the main menu. Yet all buttons are arranged in an other way, we should enhance that.

Currently the main menu has 3 blocks:

Singleplayer
Multiplayer

Options
Intro
Readme
Credits

Quit program

The singleplayer menu has 4 blocks:

Resume last game

Play Replay

Campaign
Unlimited play
load game

back

So I suggest it should look that way:
Unlimited Play
Campaign

play replay
resume last game
load game

back

That way those are arranged:
New Game Singleplayerstuff
Old Game Singleplayerstuff
Back

![s25client 2016-07-27 12-54-04-58](https://cloud.githubusercontent.com/assets/1276342/17173306/4cba4dd4-53fa-11e6-9503-f8e261561fcc.png)

PS: We should also grey out campaign (as we have not implemented them in a good way yet).

**Comment by Flamefire** [comment]
I don't think that way. Resuming is what you usually want to do. If you click "twice" on SinglePlayer you will load the last played game. This is great.
Putting Replay and Load together and also Campaign and Unlimited would be ok though. so 4 blocks: Resume, Load/Replay, New/New, exit

**Comment by Spikeone** [comment]
Agreed that it depends on.
But placing all new game options last seems wrong, at least for me.

As long as Back is aligned with quit program, I'm happy, although I like the 3 blocks - 3 blocks way (not regarding where which option is) more. But as everything is personal ;)

**Comment by Flamefire** [comment]
Leave this open please. As I think we agree on the following changes: 

- [ ] Align Exit buttons
- [ ] Place new game and load game pairs together
- [ ] Disable Campaign button for now

I have no strong opinion on the order. Only Resume first and Quit last. Then there are 3 options:

1. 3 groups: Resume, Load, Replay | Campaign, Unlimited | EXIT
2. 4 groups: Resume | Load, replay | Campaign, Unlimited | EXIT
3. 4 groups: Resume | Campaign, Unlimited | Load, replay | EXIT

Which should it be? Maybe also some input from @Flow86 ?

**Comment by Flow86** [comment]
what about Resume, Load | Campaign Unlimited | Replay | Exit ?
