### ISSUE TITLE
Add Lua interface version

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#527]
I'd add a required function to each lua script: `getInterfaceVersion()` that should return the major version of the supported interface. If this does not match the current major version, the script will not be loaded.
Similarly I'd also add `(unsigned, unsigned) rttr:GetInterfaceVersion()` that returns major and minor version of the interface. We increment the minor version with every lua feature added and reset it and increment the major version for every breaking change we make. This way we can avoid, that a script crashes the game in the middle of match.

@Spikeone @MarcusSt

**Comment by Flow86** [comment]
why not call it "compatibleLuaVersion"?

**Comment by lvanderwall** [comment]
or rather "getRequiredLuaVersion()" ?
