### ISSUE TITLE
farm field graphics overlay building graphics

### ISSUE THREAD

**Issue by lvanderwall** [Return-To-The-Roots/s25client#531]
Version: 20160728 - 14796d1

bug: Farm fields sometimes overlay building graphics (in this case the metalworks):
![field layer](https://cloud.githubusercontent.com/assets/16540971/17239427/3ca81f5a-5564-11e6-811e-b493cdfc1738.png)

I think it should be in the layer behind the building - or the farm should not be allowed to plant a field there (I recall in the original game the farm didn't plant right next to buildings)

**Comment by Flow86** [comment]
we dont have multiple layers currently, but draw from left to right. perhaps we should simply draw right to left, which would fix that problem

**Comment by Flamefire** [comment]
@Flow86 No, only shift it. We will have the same problem on the right side then. We should check the original:

- Build building that close possible?
- Farm uses that spot?

**Comment by MarcusSt** [comment]
I think layers would be the way to go. Maybe we can just precalculate things, put them in a list and paint buildings after the other objects.
Drawing from right to left:
![R->L](https://dl.dropboxusercontent.com/u/11244516/RTTR/right-to-left.png)

**Comment by Flamefire** [comment]
I rather think that fields are just not allowed there. It would be partially inside the building, no matter how you draw it.
Layers are also complicated. E.g. we need to draw this in order: Building, door, figures. Getting all this right will not be easy.
How would you (efficiently) precalculate things?

**Comment by lvanderwall** [comment]
I don't think that will be necessary -- that's a screenshot of the original S2:
![farm_limitation](https://cloud.githubusercontent.com/assets/16540971/17244177/d734b882-5580-11e6-817e-d2f77dddf21b.png)

The farmer could plant fields at both red crosses (they are two vertices apart from the first field) but never did that in several minutes. He is not allowed to plant right next to any buildings.

**Comment by Spikeone** [comment]
Okay I tested both of your cases with correct results:

![s2rttr](https://cloud.githubusercontent.com/assets/1276342/17269576/78386e42-564c-11e6-9217-24903c1611cb.png)

Couldn't find any difference between s2 and rttr while everything was running but:
In S2 a field the farmer was about to plant between the farm and the sawmill on the left was aborted when I placed the building site. In RttR he continued seeding it, that way the grown field was overlaying the sawmill but only for once.

Also I found out, that the s2 farmer waited till a rubble pile disappears, the rttr farmer just started planting new fields:
![waited](https://cloud.githubusercontent.com/assets/1276342/17269587/e4bcb6c2-564c-11e6-9219-5c751bf98c33.png)

Did you keep in mind, that harvested fields stay longer in rttr than in s2? Maybe those overlaying fields just despawn faster in s2 than they do in rttr?

**Comment by Flamefire** [comment]
Ok so changes to be done:

- [ ] Abort planting if point gets bad
- [ ] Honor rubble piles for planting

Correct?

**Comment by Spikeone** [comment]
Thats the result of my tests yes, but maybe @lvanderwall has tested this as well with an other outcome?

**Comment by lvanderwall** [comment]
@Spikeone You're right regarding buildings. If you do this:

- wait till the farmer is sowing
- build right next to that spot so the flag does not lie on the new field

the farmer plants right next to a building, but will not do it again afterwards. If the building flag lies on the field (or if you place a new flag on the field while the farmer is sowing) the farmer will abort his planting.

I haven't noticed the problem with the rubble myselft in RTTR, but in S2 you are right: The farmer does not plant right next to rubble or on it.
