### ISSUE TITLE
[wish] some kind of hidpi support

### ISSUE THREAD

**Issue by lschneiderbauer** [Return-To-The-Roots/s25client#533]
Hey guys,
on hidpi screens the text in the menus (in the main menu as well as ingame) is barely readable.

I don't expect you guys to introduce complete hidpi support for the game. But at least the font size and menu sizes could be made dpi-dependent so that you can read the text properly.

Just a thought.
Thanks.

**Comment by Flamefire** [comment]
Can't you just reduce the resolution? Can you post a screenshot of the problem (if possible)

**Comment by lschneiderbauer** [comment]
@Flamefire 
Yes, one can reduce the resolution. Apart from the usual inconveniencies (e.g. cursor moving way too fast then) that works. I suppose the graphics is not rendered "better" on higher resolutions anyway?

A screenshot:
![screenshot_20160729_145120](https://cloud.githubusercontent.com/assets/422100/17248668/3fc5dc26-559c-11e6-90e3-acfc13bd0732.png)

**Comment by Flamefire** [comment]
Basically only the visible area is increased. I think dpi-independent menus/font is a lot of work as it requires rewriting large parts of the GUI code. If at all, this is something for an enthusiast coder familiar with such things. I'd leave this here as a reminder but put it on the back of the todo-list as you can simply decrease the resolution unless someone comes up with an easy solution to the coding stuff.

**Comment by RazrFalcon** [comment]
The game scales automatically on the latest Windows 10, but on Linux it's tiny and unplayable.

**Comment by Thobov** [comment]
That is true, Windows 10 now scales most of the text and buttons in the RTTR main menu and addon settings. However, Windows 10 does not upscale the UI ingame. It would be very nice if there will be hidpi support for the ingame UI. The image below is ingame and the menus are in the left corner below. Thank you for reading and it would be amazing if this someday will be done. Have a nice day!

![377964f5743590e9b9e27bee736c0cd1](https://user-images.githubusercontent.com/33982507/82297223-a209c880-99b2-11ea-8289-65cb7e916377.jpg)

**Comment by Richard-L** [comment]
This is an important issue indeed. OpenRCT2 have a nice pixel scaler they offer in x0.25 steps, so you can set pixel scaling to: x1.0, x1.25, x1.5x, 1.75x, x2.0, etc. Really helps.

**Comment by falbrechtskirchinger** [comment]
I'd love it if people with HighDPI displays could give my PR (#1594) a spin and comment. It's almost ready for review, so I'd expect it to be fully functional at this stage.
