### ISSUE TITLE
Bugged fragments visible

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#534]
When starting a game and not moving my current visible area, I always have some strange fragments visible. Those disappear after moving the camera a bit around.
Sadly those also appear in the observation window.

![s25client 2016-07-29 14-07-22-01](https://cloud.githubusercontent.com/assets/1276342/17247901/d407e63c-5596-11e6-8c57-d5e25582553a.png)
![s25client 2016-07-29 14-08-57-55](https://cloud.githubusercontent.com/assets/1276342/17247903/d5f70b58-5596-11e6-8469-72f0cd8dda52.png)

**Comment by MarcusSt** [comment]
Seems to be fullscreen only here (see also #532).

**Comment by Spikeone** [comment]
Tested it, for me it doesn't matter if windowed, fullscreen, vertexbuffer, optimizedtextures, winapi, sdl - this bug always appears

**Comment by Flamefire** [comment]
Should be fixed with c8fccc7078d72e02daec960aa24be1c6667fd258
