### ISSUE TITLE
Lua: SetRestrictionArea() creates extra holes

### ISSUE THREAD

**Issue by lvanderwall** [Return-To-The-Roots/s25client#537]
**Version**: 20160728 - 14796d1

**Bug**: SetRestrictionArea() creates more holes than the one I would expect

**What I did:** I use a script for _miss200.wld_ to allow the player to settle on the whole island except a small rectangle just outside the HQ - borders. Then I build a fortress at the northern border and expect to capture the area around that rectangle (which should be the only hole in my area afterwards).

Lua-Script, replay (GF: 6000) and save file: [test_restrictions.zip](https://github.com/Return-To-The-Roots/s25client/files/390573/test_restrictions.zip)

**What happens:** Besides the hole I expect (green, coordinates should be: 35, 25; -- 37, 25; -- 37, 27; -- 35, 27; -- 35, 25) there are more holes (red):
![restricted_area](https://cloud.githubusercontent.com/assets/16540971/17249103/a66a2598-559e-11e6-9a91-473ad52f7072.png)

**Comment by Spikeone** [comment]
I remember that problem - as I reported that some time ago but when recreating a "bugged" version it worked fine. Maybe you just did a mistake (like me).
I'm gonna test as well.

**Comment by Flamefire** [comment]
I'm pretty sure the problem is caused due to either using unsigned values causing underflows in the subtraction of `prev->x - it->x` e.g for `1-62` in this case and/or using short values which can cause overflows in the multiplication (https://github.com/Return-To-The-Roots/s25client/blob/14796d1cb7423a87f9698001db650fa6262ae4ee/src/world/TerritoryRegion.cpp#L39). However that latter will only happen for map sizes of about 256 or using larger/wrapping polygons. I'd leave that to @MarcusSt as hw wrote the original implementation. I'd either store that area as int-points or convert them on access (std::vector range-ctor can be used) and also convert the point to test.
Please also add tests for `IsPointValid` in testRegressions.cpp that check some examples and also this specific constellation before you fix that, so we can be sure, that this fixes it.

**Comment by Spikeone** [comment]
Thats the testmap I've created when we were first talking about this bug @Flamefire  - it's still working without any problem so far.

http://www.rfmonline.de/rttr/spike/restarea.rar

But maybe that test was bad as I created a big area instead of one small area.

**Comment by lvanderwall** [comment]
If the components of `const MapPoint pt` are both (unsigned) integers and not floats, the problem might be the division of two ints in [IsPointInPolygon()](https://github.com/Return-To-The-Roots/s25client/blob/14796d1cb7423a87f9698001db650fa6262ae4ee/src/world/TerritoryRegion.cpp#L51)

In that algorithm, it's stated under **Conversion to ints (2)**, that you must move the denominator over to the other side of the inequality (which I'd do twice get rid of the flipping sign)

**Comment by MarcusSt** [comment]
This is most likely a dead end, as we cannot use floats there. The problems have been there from the very beginning and it would make more sense to reimplement this using a different algorithm.
However the one doing this will most likely not be me, as I won't have enough spare time within the next few months.

**Comment by Flamefire** [comment]
It is actually pretty easy. Just switch to ints, calculate the divisor separately and multiply by it instead. Then check if it is '<' or '>=' depending on whether it was negative or not. Some careful tests to ensure correctness would also be great. I don't understand the algorithm more than 'It works', so it would be great if you got the time for that.

**Comment by MarcusSt** [comment]
I think I got it, will commit later.

The algorithm works like that:
You cast a ray starting at the point you want to find out about along the x axis. For this ray you count how often it intersects with an edge. An even number means that it's inside, an odd number means outside.

**Comment by lvanderwall** [comment]
@MarcusSt Great idea, you multiplied the second conditional with `(prev->y - it->y)` to get rid of that division, am I right? However, if that factor is negative, then the relation operator changes from `<` to `>`. I'd say the second expression should look like

`...&& ( (prev->y > it->y)`
`          == ((ptInt.x - it->x) * (prev->y - it->y) < (prev->x - it->x) * (ptInt.y - it->y)))`
`)`

The middle line is the same as [Line 54](https://github.com/Return-To-The-Roots/s25client/blob/393b0b8b223ae6e6d45a523e4c337a0316563c71/src/world/TerritoryRegion.cpp#L54), the extra conditional above is just another way to change `<` to `>` if `(prev->y - it->y) <0`.

But I might be wrong about that...

**Comment by MarcusSt** [comment]
You're right, this is an inequation. However your suggestion won't work, as '<' and '>' are not opposites, but '<' and '>=' are. Fixed in c411cbe. I also added extensive tests.

**Comment by lvanderwall** [comment]
You're right in that regard. As I see it, equality only happens if the tested point lies on the area border (and it can only be the long middle line). The return value for those points is undecided either way (it can happen that the original function classifies border points as inner OR outer points), so it should not matter.

**Comment by Flamefire** [comment]
Please note that the equality is a feature. As mentioned in the article no matter if you check the polygon itself, or the complete area with the polygon cut out the point will consistently either on the inside OR on the outside of the polygon. So while border points are unspecified they are at least consistent

**Comment by lvanderwall** [comment]
I'm not sure what you mean with "consistent". If you mean, that any border point will always be classified the same way no matter how often you try, I agree (and that's what stated on that homepage).

If you mean that all border points are classified the same way (and we just don't know whether that's in or out), I disagree. I found a simple counter example where one border point is classified as "inside" while another is classified as "outside". But the author doesn't claim that his algorithm can do that, he only says:

> Points that are on the boundary are classified as either inside or outside. 

That does _not_ imply: All border points are classified in the same way

**Comment by MarcusSt** [comment]
What's important is that the algorithm is deterministic, i.e. you get the same result everywhere for every point. That makes it possible to just check if the right points are contained. Replacing '<' by '<=' does not really help, it only changes the behaviour of the algorithm. The algorithm works by casting a ray (or better: checking the number of edges a ray from the point to the left would cross). If you use '<', it will not include an edge the point is on, if you use '<=', it will include it, so there's no benefit at all. Making the use of '<' or '<=' depend on which y coordinate is greater violates the prerequisite that the order of the points in a polygon doesn't matter. The algorithm will stay deterministic, but only for polygons given in the same order (clockwise vs counter-clockwise). As we are using 'int's, this will lead to problems with polygons that are only one pixel wide.

**Comment by lvanderwall** [comment]
> The algorithm will stay deterministic, but only for polygons given in the same order (clockwise vs counter-clockwise)

You're right: That's where your version of the algorithm (and that on the homepage) truly is superior - your classification of border points does not depend on the orientation of the polygon (clockwise or counter clockwise), mine would have. 

The problem that some border points are classified as inner and some as outer points remains, even in the original version on the homepage for which I listed a small example:
[npoly_test.pdf](https://github.com/Return-To-The-Roots/s25client/files/392657/npoly_test.pdf)

A logical explanation can be found on the bottom of the page.

**Comment by Flamefire** [comment]
Well the basic idea of the algorithm is: Check every edge if the point is truly left of the edge (and there is an intersection at all). If the number of such checks are true an odd time then the point is in the polygon. Vertical lines are ignored. 

What bugs me is although @MarcusSt correctly said, that `<` and `>` are not opposites he used them in his commit, which IMO would change the classification of a point under certain conditions if the direction of the edge is reversed. However this does not show up neither in his tests nor in mine (https://github.com/Return-To-The-Roots/s25client/pull/529/commits/c75073a465ecb49a122622aab4c4508129c959ca#diff-e8304fcf2b0fe3f030fd683c58cb8abcR121) 
Even stranger: Using `>=` instead makes the algorithm wrong when we have equality with zero (at least).

Example: `(pt.x < (prev->x - it->x) * (pt.y - it->y) / (prev->y - it->y) + it->x))`
pt == prev == (10, 5)
it == (10, 10)
10 < (10-10)*(5-10)/(5-10)+10 ==> 10 < 0*-5/-5 + 10 ==> 10 < 10 -> False
But multiply with the -5 you get: 10*-5 >= 0*-5 + 10*-5 ==> -50 >= -50 -> True (!!!)

**Comment by MarcusSt** [comment]
This is not strange at all, it's just maths.

The opposite of `<` still is `>=`: if a is not lower than b, it must be greater **or** equal.

The reason why '<' is replaced with '>' is that you have to do this when multiplying each side of an inequality by a negative number ([explaination](http://math.stackexchange.com/questions/94790/why-do-we-reverse-inequality-sign-when-dividing-by-negative-number)). It does not change the classification at all, the algorithm behaves just like the original. Changing the `>` to `>=` will however lead to different decisions depending on which y coordinate is lower, i.e. whether the polygon is given clockwise or counter-clockwise.

**Comment by Flamefire** [comment]
Yes, I confused math and logic operations here. Multiplying by -1 switches `<` and `>` but negating (`NOT`) switches `<` and `>=`, hence my edit above (I striked the paragraph to make it more clear)

Speaking in words: Check if the point is strictly left OR the edge is strictly right.

So everything is fine now :) I still leave my tests in, as they demonstrate this: It is unspecified whether the border points are inside or outside. But independently of the orientation of the polygon they are always the same. And also: Pt € P1 && P1 € P2 <=> not (Pt € (P1 && P2)) as described above.
