### ISSUE TITLE
Missing border poles

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#538]
I just tested my old restricted areas testmap and had an other strange bug - some poles were missing so my border had some "holes".
They are visible at GF 3000 between 64:48 - 65:48 and 51:57 - 52:56

Map and Script:
http://www.rfmonline.de/rttr/spike/restarea.rar

Replay:
http://www.rfmonline.de/rttr/spike/2016-07-29_16-00-49.rar

**Comment by Flamefire** [comment]
Note: Please add a test when fixing this.

**Comment by MarcusSt** [comment]
Doesn't happen with PREVENT_BORDER_STONE_BLOCKING undefined.

**Comment by Flamefire** [comment]
Ok, so the border stone blocking is the problem. I accidentally left it activated although it was already deactivated. Need a test when this blocking gets a problem. But first a test that those border stones are there, no matter what.
