### ISSUE TITLE
Reserve window visuals / bugs

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#539]
As I was testing something for the farmer bug, I noticed some "bugs" in the reserve window.

- [ ] Buttons not greyed out in the lower section
- +/- Buttons have wrong textures (I think it's okay to keep the - red)
- [ ] Wrong alignement as you can see, in rttr it's way up
- Wrong +/- icons
- [ ] Reserve not set to 1 by default for every rank

![reserve](https://cloud.githubusercontent.com/assets/1276342/17269604/6443d7a4-564d-11e6-942a-15d4f0978512.png)

**Comment by Flamefire** [comment]
I would keep the textures but made the rest checkboxes so they will be done. I think our textures are better, design-wise (red/green, bigger marks not just text) and we have some freedom in redesigning dialogs. The default reserve is critical imo

**Comment by MarcusSt** [comment]
I'd agree to that. We should keep our design as a feature, but adopt the default reserve. @Spikeone: Can you check if there's a default reserve for harbour buildings as well?

**Comment by Spikeone** [comment]
I quite dislike the overuse of the green texture for buttons. That one is nearly everywhere in RttR and often wrong. But I'd still like the grey texture for those buttons instead of the green version - just as most buttons in s2 were.

**Comment by Flamefire** [comment]
There was no indicator for disabled buttons ATM. I implemented something by making the textures darker. Making them greyscale with OGL is not that easy so I think that effect must suffice.
