### ISSUE TITLE
Good, Okay, Bad colors wrong

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#540]
In RttR we use the wrong colors for indication if something is good / a lot, okay / medium, or bad / low.

RttR uses:
Green: 0 224 0
Yellow: 255 255 0
Orange: 255 128 0
Red: 255 0 0

S2 uses:
Green: 113 182 60
Yellow: This isn't even used in S2!
Orange: 219 125 40
Red: 215 0 0

Those colors are less bright and more decent.
![colors](https://cloud.githubusercontent.com/assets/1276342/17269638/3520a65e-564e-11e6-84ca-75c186eabe35.png)

Those colors apply for any indicator for example tools or building productivity.

**Comment by Flamefire** [comment]
Yes, our colors look to bright. I like the yellow to have another step for the colors though. Can you pick a matching yellow?

**Comment by Spikeone** [comment]
Maybe 255 191 51 (last bar) or 255 219 23 (2nd last bar). I'd prefer the last bar, although it's quite close to the orange.

![3520a65e-564e-11e6-84ca-75c186eabe35](https://cloud.githubusercontent.com/assets/1276342/17270807/dff4fe14-566b-11e6-87f3-622cab528575.png)

**Comment by Spikeone** [comment]
Those colors are still not used in any case (for example percentages for the building overlays)
