### ISSUE TITLE
Different Playerblue

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#542]
I just noticed that in S2 the player blue used to have more details than the blue has in RttR. I guess this also applies for most player colors. 

![bluenotblue](https://cloud.githubusercontent.com/assets/1276342/17269707/2183db82-5650-11e6-92df-30b1282b50ab.png)

**Comment by Flamefire** [comment]
Left is S2? IMO the right ones look better. Left is a bit to fancy for that low size/resolution and leads to pixelation.

**Comment by Spikeone** [comment]
I may agree that it's a bit much in S2, but it's also not enough in RttR as you can't see most details. It nearly doesn't make any difference if you just use the same blue or actually add some brightness levels depending on pixel position. It'd be good to have the middle of both imho.

**Comment by Flamefire** [comment]
I think this is impossible to achieve with the current colouring technique. See #563 for an explanation.
