### ISSUE TITLE
Observation window minor bugs

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#543]
The observation window has some minor, most likely visual bugs:

1) It's way too big by default in RttR, it was a bit smaller in S2
2) It's not zoomed in by default
3) It shows the wrong cursor when the player cursor is in the observation area (maybe version related?)

![observation1](https://cloud.githubusercontent.com/assets/1276342/17269717/7822de8e-5650-11e6-8c96-145329e5a6a9.png)
![observation2](https://cloud.githubusercontent.com/assets/1276342/17269718/78e0e154-5650-11e6-9f96-647178a8e34f.png)

**Comment by Flamefire** [comment]
I'd keep the size. We have higher resolutions so we can afford a few pixels more for that window.
I don't completely understand the cursor thing. The cursor switches from hand to yellow arrows in RTTR and to red blocks in S2?

**Comment by MarcusSt** [comment]
S2 only shows the cursor like it's shown in the main view, so you will get the same building aid cursor in the observation window. There's only one global cursor positon: if the mouse is above the observation window, the global cursor position on the map will be determined by it. For all other windows, the global cursor positon is determined by the coordinate in the main window the mouse is next to.

**Comment by Spikeone** [comment]
I agree that we have higher resolutions and can afford a few pixels - but in most cases (at least for me) I use them to only observe a really small area like the metalworks (check if a tool has been produced), a catapult (check if it shoots (either mine or an enemy), a military building (check what kind of soldiers walk into). For thoses cases only a small window is needed (what else do you observer?) and with the current size if you observer like 5 of those cases, you use the space of ~8 original observation windows.

**Comment by Flamefire** [comment]
Fixed the first 2 points but would keep the different cursor as a feature of RTTR

**Comment by Spikeone** [comment]
Well, the cursor is quite big and overlays details :-s

**Comment by Flamefire** [comment]
So how should we handle the cursor? Same as now but the red Block?

**Comment by Spikeone** [comment]
Good question (although thats quite an old bug and question).
The red block also overlays small objects, so that wont help.
I'd still use the red version as it's the original way.
