### ISSUE TITLE
House names / Percentages

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#544]
House names and percentages are shown in S2 above the door of most buildings as the text was moved up by some pixels. In RttR it's just at the same hight as the building node and that way you can't see the door.

Also in S2 settlers were drawn above thoses texts and building in front as well. 

![namesandpercentages](https://cloud.githubusercontent.com/assets/1276342/17269742/1824e332-5651-11e6-8fa2-b24dfadc0469.png)

This is also just a minor bug.

**Comment by MarcusSt** [comment]
Fixed in 7ec7d90.
