### ISSUE TITLE
SetRestrictedArea(): Seperate multiple polygons by nil

### ISSUE THREAD

**Issue by lvanderwall** [Return-To-The-Roots/s25client#547]
Right now, if you use multiple polygons in SetRestrictedArea(), you separate them with (0,0) - pairs. Could we change that separator to `nil `(or` (nil, nil)`, if that's easier to implement)? There are two reasons:

-` (0, 0)` is a normal point but can't be used to define multiple polygons because it acts as separator. That will lead to unexpected behavior if you accidentally use them in your polygons

-` (0, 0)` would be used frequently if you enable the whole map (to create holes later with other polygons later)

**Comment by Flamefire** [comment]
I don't think this is possible as `nil` probably translates to `0` in C++. You can try using it so your scripts look better `(nil, nil)`

There is nothing that special about `(0,0)`. That it acts as a separator is (AFAIK) only a side-effect of the chosen algorithm.  So you can use them. Only point is you can confuse it with the first point. For example enabling the whole map with a hole will look like: `(0,0, 0,0, w,0, w,h, 0,h, 0,0, 0,0, holePolyPts, 0,0)`

@MarcusSt probably knows more, but this should be correct.

**Comment by MarcusSt** [comment]
@Flamefire is right, it's just a side effect of the algorithm. There's no special handling of it. However, if possible, I think that `nil` might look nicer.

**Comment by lvanderwall** [comment]
@MarcusSt, @Flamefire Thank you for the clarification!

**Comment by Flamefire** [comment]
Correct.
We are currently discussing alternatives to the current format. Ideas:

1. Pass single `nil` as separator between polygons and only there. No need to pass start point twice. The correct handling will be done by `LuaPlayer` which inserts 0-pairs and copies start-points.
2. Pass Array of Polygons each as an array of coordinates. Example: ` [ [[0,2],[2,3],[5,3]], [[3,4],[3,5],[5,3]] ]`. Might be a bit trickier to implement in C++ but is the least error-prone version IMO. pretty verbose though.

**Comment by lvanderwall** [comment]
@Flamefire I'd favor the array format we have because of simplicity, with your first addition. If you format the points like this
```
rttr:GetPlayer(p):SetRestrictedArea(
    nil,    	    -- enable the whole map
          0, 127,
        127, 127,
        127,   0,
    nil,        	-- R=6,	X=70,	Y=71
         73,  65,
         76,  71,
         73,  77,
         73,  65,
    nil
)
```

I'd say it's about as error-prone as the verbose version (and less tedious to write :) )
