### ISSUE TITLE
Sea Exploration Path and Attack problem 

### ISSUE THREAD

**Issue by shadowvzs** [Return-To-The-Roots/s25client#550]
Hi, i played on King of The Sea map, there many island, i played vs computer and conquered every island except 3 (bottom-left, bottom-right corner and nearly right-middle).

settings was: minimum scout for exploration, harbor block.

bottom-left island harbour is exploreable with ships but non attackable (even my fortress was full on nearby islands.)

right islands kinda never discovered after hours (and i used 4x speed and around 10 harbour for exploration multiple times...)

.sav 
http://s000.tinyupload.com/?file_id=08932683748380210788

last replay
http://s000.tinyupload.com/?file_id=45776228506641921039

**Comment by Spikeone** [comment]
Tested it an can confirm both bugs.

**Comment by Flamefire** [comment]
Can you tell me a point in the replay, where the bottom-left harbor should be attackable (is explored) and/or attach a savegame from that point?
In the savegame I also see, that the harbor of right-middle was once explored...

**Comment by Spikeone** [comment]
Well, I never thought about that seems like a good idea. I can only guess that the random exploration is a result of the basically random and indirect seafaring. We can not set a target for exploration because navigation was bad => It's also possible to rediscover your own harbors.

But - as I know the seafaring is quite bad if it is the only possible way to attack I agree that we may change it to "ignore own or friendly harbors".

Just asking: random map generator? King of the sea is not a randomly generated map.

**Comment by Flamefire** [comment]
Well random exploration is ok. The scout itself works like that: Get all points in reach that are not fully explored and pick one of them randomly. This makes very much sense as e.g. a geologist would not plant a sign, where one already is. Currently the scout ignores, if the point is visible through a team member, so I'd consider that a bug to be fixed.
Sea exploration works (currently) like that: Get all harbors on same sea and pick one randomly to go to (except current harbor). This is a big bug, as exploration ships will drive to any (even own) harbors which is completely pointless except at the very beginning. This makes exploring unexplored harbors very hard (chance of 1/number of harbors), so this should be fixed.
Seafaring itself is not really random: When you send an expedition into one direction, it will pick the closest, usable harbor in that direction. That is quite good.
Note that neither of this is about attacking. Although you need an exploration expedition (or something else) to reveal the harbor.

No, the function generating random numbers ingame. If that is bad, it is possible, that a specific harbor is rarely picked. This could be one problem, why that specific harbor does not get explored (or only with a exceptionally small chance). Although I could not confirm this in tests, wikipedia states about such problems for arbitrarily choosen parameters for the RNG.

**Comment by Flamefire** [comment]
@shadowvzs or @Spikeone I still need a savegame from that point where the harbor should be attackable but is not. I'm using debug builds which makes the game REALLY slow. So skipping till I find something is quite hard. Also I don't know at which GF the harbor is visible, but you might. Note that you can use the replay to skip to a GF and then save that and send it to me, please :)

**Comment by Spikeone** [comment]
When I'm home I'm gonna create one :)

**Comment by shadowvzs** [comment]
sry but i can't play everyday.

so reply is here, in last seconds is visible the harbour
http://s000.tinyupload.com/?file_id=47407750587358677905

savegame:
http://s000.tinyupload.com/?file_id=21727105562703363779

start gf 2397309

**Comment by shadowvzs** [comment]
actually its not random map but i guess this can happen on any map where have many harbour place but each island just 1 (because if island have more harbour place then probabil player not really care if this happen or if player not play with harbour block, without harbour block easier to attack because chance for any of your ship never discover enemy military building is close to 0)

**Comment by Flamefire** [comment]
Current analysis: RTTR assigns each harbor coastal points. That are all of the 6 nodes surrounding it that are at a sea (have at least 1 neighbour completely surrounded by water) (Note: none of the 6 terrain triangles around a harbor can be water, or we would not be able to place a building there)
A build harbor blocks its own point and the points to WEST, NORTH-WEST, NORTH-EAST, so no figure can walk OVER that point (but start or finish there)
A ship goes to the first coastal point that is at the same sea as the ship. However figures could probably not walk from that point to the harbors flag. In this case the harbor is at the north side of an island and the picked point is NW, so the figure would be trapped between water and harbor -> Can't reach flag.

The solution is not easy. Ideas:

1. Unload figures ON the harbor. This will look ugly for attacks.
2. Check ALL coastal points for a path and let the ship go to a specific coastal point. Makes it more complex and will fail if the NW point is the only such point.
3. Disallow the 3 blocked points for coastal points, but that is a quite arbitrary constraint and might confuse map designers/users
4. Disallow only the NW point. For all others we should always have a path to the flag
