### ISSUE TITLE
Building a castle-sized building next to a gate destroys the gate

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#553]
You can build castles next to gates and if the castles (invisible) attachment overlay the gate it will be removed but there won't be an attachment either leading to an assertion failure on removal of the castle.

Example: Start Mission V with red as dummy, switch to it and build a castle next to the gate.

**Comment by lvanderwall** [comment]
I expected the problem was that in the old roman missions the gate is hard-coded into the map and the wrong routine might be used to set up the gate ("AddEnvObject()" instead of "AddStaticObject()") from the map file.

While playing around with those two, I found that you can build houses right next to the gate if you use "AddEnvObject()" to add it, thus destroying the gate, but you can't do that with "AddStaticObject()".

**Comment by Flamefire** [comment]
I'm not completely sure, but I though EnvObjects are simply ignored (mushrooms etc.) and removed when overbuild (can build exactly ON the object) and StaticObjects block like a flag (or similar) would: Nothing can be build that overlaps that. So if you add the gate with `AddEnvObject` then you should be able to build a house ON the gate not just next to it. While for `AddStaticObject` you should not be able to build on or castles (with its attachment on it) next to it.

**Comment by lvanderwall** [comment]
That might be true, I didn't actually try building ON the gate when I added it with `AddStaticObject()` in my first tries. I just noticed that objects like the gate or all kinds of ruins that are hard-coded into the original maps behave as if you add them by `AddEnvObject()` by script: They disappear if you build near them.

**Comment by Flamefire** [comment]
If I'm not mistaken we don't get the info, what object is static and what isn't, only ids. So for some objects we might use the wrong type. Just open an issue if you find one (like the gate)

**Comment by Spikeone** [comment]
They do not behave like envobjects but static objects with hut size. One problem might be that big building could be built close enough - so set the static object size to 2 and it should work, smaller sizes can be possibly removed by bigger building (watch my miss 2 video, removed the well and guardhouse that way).

**Comment by Flamefire** [comment]
I think there are only hut sized objects in S2. I just tried Mission II and could build a castle next to the castle ruine and it did not get removed.
![castle-castle](https://cloud.githubusercontent.com/assets/309017/17455891/488fc6ca-5bc6-11e6-973c-98de92880f29.png)

Do we consider this as a bug, which needs to be removed in RTTR or do we want this behaviour?
If we want to fix the bug, what shall we do? Building a castle removes the object or is a castle not allowed?

**Comment by Spikeone** [comment]
I think we should keep it the way it is as it's maybe okay for a mapper/scripter if some objects are removed (maybe they are only visual but env objects are a bit strange for buildings). If you reallly don't want an object being removed, one could just use a bigger size (or am I wrong here?). So I think we could keep it the way it is at the moment.

**Comment by Flamefire** [comment]
I don't think static objects should be removed because this is the difference of static objects vs environment objects. So if we don't want to change much, I'd make it so that castles simply don't remove the objects as in S2.

**Comment by lvanderwall** [comment]
![env_size](https://cloud.githubusercontent.com/assets/16540971/17457084/f43f2e68-5bec-11e6-886f-0dc791372c1d.png)

@Spikeone 
Using a "bigger size" (i.e. `size = 2`) for `AddStaticObject()` does not help. First you can override some of the building restrictions by building a castle at the right position (see middle picture), then you can build near the gate (right picture, red circle). Even if you don't do that, you can still delete the gate by building a castle in any of the blue circles.

@Flamefire
I'd say building right next to objects like the castle ruins (your picture) should be considered a bug of the original game. My suggestion is: Treat static objects like constructed buildings of the appropriate size (and size=0 if omitted). If someone wants objects that can be deleted, the mapper can always use `AddEnvObject()` instead (though that sounds a little strange if you use it on the ruins :) ).

**Comment by Flamefire** [comment]
Ok so my solution: Consider it as a bug in the original game, that castle-sized buildings do not remove environment objects at the extension spots that needs to be fixed and currently already is. As a consequence it is also a bug, that the blue spots are castles. They need to be medium houses.
Second: Remove environment/static objects from the game. We only have "environment objects" with a size. Size=0 -> Not blocking (current environment object), Size=1 -> Block point (as in S2 but with the above fix), Size=2 -> Castle like blocking (left pt and upper 2 pts)

@Spikeone @lvanderwall @MarcusSt @Flow86 Any objections/comments?

**Comment by Spikeone** [comment]
I agree that we should consider it as a bug that static objects had only one size in S2 and fix that (regarding the castle-castle situation). However I liked the way it was possible to remove static objects without needing to replace them with env objects - but as this is more a "bug feature" than a real feature, I'd agree with flamefires post. As long as it feels like the original and we do not lose any "features" we have it's all fine :+1:
