### ISSUE TITLE
compile fails with error: conversion to ‘UHWORD’ from ‘double’ may alter its value [-Werror=float-conversion]

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#554]
[ 22%] Building C object s-c/resample-1.8.1/src/CMakeFiles/s-c_resample.dir/resamplesubs.c.o
cd /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build/s-c/resample-1.8.1/src && /usr/bin/x86_64-pc-linux-gnu-gcc  -DBOOST_PP_VARIADICS=1 -DHAVE_MEMCHECK_H -Doverride=""   -march=core2 -O2 -pipe  -ggdb -Wall -Werror -pedantic -Wpedantic -Wparentheses -Wfloat-conversion -Wno-long-long -Wno-deprecated-register -Wno-unknown-pragmas -Wno-c++11-extensions -fno-strict-aliasing -Wno-variadic-macros -Wno-c99-extensions -std=c99 -g -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/contrib/backport/boost_1.56-1.58 -I/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999_build    -o CMakeFiles/s-c_resample.dir/resamplesubs.c.o -c /var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/s-c/resample-1.8.1/src/resamplesubs.c
/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/s-c/resample-1.8.1/src/resamplesubs.c: In function ‘resample’:
/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/s-c/resample-1.8.1/src/resamplesubs.c:496:14: error: conversion to ‘UHWORD’ from ‘double’ may alter its value [-Werror=float-conversion]
     LpScl *= 0.95;
              ^
/var/tmp/portage/games-strategy/s25rttr-9999-r3/work/s25rttr-9999/s-c/resample-1.8.1/src/resamplesubs.c: At top level:
cc1: error: unrecognized command line option "-Wno-c99-extensions" [-Werror]
cc1: error: unrecognized command line option "-Wno-c++11-extensions" [-Werror]
cc1: error: unrecognized command line option "-Wno-deprecated-register" [-Werror]
cc1: all warnings being treated as errors
s-c/resample-1.8.1/src/CMakeFiles/s-c_resample.dir/build.make:110: recipe for target 's-c/resample-1.8.1/src/CMakeFiles/s-c_resample.dir/resamplesubs.c.o' failed 

my system is a gentoo/linux on amd64/glibc2.22/gcc-4.9.3 with dynamic boost-1.56 libs 

full build log is here [build.log.zip](https://github.com/Return-To-The-Roots/s25client/files/403258/build.log.zip)

**Comment by MarcusSt** [comment]
This may have to do with -Werror/-Wfloat-conversion being enabled in 8eeee7c. Quick workaround: try to remove those from CMakeList.txt.

**Comment by Flamefire** [comment]
Correct. Will fix this today
