### ISSUE TITLE
Help popup when toggling player in statistics window

### ISSUE THREAD

**Issue by iceslab** [Return-To-The-Roots/s25client#560]
Toggling player in statistics window causes help text to appear everytime. This behaviour is caused by lack of `break` statement in `Msg_ButtonClick(const unsigned int ctrl_id)` in iwStatistics.cpp

**Comment by Flamefire** [comment]
Thanks for reporting.
Note: If you know a bit about git you could also fix such things yourself and open a PR, if you want. This way it is fixed much faster, as we are often already quite busy with fixing bugs and welcome every additional dev :+1: 
Fixed that locally and will push later
