### ISSUE TITLE
[addon]Soldatenstärke für Regionen bestimmen

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#57]
Soll heißen, dass man einstellen kann, dass zum Beispiel Generäle zuerst an die Front gehen und die Schützen Gebäude im Hinterland besetzen. Durch extra Regler im Militärmenü, welche sagen wo die stärksten Einheiten und wo die schwächsten seien sollen könnte man diese Einstellungen realisieren.

https://bugs.launchpad.net/s25rttr/+bug/367481

**Comment by Spikeone** [comment]
In my opinion useless!

**Comment by MarcusSt** [comment]
Original reporter: Spikeone. Criticized as useless by: Spikeone. Therefore: won't fix.

**Comment by Spikeone** [comment]
Reporter != Original Idea
