### ISSUE TITLE
Wasteland objects have wrong sizes

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#570]
Original:
![objects1](https://cloud.githubusercontent.com/assets/1276342/17650893/e322c7d4-6259-11e6-9848-6962af11c2e2.png)
![objects2](https://cloud.githubusercontent.com/assets/1276342/17650894/e3ef5a60-6259-11e6-8806-c4e6e2998fb5.png)

RttR:
![objektrttr2](https://cloud.githubusercontent.com/assets/1276342/17650979/6d6b5ff8-625c-11e6-96dc-e0fc0f6830b0.png)
![objektrttr](https://cloud.githubusercontent.com/assets/1276342/17650981/70a50354-625c-11e6-838e-47e11ae09952.png)

**Comment by Flamefire** [comment]
Please check again with latest nightly. There was a typo making all objects block nothing

**Comment by Spikeone** [comment]
My answer is gone? Strange.
Everything is fine except the big skeleton which is a valid spot in rttr but shouldn't
