### ISSUE TITLE
Wasteland lava (maybe all lava types) don't block enough

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#571]
![bugged](https://cloud.githubusercontent.com/assets/1276342/17651026/878145be-625d-11e6-9e8a-fd07cc2c28b7.png)

The shown spot shouldn't be passable by any settler. As Lava has non passable node around, this should also affect soldiers.
Tested this in the original, it was not possible to attack (although the window told you, you could) but no soldier attacked until the path was clear.

Don't know if this also affects all other lava/textures the same way

**Comment by Flamefire** [comment]
There are quite a few corner cases. First: No roads or figures next to lave and snow. But they are allowed next to water and swamp. BUT swamp maps to lave with many stones (http://settlers2.net/documentation/world-map-file-format-wldswd/), so there it is allowed.
Also figures can walk (at least) 1 node on water or swamp.
