### ISSUE TITLE
Building quality sometimes wrong

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#572]
It happens from time to time that the BQ is only shown as medium building instead of castle building.

http://www.rfmonline.de/rttr/spike/2016-08-14_13-14-47.rar

Same problem as before

**Comment by Flamefire** [comment]
Where and when exactly? The replay is >200k GFs and I don't know what to look for. Seems to be ok to me

**Comment by Spikeone** [comment]
Happens always (nearly) when destroying a building (often building site) close to a big building spot - that big big building spot stays often a medium.
Gonna test that when I'm home

**Comment by Flamefire** [comment]
If this is what I suspect then it is enough to try this with flags and building sites. Castles have the "appendices" (or extensions)...
So probably if you destroy something that is 3 points away from the (possible) castle spot, which frees something that has formerly blocked that from beeing a castle spot, then it will stay a castle. Question: Can something 3 spots away from a something influence a something else (especially a castle with its appendices)? Current assumption is NO. If you can come up with the opposite this can be changed.

**Comment by Spikeone** [comment]
https://www.youtube.com/watch?v=v6KRofuHhBs&index=1&list=PLRJTCO4nl4r9RTPhF8FOx_UM0n__hd-QX

at minute 19:00, just have a look at my actions. GF is around 35000, the replay asynced with the latest rev.
