### ISSUE TITLE
Observation window zoom

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#573]
I'm a bit confused about the zoom in effect when opening a new obseevation window.

Is this behavior wanted?
Is a more s2 like way hard(er) to implement?
Is this an unknown bug?

**Comment by jhkl** [comment]
Unknown bug. I didn't think about the observation window. 
What would be your expectation?

**Comment by Flamefire** [comment]
I thought I fixed this with https://github.com/Return-To-The-Roots/s25client/commit/555da91012fb889b4d81b329938963970d3560f6 but we have a shadowing issue there :/ Fix incoming...
