### ISSUE TITLE
rttr:MissionStatement do not always show octavianus

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#576]
As the current impelementation always shows octavianus this feature became quite useless for any custom campaign. Why don't we just add the same parameters as the messageboxex has?
=> File, ID, x, y? 
I mean that way we had the chance to implement custom campaigns.

**Comment by Flamefire** [comment]
Well... First you complained the window does not look like the one in S2 and now you don't want that ;)

I'm about to add custom images. In the current version I'm using the images 233-250 of IO.LST, which is required for the mission goal.
I will pass that to lua so you can specify one of those.
The messageBoxEx is quite hacky and error prone to layout issues. So I won't let you move the image. For now you also need to live with the limited choice but that should be enough. If we implement custom campaign lsts you can easily replace them.

**Comment by Spikeone** [comment]
I complained more about every other visual but and I'm quite thankfull that those bugs were fixed.

May you implement the passing of nil or something like that if one doesn't want any graphic? That'd be enough for now (although we should still add a way for custom graphics, even if the are auto aligned).

**Comment by Flamefire** [comment]
Yes, already planned: https://github.com/Return-To-The-Roots/s25client/pull/577/commits/7be1f803040ed2faf12e33c716118b69cba7826c#diff-a79cc72b1116b302b9ccf0d67521ab5aR30

**Comment by Spikeone** [comment]
<3 :)

**Comment by Flamefire** [comment]
BTW: I don't know the names so I simply counted the avatars ;) If you tell me the names I could replace the AVATAR<n> names

**Comment by Spikeone** [comment]
I'm not sure - looks like IDs 239 - 250 are not the ones used ingame (there is no octavianus?).  So names for 251-263
Julius
Brutus
Tsunami
Yamauchi
Olof
Knut
Mnga Tscha
Shaka
-
Hakirawashi
Erik
Todo
Octavianus

**Comment by Flamefire** [comment]
Hm, but the small ones (251+) are to small for use there. Octavianus is the big one and must be enough ;) How shall we call the explainer guy?

**Comment by Spikeone** [comment]
Maybe just "Mentor" ?
