### ISSUE TITLE
AI does not build fisheries

### ISSUE THREAD

**Issue by RM87** [Return-To-The-Roots/s25client#578]
Ai does not build fisheries. At least not on halve grass/halve mountain terrain. 
Observed on Big slaughter v2.
Add-on for non exhausting fish enabled.

Also the AI debug overlay for fish and iron ore crashes.

Attached savefile.
[Big Slaughter v2 (Auto save).sav.zip](https://github.com/Return-To-The-Roots/s25client/files/421418/Big.Slaughter.v2.Auto.save.sav.zip)

**Comment by Flamefire** [comment]
@jhkl Probably something for you?

**Comment by jhkl** [comment]
Fixed crash, debug function shows 0 fish, I will check it further in the next days.

**Comment by jhkl** [comment]
The AI and its resource maps do need a overhaul. The initial idea to use these resource maps was discarded(?), but somehow it still relies on the resource maps (even though a comment claims "//copy the value to the resource map (map is only used in the ai debug mode)").

**Comment by Flamefire** [comment]
:+1: Go for it!
If you can, try to add tests, so this does not happen anymore. At least be generous with comments, especially function/class documentation.
