### ISSUE TITLE
It is possible to jam the roads completely

### ISSUE THREAD

**Issue by RM87** [Return-To-The-Roots/s25client#579]
It is possible to jam the roads completely. Occours when player looses land and different islands of roads emerge. There is another piece of remaining land for the same player where the stuck wares are being waited for construction.
Jam on first island:
![screenshot from 2016-08-17 21-19-41](https://cloud.githubusercontent.com/assets/859636/17748484/4b06d0ba-64c2-11e6-9aa6-6923bf419fb7.png)
Place where the jammed wares are being delivered to:
![screenshot from 2016-08-17 21-53-43](https://cloud.githubusercontent.com/assets/859636/17749136/2388d9a4-64c5-11e6-9253-4bb411506d9e.png)

[Big Slaughter v2 (Auto save).sav.zip](https://github.com/Return-To-The-Roots/s25client/files/423332/Big.Slaughter.v2.Auto.save.sav.zip)

**Comment by Flamefire** [comment]
Can you add the replay to this game so we can find how that could happen?

**Comment by Flamefire** [comment]
Found the cause: AI method `DistributeGoodsByBlocking` tries to make all warehouses contain at most 30 boards. The one on the island has less than 30 boards and so the HQ is blocked for boards -> no goal for boards.
I'll fix it so, that the AI first orders warehouses by reachability and check that condition for each group.
