### ISSUE TITLE
AI removes inland military building roads too early

### ISSUE THREAD

**Issue by RM87** [Return-To-The-Roots/s25client#580]
AI does remove roads to inland military building too early by not taking into account soldiers that are still returning from the battles. This results in an inland military building with more than one trapped  soldier in it being without road. grf 482000. Location: western side of orange players land.
![screenshot from 2016-08-17 22-49-11](https://cloud.githubusercontent.com/assets/859636/17751393/97743688-64cf-11e6-89e1-6dd775dc7638.png)
[2016-08-17_21-53-08.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/423568/2016-08-17_21-53-08.rpl.zip)

**Comment by Spikeone** [comment]
Is this still a problem? Anyone encountered it?

**Comment by Spikeone** [comment]
@RM87 closing this as there hasn't been any new report of this problem lately.
