### ISSUE TITLE
Crash when zooming out

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#582]
The game crashes if you use WinAPI + Fullscreen + 1920x1080 and zoom 10% out, if you use windowed mode 800x600 this doesn't happen.

EDIT: Yes, 10%

**Comment by jhkl** [comment]
I'm guessing you mean 10%, not 100%?

I can confirm the crash with 10%, 1920x1080, Fullscreen, Win API.

I have no clue why. Maybe we have to set a stricter limit.

**Comment by jhkl** [comment]
With my Visual Studio build I can zoom to 10% @ Fullscreen/1920x1080... With the Nightly build I get a crash.

**Comment by Flamefire** [comment]
Probably outdated libs? The ones in the VS build are usually newer. Would be interesting to know where it crashes? Could you try debugging with gdb to get a function and/or line?

**Comment by jhkl** [comment]
I had to reset my PC because of black screen without any hotkeys working anymore (Alt+Tab, Ctrl+Alt+Entf, Alt+F4, ...). So no easy debugging. Ideas?

**Comment by Spikeone** [comment]
Further tests: seems not to be related to the drive nor fullscreen/windowed.

The game only crashed when using 1920x1080 (even when using sdl, windowed mode and resiszing it to fullscreen).
Maybe that helps

**Comment by jhkl** [comment]
![2016-08-23_18-57-54](https://cloud.githubusercontent.com/assets/2512962/17901462/c8841b10-6963-11e6-9bf1-f5d896a40fba.jpg)
1920x1080 WinAPI window mode works fine here.

Maybe specific map? I acutually don't know which map I used when I had the crash... Which one crashes for you?

**Comment by Flamefire** [comment]
Got something: Try a small map.
I got an assertion failure at TerrainRenderer.cpp:873. This function has 2 major problems: First it takes the modulo of a negative number for x and y which is implementation defined, second it will probably bug out if you see the map more than twice. I find it hard to understand, but from what I see it converts a point to a map point and also stores the screenoffset for that point.
I think we can simply do a regular `MakeMapPoint` and calculate the offset as `(x/WIDTH)*(TR_W*WIDTH)` which should solve part of the problem.

**Comment by Spikeone** [comment]
You are right, depends on map size - as it seems the problem is, that there is a maximum of "9 tiles" at all - means if you zoom out further and need "16 tiles" rttr crashes.

**Comment by Flamefire** [comment]
Yeah, that function was the problem: 
![rttr](https://cloud.githubusercontent.com/assets/309017/17907385/071ddc4a-697c-11e6-98ec-643f323e6967.png)

**Comment by jhkl** [comment]
Maybe the minimal zoom should actually also be limited depending on the map size

**Comment by Flamefire** [comment]
I think so too. It should be enough if you see the whole map.
