### ISSUE TITLE
Exploration expedition behavior

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#584]
We just changed the way exploration expeditions work and I think we forgot about some important aspects:

1) When playing with classic exploration you may spot the harbor point itself but you won't get the advantage of an exploration expedition with enhanced range as the point is visible
2) You may see the spot (close enough to an island or lookouttower) but can't see building you could possibly attack

That's why I suggest one more change:
A) Either not only the harbor spot itself should be honored when deciding if the spot should be explored or not but also all possibly scouted points (note: this solution has the disadvantage that this causes nearly every harbor to be scouted as you never have full view on any sea point)
B) or just honor if there is a friendly/own harbor at the spot, if so, don't scout, if not, scout.

C)
I'd keep it simple: If the harbor spot lies in own or ally territory then it is not scouted.

As I can't think of any breaking disadvantage (beside keeping unused harbors) I'd suggest B). Also a mix would be good: either you have a harbor on that spot or see all possible spots to prevent scouting

**Comment by Flamefire** [comment]
I'd keep it simple: If the harbor spot lies in own or ally territory then it is not scouted.

**Comment by Spikeone** [comment]
I'ts still possible to own a spot (maybe country is divided by a small river) but you could still scout enemy buildings? Is a check for owner simpler than a check for friendly harbor?

**Comment by Flamefire** [comment]
Then you'd need to build a harbor at every spot you don't want to scout... Imagine a map with a harbor spot at every possible coast point.

**Comment by Spikeone** [comment]
And at the same moment imagine a map where you can't scout the enemy but he scouts your harbor and attacks it every time you finish it - in my opinion thats worse.

**Comment by Flamefire** [comment]
But thats also highly unlikely as it means you own the harbor spot, but can't reach it by land AND the enemy has buildings next to that spot, but does not own it AND the enemy has no other harbor spots.

**Comment by Spikeone** [comment]
I think it's nearly as likely as your scenario - it's always map dependant. Although my scenario is less likely we should still design seafaring as general working as possible. Maybe (exploration expeditions aren't really original like) we could add some sort of bar to control how exploration expeditions work. 
Means just add a control bar to the expedition page where you could set something from 0-x where 0 = only new, 1 = only currently not visible, 2 = only currently not owned by friend or self, 3 currently no own or friendly harbor on the spot, 4 = all spots
