### ISSUE TITLE
binaries are misplaced

### ISSUE THREAD

**Issue by hasufell** [Return-To-The-Roots/s25client#590]
For a regular installation, there are 3 binaries that end up in `RTTR_DATADIR`:
* s25update
* s-c_resample
* sound-convert

This blocks packaging on most distros that have basic QA, since platform dependent files must not be placed in `/usr/share` and similar (which is the default of `RTTR_DATADIR` and rightly so).

At least for `sound-convert` I was able to fix it by just installing it into `RTTR_DRIVERDIR` (had to change `libutil/src/files.h` and `s-c/src/CmakeLists.txt`). I'm not completely sure how the rest are invoked/found, but they should either be placed in `RTTR_DRIVERDIR`, `RTTR_LIBDIR` (within a subdir) or `RTTR_BINDIR`.

**Comment by Flamefire** [comment]
According to the CMakelists they should be placed in `RTTR_LIBDIR` ("Directory for shared binaries")
That defaults to `RTTR_DATADIR` but is never really used except for setting `RTTR_DRIVERDIR`

I'm currently to busy to fix that, so if anyone got the time to implement and test that...?

**Comment by hasufell** [comment]
Well, the question is if there's anything else that need to be changed except the installation destination (like [libutil/src/files.h](https://github.com/Return-To-The-Roots/libutil/blob/0b536749933c002164f960985d583bc5da12e847/src/files.h#L131) for `sound-convert`).

**Comment by Flamefire** [comment]
Hm. IMO s-c_resample is used by sound-convert only so I think it is enough if they are place together.
s25update is referenced from the start script and from within itself. Probably do a quick grep to see if I missed anything.

**Comment by Mailaender** [comment]
```
[  563s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/s25rttr-0.8.1.git+0a8edac1-0.x86_64/usr/lib64/RTTR/s-c_resample
[  563s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/s25rttr-0.8.1.git+0a8edac1-0.x86_64/usr/lib64/RTTR/sound-convert
[  563s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/s25rttr-0.8.1.git+0a8edac1-0.x86_64/usr/lib64/RTTR/s25update
```

Shouldn't those be be placed in `/usr/bin` instead?

**Comment by Flamefire** [comment]
Is this ok? https://github.com/Flamefire/s25client/commit/ee7eef4defa7285ff01856e0ab4576f0ef468671

**Comment by Mailaender** [comment]
It looks like it is going into the right direction, but it is impossible to apply the patch as you based it upon a huge refactor https://github.com/Return-To-The-Roots/s25client/pull/662 so I get a lot of failed hunks even when trying to pick `files.h` changes and manually patch the sub-modules which are excluded from the diffs as well.

**Comment by Flamefire** [comment]
Yeah sorry for that. Was more thinking about the master after the PR. Just wanted to know if that would work for you or if there is still something missing

**Comment by Mailaender** [comment]
This is also replaces the paths in `rttr.sh` so I'd say :+1:
