### ISSUE TITLE
Can't start RttR on windows

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#599]
This error message appears with the latest windows version (updated by updater):

File or directory does not exist: ./share/s25rttr/GFX/PALETTE/PAL5.BBM
Failed to load ./share/s25rttr/GFX/PALETTE/PAL5.BBM

looks like those paths are meant for Linux.

**Comment by Flow86** [comment]
yes that path is definitly wrong. @Flamefire seems like you "killed" some paths while changing path-stuff
