### ISSUE TITLE
Repeated Asyncs

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#6]
We now have a situation in a game where asyncs happen on a very frequent basis. Please see attached Savegames for reproduction:

https://drive.google.com/folderview?id=0B-w61I34QpTgeUtRbTkxNzRFUzg&usp=sharing

 This is a Win7 64/Ubuntu 64 game. We are happy to assist with further debugging of this issue.

**Comment by danielplatt** [comment]
Game was pretty stable, until we started charburners. Generally game tends to be less stable, when more charburners are involved.

Keep the great work up btw! The game is already awesome and especially has become so much more stable since the first release. :)

**Comment by jhkl** [comment]
Hi,
can you give any more details to these 6 savegames you have uploaded? Do you get an async directly after loading? After some time? With/without actions?

**Comment by mplatt** [comment]
Hi jhkl!
They do not happen immediately after loading. I would say between 30s and 90s into the game. We did something every time though I think not one distinct action (e.g. burning a building) that preceeded the async.

**Comment by jhkl** [comment]
I found something in the ware distribution system that might be responsible. After fixing, I had no async with your savegame. If you continue to get asyncs please open another issue. This one was very helpful! :)

**Comment by mplatt** [comment]
Hi @jhkl 
This looks splendid. I haven't had the chance to test yet but I will soon. Thanks again so much for dedicating your time to investigate the async issues. Very much appreciated from my side as asyncs are most annoying :-)
