### ISSUE TITLE
RttR support for unicode-Mapnames

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#601]
This could effect other things as well.

When naming a map: ĹÔÔÔ.WLD
RttR is not able to use that map. It's simplay not shown in the "Selection of maps" Screen.

The following message is printed to the console:
Could not open '.\RTTR\MAPS\SEA\?ÔÔÔ.WLD': failed opening file: Die Syntax für d
en Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.

This is quite strange - the output is actually the following:
![output](https://cloud.githubusercontent.com/assets/1276342/19016131/00e1376e-8812-11e6-9599-017f6dbd262d.png)

This is just a minor bug

**Comment by Flamefire** [comment]
Closed by #604

Note: UTF-8 output in windows console is now working.
