### ISSUE TITLE
Crash when using UTF-8 special chars in lua-scripts

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#602]
When saving a lua file with unicode encoding (instead of utf-8) the game is not able to read the script at all. 

The following message is printed:
Lua error: ...s/Spike/Saved Games/Return To The Roots/MAPS/MISS201.lua:1: unexpe
cted symbol near char(255)

The actual first line in the script is:
,-------------------------------------------------------------------------------

**Comment by Flamefire** [comment]
Solution: Use UTF-8. I would not allow anything else as we already have everything UTF-8

**Comment by Spikeone** [comment]
Well, we can't support those languages then in missions as we can not translate messages, thats the only downside I see

**Comment by Flamefire** [comment]
Nope. UTF-8 is an encoding for unicode. So support UTF-8 = All chars supported

**Comment by Spikeone** [comment]
When I start a game with a script saved as UTF-8 (thought that was standard but ANSI is the stnadard on windows I guess) which has the following content:

function onStart(isFirstStart)
	rttr:Log("ĹÔÔÔ.WLD")
end

The game just crashes

**Comment by Flamefire** [comment]
That is a bug ;) Will look into that...

**Comment by Flamefire** [comment]
Closes by #604
