### ISSUE TITLE
Single archive download containing binaries for multiple OS

### ISSUE THREAD

**Issue by Hiradur** [Return-To-The-Roots/s25client#607]
[OpenArena](http://openarena.ws/download.php) and [Xonotic](http://xonotic.org/) provide a single download for Windows, macOS and Linux. A single archive contains both i386 and amd64 binaries for these operating systems. This makes it very easy to share the game and ensure everybody is using the same version, e.g. at LAN parties.

It would be nice if RTTR would also provide a single archive for download with binaries for multiple operating systems, for the stable versions at least. The players then only have to drop their Settlers 2 data files into the extracted archive and can start playing.

**Comment by Spikeone** [comment]
So, one player could possibly create such an archive for his LAN-Party, couldn't he? I guess not everyone has a s2 installation on his PC anyway (regarding the DATA and GFX folder).

**Comment by Hiradur** [comment]
> So, one player could possibly create such an archive for his LAN-Party, couldn't he?

He probably could. I didn't think about this before creating the issue. Maybe a simple shell script to automatically pull the separate archives and kind of merge them together would already be enough.

**Comment by Flamefire** [comment]
If one wants that then you could do that yourself. Providing such an archive here is to much work and in the end everyone needs the archive for his os/arch anyway as they can't be mixed. So the gain is very small. Just download all required archives and put them into one folder prior to the Lan party
