### ISSUE TITLE
I can build buildings on water

### ISSUE THREAD

**Issue by kropecznik** [Return-To-The-Roots/s25client#608]
In the Island of Hills map when you start in the blue player's position and build two barracks to the right you'll find a lake, where you are able to build buildings and roads. In this particular map there are even more "buildable" waters, so you'll need to make all water unbuildable.

**Comment by Spikeone** [comment]
I was able to build one flag where it shouldn't be possible but no barracks.
Checked the mapdata, texture 0x06 is used which is buildable water. Maybe S2 replaced those textures when using swd files. 

see:
![mapdata](https://cloud.githubusercontent.com/assets/1276342/21108382/3bae97ea-c095-11e6-89d1-c9315cfd4ff6.png)
and: 
http://settlers2.net/documentation/world-map-file-format-wldswd/

I consider it as a s2 fault, maps can be changed and only few are affected (mostly old original maps)

**Comment by fritzmg** [comment]
Just to mention it here: in fact, you can build on almost _all_ of the water. There are only a few, tiny exceptions, but otherwise water is just flat ground on that map.

<img src="https://user-images.githubusercontent.com/4970961/86529787-8ba8c500-beab-11ea-87bd-dc5d6e86dc04.png" width="502">
