### ISSUE TITLE
Settlers 2 data directories are required both under s25rttr and s25rttr/S2

### ISSUE THREAD

**Issue by nafets1234** [Return-To-The-Roots/s25client#610]
It seems that the destination directory for the settlers 2 data directories was changed in a newer version, but that the change was not completely done. Neither s25rttr nor s25rttr/S2 suffice, I need to copy the files to both directories.

When copying only to s25rttr the client complains that I need to copy the files to s25rttr/S2.

When copying only to s25rtts/S2 the client complains as follows:

```
Starte das Spiel
File or directory does not exist: ./share/s25rttr/GFX/PALETTE/PAL5.BBM
Failed to load ./share/s25rttr/GFX/PALETTE/PAL5.BBM
```

I am using a Mac and version 20161017.

**Comment by Spikeone** [comment]
Related board post: http://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1473

**Comment by Flamefire** [comment]
Sorry, can't do anything atm as I'm abroad

**Comment by Flow86** [comment]
I fixed the build script now (which failed after a jenkins update and produces weird results).

Can you recheck with 	todays version 20161220 90bd49b97c6d379201b6f7762006150ff1e93b34 ?

**Comment by nafets1234** [comment]
Checked with todays version. Now the data is only required under s25rttr/S2 and the game is working fine. Verified.
