### ISSUE TITLE
Blank screen when resizing window on Mac OS X

### ISSUE THREAD

**Issue by nafets1234** [Return-To-The-Roots/s25client#611]
When I change the size of the window, the content gets completely black. Clicking by chance somewhere in the dark I can hear the sound that is usually played when clicking something. So the game still seems to run. When restarting the application the window has the new size and everything works fine again.

**Comment by Spikeone** [comment]
Which version are you using? (Stable? Nightly? If nightly, which rev?)

**Comment by nafets1234** [comment]
I am using a stable version: v20161017-938de57

The Mac OS X version is 10.11.6 (El Capitan)

**Comment by carpusmedia** [comment]
I have the exact same issue, Mac OS X 10.10.5  (Yosemite)

**Comment by frin** [comment]
I can confirm this. In one of the stable builds recently downloaded off the site toggling on fullscreen mode within settings gave me white blank screen. When compiling my own or using nightly builds it produces black blank screen. If you run the game with fullscreen enabled, the game works fine in fullscreen, but it doesn't work if switching when game is already running in window mode.

I am not very proficient with libsdl so I don't know what might cause this, but I did find this: https://stackoverflow.com/questions/8367653/sdl-toggling-fullscreen-reveals-frame - "OpenGL context gets destroyed after toggling the display mode". I think the solution here would be to reinitialize the whole video mode when toggling fullscreen.

Until then, you can enable fullscreen in settings, force quit the game with opt+cmd+esc (kills it instantly), and re-run the game.

**Comment by Flamefire** [comment]
The recent nightly should fix this. Can you confirm?

**Comment by Flamefire** [comment]
Assuming this is fixed
