### ISSUE TITLE
Military buildings near enemy shoreline are filled even if sea attacks is set to off

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#612]
Look at the attached screenshot.
I disabled sea attacks but the military buildings near the shoreline are filled with soldiers anyway and they also 
have the "anchor" flag.

![bug shoreline](https://cloud.githubusercontent.com/assets/13797213/20978563/9658f8ba-bca9-11e6-8c61-56d6033adfe0.png)

**Comment by Spikeone** [comment]
working as intended as far as I know, the near harbor flag is never removed (as you can still build harbors). Thats why there is still that anchor flag. You may set the "near harbor" occupation bar to 0%.

I'm not sure if this is a bug or not so I'll flag it as question.

**Comment by Spikeone** [comment]
/push maybe we should set the setting just to 0 if sea attacks are off?

**Comment by Spikeone** [comment]
There is an addon for checking attack distance now. so part one is fixed.

The near harbor spot occupation setting should be 0 when sea attacks are off

**Comment by Flamefire** [comment]
But this is something a player can currently do, right? And it is the same as S2 so I'd say: Working as intended

**Comment by Spikeone** [comment]
Yes thats true and thus I agree. Although it'd be an improvement to completely remove near harbor check when you can't attack by sea (just as the original). Also the bar shouldn't be used (removed) when there is no seafaring. One could use near harbor spots for better upgrading thus abuse the feature a bit.

So best solution: Remove near harbor if sea attacks are disabled

Okay solution: Just set the value to 0 so you dont have to change it

Pragmatic solution: Don't change anything and let users do work

**Comment by Flamefire** [comment]
Did the original really ignore the value of the bar? I don't think so because it does either have seafaring or no harbor spots.

As in RttR IIRC you can build a harbor on a harbor spot no matter what seafaring is enabled this setting is still useful: "Soldiers near harbor spots" you get what it says, right?

**Comment by Spikeone** [comment]
Settlers 2 simply had no near harbor spot nor the setting - this is rttr only. So neither the classification nor setting was available.

**Comment by Spikeone** [comment]
+ no near harbor spot classification yes

**Comment by Spikeone** [comment]
@Flamefire this one is fixed, isn't it?

**Comment by Flamefire** [comment]
Yes, by #1479
