### ISSUE TITLE
Reserve (in HQ) count above 255 resets to 0

### ISSUE THREAD

**Issue by alfakr0ll** [Return-To-The-Roots/s25client#613]
When you pass 255 in reserve count the allocated soldiers is disallocated and the current number starts at 0 (the soldier are released into stock).

Either lock the maximum reserve count at 250 or (my pref) allow an even bigger reserve count (limit at 1000?).

**Comment by Spikeone** [comment]
Tested it with the latest rev, everything seems fine.

I guess you are using the latest stable build?

![reserve](https://cloud.githubusercontent.com/assets/1276342/21107770/25fbcd98-c093-11e6-975b-620dd244fcf1.png)

**Comment by alfakr0ll** [comment]
A clarification:
The requested number of soldiers can go above 255, but not the actual soldier reserve count.
On my screen that's listed as 24/280, and the 231 soldiers that was in reserve at 255 are moved back to stock. If you reduce to lower than 255 the reserve count moves instantly  back to the requested number (and soldiers are taken from stock).
![s2bug](https://cloud.githubusercontent.com/assets/8654663/21109429/5607243c-c099-11e6-83a6-9d92fab3b7d7.png)

**Comment by Spikeone** [comment]
May you test this issue with the latest nightly build?

**Comment by alfakr0ll** [comment]
Latest nightly build won't run at this computer. Have uploaded save file so others can try. 

Will try nightly on another computer later tonight.

[wer.zip](https://github.com/Return-To-The-Roots/s25client/files/646752/wer.zip)

**Comment by alfakr0ll** [comment]
Same problem in latest nightly (20161017)

had to make a new game because the other was to old for Nightly.

I found another bug. If you save with reserve count X/255+X, the loaded game list reserve as X/X

Savegame attached.
[test.zip](https://github.com/Return-To-The-Roots/s25client/files/647595/test.zip)
