### ISSUE TITLE
Verbesserung der deutschen Übersetzung

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#619]
Es gibt einige Tipp- und Grammatikfehler, die ich gerne korrigieren würde. Einige Dinge würde ich auch gerne vereinheitlichen, wie etwa unterschiedliche Varianten von Gold/Eisenerz/Kohle gefunden - einmal mit Punkt, zweimal ohne. 

In einem zweiten commit würde ich gerne einiges vereinfachen, so sind zum Beispiel viele der Beschreibungen in der Liste der Erweiterungen zu lang oder missverständlich. Davon könnte eigentlich vieles in den "?" Boxen verschwinden, auf denen man bei Unklarheiten klicken kann, oder? 

Die Übersetzung der Infobox des Hafens fehlt vollständig, hier ist einfach der normale Infotext des Lagers eingefügt worden. Was soll dort eigentlich stehen?

**Comment by Spikeone** [comment]
Also, wenn ich das richtig verstehe, willst du das machen oder? 
Also wenn es Fehler sind, ist es immer schön, wenn sie behoben werden ;)

**Comment by Flamefire** [comment]
See https://github.com/Return-To-The-Roots/s25client/wiki/How-to-translate-the-game

**Comment by stefson** [comment]
Ich kümmer mich die Tage erstmal um die Korrektur der Fehler.

**Comment by stefson** [comment]
So, habe einen Pullrequest eröffnet für das submodul. 
https://github.com/Return-To-The-Roots/languages/pull/6

Bitte kommentieren @Flamefire @Spikeone @Flow86

**Comment by stefson** [comment]
Has been merged into master, closing :) 
https://github.com/Return-To-The-Roots/languages/commit/33dad12f33fe7542cfede5e0bee9b9de74a630fd
