### ISSUE TITLE
Network problems in special setup

### ISSUE THREAD

**Issue by jojomi** [Return-To-The-Roots/s25client#622]
I have seen the following problem repeatedly. My setup are three players A, B, and C playing a multiplayer game. A is hosting the game and in the same network with B. C is reachable over internet. On the router A and B share the ports are forwarded to A's machine. Now A opens a game, B and C join (B using the 192.168.x.y address of A, C using A's public IP address). The game opens fine and works.

After a while (about 3 hours) the game starts to lag about every second noticably. The snake indicator tells it is B's fault. In a recent game when B was viewing an island he had discovered and settled on in a sea map, the game almost stalled for everyone. After navigating more closely to his headquarters, the game returns to its previous state (lagging about once a second).

A and C on Windows, B on Linux, nightly build as of 20170104.

**Comment by Spikeone** [comment]
Sounds like B's PC has problems keeping up, whats the framerate for B at the beginning? And what Framerate does he have when taking a look at his HQ-Area?

**Comment by jojomi** [comment]
I can check next time, what could we do in case this happens again?

**Comment by Spikeone** [comment]
Hm, looks like you haven't tested yet.
You could either take smaller maps, play without building names enabled etc.
