### ISSUE TITLE
Forester wont plant trees on borders.

### ISSUE THREAD

**Issue by alfakr0ll** [Return-To-The-Roots/s25client#624]
Is this intended?

**Comment by Spikeone** [comment]
![foresterborder](https://cloud.githubusercontent.com/assets/1276342/23073100/aad1cb00-f534-11e6-8ea9-5a37cc1c4231.png)

yes - thats the original behavior

**Comment by alfakr0ll** [comment]
Sorry for late reply, but could it be changed?
Even though it's the original behavior, is it a good behavior?

**Comment by Spikeone** [comment]
Well - maybe it's just me but I think it is. You can clearly see any border and you may also prevent blocking with trees a bit (No idea if the forester plants trees on hostile borders). 
I don't see any use, do you?
