### ISSUE TITLE
Game crashes when i try to save after 262.000 GF

### ISSUE THREAD

**Issue by AlpakaSiedler** [Return-To-The-Roots/s25client#625]
I'm playing with my girlfriend on Lan-network against 6 ai players. 
after 262.000 GF the game always crashes when we try to save it (or the autosave wants to save it). 

We disabled autosave so that it won't crash and than tried to save it again but it crashes, too.

We're playing with version 2017_02_06.

**Comment by Spikeone** [comment]
Can you provide savegames, replays and the map? Which os are you using?

**Comment by AlpakaSiedler** [comment]
i added the savegame and the map as zip. I'm running Windows 7 Home Premium, same as my girlfriend.
sorry for my bad english, i'm from germany.

unfortunately i don't have a replay, where do i find this?


[Inselwelt1.zip](https://github.com/Return-To-The-Roots/s25client/files/809767/Inselwelt1.zip)
[coolste map ever.zip](https://github.com/Return-To-The-Roots/s25client/files/809766/coolste.map.ever.zip)

**Comment by Spikeone** [comment]
C:\Users\[DeinBenutzer]\Saved Games\Return To The Roots\REPLAYS

Dort dann die entsprechenden Replays (am Datum zu erkennen).

**Comment by AlpakaSiedler** [comment]
Ich schätze mal das müsste dann die sein. 

Haben vorhin noch eine "Lösung" (zumindest vorübergehend) gefunden, ich hab den Spielstand einfach mal kopiert und umbenannt, dann hat es wieder funktioniert. 
[2017-02-28_20-02-08.zip](https://github.com/Return-To-The-Roots/s25client/files/809905/2017-02-28_20-02-08.zip)

**Comment by AlpakaSiedler** [comment]
Okay wir haben jetzt das selbe Problem bei einem neuen Spielstand bei etwa 243.000 GF, spiel stürzt wieder ab, diesmal hat der Trick mit dem Spielstand kopieren und umbennenen das jedoch nicht lösen können. Ich tu dir mal die map, spielstand und replay mit rein. 
[Replay.zip](https://github.com/Return-To-The-Roots/s25client/files/815900/Replay.zip)
[Save.zip](https://github.com/Return-To-The-Roots/s25client/files/815902/Save.zip)
[Map.zip](https://github.com/Return-To-The-Roots/s25client/files/815903/Map.zip)

**Comment by jhkl** [comment]
Zum ersten Spiel:
Im Hafen bei 186/170 sind Soldaten (z.B. objId 9647573) die zur Festung 182/165 wollen. Die wird kurz nach dem Beginn des Savegames/Replays von einem Katapult zerstört. Aus irgendeinen Grund werden die Soldaten davon nicht benachrichtigt. -> Inkonsistenter Zustand

Beim Speichern wird dann versucht das Zielgebäude zu speichern, was fehl schlägt.

Problem: Zu Beginn des Replays ist es schon "zu spät" um das Problem zu erkennen. Kannst du für das Spiel noch ein Replay hochladen, das den Zustand davor beinhält? Also vor GF 261747?

**Comment by AlpakaSiedler** [comment]
Danke für die Antwort, ich hab mal alle 3 Replays von demselben Tag die ich im REPLAY Ordner hab mit angehängt, vielleicht helfen die weiter?! 
Währ richtig super wenn das iwie in den Griff zu kriegen währe, meine Freundin und ich sind totale Siedler Fans :D 

[REPLAYS.zip](https://github.com/Return-To-The-Roots/s25client/files/818440/REPLAYS.zip)

**Comment by jhkl** [comment]
Ich denke ich habe das Problem gefunden. 

Die Savegames lassen sich nicht retten, aber du kannst mit den Replays einen ähnlichen (nicht den gleichen) Zustand erreichen. 
Lade die Replays und springe mit "J" bis zum Ende und versuche dann erneut zu speichern. "Async"-Warnungen während des Abspielen des Replays sind zu erwarten und kannst du dann ignorieren

**Comment by AlpakaSiedler** [comment]
Alles klar dann weiß ich bescheid! 
An dieser Stelle ein herzliches Dankeschön von uns an euch für dieses tolle Projekt!
