### ISSUE TITLE
PathConditionHuman Is incorrect, allows walking across water

### ISSUE THREAD

**Issue by utahwithak** [Return-To-The-Roots/s25client#626]
~~This is an incorrect check~~
~~https://github.com/Return-To-The-Roots/s25client/blob/master/src/pathfinding/PathConditions.h#L42~~

~~the comment above states~~
~~`// If no terrain around this is usable, we can't go here`~~
~~in reality what it is checking is if any point is usable~~

People can walk across V's of water which shouldn't be allowed. You can repro this easily with shipbuilders walking along beaches.

See below comment

**Comment by utahwithak** [comment]
As a follow up the edge to edge is also partially to blame. And would likely be a better place to fix it.

**Comment by Spikeone** [comment]
I'm not 100% sure if I get what you are saying.

As far as I remember 1 - Node water is only passed by settlers if there is a road, otherwise they don't.

![vs2](https://cloud.githubusercontent.com/assets/1276342/23783565/d6191ef2-055c-11e7-873c-118f857ae9a0.png)
So thats also totally valid in the original

**Comment by utahwithak** [comment]
Ok. I didn't realize it was legal in the original. Not that I think it should be. But the bug is that they **do** cross even if there isn't a road. (A hunter could walk across that while hunting, or a shipwright, or fisherman)

**Comment by Spikeone** [comment]
You may have a replay where worker cross those without roads? I'm sure it hasn't been that way all the time as I designed a map using this behavior which would be broken then...

**Comment by Spikeone** [comment]
Maybe it is a bug and related to #354

**Comment by Flamefire** [comment]
This seems to be a bug. Will need a carefully designed test case before fixing this. 
Basically we have 2 cases: roads are allowed but figures only after there is a road
