### ISSUE TITLE
[LUA] rttr:MissionStatement enhance function

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#628]
Well, this mission statement is quite good for the original missions - but for nothing else as regardless of nation, situation etc., always octavianus is shown.
This window should have optional parameters, to either at least disable the image or show a custom image.

Edit: Also the game may NOT pause always -> add another parameter

**Comment by Flamefire** [comment]
Image is changeable. Pause is enabled on single player. Is that enough for this?

**Comment by Spikeone** [comment]
Oh - so the wiki is not up to date then? I was sure one could change graphics but as the wiki had no such option I assumed that this was just an idea.
Gotta update the wiki then.

Pause: Actually, for my use case, it is. I'd still prefer an option to not pause the game but as it doesn't matter for singleplayer games (might just be annoying) it's okay.
So, It'd be  great if you could add an additional, parameter. But as I can't give any use case right now, it's also okay if this issue is closed.

**Comment by Spikeone** [comment]
@Flamefire any news, a yes / no for each question would suffice :)

**Comment by Flamefire** [comment]
The wiki was slightly wrong. Just add another param to `MissionStatement` to change the image. And finally I'll also add a last param that can disable pause. Wiki is updated.
