### ISSUE TITLE
Colors mixed up on loading game

### ISSUE THREAD

**Issue by jojomi** [Return-To-The-Roots/s25client#632]
When I load a game with two players (network, direct ID) and 3 AI players, I can't get it to work with same players and colors as initially. I **can** have the right colors, but (at least) the human players swap slots, so I continue my team mate's game and he does continue mine, **or** I can keep my people, but swap colors with my mate.

If you tell me where to find my saved games, I can attach an example.

**Comment by Flow86** [comment]
you'll find them on windows under "Saved Games\Return To The Roots" on Linux at ~/.s25rttr . I can't remember the directory on MacOS now but its somewhere inside the home directory

**Comment by jojomi** [comment]
@Flow86 Thank you!

This game was started with Mareike as red, and the other human blue. When I load a game using this file, I cannot change the "former player" for both of us. But I need to do that because when I join the game (formerly being blue), I join for my mate's slot and red color. If I accept, we swap positions (correct colors). If I decide to switch our spots using the dash signs left of our names, we spawn in the right place, but the colors are swapped. This state should be impossible imho and I can't bring the game back to the state when we left it.

This bug is around for at least 3-4 months and we already saw it with three human players.

[halb 2.sav.zip](https://github.com/Return-To-The-Roots/s25client/files/926676/halb.2.sav.zip)

**Comment by Flamefire** [comment]
Found it: Swapping players swaps everything. This makes totally sense in new games as you just want to swap positions. But for savegames only the slot (therefore socket) should be swapped.

**Comment by jojomi** [comment]
👍 great to see the fix in 86000ba151475723b9435998e78a3792854c4ed0. Can't wait for it to be merged and compiled, so I can check it :)
