### ISSUE TITLE
[suggestion] option to not allow CPU to build catapults

### ISSUE THREAD

**Issue by alfakr0ll** [Return-To-The-Roots/s25client#634]
I might be playing this different from others. But I play mainly as a time waster when it's quiet at work. I only play against CPU, and most of the play time is minimized when I do work stuff. The enemy catapults is quite annoying in this type of game. The option to disable all catapults does not fit my scenario cause I need them to make sure my border stays safe when I'm doing work stuff.

**Comment by Spikeone** [comment]
Quite unfair when you could use catapults but the AI don't, isn't it? ;)

Well, currently you can use lua scripts for having the same result.
Overall I'd suggest a more general approach, forbidding buildings for certain player, setting building limits etc.

**Comment by alfakr0ll** [comment]
Sometimes when I play, I don't want it fair I want it easy. 
So it can be a relaxing background game while I'm at work or doing other stuff.

**Comment by Spikeone** [comment]
So I'd suggest chaning this request to the general approach as it includes your addon and could be used in scripts etc.

**Comment by Spikeone** [comment]
see #666 a more general approach
