### ISSUE TITLE
AI not changing/storing units in reserve

### ISSUE THREAD

**Issue by alfakr0ll** [Return-To-The-Roots/s25client#635]
This makes the HQ a bit to easy to conquer.

How about the AI store 10% of the total for each unit in the garrison?

**Comment by Spikeone** [comment]
Even I do not store any soldiers as the HQ is one of the worst storehouses. Using distributed storehouses (with fortresses) is better than defending the HQ (I'd even like to destroy it).
So I think the AI should use storehouses instead of an HQ (just like players do).

**Comment by Spikeone** [comment]
Just a quick thought: Maybe if the HQ is close to a harbor spot or close to border the AI may increase reserves in my opinion. Although this still means the AI can't attack anymore and I as a player wouldn't do that either.
