### ISSUE TITLE
libmygettext.so is built although it is only internally used

### ISSUE THREAD

**Issue by Mailaender** [Return-To-The-Roots/s25client#637]
https://bugzilla.novell.com/show_bug.cgi?id=1037920 Not really sure what happened here for @openSUSE. As it is a sub-module here and not packaged anywhere else I assume it is some kind of custom fork, which is not meant to be compiled into a shared library .so file.

PS: Your milestones show 0.8.3 as WIP. The stable version 0.8.1 is ancient and won't compile anymore. Can you tag a 0.8.2 release for tarball generation and easier packaging?

**Comment by Flamefire** [comment]
It is used by the client as an improved version of the gettext library. So it is required. What would you suggest to do to make it work? 

Yeah I'd bump the version to 0.8.2 as the current dev is so much more stable than the stable. @Flo86

**Comment by stefson** [comment]
0.8.1 compiles just fine for me, it needs a little bit of patching though. Have a look at the gentoo portage tree!

**Comment by Mailaender** [comment]
Looking at https://gitweb.gentoo.org/repo/gentoo.git/tree/games-strategy/s25rttr/files (thanks!)

**Comment by Flow86** [comment]
@Flamefire can you look at those patches and "upstream" them if possible (like the false vs NULL patch etc)?

**Comment by Flamefire** [comment]
@Flow86 I think all of those patches are already in the master. I checked them and can't find a difference to the current master.
I'd say a retag after my latest PR is appropriate.
