### ISSUE TITLE
Map selection misses a key release event

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#643]
When using up / down in the map selection screen, the key released event seems broken for the up key. When hitting the up key and releasing it (going up one map), the game keeps  going up till the list ends. For key down it works as it should.

**Comment by Flamefire** [comment]
There is no special handling of keys in the map selection. Can you check, if this is also in other table controls?

**Comment by Flow86** [comment]
perhaps the old SDL bug again?

**Comment by Spikeone** [comment]
Well, i tested it this morning and it worked well, but I'm gonna do some additional testing, either it was related to a special order of clicks / selections or it was an OS bug. 

And as I'm writing this, I remember that borderlands the pre sequel was running, maybe that caused the bug. But I'm going to test that as well.

**Comment by Flamefire** [comment]
BTW @Flow86: could we switch to using SDL only? WinAPI seem to cause problems every now and then and I think GLFW wasn't used for ages so it is just additional maintenance overhead and source of bugs

**Comment by Spikeone** [comment]
@Flamefire but then the editor wouldn't work anymore with the current SDL.DLL

**Comment by Flamefire** [comment]
I'd remove the DLL as it won't be required anymore. Therefore no conflicts
BTW editor: would be great to update it and include in rttr. If we could reuse the terrain renderer then we'd save quite some time and code and would also know that our design is good. But that requires some work... 
Probably as a first step we could update the editor to be compatible with the new SDL.dll
