### ISSUE TITLE
Save/Load addon settings

### ISSUE THREAD

**Issue by jojomi** [Return-To-The-Roots/s25client#658]
I would like to be able to save and restore my favorite set of addons when creating a game (ideally more than one slot, but even "restore last game's addons" would be a huge improvement).

Is this implemented already and I missed it or what do you think about it if it is not yet there?

**Comment by Spikeone** [comment]
When hosting a game and changing the addon settings in the host menu, those settings are saved for the session (means hosting multiple games results in the same addons if you only change them in the first game).
For persistent addons you should use the main menu > options > addons, those settings are persistent, means they are set whenever you start the game.

I'd still agree that custom or multiple presets are a good feature...

**Comment by jojomi** [comment]
Oh, thank you, I'll hvae to check out that options menu!

**Comment by Spikeone** [comment]
I created a wish report which should cover the missing feature #665
