### ISSUE TITLE
Kartenbewertung

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#66]
Nach beenden einer Runde kann jeder Spieler die Karte von 1-10 bewerten, daraus der durchschnitt mit 10 multipliziert und auf ganze Zahlen gerundet ergibt dann eine Bewertung der Karten wodurch man filtern kann.

https://bugs.launchpad.net/s25rttr/+bug/367919

**Comment by Spikeone** [comment]
Could be done by our team or an online portal where you can browse and download maps directly.

**Comment by MarcusSt** [comment]
As you already say, this is nothing that can be done in a meaningful way in RTTR. Maps may be available locally only and there is no online map selection. Therefore this does not really make sense at the moment.
