### ISSUE TITLE
Broken graphics on linux

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#663]
something must have gone wrong here? :-) 

![2017-07-22-112833_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/28490043-72cadc94-6ed1-11e7-964f-3c951974d28d.png)

**Comment by Flamefire** [comment]
Should be fixed in 12a19a18

**Comment by stefson** [comment]
I tested this commit yesterday, but without success. The game renders exactly the same incoherent graphics.

**Comment by Flamefire** [comment]
Can you disable the optimized graphics for a test?

**Comment by stefson** [comment]
![2017-07-25-223719_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/28592830-8411af26-718a-11e7-84be-ff8989ee9d1d.png)

This is at 12a19a1 and with disabled optimized textures. Not perfect (look at the shadow of the boat) but usable, I guess.

**Comment by stefson** [comment]
![2017-07-25-223836_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/28593140-9f8085c4-718b-11e7-8414-9d26e7fa9438.png)

I just ran into another issue - if I want to load a savegame or a replay, I cannot double click on the savegamefile as it used to be the case before, instead the savegame or replay highlighted by the mouseclick is I guess 12 slots further down.

**Comment by Flamefire** [comment]
New commit should fix the optimized textures. Got to look into the shadow issue. Can you give me a save from that? 
The row issue is probably a switched or off coordinate. Will check this too

**Comment by stefson** [comment]
Broken optimized textures, the shadow issue without them and the row issue in the menu are all fixed for me. Thank you :-)

**Comment by Flamefire** [comment]
Perfect. Thanks for testing and reporting
