### ISSUE TITLE
Progress bars are not coloured if not 100%

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#664]
Is it supposed to look like this? I thought they were either light green, orange or red if less than 100 percent? 

![2017-07-30-095044_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/28751637-4fb74192-750d-11e7-8183-9671ab488e75.png)

**Comment by Spikeone** [comment]
Nope, you are right. May you also check the percent overlays as well? (either shortcut s or v)

**Comment by stefson** [comment]
![2017-07-30-110344_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/28752059-0bf5edc8-7517-11e7-9c60-69521b0e764b.png)

This seems to be ok. 

But there is another overlay, counting the amount of wares present in the queue, which is broken.

**Comment by stefson** [comment]
this is fixed by https://github.com/Flamefire/s25client/commit/6487c631ab4695c20814ff9afcd0e09aea7c6830

thank you! :)
