### ISSUE TITLE
Usage of palettes for libsiedler2 images

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#667]
I'm having trouble defining how the palettes for the images are used for loading and saving. 
The image can be either paletteted or ARGB. The file can also be either and we can pass the same or a different palette for saving as for loading. 
Assume we don't change the file format then we have 8 cases. If we pass the same palette for saving as for loading then nothing changes in any case. This leaves the following 4 cases when a different pallette is passed for saving:
ARGB file, ARGB image: nothing changed, palette ignored 
ARGB file, paletteted image: image is recolored
Paletted file, ARGB image: image stays the same as only palette indices change (loading with 2nd palette will result in the same image) 
Paletted file, paletteted image: nothing changes, palette ignored 

Similar cases apply when an image is drawn to a surface which can be Paletted or ARGB too. 
This does not seem consistent and makes the result highly dependent on the image and file format. 
Shall we disallow passing a pallette to the save and print function and let it always use the images palette? ARGB images can store the palette they were loaded with. Small we ignore the passed palette if the image already has one? 
Shall we enforce that All images are loaded in the same format so at least it is a bit predictable? 

I'm also thinking about removing the Paletted option in images completely so images are always ARGB which simplifies a lot (1 dimension less). You would still be able to print to a Paletted surface so nothing is really lost. 

Thoughts @Flow86 @Spikeone @MarcusSt

**Comment by Spikeone** [comment]
I have actually no idea what you are even writing about but, as my name is mentioned I just want to point out whats important for me:
- I need a way to check if some colors are NOT pal5 compatible (currently I'm using the lstpacker to pack and unpack the file, black pixels are not pal5.bbm)
- I'm still not sure if we even use palettes for winter / wasteland at all (which we should)
- I'm a bit confused why we do save images? Is that unpacking them?

**Comment by Flamefire** [comment]
1. Ok will keep that in mind as I'm currently throwing an error instead of using black pixels. Because there is no other way to know what was intended. 
2. So I guess we want a way to recolor textures? Then maybe disallow setting a new pallette and use an explicit recolor command. This way even images saved as argb can be recolored by making them paletted using the default palette (when loaded) and then again argb by using the new palette. 
3. Yes. But also drawing. We have: file->image->texture with the texture being argb for us. At each -> we can possibly do a conversion using a palette. 

I think giving a palette should result in a conversion in either case or we should make it completely explicit. And giving a palette for Save/load should only be a fallback if the texture does not have one

**Comment by Flow86** [comment]
Hi,
we're using different palettes (i.e for having different "color keys" for transparency, or to allow coloring via opengl i.e with font bitmaps)

**Comment by Flamefire** [comment]
Are we really? The color key for transparency is fixed to `254` and the only use of different palettes applies to the coloring of the player bitmap. So definitions I would use:
- Make bitmaps always 32bpp (ARGB): Simplifies code and reasoning about behaviour
- Allow giving a palette for loading files which is used when the file does not define a palette. If palette is used (either from file or from parameter) then it gets stored in the bitmap, otherwise the bitmap does not have one
- Allow giving a palette for writing files which is used when the file demands a paletted format and the bitmap does not have one
- Creating a bitmap from a buffer resets the bitmap. If the buffer is paletted the palette param is required but not stored
- Writing to a paletted buffer requires a palette param. Also not stored
- Additional function to write player colors to buffer which requires a palette param: It might be different than the buffer palette
- Additional function to create player colors: Requires a buffer (paletted or ARGB), a palette a start index and a count. It will make all pixels with index in [start, start+count) transparent and set the index in the player texture: Same here: Different palette may be used.

The last 2 changes allow PlayerBitmaps to be regular bitmaps as they can have the same shared interface

Thoughts?

**Comment by Flamefire** [comment]
Closed by recent commits to subproject and definitions there with tests.
Any comments are still appreciated
