### ISSUE TITLE
the game crashes just at start

### ISSUE THREAD

**Issue by PabloNHrttr** [Return-To-The-Roots/s25client#668]
Hi, i have a problem with current versions of a game. Game starts normally, you can see all the screens, but no matter what map and mode i choice, the game crashes instantly ater clicking "start game" button. It doesn't even go to loading map screen. I play on my old netbook, windows xp 32 bit. I download new version with new improvements every few months, and the last version i downloaded, and im able to play is s25rttr_20160228 . Lately i downloaded new version s25rttr_20170713, and this problem occurred. I tried older versions, but they all have the same issue. The oldest i'm able to download is s25rttr_20170626, and older are missing. What can be wrong? Is it my computer configuration's fault? Please help me.
Regards PabloNH

**Comment by Spikeone** [comment]
As far as I know we do not support WinXP officially :-/ maybe @Flamefire has more information about supported platforms

**Comment by Flow86** [comment]
windows xp should not be the problem, but you can try to check the logfile. 
on windows xp the rttr directory should be in the documents folder somewhere (i.e in "My Games"). in there should be a "LOGS" directory and logfiles.

**Comment by PabloNHrttr** [comment]
Ok, i found the logs, but i have no idea what should i looking for in it. 
Maybe you can help me? Here is the log of crashed game (v 2017.07.13)
[2017-08-04_20-16-40 (crashed).txt](https://github.com/Return-To-The-Roots/s25client/files/1201315/2017-08-04_20-16-40.crashed.txt)

And here is the log of successfully started game (v 2016.02.28)
[2017-08-04_20-23-18 (successful).txt](https://github.com/Return-To-The-Roots/s25client/files/1201319/2017-08-04_20-23-18.successful.txt)

Thanks in advice for any tips.

**Comment by Flamefire** [comment]
Sorry we need more information. If you look on the download page there are multiple versions for 2016.02.28 and 2016.02.29. They have a unique ID (sequence of letters and numbers)
Can you try which of them works for you and which doesn`t?

**Comment by PabloNHrttr** [comment]
I would, but all of these versions are not possible to download anymore (error 404). I think they all would propably work. I just didn't get a new version since 2016.02.28, and the new versions (from june and july 2017) don't work at all. Problem occured somewhere between 2016.02 and 2017.07, but i'm not able to check when exactly (which version was the first, that doesn't work) because all the versions before 2017.06.26 are gone. :(

**Comment by Flamefire** [comment]
Can you try SDL as the video driver (options)

**Comment by PabloNHrttr** [comment]
I've just checked, and game starts, thank you very much for your help. However i can't turn on fullscreen mode. Game starts in window, and changing mode to fullscreen in options doesn't help. Is there any tip, keyboard shortcut or something to make it full screen?

**Comment by Flamefire** [comment]
SDL does have problems with fullscreen on windows. Just maximize the window there.
