### ISSUE TITLE
Soldiers-flag bug

### ISSUE THREAD

**Issue by luk3ZPL** [Return-To-The-Roots/s25client#673]
1) Which version is affected?
s25rttr_20170713

2) What did you do/shall be done to reproduce the bug?
Check my save (red AI player) [random map generator]
http://www.mediafire.com/file/pftzu6n1cnlrik1/bug.7z

3) What is expected? (Unless it is a crash)
Soldiers walk from HQ to Fort

4) What happens instead?
Soldiers walk from HQ to flag and back to HQ

**Comment by luk3ZPL** [comment]
I forgot to mention that I change AI from Easy to Hard when loading, so this could be the reason.

**Comment by Flamefire** [comment]
The max rank for soldiers was set to privates which confused the AIs upgrading process. ;-)
