### ISSUE TITLE
Languages not working anymore

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#675]
Since one of the last changes languages aren't working anymore. The game is always in english. When you try to change the language, the game freezes. Sometimes your language is shown after you restarted the game but is still in english.

**Comment by Flow86** [comment]
that is caused by https://github.com/Return-To-The-Roots/mygettext/pull/5 - i told that already in there

**Comment by Flow86** [comment]
thats fixed now in the latest nightly
