### ISSUE TITLE
Allowed area can be violated

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#689]
The current setting of the allowed area allows a strange border case:

We have a military building next to disallowed area. So the building gets only minimal additional land. Then the enemy captures the bld and we recapture it. As it is now considered "capturedOnce" we get more area then we had before as the restrictions are not checked for this building anymore.

IMO this has to be changed. Idea: If the building itself is on disallowed area, then we allow all area hold by it.

Opinions? @Spikeone @jhkl

**Comment by Spikeone** [comment]
Well I always liked the idea of not blocking land gain but block military buildings in blocked areas.

That way no strange borders do appear and you may not capture a building which then holds no land. With the debug interface one can still have a visual wich areas are blocked.
Only downside is that blocking specific points then depends on mapdesing and that the user has no visual feedback why he can't build at a spefic point. Also treating blocked points as hostile fortresses and thus gaining border pushback is a way. You'd then capture military buildings with nearly no space around.

**Comment by jhkl** [comment]
I don't really know what 'allowed areas' are, I'm guessing LUA scripting stuff? So, no opinion from my side :)

**Comment by Flamefire** [comment]
It is the area in which a player is allowed to have territory in. Can be set by lua and may be required by missions.

So idea from spike: Simply disallow military buildings in blocked area. Correct?

My idea that a military building in a blocked area does hold all its land leads to another problem: From 1 captured building you could expand indefinitely as all other buildings would be in blocked area too.

**Comment by Spikeone** [comment]
Actually 3, each has it's own use, maybe we could add a parameter to the function

Type 1:
As it is, you can "hard block" nodes
Good for: making sure nobody could possibly reach a point
Example: Block a specific area where a gameobject is placed which is sacred and should belong to nobody

Type2:
Restricted nodes count as hostile military buildings and push borders back
Good for: blocking areas with a better look if a military building is built close to blocked nodes
Example: Oh no, we should not enter that land as it is cursed

Type3:
One can "soft block" nodes, restricted areas then only mean, you can not build any military building
Good for: blocking paths without any ugly visual
Example: We decided to head south, our allys defend the north

But how to deal with blocked areas when you conquer buildings. In general my opinion is, that not lifting restrictions before an enemy reaches some areas is just a mappers fault but should be handled in a good way.

Type1: Burn the building, soldiers go home
Type2: Burn the building, soldiers go home
Type3: Keep the bulding

An other approach is: conquered buildings may lift the surrounding restrictions, in some cases thats good, in some it's not. As nearly always, it depends on mapdesign

**Comment by Flamefire** [comment]
Then I would make it so that you cannot have any territory in restricted area even with conquered buildings. Hence if you conquer one, then it is destroyed instead.
Maybe later we add another area that only disallows military buildings and name it appropriately. I think the use of that is very limited so we might not need it.

Or last idea:military buildings in restricted area hold all their land AND you cannot build military buildings in restricted area. Might be counter intuitive though :/

**Comment by Flamefire** [comment]
Objections to the first idea? So conquering building in restricted area destroys that building as the solution to this?

**Comment by Spikeone** [comment]
Sounds good for me, keeps restrictions as tgey were intended. Maybe fire an event so a map editor could remove restrictions on first contact?

**Comment by Flamefire** [comment]
There is already a onOccupied event that can be used for that. What else would you need?

**Comment by Spikeone** [comment]
An information that the building was in a restricted area. One can not check if a certain point is / was in a restricted area (if its not a simple layout).
