### ISSUE TITLE
Special chars in username don't work

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#691]
Reports in forum state that the game crashes as it cannot open the log file due to an umlaut in the username (https://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1384#last)

Locally (visual studio) does work so it must be something in the crossbuild. @Flow86 @jhkl if any of you has an idea?
We are using the boost filestream for that which is imbued with utf8 prior to everything. The console output shows the path correctly and the logs folder seems also to be created.

**Comment by Flamefire** [comment]
Bug is a know MinGW related issue that does not allow to open an ofstream with a wchar: https://stackoverflow.com/questions/23393870/read-write-file-with-unicode-file-name-with-plain-c-boost

Not sure how to work around that :(

**Comment by Flow86** [comment]
@Flamefire 
Use std::wofstream, std::wifstream and std::wfstream. They accept unicode filename. File name has to be wstring, array of wchar_ts, or it has to have _T() macro, or prefix Lbefore the text. (see https://stackoverflow.com/questions/821873/how-to-open-an-stdfstream-ofstream-or-ifstream-with-a-unicode-filename)

**Comment by Flamefire** [comment]
`wfstream` will cause a bunch of other problems as writing UTF8 strings is no longer possible. Everything will be `wchar_t` which is 2 or 4 bytes depending on the platform. So this won't realy help :(

**Comment by Flamefire** [comment]
I found a solution. 2 Actually, both use another library where both have their drawbacks.

1. [Pathie](https://github.com/Quintus/pathie-cpp) ([Docu](https://quintus.github.io/pathie-cpp/index.html)) It looks like a full replacement of boost::filesystem providing UTF8 aware streams and path handling as well as symlink creation and other file/folder operations. Really cool is the builtin support for getting special directories (temp, HOME, programs folder and many more)   
Drawback: Only works as a dynamic library as the static build has bugs. Also might be overkill as we already do have boost.
2. [Boost.NoWide](https://github.com/artyom-beilis/nowide) ([Docu](http://cppcms.com/files/nowide/html/)) Provides alternatives to almost all file and stream handlers to support UTF8 on windows and falls back to standard functions on others. The filestreams accept UTF8 encoded values and it uses boost itself.
Drawback: No path handling and does not accept `bfs::path` or wide strings (`bfs::path` internal format on Windows is UTF16) so a patch would be required, although it is simple. Also requires a build for windows if we want to use `std::cout` etc with UTF8 strings (yes that works directly!)   
Another cool thing: Provides a class to convert the argc/argv to UTF8 (wrote an own class based on the same concept that would be made superflous)

I'd use Boost.NoWide and add a patch to have it use `bfs::path` to. Won't be hard and might get merged back into upstream.

For implementation I'd add this to libUtil and have all projects depend on that. So even libSiedler2 which does not yet. This makes it possible to use it in all subprojects and have finally a solution to the locale problem :)
