### ISSUE TITLE
[Trade] Add messages

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#699]
Depending on trade design (if caravan style or queue style) we may add messages. The player who gets wares may receive a message "<Playername> sent you <n> <Ware>(s)!" and the player who sent the wares may get a message "Your caravan reached it's destination".

**Comment by Flamefire** [comment]
This is a very good idea. However the message might be a bit large as you can send a lot in one caravan. So how should the message look like? I fear something like `Spikeone sent you 1 boards, 1 woods, 1 stones, 1 coins, 2 privates, 5 woodcutters, 1 donkey, 1 onion`
Also there might be a lot of caravans on the way. So there could be a lot of messages.

Also what do you mean by queue style?

**Comment by Spikeone** [comment]
By queue style I mean a trade design that works like tool ordering, you set a wanted send count, if you have for example 8 boards but want to send 10, you set boards to 10, 8 are sent immediately as you have them, 2 are in queue and are sent when available.

A caravan would then have a definite ware count  while a queue has caravans with non definite ware count.

As for the message: if there is one good (either ware or settler) post that, otherwise "Flamefire sent you 5 wares and 8 settlers"

**Comment by Flamefire** [comment]
Sounds good although it won't be to helpful. But better than nothing. Maybe even better: If it is 1 ware type and or 1 settler type then this can be posted as is. This is the most common use case so that would work.

**Comment by Shawn8901** [comment]
@Flamefire Short question, maybe a bit noobish but, how am i able to send multiple wares/figures within one caravan? If i am looking at the game and at the code it seems for me that i will only be able to send one type per caravan.
Would you prefer a message when the caravan arrives or when the caravan leave the warehouse?

**Comment by Flamefire** [comment]
Currently it is not possible. But a trade ui redesign issue exists which adds the possibility to send more. Maybe we keep it simple and send only 1 item?

**Comment by Shawn8901** [comment]
okay, i found the issue also later.  i would suggest to implement a message for one item type (as today only one can be sent) and if #216 will be implemented, we can change / remove the message.
Other question: 
Is a chat message or a post message preferred?

**Comment by Flamefire** [comment]
I would definitely say arrive as the caravan can get lost. Maybe postbone the adding till all arrived or add everything when the leader arrives?
Because what happens when the caravan arrives partially because the building is destroyed while only the first few arrived? 
Or simply keep it and add a message like "a caravan with n wood arrived" and ignore that unlikely case
