### ISSUE TITLE
[addon] Erweiterung: 3 Weggrößen

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#70]
Erste: 1 Träger
Zweite: 2Träger
Dritte:1 Träger und 1 Esel (Esel trägt 2)

Tamas Fonyodi (almoskapitany) wrote on 2010-04-25:  #1
I think, my Fast-Moving-Traffic idea is connecting to this topic. We could merge these two into one nice addon.
https://bugs.launchpad.net/s25rttr/+bug/569604

https://bugs.launchpad.net/s25rttr/+bug/370078

**Comment by Spikeone** [comment]
Fast Moving Traffic

It is an addon idea to improve the gamespeed at least 2-3 times faster.
In a nutshell, carriers don't work effectively as they are waiting for the stuffs between the two flags. The stuffs' way would be more times faster, if the carriers/donkeys waited AT THE FLAGS. In this case, they spare the half way on each road and can carry one item like the olympic torch: from hand to hand.

If three roads ran into a flag, then two carriers/donkeys would wait at the flag.
If four roads ran into a flag, then three carriers/donkeys would wait at the flag.
And if five...

Probably it doesn't have disadvantage and by this time-sparing, this could incredibly pump up the speed.
I'm attaching a picture about a more efficient usage

Tamas Fonyodi (almoskapitany) wrote on 2010-04-25:	#1
fasttraffic.jpg Edit (516.8 KiB, image/jpeg)


Tamas Fonyodi (almoskapitany) wrote on 2010-04-25:	#2
I think, this introduction was not perfect, and I have to write some more about it. I also made a counting mistake. It's after midnight....

So let's take the facts:
To make this model working properly, each road needs 2 carriers at it's ends. So one road demands 2 carriers for the perfect traffic management.

And now we have a matter of discussion.... Donkeys!
Shall we leave them in the old model, as they are needed only in heavy traffic, or convert them too in this form? In this case, it is possible to see 4 (!) carrying units on a road at the same time. I think 3 is enough and perfect...

All right guys, I know and I see, it's a little tricky, but imagine the situation this model working... just incredible traffic speed in case of one item. We would have our coins in the military building almost the same time with the soldier!

Spike (fvv1) wrote on 2010-04-25:	#3
Ehm, have you thought about the problem that this is a one way system? if a good comes from the other side, it needs much more time. Paved roads are already an idea so that the speed of the people is faster

jh (janhenrikk) wrote on 2010-04-25:	#4
Spike: One carrier at each flag. There is no other side.

Tamas Fonyodi (almoskapitany) wrote on 2010-04-25:	#5
Spike: Yes, exactly. I wrote the second post because of this problem.
Every road would have 2 carriers at it's flags (!) - and leave donkey in center. So at a multilevel junction-flag there could wait 5-6 carriers at the same time connecting to their own roads.

If there was constant traffic on a road that never stops, we wouldn't see speed increasing (just what comes from the +1 carrier). But on not busy roads, and in the case of taking one certain stuff to it's destination point, that could be solved by the speed of a walking soldier. Stuff goes directly, without relevant stopping.

Anyway, this addon would be the best for death-matches, or faster gaming experiences.
I would say this method is the improved version of the addon suggested here:
https://bugs.launchpad.net/s25rttr/+bug/370078
Probably these two could be merged into one.

Spike (fvv1) wrote on 2010-04-25:	#6
Oh well, I hadn't really read the 2nd post, dont know why :s

well, the only time, when my roads have to heavy traffic is when I want all goods from one store house in an other store house ;)
because thats the thing which is tricky in s2, you need many roads that your goods are delivered fast but not to many because you need to build buildings^^

Thats a part of s2 in my opionion, but as addon its okay and maybere interesting ;)

https://bugs.launchpad.net/s25rttr/+bug/569604

**Comment by Flamefire** [comment]
I think this changes to much of the S2 experience. Wouldn't do that (to many changes...)
