### ISSUE TITLE
Ingame window open delay

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#703]
When opening a window in game (e.g. map, messages etc.) the first time the window is opened the game lags for a moment. This happens with all windows when they are shown first. After that everything works fine but it feels extremly strange and annoying.

**Comment by Flamefire** [comment]
I cannot reproduce this with the current nightly. The only reason for this behaviour would be that the game has to load the textures into the GPU which it only does on the first time that texture is used. However on my laptop (integratedGPU) it does not lag at all. Maybe a driver problem?

**Comment by Spikeone** [comment]
Well, I asked the other player if he experienced the problem as well and he did. I may recheck this, on an other system as well (maybe with lower specs), test sdl / winapi and optimized textures as well.

**Comment by Flamefire** [comment]
Ok then I'll wait for your tests. Would be good to know where things go wrong exactly.

**Comment by Spikeone** [comment]
Strange, can't reproduce that problem either. As we both had the same issue I assumed it was a general issue.
