### ISSUE TITLE
Allow different compilation dates in multiplayer

### ISSUE THREAD

**Issue by Peuc** [Return-To-The-Roots/s25client#705]
Currently, when a client tries to connect to a server, the game checks the version to make sure both players use the same code.
The version is currently made of compilation date (YearMonthDay) followed by the beginning commit id used for compilation.

When a self-compiled client wants to play with players using nightly, it must cheat the system time prior to compiling in order to make sure the date will be the same. This is annoying and pointless, since the sole commit id is enough to achieve the same result.

What about removing the date of the version check?

**Comment by Flow86** [comment]
> What about removing the date of the version check?

this could be done for nightly-builds (with a date instead of a version)

**Comment by Peuc** [comment]
I'm not sure I understand your answer Flow86. Just to be sure:

Currently, the version attributed at build time looks like "v20170309-bf9fcc601ed2de847ea26aecec6e15cd92f8357e".
The first part is the day the compilation has been done.
The second part is the id of the git commit the code comes from.

This format is great because it gives humans a good idea of how old the build is and refer to a specific commit, so all code currently run is identified.

When a client tries to connect to a server, the server compares its own version string with the one sent by the client, to make sure the code is the same (GameServer.cpp:1091). This works great when all players use binaries coming from a single provider (ie nightly builds as provided on official website).

However, when players compile their own version, the build date part becomes a problem: the exact same code is considered as incompatible with itself when it's compiled at different point in time.
Typically, if a Linux user (who uses its own builds) wants to play with Windows users (who use nightly builds), he must compile the same version (great), with its system clock faked at the same date of the nightly build (bad).

A solution could be to keep the same version string pattern, but to compare only the second part (commit id) when compatibility is checked.

**Comment by Flow86** [comment]
> A solution could be to keep the same version string pattern, but to compare only the second part (commit id) when compatibility is checked.
I totally agree to that for nightly builds, but we should handle an official release (i.e 0.8.3) separately. 

There, the version must be checked fully, so one can't use a custom build to play with players with an official version.

**Comment by Peuc** [comment]
> There, the version must be checked fully, so one can't use a custom build to play with players with an official version.

Is the any reason for this? I mean, is an official release something more than a "seal of approval" on a commit id, saying it's tested and stable enough for everyone?

**Comment by Flamefire** [comment]
I have to agree. The only thing that has to be checked is the commit ID.
Why not allow a custom build? Due to the risk of cheating? Well it is easy enough to get around any check by simply adjusting the time or even easier using the force file mechanism the build server uses...
So I'd check commits only. If someone want to mess with it then that's not our problem

**Comment by Spikeone** [comment]
Isn't that feature used for preventing asyncs? At least the replay may contain build time so nobody ever searches an async (or other bugs) in a custom build where you can not check what has been changed.

**Comment by Flamefire** [comment]
Yes it is. But the commit id refers to a known set of source files (it is in fact a checksum, sha if I remember correctly) so with the same checksum it must be the same source and hence no async possible unless someone modified the source without committing but then its their problem not ours.

**Comment by Spikeone** [comment]
So one should not commit changes for testing (e.g. Add debug output)? I'm not doing this but thats just my idea.

**Comment by Flamefire** [comment]
Erm, no? How would you distinguish a commit that changes behaviour from such a commit? We could of course define a completely separate `ProtocolVersion` that we then have to manually change each time we do game changing fixes. This would allow players with older versions to play with others that use a version where only UI issues have been fixed. But maintaining that is gonna be a hassle. We already have a savegame version, replay version, and gamedata version. If we gonna do that, we could at least make the replay version depend on the protocol and savegame version and the savegame version depends on the gamedata version which would make it a bit more automatic.

BTW: If you still want to use a debug version you can force the used version by using a .force file or simply don't commit.

**Comment by Flamefire** [comment]
Fixed with ba35e4b
