### ISSUE TITLE
cannot enter fullscreen mode

### ISSUE THREAD

**Issue by Trolldemorted** [Return-To-The-Roots/s25client#709]
RttR's CONFIG.INI says:

```
[video]
fullscreen_width=1920
fullscreen_height=1080
windowed_width=1920
windowed_height=1017
fullscreen=1
vsync=60
vbo=0
shared_textures=1
```

but the game starts windowed.

The ingame settings menu is able to toggle the value in the config, but it will never go fullscreen.

W10 Pro N 64bit

**Comment by Flamefire** [comment]
Fullscreen mode is currently not working in windows. :(

**Comment by Trolldemorted** [comment]
It works on 2 other windows machines running w7. I was the only one in the mp match that could not go fullscreen.

**Comment by Spikeone** [comment]
It is working, a bit at least. Sometimes you need to set windowed, restart, set full screen, restart an then the option is persistent. Sadly I can't figure out why my game sometimes starts in maximized window mode but I set it 800x600.

**Comment by Flamefire** [comment]
Ah. It seems WinAPI has fullscreen but SDL doesn't. So it depends on the selected driver. Will work on that so it works on both.

**Comment by Trolldemorted** [comment]
If spike is right and the behaviour is racy this shouldn't be (only) about the driver, unless the driver frequently changes (e.g. because he runs rttr both on an integrated chip and a dedicaded graphic card on the same device), doesn't it?

**Comment by Flamefire** [comment]
I don't think the behaviour is as described by Spike. The "driver" I relate to is the selected videodriver in the game, not the hardware driver. That behaviour can only occur, if this is changed too as only one of them supports fullscreen on windows.

**Comment by Spikeone** [comment]
Yep, I'm sorry, don't know what strange bug I then often experience, but you are totally right, fullscreen is currently only working with WinAPI. Sorry for any additional work I may caused :-/
