### ISSUE TITLE
[addon] Erweiterung: Spähturm kann Erkunder töten

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#71]
Wie schon der Titel sagt, sollten Spähtürme Erkunder töten können um zu verhindern, dass sie das eigene Land auch ohne den Turm erkunden können, was einem Zeit verschaffen kann. Was schwer werden könnte, ist das visuelle darstellen, sodass es jeder erkennt.

https://bugs.launchpad.net/s25rttr/+bug/370079

**Comment by Spikeone** [comment]
In my opinion useless!

**Comment by MarcusSt** [comment]
As you are the original reporter of this, I'll just close it silently... ;-)

**Comment by Spikeone** [comment]
Parasit had this idea...
