### ISSUE TITLE
Wrong resource indicators

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#712]
RttR originally fixed wrong resources (there is no water on mountains, no iron in ground) but that seems not to work anymore.

![unbenannt](https://user-images.githubusercontent.com/1276342/31838367-c62c132e-b5dc-11e7-9610-cee873cf3676.png)

**Comment by Flamefire** [comment]
On which map does this happen?

**Comment by Spikeone** [comment]
It's a random, maybe thats the problem at all.
If so, I thought RttR would correct wrong resources or am I wrong?

**Comment by Flamefire** [comment]
Well the random generator should only place coal etc on mountain. That piece there is on a corner, so still mountain -> OK
The water should not be placed there...

**Comment by Spikeone** [comment]
Well in terms of terrain mountain meadow <-> mountain equals greenland <-> desert. While the second has no water on the transition the first should have no resources at the transition nodes. Thats how it's supposed to be (s2 like). Also an editor can't create the same result as no map editor supports that (false) behavior.
