### ISSUE TITLE
Exloration expeditions don't work anymore

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#713]
Exploration expeditions just suck in scouts but never depart.

**Comment by Flamefire** [comment]
The tests don't show any failure. Do you have a save/replay?

**Comment by Spikeone** [comment]
[Uploading 2017-10-20_20-20-36.zip…]()

~ GF 32000
```
Thats quite funny, the scouts get loaded, and when the ship should depart the following message shows up:
noShip::StartDrivingToHarborPlace: Schiff hat keinen Weg gefunden!
player 0 state 6 pos 115,83 goal coastal 8,112 goal-id 27 goalpos 7,112
```
Then the ship gets unloaded and my scouts were missing. Although they are still honored in the inventory screen.

**Comment by Flamefire** [comment]
Latest build (non-official) does not have this behaviour. The ship at ~32000 just departs as it should. Testing older versions now (Replay goes async)
Also the map has a lot of invalid trees etc. where is it from?

**Comment by Spikeone** [comment]
Was generated by the random map generator - rttr doesn't understand some (special) trees

**Comment by Flamefire** [comment]
Ah, nope its not RTTR itself. The map generator could produce invalid trees with a chance of 1:4 due to a bug I fixed very recently.
Found the scouts disappearing bug. Now the missing path bug...

**Comment by Spikeone** [comment]
Ah okay, but I think there are still some unknown trees which were used by s2mappy but not by RttR or any other editor. Going to have a look into that when I have a XP-VM

**Comment by Flamefire** [comment]
Do you know which version you used to generate the map? Was it the ingame map generator? Because the ship issue is caused by harbors spots beeing next to each other which should not happen.

**Comment by Spikeone** [comment]
But yes, I used the ingame random map generator as I wanted to give it a try
