### ISSUE TITLE
Exploration bug

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#714]
Looks like it could happen that you still can see some buildings that are in progress, see:
https://youtu.be/e_z3CF4LCZM?t=18m38s

**Comment by Flamefire** [comment]
Don't know where to look at. What/Where is something wrong?
Do you have a savegame/replay?

**Comment by Spikeone** [comment]
Oh sorry, somehow I missed this comment. Have a look at the red players country, my scout uncovers some woodcutters, one of them is still under construction, that one stays visible.
When I'm home I will search for the replay and check if this error is even visible in a replay.

**Comment by Spikeone** [comment]
~ GF 33700, 30:66
[2017-10-17_20-52-23.zip](https://github.com/Return-To-The-Roots/s25client/files/1415683/2017-10-17_20-52-23.zip)

**Comment by Flamefire** [comment]
Ah. Nope it doesn't really stay visible. See how the scout goes there again and the progress of the building site jumps.
So the bug was simply, that it was drawn in full color instead of FoW color.

**Comment by Spikeone** [comment]
Right, dont know why I didnt realize it :-s sorry, so the title is missleading
