### ISSUE TITLE
Some windows are opened to far from click position

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#720]
Some windows, for example if you click on the HQ or a building site, are opened quite far from the current click. This results in more mouse movement than it should, also it was closer in the original to the click and I don't think RttR did it that wrong all the time as I only stumbled across this after player with the latest version.

Edit: Observation window as well

**Comment by Flamefire** [comment]
They are opened 10px from the mouse which is less than in the original. Just double checked this.
The observation window seemed to be wrong, because the mouse was moved to the position where the action window was opened from, this will be fixed.

**Comment by Spikeone** [comment]
yes, 10px in x-direction but what about y? Working great at 800x600, working not so great at 2560x1440

800x600 (rttr)
![image](https://user-images.githubusercontent.com/1276342/31897481-cfd94e00-b816-11e7-9090-fe53fd76a970.png)

2560x1440 (rttr)
![image](https://user-images.githubusercontent.com/1276342/31897492-d74bb286-b816-11e7-8af2-cb47cade77ca.png)

Sorry, maybe my description wasn't as clear as I first thought, guess those screenshots show what I meant :)

**Comment by Spikeone** [comment]
I'm not certain that those windows should be centered in y-direction relative to the mouse as the 800x600 screenshot looks correct but is also not centered, rather every window is moved up by unknown pixels, I'm going to check this in the original (at least with 3 resolutions) if there is a fixed y-pixel count, 1 sec

**Comment by Flamefire** [comment]
"Should" is how we define it ;) And centered is a good way for those so I'd keep that.
The behaviour you describe seems to be related to a bug in the current nightly. It should be fixed with the new update coming soon.

**Comment by Spikeone** [comment]
Well, regarding that the activity window actually moves the mouse, I can understand that the window opens relative to the real cursor position, as then the cursor gets move the same amount of pixels every time while click position centered results in differences.
