### ISSUE TITLE
Exploration looking strange

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#727]
![image](https://user-images.githubusercontent.com/1276342/32134106-0453afb8-bbe6-11e7-8c9a-db3a4393037e.png)

It can happen that you see a certan spot you may not see at all as you can see in the image. The smith and guardhouse are visible - although they shut not. Also on the lower right the buildings seem to be more visible than the ground somehow.

**Comment by Flamefire** [comment]
Do you have a save/replay?

**Comment by MarkL1961** [comment]
I agree, visibility should only look that clear when your soldier or scout is close by and it should fade once they have moved on.  From memory if you were to get close at a later stage in the game you would often find that where you had been seeing a faded image of what was there you might find it is no longer there and sometimes changed to something else.

**Comment by Spikeone** [comment]
[2017-10-21_12-56-10.zip](https://github.com/Return-To-The-Roots/s25client/files/1435642/2017-10-21_12-56-10.zip)

**Comment by Spikeone** [comment]
[2017-10-28_11-26-52.zip](https://github.com/Return-To-The-Roots/s25client/files/1435649/2017-10-28_11-26-52.zip)

**Comment by Flamefire** [comment]
@MarkL1961 This already is the case for fog of war setting. Here the castle discovers the territory but it seems it does to much.

**Comment by Flamefire** [comment]
@Spikeone You have been better at bug reporting before ;) Which GF is it? Your replay has ~260k GFs...

**Comment by Spikeone** [comment]
@Flamefire you are right, was playing and wanted to go to bed so I just reported the bug before I'd forget it :D Will have a look into when I'm home, really need to include all information, sorry for any inconvenience

**Comment by Flamefire** [comment]
Found it by now. GF is shortly after 231570 when the castle gets conquered. Gotta check further what happens to the exploration. I guess you had FoW disabled?
The buildings on the lower right seem to be ok. I think they just seem to be lighter than usual because the floor is lighter due to its elevation.

**Comment by Spikeone** [comment]
What do you mean by "FoW disabled"? I played with fog of war and the screenshot was taken during the game. I also had this problem at an other point where I could see a barracks which I should not in my opinion. Maybe the problem has a connection to military buildings which are on the edge of visibility?

**Comment by Flamefire** [comment]
I know it may sound strange but the behaviour is correct. The castle discovers the buildings like it should. The smith and guardhouse are visible just the same as the woodcutter. They are JUST visible. The extra pieces that look wrong are cause by a soldier that attacked the bld. He discovered a bit more which is now FoW. However FoW is just a bit darker then usual and at the very edge it might not be obvious that it is darker.

**Comment by Spikeone** [comment]
Ah I see, thats why it happens near military buildings. Can we remove the fading and make it like the original?

![image](https://user-images.githubusercontent.com/1276342/32336372-72116312-bfef-11e7-9b5d-361e9b058078.png)

Not sure if it works but... it really looks odd and can't remember seeing such cases before and now 2x in one game. But I'm not sure at all

**Comment by Flamefire** [comment]
I actually like the fading much better. Don't want to invest time removing it ;)

It's probably because the distance is as far as it can go for attacking. This rarely happens...

However: Not a bug. Closed

**Comment by Spikeone** [comment]
Well, always disliked the rttr way, I may need to take a look into it as such situations as seen in the screenshot are worse :D
But agreed, not a bug, its a bug that my generals always lose which caused the view in the first place :D
