### ISSUE TITLE
[LUA] add function string player:getClientLanguage() 

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#729]
A function that returns the players language would be great so we could localize texts. If the return value is a string I could imagine something like this: 
["deDE"] ["msg1"] = "Hallo Welt"
["enGB"] ["msg1"] = "Hello World" 

So referencing messages with [p.getClientLanguage()]["msg1"] would work fine. Maybe there are better ways but we need to add a way to localize messages.

**Comment by Flow86** [comment]
perhaps directly integrate localization into the lua stuff - so perhaps have some kind of "fixed" table for localization strings and you have some function like our gettext-ones later

**Comment by Spikeone** [comment]
Well, just know how it's done in WoW Addons (or was done): Register a translation and then depending on the client language the correct one was read. Well added an archive with an example script and the translations function, if the function is added within RttR that'd be great for sure.

[Translation.zip](https://github.com/Return-To-The-Roots/s25client/files/1440836/Translation.zip)

You may change the wish if the way this is achieved changes (e.g. one doesn't need the getClientLanguage() anymore) :)

**Comment by Flamefire** [comment]
Agreed and is done.

**Comment by Flamefire** [comment]
I chose the following approach: Define a table `rttrLocales` with all translations. This is read on script loading. It first gets the `en_GB` locale and then overwrites the entries with the users locale as currently set. This way non-translated entries default to english. If a region (e.g. `GB`) does not exist, the region is removed. Translations are then done with `_('Key')`.
See https://github.com/Return-To-The-Roots/s25client/pull/726/commits/9baef759fc1a40ace5f203b74bf76b50d515472b#diff-082a8bc1fe192822394dfee448ab9302R130 as an example

Ok, this way?

**Comment by Spikeone** [comment]
Sounds good for me I guess - hopefully there will be builds soon! :)

**Comment by Flamefire** [comment]
Yeah waiting for @Flow86 to update the build sever :)

Before this gets merged: What do you think is better: Having a global table rttrLocales or have a function call?

Example:

	rttrLocales = {
		en_GB = { Foo = 'Eng', Bar = 'Eng2' },
		pt = { Foo = 'Port', Bar = 'Port2' },
		pt_BR = { Foo = 'PortBR', Bar = 'PortBR2' }
		}
	
	rttr:InitLocale({
		en_GB = { Foo = 'Eng', Bar = 'Eng2' },
		pt = { Foo = 'Port', Bar = 'Port2' },
		pt_BR = { Foo = 'PortBR', Bar = 'PortBR2' }
		})

I've got the feeling that the 2nd is better as the global is not required. Also note that I made all in one table instead of an `AddLocale("en_GB", ...)` function which is easier to implement and IMO faster and compacter to code.
