### ISSUE TITLE
Activity windows is missing buttons

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#730]
The activity window is missing a button and using a wrong icon.
Original:
![aw_or](https://user-images.githubusercontent.com/1276342/32404310-a0d70094-c14d-11e7-9946-f018f1c8fed3.png)

RttR:
![aw_rttr](https://user-images.githubusercontent.com/1276342/32404311-a4528004-c14d-11e7-8288-f0964f3f6f32.png)

**Comment by Flamefire** [comment]
Fixed with e021671fc31443b24641ccfdf290c2b4f900c4cb
