### ISSUE TITLE
Window outline

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#731]
In the original windows had an black outline, in RttR they do not have such outline.

**Comment by Flamefire** [comment]
Which looks better? Just compared them in #730 and IMO we don't need an extra outline around the borders

**Comment by Spikeone** [comment]
I actually like the outlining as it makes windows a bit darker - the original was darker than rttr is at the moment and I still like the old style - so I'd vote for the outline - maybe someone else has an opinion or I may add a comparison image with some windows open in the original and in rttr?
