### ISSUE TITLE
Some (long) map names are shown wrongly

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#732]
I just saw two maps which had a strange name.
Battle in the Middle and Countryside by a River

![image](https://user-images.githubusercontent.com/1276342/32404332-03c5b8f8-c14e-11e7-9678-dca3c3460581.png)

**Comment by Flow86** [comment]
I think thats caused by wrongly reading the title in libsiedler2 (I think there's missing a terminating '\0' which could result in the '?')

**Comment by Flamefire** [comment]
Ouch. The file is in a wrong format. According to http://settlers2.net/documentation/world-map-file-format-wldswd/ We have either:

- 19B title, NULL, 2B width, 2B height (WLD-Files)
- 23B title, NULL (SWD-Files)

Those maps have 20B title, 2B width, 2B height. Gotta implement a fuzzy detection of this mess -.-
