### ISSUE TITLE
GCC 6: Many warnings in kaguya

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#734]
Hi,

because of -Wall (mostly: -Wsuggest-override) there are extemely much errors in kaguya library. we should simply ignore warning in the kaguya library on build - its not our library, we dont want to see any warnings.

**Comment by Flamefire** [comment]
It is include as `INCLUDE_DIRECTORIES(SYSTEM` so no warnings should show.

**Comment by stefson** [comment]
Buy the way, has anyone made a testbuild for gcc-7 to see if it breaks something?

**Comment by stefson** [comment]
Is this still a thing?

**Comment by Flamefire** [comment]
Closing due to missing feedback. Shouldn't be an issue unless the compiler ignores `-isystem`
