### ISSUE TITLE
BUG: make install doesnt create apple bundle while using cross compiler

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#735]

**Comment by Flamefire** [comment]
I don't know anything about bundles for OSX. I feel that this may cause problems because we have the s25client and s25edit. But there is a property and a global CMake variable for this that seems appropriate: https://cmake.org/cmake/help/v3.0/prop_tgt/MACOSX_BUNDLE.html#prop_tgt:MACOSX_BUNDLE

**Comment by Flow86** [comment]
thats the better way to do handle that, even if its still has to be extended with additional frameworks etc for deployment, but it would be cool if cmake could create an app-bundle on macos target by default (like the portable install on windows)

in your changed version it installs into "/usr/local" - so the current prepareRelease.sh does not work anymore.

**Comment by Flamefire** [comment]
Give it a try :)

Yes and No: We are now using the "correct" CMake way of installing this stuff. I'm sure there is no `usr/local` anywhere in our codebase. The way to create the release would be setting the install path to a know directory and bundle it up from there after `make install`. I think the build server set the `CMAKE_INSTALL_PREFIX` to empty and used `DESTDIR` instead. Or maybe the `CMAKE_INSTALL_PREFIX` is missing and defaults to `/usr/local`. Then it is an error in the jenkins script.

**Comment by Flamefire** [comment]
Fixed by #970
