### ISSUE TITLE
prepareRelease.sh uses hardcoded "strip"

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#736]
we should use CMAKE_STRIP variable for that

```
./prepareRelease.sh: line 132: i686-apple-darwin10-strip: command not found
```

**Comment by Flow86** [comment]
also uses hardcoded miniupnpc dylib path

**Comment by Flamefire** [comment]
It is meant to by used by the build server so we can use hard coded values. I don't think this is of  much use for others.

**Comment by Flow86** [comment]
yea but it could be soft coded via cmake (see the PR #737 )
