### ISSUE TITLE
cannot find object while loading game due to broken path

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#738]
I just compiled a fresh git checkout and run into this while starting a new games from scratch: 
Datei oder Ordner nicht gefunden: /usr/share/s25rttr/RTTR/LSTS/GAMEAddon_0x00000006/

this data cannot be found because it is not present, instead it is present in LSTS/GAME/Addon_0x00000006/ (mind the slash)

**Comment by Flamefire** [comment]
Jep thanks. Errors like this are expected as I'm not 100% sure I found all such occurences. Changed the pathing system recently.

**Comment by stefson** [comment]
fixed, thanks :)
