### ISSUE TITLE
[wish] Variable Spielgeschwindigkeit

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#74]
Es gibt nicht mehr nur die vorgegebenen Geschwindigkeiten für Siedler 2 sonder auch individuell einstellbare Geschwindigkeiten per Regler.

https://bugs.launchpad.net/s25rttr/+bug/370453

**Comment by Spikeone** [comment]
In my opinion useless!

**Comment by MarcusSt** [comment]
The selected speeds should be enough. I see no reason for fine grained adjusting of the speed the game runs at.
