### ISSUE TITLE
Segfault on showing military aid

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#740]
I just tested a randoom map (I think Pangea?) with default settings, turns out the game segfaults straight away if using the space bar, which is used to display the 'little yellow markers' for flags and houses.

**Comment by Flamefire** [comment]
Seems like the new_map.LST folder was not loaded. Can you post the log of this crash?

**Comment by Flamefire** [comment]
Can't reproduce this. It really looks like `RTTR/LSTS/GAME/map_new.LST` is not loaded. AND you activated the military aid addon which is non-default.

**Comment by stefson** [comment]
I tried to start a new game with S2 standards, which disables the military aids, and it works just fine without any issues regarding the space bar. 

About the `map_new.LST` file, there is one folder called `RTTR/LSTS/GAME/map_new.LST/` , but no file with this name. Do you meant this folder or is there an issue regarding the filename? 

these are the absolute paths of the files which are to be found in this folder

```~ $ equery f s25rttr | grep map_new.LST
/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST
/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/20000.rle.nx0.ny0.bmp
/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/3150.player.nx140.ny80.bmp
/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/3151.player.nx140.ny80.bmp
/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/3152.player.nx140.ny80.bmp
/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/3153.player.nx140.ny80.bmp```

**Comment by Flamefire** [comment]
Yes the folder. Please enable military aid, press space and attach the log if that crashed

**Comment by stefson** [comment]
here you go, full log from console including output from gdb/backtrace

[log.zip](https://github.com/Return-To-The-Roots/s25client/files/1459000/full.log.zip)

**Comment by Flamefire** [comment]
I may have found it. The problem lies a bit deeper and is due to locales. The "20000.rle.nx0.ny0.bmp" is converted to an int via a standard stream which is supposed to return `20000`. However I think that it may not read it like this can return something else.
Try to put a `Log.write("Nr=%1%\n") %nr;` in line 1154 of Loader.cpp (after `nr=-1`) and rerun the same thing to confirm this. The output around `Lade "/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/20000.rle.nx0.ny0.bmp"` is the interesting part

**Comment by stefson** [comment]
provide a with a diff/patch, please! :-)

**Comment by Flamefire** [comment]
See above

**Comment by stefson** [comment]
my interpretation of your advice is this: 

```diff --git a/src/Loader.cpp b/src/Loader.cpp
index 6041ee9..67bb69e 100644
--- a/src/Loader.cpp
+++ b/src/Loader.cpp
@@ -1151,6 +1151,7 @@ bool Loader::LoadFile(const std::string& filePath, const libsiedler2::ArchivItem
         nrs << filename;
         if(!(nrs >> nr))
             nr = -1;
+            Log.write("Nr=%1%\n") %nr;
 
         // Dateiname zerlegen
         std::vector<std::string> wf = ExplodeString(*itFile, '.');```

**Comment by stefson** [comment]
which leads to this beauty 

```
[ 39%] Building CXX object src/CMakeFiles/s25Main.dir/Messenger.cpp.o [...]
/var/tmp/portage/games-strategy/s25rttr-9999-r2/work/s25rttr-9999/src/Loader.cpp: In member function ‘bool Loader::LoadFile(const string&, const libsiedler2::ArchivItem_Palette*, libsiedler2::Archiv&)’:
/var/tmp/portage/games-strategy/s25rttr-9999-r2/work/s25rttr-9999/src/Loader.cpp:1154:16: error: expected unqualified-id before ‘.’ token
             Log.write("Nr=%1%\n") %nr;

**Comment by stefson** [comment]
Ah, I just noticed that you edited your comment from yesterday with an attachement of a diff. Double checked your version, with the same compile error.

**Comment by Flamefire** [comment]
Sorry typo: "LOG" not Log (all caps)

**Comment by stefson** [comment]
Okay, now it passes. And here is the log: [full log.zip](https://github.com/Return-To-The-Roots/s25client/files/1460587/full.log.zip)

the most interesting part: 

```
Lade Ordner /usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST
Nr=-1
Lade "/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/20000.rle.nx0.ny0.bmp": fertig in 0ms
Nr=-1
Lade "/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/3150.player.nx140.ny80.bmp": fertig in 1ms
Nr=-1
Lade "/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/3151.player.nx140.ny80.bmp": fertig in 1ms
Nr=-1
Lade "/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/3152.player.nx140.ny80.bmp": fertig in 1ms
Nr=-1
Lade "/usr/share/s25rttr/RTTR/LSTS/GAME/map_new.LST/3153.player.nx140.ny80.bmp": fertig in 0ms
fertig in 22ms
Lade LST,BOB,IDX,BMP,TXT,GER,ENG,INI Dateien aus "/home/tim/.s25rttr/LSTS/GAME"
fertig in 0ms

**Comment by Flamefire** [comment]
Alright so my assumption is correct. Gonna take a couple of days to fix this properly as this affects more than this.

**Comment by stefson** [comment]
Okay, please ping me if you have a pull request ready for this to test.

**Comment by Flamefire** [comment]
Updated #741 to include the fix. Waiting for the build server to test this...
