### ISSUE TITLE
cursor missmatches if the plotting of a new path is cancelled

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#747]
The behavior used to be that the mouse cursor symbol from screenshot 2 should be the one used to cancel the plotting, while this one shows up right after plotting got cancelled and where it should be the normal Hand cursor. As shown in screenshot 3

![abbrechen](https://user-images.githubusercontent.com/14232936/32688390-057092ea-c6d0-11e7-88b7-85a6188abd3d.png)
![abgebrochen](https://user-images.githubusercontent.com/14232936/32688391-05a73fde-c6d0-11e7-9ef8-80ba9202e6a8.png)
![normal](https://user-images.githubusercontent.com/14232936/32688392-05dbab5c-c6d0-11e7-839a-9e55c09786e4.png)

**Comment by Flamefire** [comment]
Sorry can't follow you. You start building a path till the cancel window pops up. You press cancel and the path gets removed. You expect, that you are still in path-building mode from the flag but instead you have to click the flag again to start building a path. Is this correct?
If you want, you could explain in German if this is easier.

**Comment by stefson** [comment]
Well, I certainly don't mind to write in english, but we can try in German. 

Die Mauszeiger sind vertauscht, du siehst im ersten Screenshot den Mauzeiger vom plotten als eine Art von Torte, oder wie auch immer du es nennen möchtest, in golden auf dem grünen Hintergrund. Links vom Aktionsfenster. Dieser sollte auch so auftauchen wenn du mit der Maus über das über große rote X hoverst und drückst, nur in silber bzw. grau. So war es jedenfalls seit die letzten, ähm, 15? Jahre :) in Siedler II 

Auf dem zweiten Bild siehst du, wie der Mauszeiger direkt danach aussieht, wenn du den Dialog bereits abgebrochen hast. Hier bist du eigentlich nicht mehr beim plotten des Weges, und es sollte ein ganz normaler 'Zeigefinger' zu sehen sein als Mauscursor, so wie im letzten Bild zu sehen. Du hast aber dennoch diesen komischen Torten-Mauszeiger, das sollte so nicht sein.

**Comment by Flamefire** [comment]
English is better in general for other users but sometimes it is easier to explain in German.

Ok, found. Was a C&P bug.
