### ISSUE TITLE
random map generator does use wrong folder for saving

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#749]
This is a bit speculativ, but I think the map generator uses a wrong path as in #739 to store the generated map, because a map called MAPSRandom.swd is created in `~/.s25rttr/` but not in `~/.s25rttr/MAPS/`

Secondly, I cannot access the locally saved maps in `~/.s25rttr/MAPS/`, the tab with 'Eigene' in the menu stays empty. However, there are plenty of maps in that folder, they can be loaded via the 'Gespielte' tab.

**Comment by Spikeone** [comment]
"Own" loads all maps in the "[...]\WORLDS" folder which  may not exist.
"Played" loads all maps in "[...]\Saved Games\Return To The Roots\MAPS" (maybe thats an other path for linux / mac)

**Comment by stefson** [comment]
The folder structure is completly different for linux. It used to work, now it doesn't anymore, so there must be a regression somewhere. Haven't touched the `~/.25rttr` folder for ages!

**Comment by Flamefire** [comment]
The map path is a bug, which will be fixed with my next PR (yes same type of bug)

Own=WORLDS     
Played=MAPS

It used to be MAPS for both, but this is wrong and was fixed.
