### ISSUE TITLE
savegames are duplicated during saving 

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#766]
I just ran into this when I attached the map in #765 , there is one save in the correct path of `~/.s25rttr/SAVE/` and another one in `~/.s25rttr/MAPS/` - both files are identical, md5sum matches.

here is one save game from the random map of #765 
[Random (Automatisches Speichern).sav.zip](https://github.com/Return-To-The-Roots/s25client/files/1504056/Random.Automatisches.Speichern.sav.zip)

I run the game on linux-x86_64 and am at git head 89edd04d7b3d8fbdb8a86b79415489d8c0b713a6

**Comment by stefson** [comment]
Update: the duplication does not happen when saving the game for the first time, but upon reloading a previous savegame. If saving this new session, with the same filename, the game overwrites the file present in the correct path `~/.s25rttr/SAVE/ ` that is, and copies this one upon reloading into `~/.s25rttr/MAPS/`. This happens between selecting the savegame in the file picker window and the window where the players, speed and aim of game are selected. Hence, where the server has been started in the background but no actuall game has been started yet.

**Comment by Flamefire** [comment]
This is expected. In MAPS there are the played maps. And a savegame counts as such. Maybe we could place "played" savegames in the savegame folder. But this means, that one could have "his" savegame replaced by the servers savegame in multiplayer. So I don't think this is a good idea and I'D leaver it as-is
