### ISSUE TITLE
Alter the cancel dialog in the addon settings dialog box

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#767]
I wonder if I am the only one who would prefere something shorter here? A simple "Cancel" or "Abbrechen" would be absolutly sufficent in my opinion. If this is very trivial in the sense, that one has simply to edit line 41 of `src/ingameWindows.cpp` and the `languages/rttr-de.po` , I'd be happy to open a pull request on this! :) 

Same idea would be to change "Änderungen übernehmen" into "Übernehmen"

And something shorter and more sensible for the third option, if there is one. Right now I'm uncertain if that is possible without breaking the intention behind it. 

![0003](https://user-images.githubusercontent.com/14232936/33242387-81e9bc10-d2d4-11e7-954b-164813e8c213.png)

**Comment by Flamefire** [comment]
@Spikeone What do you think? What shall we use?

PS: It's not **that** easy as ALL translations would need to be updated

**Comment by Spikeone** [comment]
I'd agree to use "Apply" (mabye green texture), "Abort" or "Cancel" and "Default"

**Comment by Flamefire** [comment]
Applied that. I use the current texts as a tooltip though.

**Comment by stefson** [comment]
Did a quick test of the commit, I think there is a bit of a problem with the display of german umlaute, isn't it? On the old screenshot one can see that the dots of the Ä as a capital letter are somewhat squezzed to the side, and in the new Version the Ü is too small, hence not rendered as a capital letter. 

In addition to that, I expected the checkboxes to be smaller in size if the words in them are shorter?

**Comment by Flamefire** [comment]
Yes and no. The font height is fixed. So the dots can't go any higher. So yes the difference between the Ü and ü is very small. This is the original behaviour.

Nope. They stay the same size. I left them as we have the space. Once we implement presets we can make them smaller.

**Comment by stefson** [comment]
Hmm, okay. It is rather tricky to design a GUI :) 

There are some typos in the changed .po files, if you can wait for a few days I can hand you over the lines. Or open a PR and I comment on the respective lines.

**Comment by Flamefire** [comment]
Even easier: https://github.com/Return-To-The-Roots/s25client/wiki/How-to-translate-the-game -> https://translations.launchpad.net/s25rttr
