### ISSUE TITLE
Problem with new version 0.8.2 20171201 MACOS

### ISSUE THREAD

**Issue by SettlerBerlin** [Return-To-The-Roots/s25client#772]
hello,

nice project- wonderful to use the old installation under MACOS!
The newest version loaded yesterday is contains a big problem, the game doesn't start any more. Here the output of terminal- what is the easiest way to restore the previous version?

regards from germany
oliver

Last login: Sat Dec  2 10:53:36 on ttys000
/tmp/rttr.command
server:~ user$ /tmp/rttr.command
Savegame version of currently installed version: 4
Savegame version of updated version: 4
You will be able to load your existing savegames.
creating symlink A
creating symlink Versions/Current/mikmod
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/Versions/A/Frameworks/mikmod.framework/mikmod' to 'Versions/Current/mikmod': system:2
creating symlink A
creating symlink Versions/Current/smpeg
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/Versions/A/Frameworks/smpeg.framework/smpeg' to 'Versions/Current/smpeg': system:2
creating symlink A
creating symlink Versions/Current/SDL_mixer
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/SDL_mixer' to 'Versions/Current/SDL_mixer': system:2
creating symlink Versions/Current/Frameworks
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/Frameworks' to 'Versions/Current/Frameworks': system:2
creating symlink Versions/Current/SDL
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL.framework/SDL' to 'Versions/Current/SDL': system:2
creating symlink A
Error initializing your locale setting. Check your environment for invalid settings (e.g. LC_ALL or LANG=de_DE.UTF-8)
locale::facet::_S_create_c_locale name not valid

Press ENTER to close this window . . .

**Comment by Flow86** [comment]
thats the same bug i discovered here: https://github.com/Return-To-The-Roots/s25client/pull/737/files#r150392456
it seems that the locale stuff does not work correctly on osx 👎

**Comment by Flamefire** [comment]
Working on it

**Comment by Flamefire** [comment]
Could you try the recent version once it is build? Should work now.

**Comment by SettlerBerlin** [comment]
no, the automatic installed version doesn't work now:

Last login: Sat Dec  2 15:11:16 on ttys000
Cassandra:~ familiestein$ /tmp/rttr.command
Savegame version of currently installed version: 4
Savegame version of updated version: 4
You will be able to load your existing savegames.
Updating "s25client"

Downloading "s25client"                           100.00% - ok
creating symlink A
creating symlink Versions/Current/mikmod
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/Versions/A/Frameworks/mikmod.framework/mikmod' to 'Versions/Current/mikmod': system:2
creating symlink A
creating symlink Versions/Current/smpeg
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/Versions/A/Frameworks/smpeg.framework/smpeg' to 'Versions/Current/smpeg': system:2
creating symlink A
creating symlink Versions/Current/SDL_mixer
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/SDL_mixer' to 'Versions/Current/SDL_mixer': system:2
creating symlink Versions/Current/Frameworks
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/Frameworks' to 'Versions/Current/Frameworks': system:2
creating symlink Versions/Current/SDL
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL.framework/SDL' to 'Versions/Current/SDL': system:2
creating symlink A
Update finished!
Error initializing your locale setting. Check your environment for invalid settings (e.g. LC_ALL or LANG=de_DE.UTF-8)
locale::facet::_S_create_c_locale name not valid


Press ENTER to close this window . . .

**Comment by Flamefire** [comment]
I'm running out of ideas. I tried it too and get the same error. I unset LANG in `rttr.command` and still the same error. `LC_ALL` is also unset.
If I compile a sample program with `std::locale(); std::locale(""); std::locale("C");` it works both on clang and gcc.

@Flow86 I suspect a compiler/runtime issue here.

**Comment by SettlerBerlin** [comment]
ast login: Sat Dec  2 17:42:38 on ttys000
/tmp/rttr.command
server:~ user$ /tmp/rttr.command
Savegame version of currently installed version: 4
Savegame version of updated version: 4
You will be able to load your existing savegames.
Updating "s25client"

Downloading "s25client"                           100.00% - ok
creating symlink A
creating symlink Versions/Current/mikmod
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/Versions/A/Frameworks/mikmod.framework/mikmod' to 'Versions/Current/mikmod': system:2
creating symlink A
creating symlink Versions/Current/smpeg
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/Versions/A/Frameworks/smpeg.framework/smpeg' to 'Versions/Current/smpeg': system:2
creating symlink A
creating symlink Versions/Current/SDL_mixer
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/SDL_mixer' to 'Versions/Current/SDL_mixer': system:2
creating symlink Versions/Current/Frameworks
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL_mixer.framework/Frameworks' to 'Versions/Current/Frameworks': system:2
creating symlink Versions/Current/SDL
Failed to create symlink: './s25client.app/Contents/MacOS/Frameworks/SDL.framework/SDL' to 'Versions/Current/SDL': system:2
creating symlink A
Update finished!
Return To The Roots v20171202-6f03a74ed1a724db26d77b7a2f3b197d1ac0fc2a
Compiled with Gnu GCC C/C++ (4.2.1) for Mac OS (10.0.0) 64 Bit

Error initializing your locale setting. Check your environment for invalid settings (e.g. LC_ALL or LANG=de_DE.UTF-8)
locale::facet::_S_create_c_locale name not valid


Press ENTER to close this window . . .

**Comment by SettlerBerlin** [comment]
Whats different to last version? Previous without problems loading...

**Comment by Flamefire** [comment]
No new install required. Will try to fix it tomorrow. What was the last version that worked for you?
BTW: you can simply download an old version and copy it over the current version. Nothing should be lost

**Comment by Flamefire** [comment]
Ok, fixed with 54c7864904fe6ed387a9e13c11d7ed3043ea5800

However there was a bug that the updater might not run. If it does not auto-update either edit the rttr.command so ./bin/RTTR/s25update is called instead of ./share/s25rttr/RTTR/s25update or manually download and copy it over the existing files

**Comment by SettlerBerlin** [comment]
THX!!!
