### ISSUE TITLE
'observation window' is broken

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#782]
I don't use this function very often, so not sure when this happened? Noticed yesterday with a git copy of two days ago, but the issue still persists with current head of git. 

![2017-12-16-085656_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/34068655-6b58c9a8-e23f-11e7-8329-1ebcb626d64f.png)

**Comment by Flamefire** [comment]
Thanks. Bug introduced with the black border for windows

**Comment by stefson** [comment]
Black screen is fixed. 

Is it the original behaviour of the game to not to close the window upon right clicking within it? And if this is true, is the mouse arrow supposed to be the same one within the preview window, no matter if one does move around freely or does use the right-click to navigate / move?

**Comment by Flamefire** [comment]
Good point. Fixed. It closes when NOT right clicking in the map area of the window. Mouse cursor changes now
