### ISSUE TITLE
The intro message gets already shown in loading screen for campaigns (LUA)

### ISSUE THREAD

**Issue by Holzi01** [Return-To-The-Roots/s25client#783]
If you start a campaign the intro message is displayed already while loading the map and not when the map starts. This seems to be working fine in v20171214 but doesnt work for me in the latest nightly build (v20171216)

Thanks!

**Comment by Flamefire** [comment]
Which Lua script do you use? Could you attach it here?

**Comment by Holzi01** [comment]
I downloaded the LUA scripts from the forum thread (original Roman Campaigns): http://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1443

As far as I tested so far it is with all levels of the campaign.
Thanks for your answer!
