### ISSUE TITLE
How does trading work?

### ISSUE THREAD

**Issue by spacemanspiff2007** [Return-To-The-Roots/s25client#797]
Hi,
at the moment it is not clear to me how trading works.
Maybe you can include one or two sentences in the add-on description?

**Comment by Shawn8901** [comment]
Hi,
If you enable the plugin you can click on a allied warehouse or HQ. 
Within the menu, which pops up you are able to select a ware or a figure type.
There is also a input field, where you put the amount of wares/figures you want to trade.

If you hit the OK button one of your warehouses (or the HQ) will send caravan of donkeys (if you selected wares) with the amount of wares or a caravan of figures if you selected those.

That's all the "magic".  There is no automatic buy/sell system or any other kind of automatism for a "real" trade.

**Comment by spacemanspiff2007** [comment]
So do I need donkeys to make it work? Can one donkey still carry 2 items?

**Comment by Shawn8901** [comment]
every donkey should transport 1 item.
Not 100% sure about the implementation, but the donkey on the road also transports only 1 item?

**Comment by Spikeone** [comment]
I will just leave that here:
https://www.youtube.com/watch?v=PIwP7o-7hzk ;)

**Comment by Spikeone** [comment]
Question has been answered, closing this issue.
