### ISSUE TITLE
[wish] Schlosserei

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#80]
Der Schlosser arbeitet auch wenn alle Regler in der Werkzeugübersicht auf Null stehen. Er stellt dann zufällig irgendetwas her. Das ist besonders am Anfang nervig, da man wichtige Ressourcen verlieren kann. Schlussendlich baut man ja einen Schlosser vorsorglich, damit man schnell eingreifen kann, wenn ein Werkzeug fehlt und nicht damit er wahllos werkelt.

Klar kann man auch die Produktion in der Schlosserei ab- und anschalten, aber da man zur gezielten Herstellung sowieso in das Werkzeugmenü muss, wäre das doch unnütze Arbeit.

Die Befehlskette etwas einfach dargestellt:

Jetzt: Merken, dass ein Werkzeug fehlt -> Menü öffnen und den Schieberegler rübersetzen -> Schlosserei suchen -> Produktion anschalten -> Warten -> Schlosserei wieder suchen und abschalten -> Schieberegler ggf wieder auf Null setzen.

Ändert man das Ganze nun so, dass der Schlosser nur dann arbeitet, wenn auch wirklich ein Schieber ungleich Null ist, fallen da einige unnötige und unlogische Schritte weg.

https://bugs.launchpad.net/s25rttr/+bug/389152

**Comment by Flow86** [comment]
find ich sinnvoll - wie war das im original, hat er da bei "alles 0" was gemacht?
