### ISSUE TITLE
rttr:ResetAddons() not working

### ISSUE THREAD

**Issue by KaioKen-J** [Return-To-The-Roots/s25client#800]
Hey guys,
Im on the 20180103 version and cant get the rttr:ResetAddons() to work, can anyone confirm?

**Comment by Flamefire** [comment]
Jep correct. Any change to the GGS  overwrite changes done and sent to the server but not yet sent back. In lua you do exactly that: Change the GGS multiple times without waiting for the server to reply causing newer changes overwrite the whole config.

Fix incoming

**Comment by KaioKen-J** [comment]
Thank you, good sir!
