### ISSUE TITLE
Replays dont work

### ISSUE THREAD

**Issue by KaioKen-J** [Return-To-The-Roots/s25client#801]
On the 20180103 version everytime I wanna play a replay the game crashes and ask me to sent a report, which I did.

**Comment by Shawn8901** [comment]
Hi,
Maybe it would be helpful, if you could attach your replay.

**Comment by KaioKen-J** [comment]
Sure, didnt think about it because no replays work at all. here is just a random one 
[2018-01-06_20-13-39.zip](https://github.com/Return-To-The-Roots/s25client/files/1649905/2018-01-06_20-13-39.zip)

**Comment by Flamefire** [comment]
Fixed with #803
