### ISSUE TITLE
Crash at starting

### ISSUE THREAD

**Issue by Babjatekos** [Return-To-The-Roots/s25client#802]
Howdy!

I'm using win 8.1 and I got crash after I started the game - ver.: s25rttr_20171228 -
Log file here: https://pastebin.com/qxn3xekw

I copied the files what needed from original S2... I dont know what to do.
I also get an instant crash after star with version Version 0.8.2.

**Comment by Shawn8901** [comment]
Do you have some special characters in your installation path or path to user directory?

**Comment by Babjatekos** [comment]
I tested a little bit and the 0.8.1 version Works fine from this path: d:\S25rttr_0.8.1 with no problem.
Any other version what is above that are not working. These versions stop working even after the start up or causes the error what is the same thing what is mentioned above.
I don't think I use any special characters - like: # & / : ; etc - in installation path or directory. My 0.8.2 is at d:\s25rttr_0.8.2, I tried the d:\s25rttr0.8.2, and I also tried to start in from c: ... nothing... 
Or if you mean special character like the á in my c:\users\tamás and there is an: á in it ... and that is count as a special character?

**Comment by Shawn8901** [comment]
Yes, can you please try it with another user and then report the result?

**Comment by Babjatekos** [comment]
I tested it with a basic new user called: test ... and it is worked finy. 
With my user which contains an á character - what is a character from hungarian language - aren't working. 

What you linked in, that makes more sense to me... but if I understand that right, this problem wont be solved in the near future. Am I right? :(

**Comment by Flamefire** [comment]
Yes the special char might be causing the problem although I thought this was fixed in a PR. Not sure, why it doesn't work for you, so I got to investigate again...

**Comment by Flamefire** [comment]
@Babjatekos Could you upload the original log as a zip here (simply Drag&drop into the edit field) as I want to take a closer look at it but Copy&Paste might omit some encoding issues.

**Comment by Babjatekos** [comment]
[2018-01-24_15-38-34.log](https://github.com/Return-To-The-Roots/s25client/files/1660170/2018-01-24_15-38-34.log)

Hope this is what you need.

**Comment by Flamefire** [comment]
That bug was actually already fixed with a completely unrelated change. But the build server had a problem which is now fixed too. Everything should work again :)

For the record: Calling `tolower` on an UTF8 string seems to destroy the UTF8 encoding in some cases. The fix used simply does not use that `tolower`ed string as UTF8 anymore.

**Comment by Babjatekos** [comment]
I'm happy to help. :)

And all of that means if I start it again, it have to work fine for me from now? :)
And a stupid questions: Can I use the 20180103 version, and do I need to start the rttr.bat to do some patching, or I do not have to do anything? :)

**Comment by Flamefire** [comment]
starting rttr.bat will always update to the latest version and start the game afterwards. So yes, just start that :)

**Comment by Babjatekos** [comment]
Done and it is working again! :)

Thank you very much! :)
