### ISSUE TITLE
Wrong mouse position in dialog at set flag or building a way/street

### ISSUE THREAD

**Issue by Th0m45G** [Return-To-The-Roots/s25client#807]
Click on a golden flag in a long way or click a flag to build a way. In the past the default position of the mouse cursor was adjusted to the default used left button like "set flag" or "build way" which makes it possible to build flags and ways faster by double click without searching the button in the dialog. Older RTTR versions does this too like i am used to. The actual version not. This makes it very difficult to build fast.

**Comment by Flamefire** [comment]
Still working. Check if you have "Smart cursor" enabled in the main settings.

**Comment by Th0m45G** [comment]
You are right. Seems like i clicked the option because of the tooltip that it is useful for splitscreen but didnt mentioned the other tooltip that this turns off the behaviour of the postioning. Sorry :)
