### ISSUE TITLE
Pausing game loses connection to server

### ISSUE THREAD

**Issue by McKenning** [Return-To-The-Roots/s25client#808]
**Affects**: Nightly Builds. Stable releases unaffected.

Pausing any game and then unpausing causes four messages to be received in the console:

Receiving Message from server failed
Lost connection to server!
server state changed to stop
client state changed to stop

This is repeatable in various custom maps and has been occurring since release 20171228.
![screenshot_1](https://user-images.githubusercontent.com/36162467/35812396-0d56472c-0a4e-11e8-9aae-e78604fdc9cc.png)

**Comment by Flamefire** [comment]
Which OS is this? I don't have it on latest windows nightly

**Comment by McKenning** [comment]
Windows 10 Pro 1709.  I used the latest nightly x64 - revision 7ba2df7.

**Comment by Flamefire** [comment]
I updated the nightly to include some more information. Please try it again and post the log file please

**Comment by McKenning** [comment]
I was able to download the new release and test. However, this time when I unpaused, it crashed the game. I've attached the logfile.
[2018-02-06_13-16-02.log](https://github.com/Return-To-The-Roots/s25client/files/1700772/2018-02-06_13-16-02.log)

**Comment by Flamefire** [comment]
Ok, seems you got kicked for some reason. Updated the client to avoid the crash (and fix another similar crash). Please try again

**Comment by McKenning** [comment]
Back to the original error message without the game crashing. Here is the logfile.
[2018-02-07_12-54-54.log](https://github.com/Return-To-The-Roots/s25client/files/1704585/2018-02-07_12-54-54.log)

**Comment by Flamefire** [comment]
Could you describe your steps for this problem. Especially: How long till you pause and how long till you unpause the game? Also there should be a new nightly in a couple minutes which may contain additional  log output and also a possible fix. See if this helps, please but still answer the above questions.

**Comment by McKenning** [comment]
I don't usually pause the game for at least 10-15 minutes after I start. Then, it's usually paused for about 10-15 minutes before the error is manifest. Before this bug report, I could pause the game for just a second or two and it would kick me. Now, it is much longer, but still a reasonable time before I'm kicked. I will check the latest build today and report back.

**Comment by Flamefire** [comment]
Some context why I was asking: The server starts a timer per player, when the player did not sent his commands but the server is ready (by its time) to execute the commands. This timer is reset when commands from that player arrive.

Pausing on client side is immediate (you may want to pause on a specific frame) but the server is just getting notified which might take a bit (usually milliseconds). So the server will start the players timer before the pause command comes. Having it paused then for >=5 minutes and resuming will then trigger the timeout which gets you kicked. So it should be impossible to get kicked if you unpause after less than ~4minutes. Especially you should not get kicked before the unpause or if you unpause within a minute or so. If you do (especially after the latest update) tell me.

Final note: The fix in 800f01ec479423c6a56866f974dad50d719e02c8 is simply to reset the timer on pause.

**Comment by McKenning** [comment]
That seems consistent with what I am seeing. Unpause within a minute is no problem. After five, it kicks me.

I will try 8259910 today and let you know.

**Comment by McKenning** [comment]
The issue appears to be resolved. I was able to pause it for short (1sec-5min) and long (10min to 1 hour) without it crashing.

The console window now shows a continuous message (about every second):

"Different timeouts 299!=300"

![image](https://user-images.githubusercontent.com/36162467/36048278-e9837a6c-0d9b-11e8-9f79-353eb5a38eae.png)
