### ISSUE TITLE
Strange mouse behaviour 

### ISSUE THREAD

**Issue by WernerAntonWolf** [Return-To-The-Roots/s25client#809]
Hi!

Todays version (rttr.bat) on two computers:
Mouse move with right button pressed leads to extremly asynchonous movement and when doing that for several seconds, program freezes.

How can we send you additional information?

Family Wolf

**Comment by Flamefire** [comment]
Hey! I need the following infos:

- Which OS are you using? Windows?
- Which version of rttr (x86, x64)?
- Which video driver (if windows), SDL or WinAPI? (see video-config screen)
- Does this happen all the time and where? Is it already in the main menu (right after opening rttr) or in game?

**Comment by WernerAntonWolf** [comment]
Hi!

 

Betriebssystemname    Microsoft Windows 7 Professional

Version                6.1.7601 Service Pack 1 Build 7601

Zusätzliche Betriebssystembeschreibung           Nicht verfügbar

Betriebssystemhersteller           Microsoft Corporation

Systemname     COUGAR

Systemhersteller            MSI

Systemmodell  MS-7846

Systemtyp          x64-basierter PC

Prozessor           Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz, 3501 MHz, 4 Kern(e), 8 logische(r) Prozessor(en)

BIOS-Version/-Datum   American Megatrends Inc. V10.1, 01.10.2013

SMBIOS-Version             2.8

Gebietsschema               Österreich

Hardwareabstraktionsebene    Version = "6.1.7601.17514"

Installierter physikalischer Speicher (RAM)        16,0 GB

 

We use SDL. 

Unfortunately there are no details stored in the s25client.exe. In the task manager there is no *32 so I suppose its 64bit version.

 

The symptoms:

* If you start the s25client the main window is opened. If you switch to a different program, the mouse goes to screen position 0x0 and is blocked there.

* Back in rttr, when right clicking the mouse and moving it, the cursor is moving too slow. When stopping the movement and right click, the cursor still moves for several seconds.

* Sometimes when building a street, the edit windows comes up again and I have to close it manually.

 

Hope this helps.

 

Greetings,

Werner

 

Von: Alexander Grund [mailto:notifications@github.com] 
Gesendet: Sonntag, 11. Februar 2018 19:03
An: Return-To-The-Roots/s25client
Cc: WernerAntonWolf; Author
Betreff: Re: [Return-To-The-Roots/s25client] Strange mouse behaviour (#809)

 

Hey! I need the following infos:

*	Which OS are you using? Windows?
*	Which version of rttr (x86, x64)?
*	Which video driver (if windows), SDL or WinAPI? (see video-config screen)
*	Does this happen all the time and where? Is it already in the main menu (right after opening rttr) or in game?

**Comment by Flamefire** [comment]
Ok, there is a fix in the pipeline and will be included probably tomorrow.

Note: The console window and log say, whether it is running for x86 or x64 at the very top. In this case it doesn't matter so just for future reference.

**Comment by WernerAntonWolf** [comment]
Thank you very much!

 

Von: Alexander Grund [mailto:notifications@github.com] 
Gesendet: Montag, 12. Februar 2018 00:16
An: Return-To-The-Roots/s25client
Cc: WernerAntonWolf; Author
Betreff: Re: [Return-To-The-Roots/s25client] Strange mouse behaviour (#809)

 

Ok, there is a fix in the pipeline and will be included probably tomorrow.

Note: The console window and log say, whether it is running for x86 or x64 at the very top. In this case it doesn't matter so just for future reference.

**Comment by Flamefire** [comment]
Fixed by a28d8c6

**Comment by WernerAntonWolf** [comment]
Tested, working!

 

Thank you very much for this fast and good working implementation.

 

Werner

 

 

Von: Alexander Grund [mailto:notifications@github.com] 
Gesendet: Montag, 12. Februar 2018 19:07
An: Return-To-The-Roots/s25client
Cc: WernerAntonWolf; Author
Betreff: Re: [Return-To-The-Roots/s25client] Strange mouse behaviour (#809)

 

Closed #809 <https://github.com/Return-To-The-Roots/s25client/issues/809> .
