### ISSUE TITLE
Grenz"lücken"

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#81]
Wenn man eine Grenze hat, sind dazwischen manchmal einfach "lücken",sehr komisch.

[MarcusSt: removed images that do not exist any more]

https://bugs.launchpad.net/s25rttr/+bug/392733

YES, this IS still a bug

**Comment by Flamefire** [comment]
Wurde doch asl "Not fix" geschlossen. Grenze ist doch nur vom Feuer überdeckt, oder?

**Comment by jhkl** [comment]
Es geht wohl um die Lücken, nicht um die Feuerstellen! kA wieso das mit Won't fix geschlossen wurde? Vielleicht schwierig zu beheben?

![fehler](https://cloud.githubusercontent.com/assets/2512962/9008401/69c30c2c-379a-11e5-9f78-c5e0ec15402f.JPG)
![fehler2](https://cloud.githubusercontent.com/assets/2512962/9008403/6e5cc3cc-379a-11e5-8047-0c69dfaf8a71.JPG)

**Comment by Flow86** [comment]
evtl falsch verstanden, so ists definitiv ein bug

**Comment by Spikeone** [comment]
Ich Stelle die auf wobt fix wenn die von launchpad hier landen weil der launchpad bugtracker auf der hp immer noch als bugtracker gezeigt wird und so niemand auf die Idee kommt dort neue Informationen zu posten.
Und hj. hat das richtige Bild gemacht ja - ich marine damals gehört zu haben das liegt daran wenn zwei den gleichen anrechtswert haben oder so.

**Comment by MarcusSt** [comment]
@Flow86 gibt es eine Möglichkeit, den auf Launchpad zu schließen bzw. hierher zu verweisen?

**Comment by Flamefire** [comment]
Ich würde den Bug hier schließen. Es scheint dadurch zu kommen, dass beide den gleichen Anrechtswert haben. Ich sehe es als OK, dass dann keiner das Land bekommt. Gibt sonst keine faire Lösung.

**Comment by Spikeone** [comment]
Der, der weniger Land hat (Statistik) sollte diesen Punkt bekommen - das ist denke ich auch fair. Bringt in den meisten Fällen nichts aber es sieht einfach nicht schön aus.

**Comment by Flamefire** [comment]
Kannst du das in der aktuellen Version reproduzieren?

Statistik ist auch blöd. Dann müsste sich das ändern, wenn sich die Statistik ändert... Wenn dann würde ich sagen, der Spieler mit der niedriegeren ID als Tie-Breaker. Vorher noch sowas wie Nähe zum Militärgebäude oder Größe des Militärgebäudes mit reinbringen.

**Comment by Spikeone** [comment]
Werde ich prüfen, ggf Lücken von Nord nach Süd schließen, damit man unten eine Fahne hat um ein Gebäude zu bauen.

**Comment by Flamefire** [comment]
Reproduziert. Das Problem ist: Eigentlich gehört der Punkt zu gelb (2. screenshot). Damit hätte man eine recht hässliche ecke in den gelben Grenzsteinen. Darum wird der Punkt einfach weggenommen und fertig. Man könnte entweder die Ecke reinmachen (unschön) oder einfach nem anderen spieler geben, der keine ecke produziert.
Das ganze tritt extrem selten auf, da es davon abhängt, in welcher reihenfolge die gebäude gebaut werden

**Comment by Spikeone** [comment]
Ist tatsächlich gar nicht mal so selten, eigentlich tritt das fast in jedem Spiel auf, wird ja auch vermutlich an der Reihenfolge der Eroberung dann ebenfalls abhängen oder? Also es zu fixen sähe schon schön aus! :)

**Comment by Flamefire** [comment]
Dann mit ecke und fair oder ohne ecke und schöner?

**Comment by Spikeone** [comment]
Ohne ecken und schön (bzw. dem original ähnlicher)

**Comment by Flamefire** [comment]
For future reference: What we want to avoid is this:
![borderbloggs](https://user-images.githubusercontent.com/309017/33223217-df7cfde2-d15d-11e7-8bc7-426d03b95248.png)
[Savegame](https://github.com/Return-To-The-Roots/s25client/files/1502491/Border.zip) Just switch to yellow and attack the barracks.

Note also that this depends on the order the buildings were built as when 2 military buildings have the same distance to a point, the newer one gets it. IMO this is bad and the older one should get it or the current owner should keep it.
