### ISSUE TITLE
cannot open the game bar in fullscreen mode

### ISSUE THREAD

**Issue by Trolldemorted** [Return-To-The-Roots/s25client#810]
If the game is running in fullscreen mode, pressing win+g does not open the game bar, rttr only changes the brightness a few times.

W10 Pro N
WinApi/OpenGL

**Comment by Flamefire** [comment]
This is a windows issue: https://support.xbox.com/en-US/xbox-on-windows/social/troubleshoot-game-dvr-windows-10#eafd8bbc95cf49038b8c75492b8e0a11
