### ISSUE TITLE
capturing screenshots with the print key does not work

### ISSUE THREAD

**Issue by Trolldemorted** [Return-To-The-Roots/s25client#812]
Instead, this is captured:

![grafik](https://user-images.githubusercontent.com/10261186/36072413-9737a01e-0f1f-11e8-8813-ee7ea61782b3.png)

W10 Pro N 64bit

**Comment by Flamefire** [comment]
This is expected. The default PRINT-screenshot is not able to capture screenshots from fullscreen apps.
I added a screenshot function to rttr: Pressing PRINT will now save a screenshot to the userdata directory and display a message in the console.

Will be merged tomorrow, hope this helps :)
