### ISSUE TITLE
Music does not start automatically

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#813]
Hi,

got this Bug via Email:

> leider starte die Musik immer noch nicht, wenn man das Programm
> startet (Version vom 7.02.) nachstehend die Fehlermeldung aus dem
> Terminal. Kann es evtl. damit zusammenhängen?

I asked if the sound does not work at all and got this reply:

> es wird die Musik nicht angespielt. Erst wenn man in den Einstellungen die Musik
> ab- und wieder anschaltet wird sie wieder angespielt. Der Ton funktioniert.

**Comment by Flow86** [comment]
> leider wird die Musik nicht abgespielt. Zusätzlich geht jetzt auch der „Workaround“, in den Einstellungen Musik aus- und wieder einschalten, nicht mehr. Nachstehend die Fehlermeldung aus dem Terminal.
> ```  
> 2018-02-13 11:10:43.942 s25client[851:17953] 11:10:43.942 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
> Loaded audio driver "(SDL) Audio via SDL_mixer-Library"
> ```

**Comment by Flamefire** [comment]
Woot? Can I have a full log file with latest version and try to enable music via main settings menu?

**Comment by Flow86** [comment]
habe das log angefordert:

[2018-02-13_11-12-46.log](https://github.com/Return-To-The-Roots/s25client/files/1720342/2018-02-13_11-12-46.log)

**Comment by Flamefire** [comment]
Er hat die ogg files nicht. Ich pushe gleich ein update, dass eine entsprechende Meldung anzeigt, aber im Prinzip muss er einfach nur den updater ausführen. Ich dachte das passiert unter OSX automatisch? Hat er das irgendwie manuell gestartet oder mit "noupdate"?

**Comment by Flow86** [comment]
keine ahnung, eigentlich halt mit doppelklick auf die app. sollte da ja eigentlich ein update machen - evtl pfade nicht richtig?

**Comment by Flow86** [comment]
Hmm, wenn ichs versuche in meiner VM zu starten, bekomme ich:
```
.... 
rttr.command: line 61: ./s25client.app/Contents/MacOS/libexec/s25rttr/s25update: cannot execute binary file
....
```
d.h der updater läuft gar nicht an

**Comment by Flow86** [comment]
Nachtrag:

```file s25client.app/Contents/MacOS/libexec/s25rttr/s25update
s25client.app/Contents/MacOS/libexec/s25rttr/s25update: ELF 64-Bit LSB executable, x86-64
```

Doch mal wieder ein cmake-bug?
