### ISSUE TITLE
Military Aid breaks distance calculations

### ISSUE THREAD

**Issue by McKenning** [Return-To-The-Roots/s25client#815]
When selecting option to use "Military Aid", military building proximity indicators fluctuate when certain events take place. I have seen this happen on both the player and AI side military buildings.

Screenshot 1: After a fresh load from saved game, everything appears normal, then when the AI attacks, the flags change to "interior" rather than "border" as indicated by the adjoining enemy fortresses. See bottom two roman fortresses.
![rttr_1](https://user-images.githubusercontent.com/36162467/37037757-39f79e06-2110-11e8-922f-42fb39cfe161.png)

Screenshot 2: After the attack finishes, the flags return to their correct state with the bottom roman fortress flag showing "border".
![rttr_2](https://user-images.githubusercontent.com/36162467/37037804-5633c018-2110-11e8-9d71-a1e86b17f145.png)

Screenshot 3: After an unknown trigger, the flags again go to "interior" within a couple of minutes.
![rttr_3](https://user-images.githubusercontent.com/36162467/37037873-8347d3f0-2110-11e8-847b-27c62d595b25.png)

I have also observed the flags changing when military buildings far away are occupied.

Using version 20180213 on Windows 10 x64.

Logfile attached.
[2018-03-06_07-05-19.log](https://github.com/Return-To-The-Roots/s25client/files/1785373/2018-03-06_07-05-19.log)

**Comment by Shawn8901** [comment]
could you please attach the save file?

**Comment by McKenning** [comment]
Savegame attached:
[Savegame.zip](https://github.com/Return-To-The-Roots/s25client/files/1802892/Savegame.zip)

Military settings:
![image](https://user-images.githubusercontent.com/36162467/37286543-d292e768-25c7-11e8-9cb7-6326854c9091.png)

Economy Settings:
![image](https://user-images.githubusercontent.com/36162467/37286586-fb3f35b8-25c7-11e8-8531-c744453a33f9.png)

Gameplay Settings:
![image](https://user-images.githubusercontent.com/36162467/37286603-0a893122-25c8-11e8-9b6a-916f4eeb0fc3.png)

Other settings:
![image](https://user-images.githubusercontent.com/36162467/37286629-19279a48-25c8-11e8-8460-03493322fed5.png)

**Comment by Shawn8901** [comment]
As you are using the "Frontier Distance check reachability" - mod, could you check the scenario if that's disabled? i would guess that it treats the military building as not reachable.
As i understood you right, it happens if you are switching on and off the military aid mod, right?

**Comment by McKenning** [comment]
I will check, but I have to start a new game with the frontier add-on disabled.

**Comment by Shawn8901** [comment]
i will take a look into that as soon as i have some free time for that.
