### ISSUE TITLE
Exakt gleiche Bauplätze in Original und RttR gefordert

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#82]
Mir ist bei einer meiener Karten aufgefallen, das irgendetwas mit den Bauplätzen nicht stimmt denn da wo man im Originalen nichts bauen kann, geht das in RttR serwohl. Eventuell hängt es auch mit den falschen Höhen zusammen, ich weiß es nicht.

Spike (fvv1) wrote on 2009-07-20:	#1
Beide Stellen im Vergleich Edit (592.6 KiB, application/rar)

FloSoft (flosoft) wrote on 2009-07-21: Re: [Bug 401929] Re: UngleicheBauplätze in Original und RttR	#2
kann es sein das man im s25 bei den "krüppelfichten" an der stelle die
baracke bauen kann, im original kann man dort nur fahnen bauen.

Spike schrieb:
> ** Attachment added: "Beide Stellen im Vergleich"
> http://launchpadlibrarian.net/29300177/Vergleich.rar
>

Spike (fvv1) wrote on 2009-07-21: Re: Ungleiche Bauplätze in Original und RttR	#3
Glaube ich nicht, sind meist andere Sachen da, ich kann ja das nachher nochmal ohne bäume machen, dann mal sehen.

Spike (fvv1) wrote on 2009-07-21:	#4
Nochmal 2 im Vergleich Edit (539.5 KiB, application/rar)
Als bezugspunkte gelten die 4 Bäume, zwischen den Bäumen wurde nie etwas gebaut oder lief ein weg entlang

Spike (fvv1) wrote on 2009-07-21:	#5
Falschen plätze nochmal makiert in dem Bereich Edit (266.4 KiB, image/jpeg)

OLiver (postfach-von-oli) wrote on 2010-04-08:	#6
Es ist schwierig und imho sinnlos, den genauen gleichen Algorithmus dazu herauszufinden/anzuwenden.
Kann ja jemand machen, der Lust dazu verspürt => Wishlist

https://bugs.launchpad.net/s25rttr/+bug/401929

**Comment by jhkl** [comment]
<Spikeone> problem a) BQ RttR != BQ s2
<Spikeone> problem b) BQ kann sich in RttR verändern, in s2 nicht
<Spikeone> problem c) BQ wird nicht an der letzten grenzreihe im süden geupdated bei militärgebäudebesetzung (da haste dann gar keine BQ bis du ne fahne setzt und abreißt)
<Spikeone> problem d) Wenn du ein gebäude abbrennst, bleiben angrenzende gebäude häufig mittlere gebäude statt wieder große zu werden, wege neu bauen hilft um die BQ zu aktualisieren

**Comment by Flamefire** [comment]
@Spikeone Wenn das noch aktuell ist, kannst du das ganze nochmal reproduzieren und ein Save/Replay + Screenshots mit Hinweis, was anders ist, dazupacken?

@jh: b) Würde ich so lassen. Ist sonst zu schwer umsetzbar. Was ist z.b. mit Gebieten wo Bäume stehen? Da ändert sich die BQ ja durch das Entfernen der Bäume. Warum also nicht durch Planieren (oder wodurch ändert die sich in RTTR)?
c) Gibts das immernoch? Replay möglich?
d) War glaube im Original auch so. Könnten aber ne Neuberechnung der BQ am Ende des Brennvorgangs anstoßen...

**Comment by Spikeone** [comment]
Was ich genau testen sollte weiß ich nun nicht aber ich habe was getestet:
b) Ist in RttR extremer als in S2, in S2 war es kaum möglich "neue" große Gebäude zu schaffen, in RttR ist das massiv möglich (siehe mein Video zum Thema Terraforming)
c)
![nichtaktualisiert1](https://cloud.githubusercontent.com/assets/1276342/14413016/78977eda-ff6e-11e5-92d7-4a16627cbdca.png)

![fahnetuts](https://cloud.githubusercontent.com/assets/1276342/14413019/7e044cd6-ff6e-11e5-86de-b0f149783572.png)

d) Soweit ich mich erinnere ist das korrekt, ich bin mir aber nicht sicher, ob man diesen Bug nicht entfernen sollte.

**Comment by Flamefire** [comment]
Testen (was mir einfällt, im Prinzip zu den Punkten a-d):
1. Wo unterscheiden sich RTTR in S2 BQs (ohne Änderung durch Gebäude) mit Screenshot und replay/savegame
2. "Terraforming" in S2 und RTTR. Insbesondere: Was verändert S2 beim planieren? Wie verändern sich dort die BQs?

b) Testcase mit Vergleich zu S2 nötig. u.U. wird das durch a) auch schon behoben... Oder wir planieren falsch
c) Worauf muss ich achten? Sieht doch völlig ok aus?
d) Ok, bin auch für fixen

**Comment by Spikeone** [comment]
a) Merri weiß wie berechnet wird, und ja ich teste das terraforming
b) -
c) die neue Fahne erzeugt einen Bauplatz, Hütte, der vorher nicht sichtbar war.

**Comment by Flamefire** [comment]
a) Hat er das iwo veröffentlicht?
c) Ah... Ok :D Kannst du das Replay uploaden? Dann guck ich mir das mal an

**Comment by Spikeone** [comment]
a) alles was ich dazu mitbekommen hatte war das: http://settlers2.net/2012/08/figuring-out-building-sites/
c) mach ich aber erinner mich ruhig via irc dran :D

**Comment by Flamefire** [comment]
Habs gefunden: https://github.com/Merri/settlers2/blob/master/map-blocks/8_BUILD_SITE.md

Jetzt brauch ich nur noch ein paar test-cases :)

Ich bin ja generell dafür, in RTTR die BQ für einen Punkt zu speichern. Wenn das player-territory für den gefragten Spieler ist, wird es so genommen, sonst ist es BQ_NOTHING. Das erspart die Neuberechnung der BQ in AIs und ist ein weiterer Schritt Richtung Splitscreen (Entkopplung Daten von Interface nötig) @jh @MarcusSt @Flow86

**Comment by jhkl** [comment]
:+1: 

Ja, entkoppeln ist toll für die AI, die aktuell 'andauernd' die BQs neuberechnet.

**Comment by Flamefire** [comment]
Erster Test der Umstellung: https://github.com/Flamefire/s25client/commit/e4c91da58e02c7274e1b459e5240c691d41617cb
Scheint soweit zu klappen, nur dass er jetzt beim Zugriff die Spielergrenzen checken muss... Sollte aber OK sein, da es nur den aktuellen View intressiert (Der könnte das später auch cachen...) und das damit nicht viele Punkte sind. Rest sollte schneller laufen, insbesondere die AI, die dort jetzt deutlich weniger rechnen muss (Territory check statt BQ komplett berechnen)

Ich werd im Zuge dieses issues mal versuchen alles Welt Zeug vom Gameclient zu entkoppeln. Dann kann man das ganze in ner Test-Suite testen. Sollte nicht zuviel Aufwand sein.

**Comment by Flamefire** [comment]
Hab nen lustigen Bug bei der BQ Berechnung gefunden. Dadurch konnte Hütten gebaut werden, wo eigentlich nur Flaggen gehen sollten.
Damit sollte a) behoben sein. d) guck ich mir an. Für c) fehlt mit noch das replay von @Spikeone ;-)

**Comment by Spikeone** [comment]
Stimmt, ich les das immer morgens in der Bahn, ich mach mir mal ne Notiz, obwohl das replay outdated seien sollte.

**Comment by Flamefire** [comment]
Ok. Wenn du das ansonsten mit nem neuen replay reproduzieren kannst, wäre das super. Dann kann man das hier endlich fixen :)

**Comment by Spikeone** [comment]
Could not reproduce the bug I encountered when I first posted pictures but:
![first](https://cloud.githubusercontent.com/assets/1276342/15475775/fcfa1f02-210b-11e6-95c2-a732f9d45d95.png)
![second](https://cloud.githubusercontent.com/assets/1276342/15475777/007571b8-210c-11e6-92ca-33914e9d0f9d.png)

Huts suddenly become medium building spots?
http://www.rfmonline.de/rttr/spike/2016-05-23_17-23-57.zip

**Comment by Flamefire** [comment]
They should have been medium before... Fixed in the PR.
If you really can't reproduce that bug, I'd consider it fixed. Burning and terraforming remaining.

**Comment by Flamefire** [comment]
Recalculation after burning (Point c) ) seems to work already. Could not reproduce it so I considers this fixed to unless someone can get me a replay to prove the opposite ;)
Will check the terraforming part but I'd probably leave it as I don't want to change the BQ calculation to "cripple" it.

**Comment by Flamefire** [comment]
Just tried the terraforming with a small testmap in S2 and it works there as well. So keeping it.

**Comment by Spikeone** [comment]
Going to test this on the 4th mission map tomorrow as I remember that it was quite extreme on that map. I know that it was possible, but only for building spots close to medium/big building spots. In rttr you can use "new" medium/big building spots as well for terraforming.

**Comment by Flamefire** [comment]
I'd say don't bother with this. "Terraforming" is quite a lot of work and the result is also logical: Planer makes terrain all the same level -> BQ improves.

**Comment by Spikeone** [comment]
Also, wenn ich Karten erstelle habe ich 2 wichtige Gedanken zu Terraforming im Kopf:
a) Es kann mir egal sein wie "gleich" einzelne Startpunkte sind nachdem ich Zufallshöhen gesetzt habe da man das alles mit Terraforming zurecht biegen kann im Spiel
b) Ich weiß nie genau, ob Karten die bestimmte Bauplätze explizit brauchen (Zum Beispiel möchte ich jedem Spieler in einer Bergpassage nur kleine Gebäude zugestehen) diese zum einen haben und ob die Bauplätze auch so bleiben.

Hinzu kommt: es ist kein wirkliche "feature" sondern das betreiben der Handhabung wegen nur wenige. Es wäre fast schöner wenn es ein Addon mit "Lock BQ" gibt, wo höhen nicht mehr die BQ beeinflussen sondern nur Objekte (Nach einer Initialen Berechnung) und "Terraforming BQ", hier kann man auch eine Fahne setzen und schlicht "Call Planer" machen (Ähnlich Geologist und Scout) welcher dann rum die Fahne herum planiert. 

Warum ich jetzt auf einmal wieder auf deutsch schreibe... ich weiß es nicht ;)

**Comment by Flamefire** [comment]
a) Es geht ja auch ;) Also kein Problem
b)Kleine Gebäude werden nicht planiert. -> Kein terraforming möglich -> Kein Problem

Die Addons sind durchaus möglich. Aber würde ich sehr weit hinten anstellen. Das "Locken" der BQ ist sehr schwierig umsetzbar, da ja die BQ von mehr als nur der Höhe beeinflusst wird. Man bräuchte dann mehrere unterschiedliche Berechnungen, was es echt unschön macht. Das 2. sollte aber tatsächlich recht einfach möglich sein. Das aber auch später. Wichtig war erst mal, dass es generell funktioniert und wie in S2 ist.

**Comment by Spikeone** [comment]
Du kannst dich aber von einem Bereich der große Bauplätze hat langsam Vorarbeiten zu dem Bereich der nur kleine Bauplätze hat, das stört leider etwas.

Mehr stört mich, dass es ein Feature ist, dass neuen Spielern wegen Unwissenheit verwehrt bleibt

**Comment by Flamefire** [comment]
Wenn das wirklich ein Problem ist, dann einfach 1 Schicht Bergwerk oder so hin und fertig ;)

Naja das sind halt "Profifeatures" ;)
