### ISSUE TITLE
FindLua broken 

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#827]
@stefson reported:

This broke compile with system lua, I have lua-5.2.3 installed and built against it for ages now:

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LUA: Found unsuitable version "", but required is exact
  version "5.2" (found LUA_INCLUDE_DIR-NOTFOUND)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:375 (_FPHSA_FAILURE_MESSAGE)
  libutil/cmake/Modules/FindLUA.cmake:134 (find_package_handle_standard_args)
  src/libGamedata/CMakeLists.txt:43 (find_package)

**Comment by Flamefire** [comment]
@stefson where is your Lua.h and what is the cached cmake value for LUA_LIBRARY?

**Comment by stefson** [comment]
my system-lua.h is at /usr/include/lua5.2/lua.h 
for the cached cmake value you'd have to tell me where to find it.

**Comment by Flamefire** [comment]
Use cmake-gui or ccmake in the build dir, toggle advanced mode on (t key) and look for the entry

**Comment by stefson** [comment]
ah, found it: its looking for the `LUA_LIBRARY` in `/usr/lib/liblua5.2.a` ; the file is present and exists. 
but `LUA_INCLUDE_DIR` states as `LUA_INCLUDE_DIR-NOTFOUND`

this is a list of all files installed on my system by lua: [lua.list.gz](https://github.com/Return-To-The-Roots/s25client/files/1939236/lua.list.gz)

**Comment by Flamefire** [comment]
Thanks. Found a typo in the module and opened another PR

**Comment by stefson** [comment]
with the latest git checkout, I got this: 

```CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LUA: Found unsuitable version "", but required is exact
  version "5.2" (found /usr/include/lua5.2)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:375 (_FPHSA_FAILURE_MESSAGE)
  libutil/cmake/Modules/FindLUA.cmake:137 (find_package_handle_standard_args)
  src/libGamedata/CMakeLists.txt:43 (find_package)
```

**Comment by Flamefire** [comment]
Strange. You you attach your lua.h?

**Comment by Flamefire** [comment]
Ok they use tabs instead of spaces so my regex failed. Alright. Fixed :)

**Comment by stefson** [comment]
Fixed if given that you pushed the changes to libutil! :grin:
