### ISSUE TITLE
Fehler beim Hosten einer neuen Karte, wenn die Option IPv6 gewählt wurde

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#83]
Wenn ich ein "Direkte Ip" Spiel hosten will, lädt das Spiel endlos, wenn die Option 1Pv6 gewählt wurde.
Unter Nutzung der Option 1Pv4 funktioniert alles wie es sollte

Version: 6062
Windows Xp

Stefan Kriwanek (Divan) (dev-stefankriwanek) wrote on 2010-02-22:   #1
Das hat nicht wirklich was mit IPV6 zu tun. Ich hab auf Ubuntu denselben Effekt wenn ich zwar IPV4 gewählt hab, aber keine aktivierte Netzwerkverbindung (mit IPV4) habe.

Das Spiel liefert nach dem Klick auf Spiel Starten auch in der Konsole
GameClient::Connect: ERROR: Connect failed!
und tut dann aber nichts mehr. Also zwei Sachen die wir fixen müssen:
1. GameClient::Connect funktioniert nicht ohne aktive Netzwerkverbindung. (viell. unter Linux dann den loopback-Adapter nutzen oder direkt nen socket? Und was ist mit Windows?)
2. Wir sollten das Bitte-Warten-Fenster beenden, falls irgendwas schiefgeht.

FloSoft (flosoft) wrote on 2010-02-22:  #2
das Problem ist folgendes:

getaddrinfo benötigt (leider) eine aktive Internetverbindung um die Namen aufzulösen, evtl könnte man das für "localhost" überspringen und direkt die entsprechende Adresse verwenden.

Ansonsten sollte der Bug das das Wartefenster beim Fehlschlag nicht benachrichtigt wird, behoben werden ;-)

FloSoft (flosoft) wrote on 2010-02-22:  #3
achja nachtrag:

bei mir kann ich auch ohne netzwerkverbindung korrekt hosten: wenn in der hosts-datei jeweils 127.0.0.1 (ipv4) und ::1 (ipv6) für localhost eingetragen sind, sonst fragt er logischerweise den dns ab und schlägt fehl.

Habe das ganze nun umgangen, für localhost wird nun keine abfrage mehr benutzt

Punkt 1: behoben in rev6068

https://bugs.launchpad.net/s25rttr/+bug/525738

**Comment by MarcusSt** [comment]
Summary of what is left to do: close "please wait" window if something went wrong connecting to a game.

**Comment by Spikeone** [comment]
Hosting IPv6 works. Also an error message appears if something wents wrong.
