### ISSUE TITLE
s25client crashes during exit

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#837]
This does not seem to have any serious consequences, nontheless it should be adressed at some point in the future. Here is the output: 

```Thread 1 "s25client" received signal SIGSEGV, Segmentation fault.
__GI_getenv (name=0x7fffe186836f "LGRIND") at getenv.c:84
84	getenv.c: Datei oder Verzeichnis nicht gefunden.
(gdb) q
A debugging session is active.

	Inferior 1 [process 15627] will be killed.

Quit anyway? (y or n)

**Comment by Flamefire** [comment]
If you have the bug and rttr as debug build, can you provide a backtrace? (type `bt` in GDB once it breaks)

**Comment by stefson** [comment]
sure, here it is: 

```Thread 1 "s25client" received signal SIGSEGV, Segmentation fault.
__GI_getenv (name=0x7fffe186836f "LGRIND") at getenv.c:84
84	getenv.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_getenv (name=0x7fffe186836f "LGRIND") at getenv.c:84
#1  0x00007fffe18349c8 in pa_in_valgrind ()
   from /usr/lib64/pulseaudio/libpulsecommon-11.1.so
#2  0x00007fffe1a9a759 in ?? () from /usr/lib64/libpulse.so.0
#3  0x00007ffff7de9aaa in _dl_fini () at dl-fini.c:235
#4  0x00007ffff5c49350 in __run_exit_handlers (status=0, 
    listp=0x7ffff5fba5d8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, 
    run_dtors=run_dtors@entry=true) at exit.c:83
#5  0x00007ffff5c493ba in __GI_exit (status=<optimized out>) at exit.c:105
#6  0x00007ffff5c31548 in __libc_start_main (main=0x555555710d26 <main(int, char**)>, 
    argc=1, argv=0x7fffffffdbd8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdbc8) at ../csu/libc-start.c:329
#7  0x000055555570deca in _start ()
```

Usually I don't use pulseaudio on this system, neither is the daemon running at the moment. Had to install it temporarilly :-(

**Comment by Flamefire** [comment]
Ouch... Currently no idea where this is coming from... Our code is not shown there. Maybe a bug somewhere else?

**Comment by stefson** [comment]
Indeed, I'm not very happy about having to install pulseaudio. It is not a terrible crash after all, I'll check again upon removal of this bloaty thing in a few weeks.

**Comment by baka0815** [comment]
@stefson So, there is no crash after uninstalling pulseaudio?

**Comment by stefson** [comment]
jipp, pulseaudio was the cause of the crash. I didn't realize this in the first place, otherwise hadn't opened this issue because it had to be installed for a project at university, as mentioned before. I don't use a debianish distro but gentoo, which makes it easy for me to add, up- and downgrade packages as I please for the most of it. 

If none else is affected by this, the issue can be closed!
