### ISSUE TITLE
Bug: Ressourcenfehler im Kartengenerator

### ISSUE THREAD

**Issue by JoeDufff** [Return-To-The-Roots/s25client#842]
In der aktuellen Version 20180512 gibt es mit dem Kartengenerator im Spiel ein Ressourcenfehler. Die Geologen finden in den Bergen keine Ressourcen.

![siedler 2](https://user-images.githubusercontent.com/39239747/40278823-a2743f44-5c38-11e8-91b3-52ecd0c1d604.png)

und

![siedler 2_1](https://user-images.githubusercontent.com/39239747/40278829-af5fe8de-5c38-11e8-9b1f-c334a0a5d804.jpg)

**Comment by Shawn8901** [comment]
@Flamefire: Gibt es einen Grund warum im Kartengenerator Feuchtigkeit vorhanden sein muss, damit dieser Ressourcen platziert? In diesem Commit (96cd7567b4d5508185419453b0c4eec683400b75) hast du die Feuchtigkeit eingefügt und hier (6dcdd24aec5a4361b600b9011872b76638aca37a) diesen in den Kartengenerator eingebaut.
Da jedoch ein Berg keine Feuchtigkeit aufweisen kann (https://github.com/Return-To-The-Roots/s25client/blob/3e1e00472b602c596e23b1408bf9cf9e125ec12d/src/libGamedata/gameData/TerrainDesc.cpp#L79), ist damit jeder ohne Ressource (siehe https://github.com/Return-To-The-Roots/s25client/blob/3e1e00472b602c596e23b1408bf9cf9e125ec12d/src/mapGenerator/RandomMapGenerator.cpp#L272). Davor wurde nur auf Minable gepüft. Ich vermute, dass dies hier ein versehen ist. Wenn man diesen Check wieder raus nimmt, sollte es wieder wie früher funktionieren.
