### ISSUE TITLE
S25client crashes after asking for debug data

### ISSUE THREAD

**Issue by ongaku86** [Return-To-The-Roots/s25client#843]
Hey there,

I hope I haven't overlooked a similar topic, if I did, sorry bout that.

I am trying to reinstall RTTR on my mums system but it crashes after launch. After closing the debug data window I get a message saying that S25clint is - due to a problem - not working correctly anymore and therefore shut down. This is what it says in the black window (which I cannot name in english):

![troubleshoot s25](https://user-images.githubusercontent.com/16455260/40279849-155a70b2-5c4a-11e8-8c4f-744f1dc7fd66.jpg)

If anyone could help me out with this it would be really great, like many others I've been playing it for years and am so happy about the RTTR project!

Astrid (Germany)

**Comment by ongaku86** [comment]
Forgot to add the system data (its sunday, after all...):

   Operating System: Windows 7 Home Premium 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr.170913-0600)
           Language: German (Regional Setting: German)
System Manufacturer: Acer
       System Model: Aspire 7750G
               BIOS: InsydeH2O Version V1.14
          Processor: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 CPUs), ~2.2GHz
             Memory: 8192MB RAM
Available OS Memory: 8044MB RAM
          Page File: 3479MB used, 12606MB available
        Windows Dir: C:\Windows
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: 96 DPI (100 percent)
 System DPI Setting: 96 DPI (100 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.01.7601.17514 32bit Unicode

**Comment by Shawn8901** [comment]
Hi,
hint: all active contributor are speaking german, so no problem with the german message boxes.
About the issue itself: is it somehow reproducible? If yes could you describe how? for me its not clear what/which "debug data window" you mean.

**Comment by Flow86** [comment]
Hi,
have you tried to run the game via `rttr.bat`? in your screenshot it looks like you started it via `s25client.exe`.

@Shawn8901 
The only possibility to get that exception (which is displayed in the black console window) mentioning `boost::filesystem::unique_path` is here:

https://github.com/Return-To-The-Roots/libutil/blob/f098f7a5abea9d1b82411a14a322e520258a93e2/src/tmpFile.cpp#L44

> Schlüssel ist im angegebenen Status nicht gültig.

@ongaku86 is your hard drive encrypted?

**Comment by Flow86** [comment]
ah noch was, das Problem hatte schonmal jemand und konnte es lösen:

https://www.siedler25.org/index.php?com=forum&mod=forum&action=thread&id=1381
