### ISSUE TITLE
a630a68 broke the build with gcc-6.4.0

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#846]
```
-- Found OpenGL: /usr/lib/libGL.so  
-- Found Gettext: /usr/bin/msgmerge  
-- Boost version: 1.65.0
-- Found the following Boost libraries:
--   filesystem
--   iostreams
--   system
--   program_options
--   locale
--   chrono
--   regex
CMake Warning at src/libGamedata/CMakeLists.txt:25 (message):
  Could not find lua.h in contrib


CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Lua: Found unsuitable version "", but required is exact
  version "5.2" (found )
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:375 (_FPHSA_FAILURE_MESSAGE)
  libutil/cmake/Modules/FindLua.cmake:234 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/libGamedata/CMakeLists.txt:62 (find_package)


-- Configuring incomplete, errors occurred!
```

The revision just before that commit reports a missing lua.h file in contrib as a warning, but this does not break the compile. Log from cmake: [CMakeError.log.gz](https://github.com/Return-To-The-Roots/s25client/files/2069234/CMakeError.log.gz)

**Comment by Flamefire** [comment]
Then something is wrong on your side. Does  `git status` report anything? It checks for `${CMAKE_SOURCE_DIR}/contrib/lua/include/lua.h` and issues the warning if it is not found. The file is in the repo. So everything is ok and the failure expected if you deleted that file

**Comment by stefson** [comment]
The lua headers reside in /usr/include/lua5.2; I'm building against them since 2015 or so :-) I use system headers for all, the contrib folder is simply deleted before the compile starts.

**Comment by Flow86** [comment]
Buildserver broke too:

```
[windows.x86_64] CMake Error at libutil/cmake/Modules/GatherDll.cmake:35 (file):
[windows.x86_64]   file STRINGS file "/workdir/contrib/lua/win64/liblua52.a" cannot be read.
```

**Comment by Flamefire** [comment]
@stefson Try again with the latest update and clear your cache. That should do the trick

@Flow86 Ah yeah, I forgot that  CMake does not redo the search when the file does not exist anymore. Could you clear the cache for all build steps once?

**Comment by stefson** [comment]
This is acutally much better! 

```
-- Found OpenGL: /usr/lib/libGL.so  
-- Found Gettext: /usr/bin/msgmerge  
-- Boost version: 1.65.0
-- Found the following Boost libraries:
--   filesystem
--   iostreams
--   system
--   program_options
--   locale
--   chrono
--   regex
CMake Warning at src/libGamedata/CMakeLists.txt:48 (message):
  Could not find lua.h in contrib


-- Found Lua: /usr/lib/liblua5.2.so;/usr/lib/libm.so (found suitable exact version "5.2.3") 
```

**Comment by Flamefire** [comment]
I guess I should remove that warning...
So it does work now? Then please close the issue.

**Comment by stefson** [comment]
The warning might irritate some people, but it appears to be benigne to me. 

Thanks for the fix :-)
