### ISSUE TITLE
Catapult strike on empty building -> crash 

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#85]
in 99% the app crashes after a catapult strike on an empty military building. (noc soldiers because of attack)

https://bugs.launchpad.net/s25rttr/+bug/1429798

**Comment by Spikeone** [comment]
Untested, maybe no bug (addon settings?)

**Comment by MarcusSt** [comment]
Could somebody test this? :-)

**Comment by Spikeone** [comment]
I think this bug is not valid - got some games when I got such shots and no crashes at all
