### ISSUE TITLE
Move contrib binaries out of main archive

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#852]
I want to remove the contrib archives (at least the MSVC) from this repo as every time something in it changes, a whole binary is reuploaded which hides the changes and bloats this repo.

@Flow86 created the https://github.com/Return-To-The-Roots/contrib repo, but that is not really usable. Cloning it will download ~240MB which is to much (MSVC contrib folder is 25MB)

Hence my idea would be:
- Remove all files from https://github.com/Return-To-The-Roots/contrib and write only links into the Readme
- Add an unpacked version of msvc-contrib to it
- Remove full-contrib-msvc.rar from this repo (optional also the lua stuff. It can be installed in every Linux distro easily and for MSVC we include it anyway. What about the build server? Does it have those too or can they get installed?)
- Use CMakes [ExternalProject](https://cmake.org/cmake/help/v2.8.12/cmake.html#module:ExternalProject) to download a specific revision of the mscv contrib in case one generates a MSVC project (Either download as git repo (clone) or as a zip. Repo is probably better for updates)

This way we can keep this repo smaller and see what was changed.

**Comment by Flow86** [comment]
we should reorganize the repo to use Git LFS (https://git-lfs.github.com/) instead. so only the file pointers are stored inside the repository, and the files are downloaded from githubs content servers.

only thing is you need an up to date git client or have to install the git lfs filters manually.

**Comment by Flamefire** [comment]
I'd rather not use that:
- Extra dependencies and stuff to setup/understand
- Not really suitable for this use case: Have the contribs not as an archive but unpacked so modifications are clearly visible. Tracking this with git LFS is hard to impossible (seems you track files by extension, we will have header files there). Of course if we continue with archives then this is better.

**Comment by Flamefire** [comment]
*Ping

**Comment by Flamefire** [comment]
Used git lfs with 70b7235c83eb62d71ef8838e2da4a09b2db45fdb
