### ISSUE TITLE
2/233 tests are broken on arm

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#855]
```
cd build/bin/
user@rpi2:~/s25client-0d8e96a8512c8190e631eaa3e9e40461b0f37c6c/build/bin$ ls
s25client  s25edit  Test
user@rpi2:~/s25client-0d8e96a8512c8190e631eaa3e9e40461b0f37c6c/build/bin$ ./Test 
Running 223 test cases...
Loaded audio driver "MockupAudio"
/home/tim/s25client-0d8e96a8512c8190e631eaa3e9e40461b0f37c6c/src/test/testLua.cpp(259): fatal error in "GameFunctions": exception LuaExecutionError is expected
/home/tim/s25client-0d8e96a8512c8190e631eaa3e9e40461b0f37c6c/src/test/testLuaSettings.cpp(172): fatal error in "SettingsFunctions": exception std::runtime_error is expected

*** 2 failures detected in test suite "RTTR_Test" 
```

These errors are lua related, it seems. The tests are from the ubuntu-16.04 test build, liblua-5.2-dev and friends got installed to please the lua system dep. 

All 233 tests have passed on amd64.

**Comment by Flamefire** [comment]
I guess this is due to disabled exception support: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0491h/Cacgbadh.html

We have to add `--exceptions` to the cxx flags

**Comment by stefson** [comment]
Does that mean that you would like to add `-Wno-exceptions` to the cppflags?

**Comment by Flamefire** [comment]
What? Completely wrong. I wrote to " add `--exceptions` to the cxx flags" because the error is due to **disabled** exception support. Also why would you assume `-Wno*` could **enable** anything?

FYI: `-f` is for features, `-W` is for warnings.

**Comment by Spikeone** [comment]
@stefson @Flamefire is this still a valid issue?

**Comment by stefson** [comment]
I'm not sure, don't have any clang on my arm at the moment

**Comment by Flamefire** [comment]
Won't work yet. Gotta add the flag.
