### ISSUE TITLE
no new charcoalers under some circumstances

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#861]
Ran into this, as I was running out of coal and started to build some three charcoalers. Also out of shovels, so build some from the last available iron, but nothing happens for an infinite amount of time. The replay is here: 

[2018-08-10_21-31-17.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/2279342/2018-08-10_21-31-17.rpl.zip)

You can skip to ca 620.000, the toolmaker is close to my own headquarter. It produces five shovels, but no worker picks them up to become a charcoaler. 

I solved this by collecting every available tool, axes, saws, etc, into the headquarter, and reloading the savegame. To reload only had not solved it. Savegame is available, but its just after the problem was solved, so it may not be helpfull: [Kaesetoast.sav.zip](https://github.com/Return-To-The-Roots/s25client/files/2279361/Kaesetoast.sav.zip)

**Comment by stefson** [comment]
Is there a way to give an exact location? I mean, close to my own headquarter was my idea of giving a location? Also, the git id of this is from the modernOGL branch, not the master branch.

**Comment by Flamefire** [comment]
Press F3 for coordinates. In this case the relevant event is the toolmaker (the only one, so easy to find) which produced the shovel at 613500

**Comment by stefson** [comment]
Ok, I'll try to remember the F3 debug output next time. By the way, do you know why the maps name in the games menue is `Kaesetost`, but the filename is `rttr/maps/new/AM_KAESETOAST.SWD` ?

**Comment by Flamefire** [comment]
The name is in the map. The filename does not matter
