### ISSUE TITLE
Some files failed to load in client

### ISSUE THREAD

**Issue by looceb** [Return-To-The-Roots/s25client#875]
Hey guys,

I tried to get ur client starting and i copied the data and gfx files before, but there comes everytime the same screen.  The files are working on another pc of my friend but not at my own. I tried to get the path as short as possible and tried to get it work in the most compatibility modes and also run it in different admin modes. My username has no space in, like the guy with the last issue in the forum.

I would be glad if u could help me.

Thx for your nice project!

**Comment by looceb** [comment]
![screen](https://user-images.githubusercontent.com/43609889/46082948-98f63300-c1a0-11e8-8067-21d410ea299c.png)

**Comment by Flamefire** [comment]
Will look into this.

Note: There is never a need to start RttR as admin unless you put it into C:/ProgramFiles or another folder that requires admin rights to modify.

**Comment by looceb** [comment]
Thank you very much for your quick reponse i hope you can solve it :)

**Comment by Flamefire** [comment]
Found. Executing `"C:\foo\cmd.exe" -t param` does not work on windows w/o some care, but it could be `"C:\foo with space\cmd.exe" -t param` and that requires quotes...

Implemented a proper wrapper and will merge it once CI succeeds.

**Comment by looceb** [comment]
Thank you very much it works now perfectly 👍 

Thanks for your quick response and work :)
