### ISSUE TITLE
random maps function spawns palmtrees in winter worlds

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#877]
It's a bit cold for palm trees to grow, but foremost it's breaking the immersion as they don't have a snowy texture available. Would you mind turning them off for winter worlds? 

![2018-09-27-095307_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/46131269-854bda80-c23b-11e8-81d6-bd7488c98695.png)

**Comment by vader1986** [comment]
This one should be fixed by #1187

**Comment by stefson** [comment]
ah yeah right, I forgot that you're not allowed to close the issue on your own.
