### ISSUE TITLE
Not starting: missing liblua52.so and CURL_OPENSSL_3

### ISSUE THREAD

**Issue by taleteller** [Return-To-The-Roots/s25client#878]
This is on ubuntu 18.04 using the revision a5b6e57 x64 linux from settlers25.org and my first attempt to move settlers 2 out of the dosbox. Installation happened as described in the wiki. 
```
$ ./rttr.sh 
checking for an update ...
/tmp/s25update.31265: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /tmp/s25update.31265)
/opt/s25rttr/bin/../bin/s25client: error while loading shared libraries: liblua52.so: cannot open shared object file: No such file or directory
An error occured: press enter to continue
```

Obviously, its not starting, but at least it complains in a constructive way. The program has found curl, but fails the required option ``CURL_OPENSSL_3``. You should consider changing this, since ssl3 is not about to come back. Until then the updater wont work. 

Lets check package status for liblua 5.2 on my system ...
```
liblua5.2-0/bionic,now 5.2.4-1.1build1 amd64  [Installiert,automatisch]
  Shared library for the Lua interpreter version 5.2
```
Its installed, but the library is named differently than in the build target. Therefore i symlink it to the lib folder with the expected name

```
ln -s /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 /opt/s25rttr/lib/liblua52.so
```

After the next start the game runs fine. You might consider to add this step to the installation guide.

**Comment by Flamefire** [comment]
I fixed the lua issue by using a static library instead.

About CURL: Thats on your side unfortunately. Rttr links against libcurl 3 but you have libcurl 4 which has changed on Ubuntu 18.

Try Google or one of those (**Untested, no warranty, just found with google**):

- sudo apt install libcurl3
- sudo apt-get install libcurl3:i386 
- sudo apt-get install libcurl4:i386 
- https://www.ngemu.com/threads/ubuntu-bionic-libcurl-so-4-curl_openssl_3-not-found.204577/

Other idea: Build RttR from source then you won't have the problem.

**Comment by Flamefire** [comment]
`CURL_OPENSSL_3` may not mean SSL3 (I'm not sure what it means, probably libcurl**3**)

The build server uses an older Ubuntu, maybe @Flow86 can upgrade the libs, but I doubt so (he was working on updating the whole stack, but didn't finish yet), so no we can't do that for now.

We only connect to our server so the version is fine as long as that works. From googling others seem to have solved this so maybe you can too. E.g. try putting an older libcurl (3) into the rttr folder where it can be found (or set LD_LIBRARY_PATH).

And again: You may simply build RTTR yourself. Sorry but I can't do more currently.
