### ISSUE TITLE
Build doesn't work: sh: 1: sound-convert: not found

### ISSUE THREAD

**Issue by daviel** [Return-To-The-Roots/s25client#880]
I was trying to build the source on my Raspberry Pi (Raspbian) as well on my regular debian 9 (Intel Skylake). Building went through without problems but after starting the client the following error came up:

```
Starte Sound-Converter...
sh: 1: sound-convert: not found
ERROR: Some files failed to load.
```

The only workaround I found was to copy the s-c_resample and sound-convert binarys to the users scope like so:

`
cp s-c_resample sound-convert /usr/bin/
`

The sound-convert binary is called in the Loader.cpp file in the ConvertSounds(...) method. Printing the call and the parameters showed the following which looks quite correct:

> /home/david/Schreibtisch/s25client/build/libexec/s25rttr/sound-convert 
-s "/home/david/Schreibtisch/s25client/RTTR/sound.scs" 
-f "/home/david/Schreibtisch/s25client/build/share/s25rttr/S2/DATA/SOUNDDAT/SOUND.LST" 
-t "/home/david/.s25rttr/LSTS/SOUND.LST"

So most probably the sound-convert binary calls s-c_resample from the users bin-path rather from the local directory where itself is saved. But it doesn't work if I only copy s-c_resample the the /usr/bin.

**Comment by Flamefire** [comment]
I don't understand the last part:

>So most probably the sound-convert binary calls s-c_resample from the users bin-path rather from the local directory where itself is saved. But it doesn't work if I only copy s-c_resample the the /usr/bin.

Isn't the error message that `sound-convert` was not found?

**Comment by daviel** [comment]
> I don't understand the last part:
> 
> > So most probably the sound-convert binary calls s-c_resample from the users bin-path rather from the local directory where itself is saved. But it doesn't work if I only copy s-c_resample the the /usr/bin.
> 
> Isn't the error message that `sound-convert` was not found?

What I meant was that from the output of Loader.cpp the absolute path is used for sound-convert(which should work). But if sound-convert tries to load s-c_resample if fails to find it. I thought maybe the error message gets mixed up but I am not 100% sure about that.

**Comment by Flamefire** [comment]
It was sound-convert which was not found.

The impl did something like "cd <PATH> && sound-convert <ARGS>" which doesn't work on linux. It needed "./sound-convert"

Thanks for reporting

**Comment by daviel** [comment]
Great work! Thank you for fixing it that fast.
