### ISSUE TITLE
Own maps no longer working

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#884]
You can no longer see maps located in the games directory WORLDS folder in the Selection of maps screen. I guess the saved games WORLDS folder is used which is (or at least was) not the intention behind "Own Maps".

![image](https://user-images.githubusercontent.com/1276342/47839360-d4dd7300-ddb2-11e8-964d-c8abb72ab08b.png)

**Comment by Flamefire** [comment]
This is true. This folder was(?) moved to the user-folder but it is NOT the same as the "played maps" folder. This change is due to common operating systems not allowing write access to the programs folder which would make using this folder impossible. Maybe one could use both folders (probably hard to implement) but isn't the users folder (Saved Games->RTTR in Windows) better?

**Comment by Spikeone** [comment]
Well, as we do not force anyone to install RttR in the programs folder (I know that even windows 7 users have sometimes no write access) I don't  see any reason to always use the Saved games Worlds folder. Also the idea of RttR was to use the original game folder which then results in own maps which were saved in the worlds folder. I personally use 3 different tools to edit maps (s25edit, s2edit, my map tool) and got them installed in the same folder since ~2012. For the editor it might be usefull on some (maybe most) OS to use the saved games folder but for own maps one should at least allow both folders. 

Or just a simple switch, set by default to the saved games folders (and if we have a installer one could change the setting while installing like one does in battle for wesnoth). 

But in my opinion the saved games folder is not as handy as the original worlds folder as I now just open the s25client exec path and got the worlds folder - no need to navigate to saved games. Some of those ideas may be lazyness but I still  think the local worlds folder should be at least read.
