### ISSUE TITLE
Minilag when a new song is played

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#893]
Once you start playing and a new song is loaded there is a mini lag in game. This happens only once for any song (guess the song is still loaded next time it plays).

**Comment by Flamefire** [comment]
From what I see what happens it is this:

- New song selected -> Get loaded or load:
- Write (possibly) converted song to file
- Load this file via SDL

It seems the 2nd point is taking the longest time causing the lag. Not sure if this can be avoided at all, but maybe it can be made better. I'm working on new resource management which might already fix this.
