### ISSUE TITLE
Songs stop playing

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#894]
So I was playing quite some time with ingame music. After the 2nd or 3rd time playing all songs, the music just stopped and didn't continue.

**Comment by Flamefire** [comment]
The music player has a repeat option (bottom right). The playlist stops after this many times through.

**Comment by Flamefire** [comment]
Is this resolved or do you want that the playlist repeats endlessly (remove the repeat count function)?

**Comment by Spikeone** [comment]
Well the original simply had a "start / stop" and "play song number x" button. 

I'd say we need 2 buttons - play playlist endlessly (switch button on/off) and play random order (on/off). by default random order is off and endless is on.

**Comment by Spikeone** [comment]
@Flamefire this one is fixed, isn't it?

**Comment by Flamefire** [comment]
Yes, by #1487
