### ISSUE TITLE
AI Debug window available if disabled

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#895]
So I just set my addon settings and disabled the AI debug window as always. Sadly there still is the option to open it in the main menu when playing. I guess if there is only one player the window is shown regardless of the settings but one can't be sure about that.

**Comment by Flamefire** [comment]
It should always be there for Debug builds, else depend on setting. But maybe there was a wrong define used. Check again after update

**Comment by Spikeone** [comment]
Just asking - shouldn't everybody have the AI debug window then? It's just player 1 / The host

**Comment by Flamefire** [comment]
No. Only the host **has** the AI. So other players simply don't have the AI data which makes this impossible.

**Comment by Spikeone** [comment]
Oh really? Did this change? I remember that the "disable addon" has been added because everbody could view the ressource map. Maybe this has been changed long time ago.

**Comment by Flamefire** [comment]
No. It is not possible and never could have been. Only host could see that (which is enough to be unfair in a multiplayer game)
