### ISSUE TITLE
Zooming causes black lines

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#896]
When zooming often black lines appear. Using the mousewheel does not cause the bug as often as "Z" does. But at 75% it is quite... ugly.

![image](https://user-images.githubusercontent.com/1276342/47868129-bbb0e280-de03-11e8-867c-cc13ff0557d8.png)

**Comment by Flamefire** [comment]
Damn rounding errors -.-

**Comment by Flamefire** [comment]
Problem identified: Rectangles loaded from S2 are 32x31 pixel for some textures. Textures created are Powers-Of-2 to better fit video drivers. The remaining pixel is filled with transparent or black (depending on alpha being used or not)

This bleeds through when resizing the texture: Interpolating the border pixel might lead to the outer color getting used. Possible solution: Fill border pixels with neighbor color.
