### ISSUE TITLE
Drop support for MSVC < 2015

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#897]
I think we should require Visual Studio 2015+. This gets more important when we use modern C++ (finally once CI is solved) as VS 2013 does not fully support all (good) features: https://msdn.microsoft.com/de-de/library/hh567368.aspx

As you can even get MSVC 2017 community for free we could even raise this to VS 2017. CI currently tests 2015 and 2017.

Note: This applies to

- Supported features from C++11/14
- Shipped contrib libs (there is currently a pre-2015 and a post-2015 version due to incompatibilities)

**Question** MSVC 2015 or 2017?

**Comment by Spikeone** [comment]
As I personally only use MSVC2013 and MSVC2017 I'd vote for 2017 :)

**Comment by Flamefire** [comment]
Note that 2015 would include 2017 but 2017 would exclude 2015 ;)

**Comment by Spikeone** [comment]
Well, then there is no need to ask, is there? At least I don't care as long as 2013 or 2017 is supported - but thats mainly your business :)

**Comment by Flamefire** [comment]
2017 has more features/better compiler standard but excludes 2015. I'm fine with that (although I would need to upgrade my VS) but I wanted to hear others opinions. Especially @Flow86

**Comment by Flow86** [comment]
Yes we can drop support lower than VS2015. Since VS2015 is still the most used VS at the moment, we can't drop the support for that

**Comment by Flamefire** [comment]
I just ran into a problem with MSVC 2015 where I remembered why I wanted to drop it: It does not support generalized constexpr: https://docs.microsoft.com/de-de/cpp/visual-cpp-language-conformance?view=vs-2017

This means some even simple things are not possible. E.g. from `Point<T>` subtraction:

```
template<typename T>
constexpr Point<T>& operator-=(Point<T>& lhs, const Point<T>& right)
{
    lhs.x -= right.x; // Nope. Not in MSVC
    lhs.y -= right.y;
    return lhs;
}
```

In this case it is not that important. If it turns out we need it, we should drop MSVC2015

**Comment by Flow86** [comment]
nope that error is fully correct for c++11, since there constexpr implies const. with c++14 constexpr does not imply const anymore, then you will get the above compiled correctly.

btw the current PR does not compile on gcc too:

```
/source/libs/common/include/Point.h: In instantiation of 'constexpr auto operator*(const Point<T>&, U) [with T = int; U = unsigned int]':
/source/tests/common/testPoint.cpp:84:30:   required from here
/source/libs/common/include/Point.h:201:49: error: no match for 'operator*=' (operand types are 'Point<int>' and 'const unsigned int')
```

**Comment by Flamefire** [comment]
> nope that error is fully correct for c++11, since there constexpr implies const. with c++14 constexpr does not imply const anymore, then you will get the above compiled correctly.

This is unrelated. The above is not a member function hence the "implies const" does not apply here.   
Prior to C++14 ("generalized constexpr") you could only have a return statement in the constexpr function. We do use C++14 but MSVC does not support those.

> Also its not seen as a good style to rely on "non const" in constexpr (yet). you should also not constexpr operators modifying this.

You can do some quite amazing things with that ;)

> the current PR does not compile on gcc too

Yep. Code valid in MSVC but not in C++ -.-

**Comment by Flamefire** [comment]
> Yes we can drop support lower than VS2015. Since VS2015 is still the most used VS at the moment, we can't drop the support for that

Coming across this again. The "constexpr does not imply const in C++14" comes up again. The C4814 is not even listed on the MS pages -.-

Although it is not really required playing with constexpr would be great. This needs MSVC 2017 which also has the `/std:c++14` flag with improved compatibility. Do you have any references on the "most used VS"? Is it really required with MSVC 2019 just released and 2017 community edition available?
