### ISSUE TITLE
Game music doesn't stop when quitting the game

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#898]
I wanted to reproduce #893 and #894 , and noticed that the in game music does continue to play when leaving the game, eventually coming to a halt when /usr/bin/s25client is terminated. 

Or is this intended behavior? I mean, didn't the game made a difference between activating the in game sounds and music from within playing a session, and on the other hand playing a click sound when clicking the buttons in the menues and background music while selecting maps and getting ready to start a session?

**Comment by Flamefire** [comment]
This is expected. I do also have the game music in the main menu. I think the original has this to @Spikeone ?

**Comment by Spikeone** [comment]
Just tested it - music starts once the game starts and then runs in an endless loop. It doesn't matter if you start / stop a game or anything else. Can't tell about the effects as they do not play using dosbox :-/

Tested in v1.51en
