### ISSUE TITLE
Troubles making s25client

### ISSUE THREAD

**Issue by meloxu** [Return-To-The-Roots/s25client#9]
Hey, after following the instructions I ran into the following problem while running `make`:

    Linking CXX shared library libvideoSDL.so
    /usr/bin/ld: CMakeFiles/videoSDL.dir/SDL.cpp.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
    CMakeFiles/videoSDL.dir/SDL.cpp.o: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    driver/video/SDL/src/CMakeFiles/videoSDL.dir/build.make:139: recipe for target 'driver/video/SDL/src/libvideoSDL.so' failed
    make[2]: *** [driver/video/SDL/src/libvideoSDL.so] Error 1
    CMakeFiles/Makefile2:472: recipe for target 'driver/video/SDL/src/CMakeFiles/videoSDL.dir/all' failed
    make[1]: *** [driver/video/SDL/src/CMakeFiles/videoSDL.dir/all] Error 2
    Makefile:116: recipe for target 'all' failed
    make: *** [all] Error 2

Unfortunately I have no idea where the problem lies. I'm using arch linux on a 64bit system.
Could someone please point me into the right direction?

**Comment by Flow86** [comment]
Hi,

how to you run the build? on my 64bit machine, the cmake files automatically adds -fPIC (in driver/src/CMakeLists.txt)

**Comment by meloxu** [comment]
HEy, I do this exactly:

    git clone https://github.com/Return-To-The-Roots/s25client s25client
    cd s25client
    git submodule update --init
    cd build
    ./cmake.sh --prefix=.
    make

In case it's relevant:
> cmake 3.2.3-1
> make 4.1-1

There's no difference, running those commands as root or not.

**Comment by Flow86** [comment]
can you please post the complete output of cmake.sh? perhaps I can track it down. And "lsb_release  -a" if its available on your platform

**Comment by chrimobs** [comment]
Compiling the latest version results in the following error:
```
[ 21%] Building CXX object libutil/src/CMakeFiles/s25util.dir/UPnP.cpp.o
/home/xxx/s25client/libutil/src/UPnP.cpp:78:33: fatal error: miniupnpc/miniupnpc.h: Datei oder Verzeichnis nicht gefunden
#include <miniupnpc/miniupnpc.h>
```
`./cmake.sh --prefix=.` did not come up with any errors.

**Comment by Flow86** [comment]
you have to install miniupnp-dev first

**Comment by chrimobs** [comment]
I believe it would be good then to let `cmake` check for that as well(?)

**Comment by Flow86** [comment]
yes I always forget that to add to the cmake checks

**Comment by uqs** [comment]
Hey, so I'm trying to build this under FreeBSD, but I have zero clue about CMake and what I've tried seems to find the miniupnpc library, but doesn't add the proper include path.

Please see:
https://github.com/uqs/s25client/commit/2b468c0ad1fd07d44eba2fdefc2939760b7907bd
and
https://github.com/uqs/libutil/commit/9892bf7395d76092aa7d0aac26e3b7116e4880ec

I guess the latter would also break the MSVC case. But it also doesn't work anyway:

[ 18%] Building CXX object libutil/src/CMakeFiles/s25util.dir/UPnP.cpp.o
/data/src/s25client/libutil/src/UPnP.cpp:83:14: fatal error: 'miniupnpc/miniupnpc.h' file not found
    #include <miniupnpc/miniupnpc.h>

Help?

**Comment by Flow86** [comment]
well, where is your miniupnpc.h in your filesystem?

**Comment by uqs** [comment]
/usr/local/include/miniupnpc/miniupnpc.h

And FindMiniupnpc does find it, but the CFLAGS are not applied, it seems.
