### ISSUE TITLE
Victory conditions don't work anymore

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#902]
They haven't  been nice but now you don't even get the "player xy won" or "Team xy won" message in the chat anymore. Seems like the conditions are broken.

**Comment by Spikeone** [comment]
[2018-11-03_17-39-16.zip](https://github.com/Return-To-The-Roots/s25client/files/2545135/2018-11-03_17-39-16.zip)

Just created a new one using a dummy.

**Comment by Flamefire** [comment]
The message is still there. It gets printed with the next statistic update, so a few seconds later. Will make it instant

**Comment by Spikeone** [comment]
Hm, waited quite a moment in my original game and never saw it. We continued playing for around 2000GF and I checked the console output - gotta keep the point where the message is shown so I can add a window ;)

**Comment by Flamefire** [comment]
Check your replay. With that the message comes around 6k GF or so

> gotta keep the point where the message is shown so I can add a window ;)

I don't understand this

**Comment by Spikeone** [comment]
[test2.zip](https://github.com/Return-To-The-Roots/s25client/files/2554774/test2.zip)

But not in the original save game - waited some time but never saw the message. The first savegame had no teams, maybe this was the cause?

And I just wanted to say, that in the original a window was shown when winning the game. I'd like to add that and now I know where I possibly could trigger it :)

**Comment by Flamefire** [comment]
For your save there is no objective set. IMO "no objective" makes only sense for missions so total_domination should be the default but this may break scripts expecting this.

**Comment by Spikeone** [comment]
Hm, pretty sure I set a goal - maybe the host menu showed it as set although it wasn't? I started an other game before where I also enabled that option and it was kept for the next game but that might be a visual only then

**Comment by Flamefire** [comment]
Unlikely. From what I know is that most settings are kept when starting another game but those are reset when closing the client.
