### ISSUE TITLE
Lobby chat -> new server message

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#903]
When hosting a game using the internet lobby, you got the lobby chat. Any lobby message is routed to the server chat. Sadly this also routes the "<SYSTEM> %player created server %servername" message so you will always start with a blinking "Lobby Chat" button. 
Maybe System messages shouldn't be routed?

**Comment by Spikeone** [comment]
While I was testing this now some times I also observed the following: This "<SYSTEM> Spike created server Spikes's Game" message isn't always displayed. Looks like it depends on how long the server needs to be set up. If I pick a map for the first time I nearly always see that message, if I then pick it again, no message is displayed.

Regarding the player problem yes, thats true - thought about "I know a player joined a lobby because I'm hosting" but maybe there are two games :-s Guess it's not that easy to not route messages triggert by the host himself, is it? (Or it's just me who is annoyed by blinking buttons and has to click those to make it stop :D)

**Comment by Flamefire** [comment]
Yep first time the maps is transferred (to you).

No I meant the main lobby not the game lobby. You may want to see this. Only idea I have would be to not send this message to the player who hosted in the first place. But this requires changing the lobby server

**Comment by Flamefire** [comment]
It is still transfered via network although it is local in this case

**Comment by Flamefire** [comment]
I found that this message is generated by the lobby server which I have access to. Fix will come soon

**Comment by Flamefire** [comment]
Fixed
