### ISSUE TITLE
Inexhaustible wells enabled by default

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#917]
Currently inexhaustible wells are enabled by default. Thats not a settlers 2 settings. Addon settings should be settlers 2 like by default.

**Comment by Xermio** [comment]
The addon "**Ex**haustible Water" is set to "**Inex**haustible Water" when I click at "Default".

This is the correct setting as far as I know. I could let run a test game, but I'm very sure.

**Comment by Spikeone** [comment]
Oh my, you are right - haven't been playing the original for too long. Wells were inexhaustible in the original so nobody every understood why geologists found it everywhere.

Sorry about that.
