### ISSUE TITLE
Code comment translation to english / cleanup / removal

### ISSUE THREAD

**Issue by lweberk** [Return-To-The-Roots/s25client#93]
- [ ] Translation to english
- [ ] Removal of redundant comments (like "class X constructor" on a ctor) 
- [ ] Move comment to trailing style where it improves readability (out of the way of the actual code, leaving it to speak for its own)
- [ ] Fix encoding issues left behind by 562ba18c8b4175b5fc7ca94cfc30a0d963c917ef

**Comment by Flow86** [comment]
I think theres still to few comments on the code, but youre right, some comments can safely be removed. 

But: The doxygen comments should be updated everywhere

**Comment by MarcusSt** [comment]
See #94 for the reasons for "enhancement".

**Comment by lweberk** [comment]
@Flow86 
Oh, true. Actually never took a look at it :P. Will have to do.

On another note... should we draw upon a an existing code style standard like K&R or Linux Kernel, ... ? Or should I just go ahead and see if you like what you guys see?
I'd be going for a slightly modified Linux Kernel style. Rationale: it makes efficient vertical space usage and is very readable.
One modification being, keeping the current 4 spaces indentation.
Rationale: For horizontal alignment the best option available
Another modification being the horizontal restriction at 80 columns, expanding onto a soft limit of 100 and a hard limit of 120.

Please advise.

**Comment by Flamefire** [comment]
Style please to the other issue. Or merge those 2. I'd stick as close to the current code as possible but enforce a uniform style. Besides that: 100 - 120 seems to be good to me

**Comment by Flow86** [comment]
since I have 24" Monitors, 80 columns is a bit outdated, I think 100-120 is okay.

I would keep the current coding style.

As soon as we have a bit stable version again, we could fix the style of all files (astyle --style=bsd -CSNpcOo -k1 -z2 -Q)
