### ISSUE TITLE
Can't escape options menu anymore with error: The port you entered is invalid

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#934]
I meant to change music, not the port number: 

![Screenshot](https://user-images.githubusercontent.com/14232936/48317828-380fa680-e5f8-11e8-8667-480044e174bc.png)

and also its not relevant which port you set, tried severall values between 1 and 65535, none is accepted.

**Comment by Xermio** [comment]
You need to change the Proxyserver-Port too. (As workaround)

I also had this bug today.

**Comment by Xermio** [comment]
Yes I know, this is a bug. But when you change the Proxyserver-Port to 1 as example, you can leave the menu.

It seems like the default setting 0 is not compatible with the check of the portnumber.

**Comment by stefson** [comment]
it seems this caused a compile error? 

```
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/desktops/dskOptions.cpp:539:17: error: 
      no matching function for call to 'validatePort'
            if(!validatePort(groupAllgemein->GetCtrl<ctrlEdit>(371)->GetText(), SE...
                ^~~~~~~~~~~~
/var/tmp/portage/games-strategy/s25rttr-9999-r4/work/s25rttr-9999/src/desktops/dskOptions.cpp:510:6: note: 
      candidate function not viable: no known conversion from 'unsigned int' to
      'uint16_t &' (aka 'unsigned short &') for 2nd argument
bool validatePort(const std::string& sPort, uint16_t& outPort)
```

[build.log.zip](https://github.com/Return-To-The-Roots/s25client/files/2570919/build.log.zip)

**Comment by Flamefire** [comment]
You need to update the submodules

**Comment by stefson** [comment]
Ok, works for me now. Thank you! :)

**Comment by stefson** [comment]
Now it's port 1080 as a default, not allowing port 0. Should be fine though.
