### ISSUE TITLE
Change active window handling during scrolling

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#954]
Change behavior to either: Opening a window does NOT make it active when scrolling OR opening a window DOES stop scrolling

Reason: Logic (only 1 window active at any time)

**Comment by Spikeone** [comment]
Tough decision - but I think not making a new window active is the best way as active windows don't behave different to non active windows (you also need 1 click to activate it and trigger an action if you hit one). 

So just don't make it active I guess.

**Comment by Spikeone** [comment]
@Flamefire This one seems fixed as well? I can't remember the exact problem (guess right click scrolling and hitting M or L or something like that) but it currently feels good.

**Comment by Flamefire** [comment]
> guess right click scrolling and hitting M or L or something like that

Yes. In that case either the window should not be active or scrolling should stop as scrolling means the desktop (main window) is active. Not sure what the resulting problem was but there was some

**Comment by Spikeone** [comment]
As far as I remember the window was active and one stopped scrolling but kept the cursor - anyway, this was fixed :)
