### ISSUE TITLE
Source tarball

### ISSUE THREAD

**Issue by nE0sIghT** [Return-To-The-Roots/s25client#96]
As requested [here](https://bugs.launchpad.net/s25rttr/+bug/1069546) please create a source tarball for current (stable) s25rttr version and any feature version as well.

**Comment by Flow86** [comment]
the current stable source tarball can be downloaded here: https://github.com/Return-To-The-Roots/s25client/archive/0.8.zip

**Comment by hasufell** [comment]
These don't contain the submodules, so for packaging these seem broken.

**Comment by nE0sIghT** [comment]
Also they are outdated

**Comment by Flamefire** [comment]
The missing submodules are a very valid point.
Regarding outdated: The latest stable release is 0.8.1, so it is not outdated as nightlys are no releases. However I think we need more releases.
For example the current version is pretty stable.  We could tag that as 0.8.2 and move all remaining issues up to 0.8.3 or higher. There are a few remaining kinda high priority bugs which should be fixed, but in general the nightly is much better than 0.8.1.
I'd even name this 0.9.0 following the major=Really big change, medium(?)=feature change, minor=patches strategy and allow also 0.10.0 ;-)

**Comment by hasufell** [comment]
> The missing submodules are a very valid point.

When you do releases (not just tags) you can also upload source tarballs that have everything necessary. E.g. [flex](https://github.com/westes/flex/releases/tag/v2.6.1) does that where the non-generated tarballs have a bootstrapped autotools.

**Comment by Mailaender** [comment]
This is also a major inconvenience for @openSUSE so I would appreciate a 0.8.2 tag. For a network game I think it is essential that everyone packages the same version and not random git commits, because stable is so broken and outdated.

**Comment by Flow86** [comment]
Hi,
unfortunately github does not support submodules inside the (automatic) tarballs "releases" page.

to get the full source, you have to git clone it. 
A release in github is also a git tag, so the following works to the the "full" source:

```
git clone ...
git checkout 0.8.1  # < or use any other "release"-tag here
git submodule update --init
```

**Comment by Mailaender** [comment]
This isn't a huge problem for @openSUSE as http://openbuildservice.org/2016/04/08/new_git_in_27/ exists, but probably other distributors. Uploading a source tarball would be nice. Tagging a new release after 2 years is a must. For now I packaged the current master with some patches as the sub-modules  seem to lack behind. https://build.opensuse.org/package/show/games/s25rttr

**Comment by Flamefire** [comment]
I have been working on creating automatic source tarballs with everything included. Can you check if this is working as required: Go to https://github.com/Flamefire/s25client/releases and download the `s25client_src_<tagname>.tar.gz`

If it does I'll add those to the upcoming releases of the main repo. **The above mentioned are tests only and will be removed**

CCing @stefson

**Comment by stefson** [comment]
I think the third attempt is the one that has included the external repos, such as data/RTTR/MAPS and anything that resides in external/ it also didn't fetch anything from external repos during configure

I'll give it a compile test if you're happy with the data structure of the archive file, ok? 

CCing @chewi for your thoughts

**Comment by Flamefire** [comment]
Yes you are supposed to take the latest.
Also the automatic version derival from the git version is likely not working so you'll have to set `RTTR_REVISION` manually in cmake, but cmake will tell you.

>  if you're happy with the data structure of the archive file, ok?

That archive is mostly a `git checkout && git submodule update --init && tar *`, nothing is supposed to be changed to the folder structure

**Comment by Flow86** [comment]
is it possible to create an override version file inside the archive, so the version detection still works?

**Comment by Flamefire** [comment]
Would need to add logic for that in the CML, but is certainly possible. How would you call this file? `forced.revision`?

**Comment by Flow86** [comment]
no it only should use it if its not set, like "check git or check revision.txt"

I prefer to call it "revision.txt" - so you know from which version the zip file was generated. (and we can use it to fill revision)

**Comment by stefson** [comment]
> I have been working on creating automatic source tarballs with everything included. Can you check if this is working as required: Go to https://github.com/Flamefire/s25client/releases and download the `s25client_src_<tagname>.tar.gz`
> 
> If it does I'll add those to the upcoming releases of the main repo. **The above mentioned are tests only and will be removed**
> 
> CCing @stefson

please have a look into the archive, for test1 test2 and test4 all the dirs fetched recursivly from external repo are empty at 0 byte

test3 has them included, so that should be a test canidate for further testing it at compile and runtime

**Comment by Flamefire** [comment]
> please have a look into the archive, for test1 test2 and test4 all the dirs fetched recursivly from external repo are empty at 0 byte

Where do you see a `s25client_src_<tagname>.tar.gz` for those?

**Comment by Flamefire** [comment]
@Flow86 Done: https://github.com/Flamefire/s25client/commit/f430338455adebee00e868106c09918c5b77809a

**Comment by chewi** [comment]
`s25client_src_test6.tar.gz` looks good to me. My only suggestion is that perhaps dev-tools doesn't really need to be included and removing that would reduce the size by 10MB.

**Comment by Flow86** [comment]
yes, but if we remove the devtools, the source tarball is incomplete and perhaps only usable for linux (not even that)

**Comment by Flamefire** [comment]
Well this package is meant for package maintainers mainly. The devtools are just prebuild libraries to ease development/first-start-experience. They are completely optional.
On Windows you got to install the required libs (SDL2, lua, ...) yourself which is possible although likely annoying. CMake will tell you what is missing.   
On Linux all you need is lua 5.2 (dev)   
On OSX we only have a libSDLmain which is likely unused and should be removed.

So: I'd agree to remove this and adjust the CML to handle that.

**Comment by stefson** [comment]
alright, I got confused by the naming scheme: s25client_src_test6.tar.gz is the full source archive, while the static links from github archive are labled as source code (tar.gz): https://github.com/Flamefire/s25client/archive/test6.tar.gz

I don't have a strong opinion on wether to remove dev-tools or not, it's always possible to remove the folder before compiling if things get pulled from there unintentionally.

**Comment by Mailaender** [comment]
I have the feeling your list of dependencies is incomplete:

```
[    7s] -- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
[    7s] -- Could NOT find SNDFILE (missing: SNDFILE_INCLUDE_DIR SNDFILE_LIBRARY) 
[    7s] -- Could NOT find FFTW (missing: FFTW_LIBRARY FFTW_INCLUDE_DIR) 
[    7s] -- Linking against boost dynamic or static libraries
[    7s] -- Boost version: 1.66.0
[    7s] -- Found the following Boost libraries:
[    7s] --   system
[    7s] --   filesystem
[    7s] --   iostreams
[    7s] -- Fetching Boost.Nowide from repository...
[    7s] CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:2275 (message):
[    7s]   error: could not find git for clone of boostnowide-populate
[    7s] Call Stack (most recent call first):
[    7s]   /usr/share/cmake/Modules/ExternalProject.cmake:3029 (_ep_add_download_command)
[    7s]   CMakeLists.txt:13 (ExternalProject_Add)
```

There is no boost nowide on @openSUSE and the build service does not allow downloads from the internet during the build for security reasons so I can't test this.

**Comment by Flamefire** [comment]
Well Boost.Nowide is a dependency if you are not willing (or allowed) to download it during build. If you have an idea how to make the current list of requirements better, please open a PR. :)

**Comment by Mailaender** [comment]
I grabbed the boost-nowide package from Fedora, but it isn't recognized. I still wants to download it's own. The files are located in `/usr/include/boost/nowide`. Maybe your cmake scripts are ignoring it.

**Comment by Flamefire** [comment]
I guess that fedora still ships with an old version of Nowide before it was officially included into Boost. That version has quite a few bugs and is incompatible with rttr.

It is possible to build Boost.Nowide from source as a static library using the system-installed Boost as it has only been included in Boost 1.73. You could do that as part of the rttr build or update the upstream package.

Another alternative is to download a checkout of Boost.Nowide without building and setting `-DFETCHCONTENT_SOURCE_DIR_BoostNowide=<path>` to that source directory to avoid FetchContent downloading it.

**Comment by Mailaender** [comment]
Can you explain https://github.com/boostorg/nowide/releases a bit? Is it included in boost-1.73.0? Which version do I need?

**Comment by Mailaender** [comment]
I managed to package a recent version https://build.opensuse.org/request/show/805658. Next odd ball is Lua 5.2 which seems to be deprecated and unavailable.

**Comment by stefson** [comment]
gentoo picks a patch to loosen that strict lua requirement, maybe you find it helpfull? https://github.com/gentoo/gentoo/blob/master/games-strategy/s25rttr/files/s25rttr-loosen-libs.patch

**Comment by Mailaender** [comment]
CMake doesn't check for libboost_regex, but it is required later on.

**Comment by Mailaender** [comment]
Linux icons and .desktop files formerly in the debian folder seem to be missing completely now.

**Comment by Flamefire** [comment]
> Can you explain https://github.com/boostorg/nowide/releases a bit? Is it included in boost-1.73.0? Which version do I need?

The vx.y.z are SemVer releases. You likely want the latest one of those.

> Next odd ball is Lua 5.2 which seems to be deprecated and unavailable.

Huh? Why that? We can check if we can support 5.3 too

> gentoo uses a patch to loosen that strict lua requirement, maybe you find it helpful

Why 5.1? 

> CMake doesn't check for libboost_regex, but it is required later on.

Where would that be needed? CMake does usually check for all libraries.

> Linux icons and .desktop files formerly in the debian folder seem to be missing completely now.

This? https://github.com/Return-To-The-Roots/s25client/tree/master/tools/release/debian

**Comment by stefson** [comment]
I don't know why that patch exists other than to loosen the strict lua requirement, but you can ping chewi as he is the author of that patch. I'm building against a system lua-5.2.4 and feeling pretty good with that.

**Comment by Mailaender** [comment]
> Problem: libsamplerate.so()(64bit) benötigt von s25rttr-test6-0.x86_64 wird nirgends zur Verfügung gestellt

libsamplerate is not properly linked.

**Comment by stefson** [comment]
you most likely didn't passed additional `-DRTTR_USE_SYSTEM_SAMPLERATE=ON` to build against system libsamplerate.so

**Comment by Mailaender** [comment]
Thanks. https://build.opensuse.org/package/show/home:Mailaender:branches:games/s25rttr now builds properly from the source tarball. I only made some minor adjustments.

**Comment by chewi** [comment]
Gentoo's Lua situation is a bit of a mess so only 5.1 is supported right now. I can't take that battle on myself so I can only hope it'll improve but it seems to work just fine in this case.

I hadn't realised you were bundling part of Boost. Gentoo has 1.73.0 so I've just updated my system and I can see nowide present now. I'll update our package accordingly.

**Comment by stefson** [comment]
The snapshot you've pushed to the tree doesn't depend yet on boost-1.73.0, so that should be fine unless you decide to update it. 
I've pinned my own ebuild to commit a01a3ec937ba63e955b0982dc217573d540149a4 , which is the last one without the changes introduced.

**Comment by Flamefire** [comment]
@Flow86 What do you say about taking this patch upstream? https://build.opensuse.org/package/view_file/home:Mailaender:branches:games/s25rttr/desktop.patch

Sounds reasonable to me to avoid the wrapper which (tries to) only update the LD_LIBRARY_PATH

**Comment by Flow86** [comment]
if we set RPATH correctly, it should work without setting the LD_LIBRARY_PATH.

**Comment by Flamefire** [comment]
> Gentoo's Lua situation is a bit of a mess so only 5.1 is supported right now. I can't take that battle on myself so I can only hope it'll improve but it seems to work just fine in this case.

We might be able to work with other lua versions. IMO 5.1 should be supported but I expect at least reduced performance. Were you able to test a few games with lua 5.1?

> I hadn't realised you were bundling part of Boost. Gentoo has 1.73.0 so I've just updated my system and I can see nowide is present now. I'll update our package accordingly.

Well, Boost.Nowide is a bit special. It is intended to be used as part of Boost 1.73+ and equally well separately installed with (almost) any Boost version so distros can just upgrade that to the latest version without requiring to upgrade all of boost which may be problematic.   
Additionally this allows us to build it alongside RttR, if an older boost version is used, automatically.

> I've pinned my own ebuild to commit a01a3ec , which is the last one without the changes introduced.

Any particular reason for that?



I also just created a new test tag (tag8) which:
- separates out dev-tools to an extra archive
- uses libssamplerate via fetchcontent to match Boost.Nowide
- Renames the `RTTR_USE_SYSTEM_<lib>` variables to be consistent with FetchContent (sorry. Should have done that from the start...)
- Add a `PACKAGING.md` which should explain what you need.

@Mailaender FYI: `libboost_chrono-devel` is no longer required. `libboost_test-devel` can be dropped if you build with `BUILD_TESTING=OFF` (decide for yourself).

Generally I suggest to use `-DRTTR_USE_SYSTEM_LIBS=ON` for packages, see the new md file.

> if we set RPATH correctly, it should work without setting the LD_LIBRARY_PATH. 

@Flow86 For the .desktop file shouldn't we be able to assume that either RPATH or LD_LIBRARY_PATH have been set correctly?

**Comment by chewi** [comment]
> We might be able to work with other lua versions. IMO 5.1 should be supported but I expect at least reduced performance. Were you able to test a few games with lua 5.1?

My machine is fast so I wouldn't have noticed any performance issues. I did play single player for a good hour or two and it was fine.

**Comment by Flow86** [comment]
@Flamefire we can't assume that its set up - who should set it up? its only a path needed by rttr, so why should someone add it globally to their profile?

**Comment by Flamefire** [comment]
> I did play single player for a good hour or two and it was fine.

Ok, I'll do a test with 5.3 then change the requirements

@Flow86 It sets up `LD_LIBRARY_PATH` to `<PREFIX>/lib`, so for usual installations (e.g. to `/usr/local`) that path alread is in `LD_LIBRARY_PATH`. And the only reason we set it is for libminiupnpc.so which should be installed to the system too.   
We can (and should) keep the rttr.sh setting that for the "portable" Download, but for the desktop file and distributions I see no reason for that.

**Comment by stefson** [comment]
the reason for me pinning my own binary to https://github.com/Return-To-The-Roots/s25client/commit/a01a3ec937ba63e955b0982dc217573d540149a4 for the moment is simply that boost isn't slotted and so the upgrade to boost-1.73.0 caused the usual breakages. These should get fixed in the near future, I believe libreoffice got fixed just yesterday. I'll catch up with that as soon as I've got enough spare time.

**Comment by Flamefire** [comment]
@stefson Ok sure. You could consider using the method explained in https://github.com/Return-To-The-Roots/s25client/issues/96#issuecomment-628766875 to build a static variant without touching any of the upstream boost.

Alternatively check for an upstream nowide package and update that using the cmake version of nowide

**Comment by Mailaender** [comment]
`FETCHCONTENT_FULLY_DISCONNECTED` is mentioned in the packaging documentation, but doesn't seem to exist.

**Comment by Mailaender** [comment]
```
[    6s] CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:2275 (message):
[    6s]   error: could not find git for clone of libsamplerate-populate
[    6s] Call Stack (most recent call first):
[    6s]   /usr/share/cmake/Modules/ExternalProject.cmake:3029 (_ep_add_download_command)
[    6s]   CMakeLists.txt:13 (ExternalProject_Add)
```

It looks like `-DRTTR_USE_SYSTEM_LIBS=ON -DRTTR_USE_SYSTEM_SAMPLERATE=ON -DFETCHCONTENT_FULLY_DISCONNECTED=OFF` none of the parameters are now recognized. It still wants to download the dependency.

**Comment by Mailaender** [comment]
Never mind it is `DFETCHCONTENT_FULLY_DISCONNECTED=ON` which is just counterintuitive.

**Comment by Mailaender** [comment]
The new Lua detection is broken for me:

```
[    7s] CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
[    7s]   Could NOT find Lua: Found unsuitable version "", but required is at least
[    7s]   "5.1" (found LUA_LIBRARY-NOTFOUND)
[    7s] Call Stack (most recent call first):
[    7s]   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
[    7s]   external/libutil/cmake/FindLua.cmake:244 (find_package_handle_standard_args)
[    7s]   libs/libGamedata/CMakeLists.txt:14 (find_package)
```

I have both runtime and library installed:

```spec
BuildRequires:  lua51
BuildRequires:  lua51-libs
```

**Comment by Flamefire** [comment]
Intresting. Can I see your CMakeCache file, the lua.h and the output when running cmake with `-DLUA_Debug=ON`? I tested it on my system without issues, but will retry on another one

**Comment by Mailaender** [comment]
Yes, it was lua51-devel missing. I forgot that this is not managed code, but native.

```
[    4s] -- Testing ('make test') is enabled. Add -DBUILD_TESTING=OFF to disable tests.
[    4s] CMake Error at external/CMakeLists.txt:12 (add_subdirectory):
[    4s]   The source directory
[    4s] 
[    4s]     /home/abuild/rpmbuild/BUILD/s25client_test9/external/dev-tools
[    4s] 
[    4s]   does not contain a CMakeLists.txt file.
```

The unit tests spit out an error message.

**Comment by Flamefire** [comment]
Yes found that warning too. Fixed in the test10 tag

**Comment by chewi** [comment]
I gather that `RTTR_USE_SYSTEM_LIBSAMPLERATE` is supposed to default to the value of `RTTR_USE_SYSTEM_LIBS` but if I give `-DRTTR_USE_SYSTEM_LIBS=ON` without `-DRTTR_USE_SYSTEM_LIBSAMPLERATE=ON` then it doesn't try to use the system copy. Don't know why.

**Comment by Mailaender** [comment]
Try setting `-DFETCHCONTENT_FULLY_DISCONNECTED=ON`.

**Comment by Mailaender** [comment]
https://build.opensuse.org/package/show/home:Mailaender:branches:games/s25rttr test10 builds and runs fine again.

**Comment by chewi** [comment]
> Try setting `-DFETCHCONTENT_FULLY_DISCONNECTED=ON`.

That does work but I can't see why and that bothers me. That variable should only get used in the `else` clause here but it shouldn't be entering that clause in the first place.

```cmake
option(RTTR_USE_SYSTEM_LIBSAMPLERATE "${RTTR_USE_SYSTEM_LIBS}" "Use system installed libsamplerate. Fails if not found!")
if(RTTR_USE_SYSTEM_LIBSAMPLERATE)
        ...
else()
    include(FetchContent)
    ...
endif()
```

**Comment by Flamefire** [comment]
@chewi did you set that on the first cmake run? I. E. In an empty build folder? Otherwise the variable will already be set in the cache to the default even when changing it.

**Comment by chewi** [comment]
Yes, this is using my package, which will always start with a clean build folder.

**Comment by Flamefire** [comment]
Found it: I always forget that the order of the arguments is different: The default value comes last -.-
Fixed in test11

**Comment by chewi** [comment]
That's good now, thanks!
