### ISSUE TITLE
Drop support for 32Bit

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#962]
Currently we have Windows and Linux 32 and 64 bit versions. Especially for CI this is a burden:

- 32/64 Bit
- Debug/Release
- Different compilers (e.g. clang/gcc, VS 2015/2017)

-> 2^3=8 combinations per OS, possibly more

Is anyone still using 32Bit Linux or Windows?   
Can we stop testing on 32Bit Linux and/or Windows? (Self compilation will [most likely] still be possible, but may need own work)

At least I'd restrict the windows compilers to 1 32Bit version (VS2017, 32Bit, Debug) to speed up the slow appveyor CI.   
I guess we never test linux 32 Bit on CI as only native build is tested. Jenkins (official build server) does it of course

@Flow86 @Spikeone

**Comment by Spikeone** [comment]
Actually I'm using the 32bit build on low end PCs like my old tablet. Also I have no idea how many people use the 32bit build, maybe @Flow86 could check how often that version is downloaded?

**Comment by Spikeone** [comment]
Actually they only have 32bit installed - at least my old tablet and my old netbook. Don't know if they'd support x64 at all. But I don't think that we are quite representative for all users - can we log build version when players join the lobby? On the other hand ppl. may use x86 although they have a x64 OS (like me at the moment).

**Comment by Flamefire** [comment]
Ok, so don't drop Windows 32 bit. I'll reduce the testers though (1 should be enough to catch bugs)

**Comment by baka0815** [comment]
Most Linux distributions drop 32bit support, so it may be ok to drop that support too. However I'm unsure if low end PC like the raspberry shall be supported for which 32bit support might be necessary.
