### ISSUE TITLE
Road on Border

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#968]
![2018-12-19_01-28-15](https://user-images.githubusercontent.com/1276342/50191869-0644da80-0330-11e9-8787-bfca4629f24f.png)

[2018-12-18_23-03-23.zip](https://github.com/Return-To-The-Roots/s25client/files/2692837/2018-12-18_23-03-23.zip)

**Comment by Flamefire** [comment]
I hate this kinds of bugs -.- They are very hard to reproduce, but I'll try.

**Comment by Spikeone** [comment]
Problem still exists:

![image](https://user-images.githubusercontent.com/1276342/68085051-969ee780-fe3c-11e9-955f-acb142ebfcf6.png)

Seems to affect long roads where the road itself is outside the area but the flag not. Going to test that, maybe easy to reproduce.

**Comment by Spikeone** [comment]
Yep just tested it. When a road is on the border but none of the flags is, the road persists. Looks like road segments may only be not outside the border but on still works.

[2019-11-03_13-21-33.zip](https://github.com/Return-To-The-Roots/s25client/files/3801551/2019-11-03_13-21-33.zip)

**Comment by q9f** [comment]
I was able to reproduce this last night. It appears flags get destroyed once the border moves, but roads stay in tact as long as they are inside your country (correct) or on the border (bug).
