### ISSUE TITLE
Textures off when zooming

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#969]
![2018-12-19_01-28-15](https://user-images.githubusercontent.com/1276342/50192091-26c16480-0331-11e9-936c-47bb97b5143c.png)

**Comment by Flamefire** [comment]
Does this happen anywhere else? I suspect it happens always when there is a border to right upper side. Maybe one of the other 5 sides is also affected?

**Comment by Spikeone** [comment]
Seems to only happen with the top right border and at zoom levels <= 100%, means I zoomed to 150% and the problem vanished, zoomed to 75% and it was still persistent.

**Comment by Spikeone** [comment]
Seems to happen no longer, possibly already fixed by @Flamefire
