### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by x12r13** [Return-To-The-Roots/s25client#971]
After the nightly build doesn't work for me (GLXBadContext) I'm trying to build the program from source.

After downloading and creating a sub directory build the setup is done with

$> cmake -DCMAKE_BUILD_TYPE=Nightly ..

This seems to work without problems.

But when calling 
  $> make
(even using DESTDIR) an error occures.

-- Creating symlinks in  to ease debugging.
CMake Error at copyDepsToBuildDir.cmake:41 (file):
  file problem creating directory: /share/s25rttr

Any ideas?

Operating System: Debian Buster / x64

**Comment by Flamefire** [comment]
You seem to be a CMake beginner, am I right? In this case I suggest using cmake-gui or ccmake which e.g. shows the available choices. In your case `CMAKE_BUILD_TYPE=Nightly` is invalid. See the Readme.MD in the repo root: `cmake -DCMAKE_BUILD_TYPE=Release ..`

`DESTDIR` is only used during install.

I'll add another check to catch your mistake with a better error message.

**Comment by x12r13** [comment]
Stimmt, bin kein cmake Benutzer. Habs nur beim Drüberlesen am Schluss der Datei CMakeLists.txt entdeckt :)

Kompilieren läßt es sich jetzt, mal gucken ob das GLX Problem verschwindet.

Danke fuer deine Hilfe!

**Comment by x12r13** [comment]
Compilation works, but the error is still the same:

Starte Spiel
Lade "/home/av/games/s25rttr_local/usr/local/share/s25rttr/RTTR/splash.bmp": fertig in 6ms
X Error of failed request:  GLXBadContextTag
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  16 (X_GLXVendorPrivate)
  Serial number of failed request:  43
  Current serial number in output stream:  44
An error occured: press enter to continue

**Comment by Flamefire** [comment]
Are other OpenGL applications working? What is the output before this error? Could you debug to see what call produces this error? Could you update all drivers/mesa/xserver related things?

Don't know what it is as it looks like a driver failure.

**Comment by Flamefire** [comment]
> At the ogre developer list they discussed a similar problem. Someone found out, that the error occurs when OpenGL plugin is loaded BEFORE creating SDL Window. Re-arranging the order fixed the issue.

I guess you are referring to https://forums.ogre3d.org/viewtopic.php?f=2&t=67851 ?   
I have no idea what they are referring to with "OpenGL plugin", but as far as I can tell their error came from using OpenGL before initializing the context. I'm quite sure this is not the case with us. The current control flow is:
- CreateScreen: Create window and ogl context via SDL
- LoadAllExtensions: Load OGL function pointers
- RenewViewport: Create viewport and setup global context settings
- Show splashscreen: Create texture from bitmap and draw it <-- Seems to fail?

I don't see anything wrong here. Your setup is quite particular so it may cause subtile bugs (either in our code or in the setup). 0.8.2 is working right now (without any other changes)?

To go further we need to dig deeper. How familiar are you with debugging (gdb)? Are you able to build in Debug mode and get a backtrace when this error occurs?

**Comment by x12r13** [comment]
besides the fact that xorg debugging is always a mess i could give it a try, but i have to install the dev libs at first i guess.

your 0.8.2 stable binary works without any (obvious) problems.

**Comment by Flamefire** [comment]
You already self-compiled, so there should be no need to install anything additional. Just use `-DCMAKE_BUILD_TYPE=Debug` and compile as usual

**Comment by Flamefire** [comment]
Ah I misunderstood. Just check which call of rttr causes the issue. Debugging into xorg is hopefully not required

**Comment by x12r13** [comment]
Anbei mal meine erste debug session. Wo soll ich denn die break points setzen, bzw was interessiert dich?

[gdb.log](https://github.com/Return-To-The-Roots/s25client/files/2706488/gdb.log)

**Comment by Flamefire** [comment]
I assume there is an opengl call that produces the error. (IMO OpenGL calls into X which fails in this case)

So either catch all exceptions so get stopped at the place where it is thrown and produce a backtrace (calls that lead to that exception) or you single step until you find the call manually. In that case I suggest to set a BP in `glArchivItem_Bitmap::Draw` and step over till you find the crashing call. Then restart and set a BP in the function with the crashing call. Repeat till you found a non-RTTR function.

**Comment by Flamefire** [comment]
I close this as the initial issue is resolved. Please open a new one once you get the information which call crashes. Thank you 👍
