### ISSUE TITLE
Lobby crashes frequently

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#973]
Although I have no idea why this happens - the lobby seems to crash (or at least no one can connect) quite frequently. I myself did not cause the problem yet but others did. 

It always looks like the following:
1) user joins lobby
2) user disconnects lobby
3) nobody can connect anymore

The lobby bot shows the following messages:

> [13:46:17] -[LobbyBot]/#siedler2.5- * join (1): Lavro
[13:46:37] -[LobbyBot]/#siedler2.5- [LOBBY] Connection lost.

I asked Lavro what he did and he said he connected to the lobby, saw no player, disconnected. Was using v.20181215.

The lobby does not seem to restart / reconnect after it is down (only the 0:04 restart helps)

**Comment by Flamefire** [comment]
@Flow86 any logs on the server?

**Comment by Spikeone** [comment]
/push - seems to crash even more frequently but restarts more often - still down atm

**Comment by Flamefire** [comment]
@Flow86 again: Any logs from the server?

**Comment by Flow86** [comment]
```
Feb 03 14:30:54 tyra start.sh[13997]: terminate called after throwing an instance of 'St9bad_alloc'
Feb 03 14:30:54 tyra start.sh[13997]: what():  std::bad_alloc
```

**Comment by Flamefire** [comment]
Looks like either running out of memory (mem leak?) or trying to allocate to much memory (misread packet size?)

**Comment by Spikeone** [comment]
Maybe the following helps: Seems to happen quite frequently when >2 players are in the lobby and one of them tries to host a game. Not sure if it happens as soon as someone writes something in any chat (ingame lobby, ingame lobby <-> lobby, lobby)

**Comment by Spikeone** [comment]
/Push - Lobby still crashes frequently. As far as I have seen the lobby immediatly crashes if a 4th user joins at the same time which makes hosting games with 3+ players impossible.

Sadly I can't test that as I dont have 4 accounts

**Comment by Flamefire** [comment]
Would need some logs from @Flow86 which show the issue. Postponing for now

**Comment by JonasTrampe** [comment]
@Flow86 NastX here - could you provide us the code for the lobby - maybe in a private Repo?

**Comment by Flow86** [comment]
its working stable for now, right?
