### ISSUE TITLE
Attack distances wrongly calculated

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#974]
Map: Toe to Toe (Tür an Tür)

![image](https://user-images.githubusercontent.com/1276342/50423799-87353200-085a-11e9-8eb2-21babc241281.png)
(RttR)

With the same setup you could only attack with 2 soldiers in the original. Although the indicator flags were the same. This needs some further testing - maybe @jhkl has some more information about attack distances and the correct calculation?

EDIT:
When using 2 watchtower at the same position one could attack with 4/6 of the top tower.
![image](https://user-images.githubusercontent.com/1276342/50423878-dcbe0e80-085b-11e9-908f-874f589e7940.png)

**Comment by Flamefire** [comment]
I'd say the original is buggy. I recreated you situation with 2 guardhouses.

- The lower one occupied: 1/1
- Both: 2/2
- Attack with 2: Both from the lower build O.o
- After both left I could still attack with 1/1 (from the upper)

**Comment by Spikeone** [comment]
Well, I created the same situation with two guardhouses - and could only attack with 2 soldiers as well. But my upper guardhouse could not attack at all. So I also had the 2 soldiers attack option but that option was available after the first guardhouse was finished - then the second one was finished and I still could only attack with 2 soldiers (also after clicking the HQ again trying to attack).

Still you are right, the original had a bug where you could first attack with x-soldiers, then while no soldiers reoccupied the building, could still attack with some soldiers which were left. Guess it's about settings and rounding - so maybe first you are allowed to attack with 1/3 of all buildings, which might be  2/6, then again 4 soldiers left and the distance still says 1/3 can attack - which would be at least 1 soldier in the given example. Thats one of the few bugs I think we should not recreate.

**Comment by Spikeone** [comment]
@Flamefire did we agree on not recreating this bug? Although the attack distances are still wrong (we tested that some time ago)

**Comment by Flamefire** [comment]
Yes I think we should not include obvious bugs. The bug here was that calculating the number of soldiers took into account all buildings but when sending the buildings were emptied one after another without taking the distance of each building into account. RttR does it correctly.

So I'd say: If the attack distance per building is different then it is a bug in RttR. So only compare single buildings.
