### ISSUE TITLE
Icons for new functions

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#98]
There are some new functions like go to position, go to next same and send out soldiers (if military control addon is enabled). Sadly they do not use propper icons describing their function so I made some new icons long time ago. Maybe they could be added as they make clear what most functions mean.

![nextsame rle nx11 ny6](https://cloud.githubusercontent.com/assets/1276342/9021778/c3950ab4-3855-11e5-93f9-37837b5445f6.png)
![sendout_01 rle nx16 ny14](https://cloud.githubusercontent.com/assets/1276342/9021779/c5951afc-3855-11e5-8b26-cfb45a7ebfbf.png)
![gottopos rle nx11 ny6](https://cloud.githubusercontent.com/assets/1276342/9021780/c716f6d4-3855-11e5-84ba-fd99a45a9602.png)

http://www.rfmonline.de/rttr/spike/desktop.rar

**Comment by Flamefire** [comment]
I'd really like to extent the current loader for the dynamic nations. I plan, that you can give a filename (image) or a settlers2 archive name and an offset to specify which texture to use.
If the loader can handle this, it should be easy to add new textures.

**Comment by Spikeone** [comment]
Well, there is already an icon for those function and there are already new icons like the near Harbor military setting.
Also a rttr.lst (file or folder) would be great for additional objects/textures. But that's something else.

**Comment by Flow86** [comment]
you can simply add them to a free place i.e in the "overwrite io.lst" (or whereever the other icons are in the original) the loader can append them already on load. no need to add another "file" for simply adding some icons.

**Comment by Spikeone** [comment]
Thats true that the loader loads those files, but those are NOT icons which should be overwritten, they are used twice so overwriting them may fixes those function icons but other functions will have the same icons.
For icons there are no new lists needed, thats also true, we have
\RTTR\LSTS\io_new.LST
Where those icons should be placed and loaded from.
Both of you missunderstood what this bug is about, not adding a new loader function, not adding a new .lst file that is loaded - just adding icons for existing functions which are currently using icons from other functions.

**Comment by Flow86** [comment]
yes simply use a free "slot" for the icon on existing lsts.

**Comment by Spikeone** [comment]
Still, these functions are included, the "store out highest rank" function uses the icon from "collect all" which is in my opinion a bug and just a placeholder atm.

**Comment by Spikeone** [comment]
![currentstate](https://cloud.githubusercontent.com/assets/1276342/9038589/a49e0d44-39f5-11e5-9a96-563536c37b9c.png)

I think we missunderstood each other, my rttr.lst was a comment for Flamefire, not for this issue.Hopefully this picture explains the current state, the should state and why its not possible to just overwrite existing icons (as they are used elsewhere)
