### ISSUE TITLE
Ghost games

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#986]
This bug has been around since ages. The lobby shows games of players that are no longer existing. In fact you sometimes close your game and the game is still listed in the lobby browser. You then have to rename your new game as there can't be 2 games with the same name.

![image](https://user-images.githubusercontent.com/1276342/50552362-b7813400-0c91-11e9-99ad-885a4d2552e3.png)

**Comment by Flow86** [comment]
@Flamefire  hmm there seems to be a "player closed server" message missing since the lobby client reworks?

**Comment by Flow86** [comment]
https://github.com/Return-To-The-Roots/liblobby/blob/3efa4b7ff2006f80cc93c13dbf197474740a9d1c/src/LobbyClient.cpp#L227 

its only called if activly going back to dskLobby. but I dont know what happens if you dont get back to lobby or can't create a game? 
I think there are some cases which are not catched I think

**Comment by Flamefire** [comment]
Not sure about that. However there is 1 important case: The player simply drops. In this case no message is sent and the game persists.

Anyway the current state handling of lobby clients/server etc. is flawed/inconsistent. We should implement a proper state machine on both client and server. This requires (or at least would be better) to merge the server and client lobby libraries again.

**Comment by Flow86** [comment]
yes could be better.
I think there could also be a flaw inside the "connection lost" state in the server part which does not remove the server in the database

**Comment by Flamefire** [comment]
Yep that's what I meant

**Comment by Flamefire** [comment]
Fixed with https://git.ra-doersch.de/rttr/s25lobby/merge_requests/7
