### ISSUE TITLE
Can't host with 0.8.2 anymore

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#988]
At least on Windows 7 you can no longer host a game using the internet lobby and the latest stable version. This seems to be a common problem as a lot of people have reported it in the lobby chat. Also any crash creates a ghost game.

EDIT: Also affects Linux users

We should create a new stable as the old stable is quite unstable compared to the current version.

Log doesn't tell much:

<<< NMS_MAP_DATA(446)
>>> NMS_MAP_CHECKSUM
>>>NMS_MAP_CHECKSUM(3669448)
<<< NMS_MAP_CHECKSUM
CLIENTSERVER >>> CLIENT>>> NMS_PLAYER_NEW
SERVER >>> BROADCAST: NMS_PLAYER_NEW(>>> NMS_PLAYER_LIST(4)
>>> NMS_GGS_CHANGE
>>> NMS_LOBBY_SERVER_UPDATE_PLAYER(1,4)
SERVER >>> BROADCAST: NMS_GGS_CHANGE
>>> NMS_SERVER_NAME(Spikes Spiel)
>>> Addon Status:
	0x00900007=0
	0x00900006=0
	0x00C00000=2
	0x00000000=0
	0x00200002=0
	0x00000003=0
	0x00000004=0
	0x00000002=0
	0x00300001=0
	0x00200000=0
	0x00100002=0
	0x00100001=0
	0x00000005=0
	0x00200001=1
	0x00900000=0
	0x00900003=0
	0x00700000=0
	0x00900008=0
	0x00400000=0
	0x00000006=0
	0x00A00000=2
	0x00900001=2
	0x00900004=0
	0x00200003=0
	0x00B00000=0
	0x00500000=1
	0x00900002=0
	0x00800000=0
	0x00000001=0
	0x00900005=0
	0x00100000=0
	0x00600001=0
	0x00000007=0
	0x00300000=0
<<< NMS_MAP_CHECKSUM(1)
<<< NMS_SERVER_NAME(Spikes Spiel)
<<< NMS_PLAYER_LIST(4)
    0: Spike 2 0 0 2 4278221275 0 false
    1:  0 0 0 2 4278221275 0 false
    2:  0 0 0 2 4278221275 0 false
    3:  0 0 0 2 4278221275 0 false
Saeubere Texturespeicher: fertig (nach 0ms)
Connection to 5.9.167.129:4123
Sucessfully connected to debug.rttr.info:4123

**Comment by Flow86** [comment]
should be fixed in nightly build. We need to release a new stable soon
