### ISSUE TITLE
RPATH issue with darwin

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#992]
the new toolchain works, but the rttr binaries generated with the cross compiler are missing the RPATH entry

`otool -l $bin | grep RPATH -A 2`

We need to add something which runs `install_name_tool -add_rpath @executable_path` and `install_name_tool -add_rpath @executable_path/..` (for Frameworks to be found) on each binary installed.

We could also provide the rpath while compiling by adding it to the CMAKE_EXE_LINKER_FLAGS.

`-DCMAKE_EXE_LINKER_FLAGS="-rpath @executable_path -rpath @executable_path/.."`

the CMAKE_INSTALL_RPATH is completly ignored on cross compiler runs :-/

any better idea to solve that?

I dont want to change the precompiled SDL frameworks, since they're build with "@rpath/Frameworks/..."

Since the libaudioSDL does not work at my virtual macos, perhaps someone with a real mac could check if its only a virtualbox problem with audio or if there's still an issue

**Comment by Flow86** [comment]
I've added the RPATH temporarily via cf97028

**Comment by Flow86** [comment]
I've found my problem with the audio-driver after Ive did some kind of printf debugging with adding a "dlerror()" here:
https://github.com/Return-To-The-Roots/s25client/blob/1a1817d30eb026229c69e9f64845e808a872d34d/libs/s25main/drivers/DriverWrapper.cpp#L131

we should perhaps add a proper way to display the error (on osx/linux with dlerror, on windows with FormatMessage + GetLastError)

**Comment by Flamefire** [comment]
We should rather find out why `CMAKE_INSTALL_RPATH` is not working as it should. Your change might work but is quite hacky. Any ideas already?

**Comment by Flamefire** [comment]
Digging into the CMake source code I found a place where `install_name_tool -add_rpath` is called on installation time. So `CMAKE_INSTALL_RPATH` should work. I'd need access to a build tree to further debug this.

**Comment by Flamefire** [comment]
SoundConverter fails too:

```
Starte Sound-Converter...
dyld: Library not loaded: libminiupnpc.5.dylib
  Referenced from: /Applications/s25client.app/Contents/MacOS/libexec/s25rttr/./sound-convert
  Reason: image not found
```

**Comment by Flow86** [comment]
I really question why the soundconvert dies Link zu miniupnpc? O.o

**Comment by Flamefire** [comment]
It links to s25util which links miniupnpc

**Comment by Flamefire** [comment]
Ok, after lot's of debugging I found the reason: 

- `cmInstallTargetGenerator::AddChrpathPatchRule` uses `cmComputeLinkInformation::GetRPath` to get the rpaths for install and build. But the result is empty
- `cmComputeLinkInformation::GetRPath` checks if `RuntimeFlag` is empty which is in this case `CMAKE_EXECUTABLE_RUNTIME_CXX_FLAG` cmake var. This is empty
- `CMAKE_EXECUTABLE_RUNTIME_CXX_FLAG` gets (ultimately) initialized from `CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG` (also empty)
- `CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG` would be set by Darwin.cmake if `"${DARWIN_MAJOR_VERSION}" GREATER 8`
- `DARWIN_MAJOR_VERSION}` gets set from `CMAKE_SYSTEM_VERSION` which CMake does not set in Cross-compile: 
> When the CMAKE_SYSTEM_NAME variable is set explicitly to enable cross compiling then the value of CMAKE_SYSTEM_VERSION must also be set explicitly to specify the target system version.

Solution: Set it in the toolchain files

**Comment by Flamefire** [comment]
Fixed by https://github.com/Return-To-The-Roots/s25client/pull/996/commits/589b88dced158dce5dd78559d7fe23094f3763cb

**Comment by Flow86** [comment]
rpath still seems not to get added O.o?

**Comment by Flow86** [comment]
ah, seemed to be a cmake cache failure. I removed the whole directory and rebuilt it, now it seems to work

**Comment by Flamefire** [comment]
We should do this by default. We have ccache to cache the compilation but the persistent CMakeCache becomes a problem every now and then.
