### ISSUE TITLE
osx arch detection fails on osxcross

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#997]
[quote]
-- Checking /usr/lib/apple/SDKs/MacOSX10.11.sdk/usr/lib/libSystem.B.tbd for possible architectures
-- Possible architectures: x86_64;i386
-- Building architecture x86_64
-- Building architecture i386
-- Building architecture ppc
-- CHOOSEN_OSX_ARCHS: x86_64;i386;ppc

....

osxcross: error: unsupported architecture: 'ppc'
osxcross: error: while detecting target

[/quote]

I don't know why he adds ppc to the list in cmake/darwin.cmake ?

**Comment by Flow86** [comment]
ah ... 
OSX_POSSIBLE_ARCHS vs OSX_DETECTED_ARCHS

;-) 
the wrong one was used in cmake/darwin.cmake

**Comment by Flow86** [comment]
fixed via 9b966d3

**Comment by Flamefire** [comment]
Thanks O.o
