### ISSUE TITLE
SDL2 detection fails on osx(cross)

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#998]
``` 
-- Could NOT find SDL2: Found unsuitable version "1.2.15", but required is at least "2.0.4" (found /usr/lib/apple/SDKs/MacOSX10.11.sdk/Library/Frameworks/SDL.framework/Headers)
```

SDL2 framework is here:

`/usr/lib/apple/SDKs/MacOSX10.11.sdk/Library/Frameworks/SDL2.framework`

I don't know why he even tries to use SDL.framework? in FindSDL2.cmake everything states SDL2 ?

/assign @Flamefire

**Comment by Flamefire** [comment]
Because SDL is stupid and does not use proper convention of using e.g. `#include <SDL2/SDL2.h>` but instead `#include <SDL.h>` where `SDL.h` is hopefully in a folder `SDL2` but may not be -.-
